# Generated by Django 2.2.11 on 2020-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbody',
            name='body_type',
            field=models.PositiveIntegerField(choices=[(1, 'Gram Panchayath'), (2, 'Block Panchayath'), (3, 'District Panchayath'), (4, 'Municipality'), (5, 'Corporation'), (6, 'Others')], help_text='denotes the type of local body'),
        ),
    ]
