# Generated by Django 2.2.11 on 2020-05-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200524_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Name", max_length=255, verbose_name="name"),
            preserve_default=False,
        ),
    ]
