# Generated by Django 6.0 on 2026-03-26 17:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('whatsapp_id', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message="WhatsApp ID must be in E.164 format: '+[country code][number]'. Up to 15 digits.", regex='^\\+?[1-9]\\d{7,14}$')])),
                ('is_verified', models.BooleanField(default=False)),
                ('can_receive_ppi', models.BooleanField(default=False, help_text='Can this user receive Personally Identifiable Information?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
