services:
  backend:
    image: care_local
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        ADDITIONAL_PLUGS: ${ADDITIONAL_PLUGS:-}
    env_file:
      - ./docker/.local.env
    environment:
      ADDITIONAL_PLUGS: '[{"name":"booking_notifications","package_name":"booking_notifications","version":""}]'
    volumes:
      - .:/app
      - ../care_booking_notifications_be:/plugs/care_booking_notifications_be
    entrypoint:
      - bash
      - -c
      - |
        pip install -e /plugs/care_booking_notifications_be --quiet
        exec bash scripts/start-dev.sh
    ports:
      - "9000:9000"
      - "9876:9876" #debugpy
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      celery:
        condition: service_healthy

  celery:
    image: care_local
    env_file:
      - ./docker/.local.env
    environment:
      ADDITIONAL_PLUGS: '[{"name":"booking_notifications","package_name":"booking_notifications","version":""}]'
    volumes:
      - .:/app
      - ../care_booking_notifications_be:/plugs/care_booking_notifications_be
    entrypoint:
      - bash
      - -c
      - |
        pip install -e /plugs/care_booking_notifications_be --quiet
        exec bash scripts/celery-dev.sh
    restart: unless-stopped
    depends_on:
      - db
      - redis
