[tool.coverage.run]
branch = true
source = ["care"]
parallel = true
concurrency = ["multiprocessing"]
relative_files = true
omit = [
  "*/tests/*",
  "*/migrations*/*",
  "*/asgi.py",
  "*/wsgi.py",
  "manage.py",
  ".venv/*"
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError"
]
ignore_errors = true


[tool.isort]
profile = "black"
known_third_party = [
  "allauth",
  "boto3",
  "celery",
  "crispy_forms",
  "dateutil",
  "django",
  "django_filters",
  "django_rest_passwordreset",
  "djangoql",
  "djqscsv",
  "drf_spectacular",
  "dry_rest_permissions",
  "environ",
  "freezegun",
  "hardcopy",
  "healthy_django",
  "jsonschema",
  "jwt",
  "phonenumber_field",
  "phonenumbers",
  "pytz",
  "pywebpush",
  "ratelimit",
  "requests",
  "rest_framework",
  "rest_framework_nested",
  "rest_framework_simplejwt",
  "sentry_sdk",
  "simple_history"
]
