import os
import django
from django.conf import settings

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.local')
django.setup()

from care.messaging.dispatcher import IntentDispatcher
from care.users.models import User
from care.messaging.models import WhatsAppProfile
from care.facility.models.patient import PatientMobileOTP

def test_bot():
    whatsapp_id = "test_wa_123"
    
    # Pre-test cleanup
    WhatsAppProfile.objects.filter(whatsapp_id=whatsapp_id).delete()
    PatientMobileOTP.objects.all().delete()
    
    # 1. Start Command
    print("--- Test /start (Logged out) ---")
    dispatcher = IntentDispatcher(whatsapp_id, "/start")
    print(f"Reply: {dispatcher.dispatch()}")
    
    # 2. Login Flow - Step 1: /login command
    print("\n--- Test /login command ---")
    dispatcher = IntentDispatcher(whatsapp_id, "/login")
    print(f"Reply: {dispatcher.dispatch()}")
    
    # Find a user to link or create one
    user = User.objects.first()
    if not user:
        print("Creating mock user for testing...")
        user = User.objects.create(username="bot_test_user", phone_number="+919000000001", email="bot@test.com")
    else:
        # Ensure user has a valid phone number format for the dispatcher
        if not user.phone_number or not user.phone_number.startswith("+"):
            user.phone_number = "+91" + "".join([str(i) for i in range(10)])
            user.save()

    print(f"Linking with phone: {user.phone_number}")
    dispatcher = IntentDispatcher(whatsapp_id, user.phone_number)
    print(f"Reply: {dispatcher.dispatch()}")
    
    # Extract the OTP generated by the bot logic in step above
    otp_obj = PatientMobileOTP.objects.filter(phone_number=user.phone_number).latest('created_date')
    print(f"Bot generated OTP: {otp_obj.otp}")
    
    # Submit incorrect OTP first
    print("\n--- Submitting wrong OTP ---")
    dispatcher = IntentDispatcher(whatsapp_id, "00000")
    print(f"Reply: {dispatcher.dispatch()}")

    # Submit correct OTP
    print("\n--- Submitting Correct OTP ---")
    dispatcher = IntentDispatcher(whatsapp_id, otp_obj.otp)
    print(f"Reply: {dispatcher.dispatch()}")
    
    # 3. Success check - Commands after login
    print("\n--- Test /meds after login ---")
    dispatcher = IntentDispatcher(whatsapp_id, "/meds")
    print(f"Reply: {dispatcher.dispatch()}")

    print("\n--- Test /records after login ---")
    dispatcher = IntentDispatcher(whatsapp_id, "/records")
    print(f"Reply: {dispatcher.dispatch()}")

    print("\n--- Test /logout ---")
    dispatcher = IntentDispatcher(whatsapp_id, "/logout")
    print(f"Reply: {dispatcher.dispatch()}")

if __name__ == "__main__":
    test_bot()
