# Generated by Django 2.2.11 on 2020-05-22 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_care_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylocalgovtbody',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitylocalgovtbody',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitylocalgovtbody',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facilityuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilityuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilityuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
