# Generated by Django 2.2.11 on 2020-05-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0002_care_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.FacilityType"
            ),
        ),
    ]
