# Generated by Django 2.2.11 on 2020-05-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_care_platform'),
        ('facility', '0002_care_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the Testing Lab', max_length=255)),
                ('address', models.TextField()),
                ('lab_type', models.IntegerField(choices=[(1, 'A1C'), (2, 'BLOOD COUNT TESTS'), (3, 'DIAGNOSTIC IMAGING'), (4, 'HEPATITIS TESTING'), (5, 'KIDNEY TESTS'), (6, 'THYROID TESTS'), (7, 'URINALYSIS')], default=2)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labs', to='accounts.District')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
