# Generated by Django 2.2.11 on 2020-05-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0009_auto_20200530_2203"),
        ("facility", "0009_auto_20200530_2150"),
    ]

    operations = []
