# Generated by Django 2.2.11 on 2020-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0010_auto_20200530_2249"),
        ("facility", "0010_merge_20200530_2218"),
    ]

    operations = []
