# Generated by Django 2.2.11 on 2020-05-31 04:20

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0011_merge_20200530_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=fernet_fields.fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='testinglab',
            name='address',
            field=fernet_fields.fields.EncryptedTextField(default=''),
        ),
    ]
