# Generated by Django 2.2.11 on 2020-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_care_platform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpatient", old_name="age", new_name="month",
        ),
        migrations.RenameField(model_name="patient", old_name="age", new_name="month",),
        migrations.AddField(
            model_name="historicalpatient",
            name="clinical_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="portea_able_to_connect",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="portea_called_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="clinical_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="portea_able_to_connect",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="portea_called_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="aadhar_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Aadhar Number of Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="20",
                max_length=4,
                verbose_name="Blood Group of Patient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="disease_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "NOT TESTED YET"),
                    (2, "SUSPECTED"),
                    (3, "POSITIVE"),
                    (4, "NEGATIVE"),
                    (5, "RECOVERY"),
                    (6, "RECOVERED"),
                    (7, "EXPIRED"),
                ],
                default=1,
                verbose_name="Disease Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="nationality",
            field=models.CharField(
                default="indian", max_length=255, verbose_name="Nationality of Patient"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="passport_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Passport Number of Foreign Patients",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="aadhar_no",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Aadhar Number of Patient",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="20",
                max_length=4,
                verbose_name="Blood Group of Patient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="disease_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "NOT TESTED YET"),
                    (2, "SUSPECTED"),
                    (3, "POSITIVE"),
                    (4, "NEGATIVE"),
                    (5, "RECOVERY"),
                    (6, "RECOVERED"),
                    (7, "EXPIRED"),
                ],
                default=1,
                verbose_name="Disease Status",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nationality",
            field=models.CharField(
                default="indian", max_length=255, verbose_name="Nationality of Patient"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_no",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Passport Number of Foreign Patients",
            ),
        ),
        migrations.AlterField(
            model_name="patientconsultation",
            name="admitted_to",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "NOT ADMITTED"),
                    (1, "INWARD WITHOUT OXYGEN"),
                    (2, "INWARD WITH OXYGEN"),
                    (3, "ISOLATION ROOM"),
                    (4, "ICU WITHOUT VENTILATOR"),
                    (5, "ICU WITH VENTILATOR"),
                    (6, "HOME ISOLATION"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
