# Generated by Django 2.2.11 on 2020-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_care_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatient",
            name="aadhar_no",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Aadhar Number of Patient"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="age",
            field=models.PositiveIntegerField(default="20"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="20",
                max_length=4,
                verbose_name="Blood Group of Patient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="nationality",
            field=models.CharField(
                max_length=255, verbose_name="Nationality of Patient"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="passport_no",
            field=models.CharField(
                db_index=True,
                max_length=255,
                verbose_name="Passport Number of Foreign Patients",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="aadhar_no",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Aadhar Number of Patient"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(default="20"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="20",
                max_length=4,
                verbose_name="Blood Group of Patient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="nationality",
            field=models.CharField(
                max_length=255, verbose_name="Nationality of Patient"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_no",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="Passport Number of Foreign Patients",
            ),
        ),
    ]
