# Generated by Django 2.2.11 on 2020-05-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0007_care_platform"),
        ("patients", "0006_care_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSampleTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "result",
                    models.IntegerField(
                        choices=[
                            (1, "SAMPLE SENT"),
                            (2, "POSITIVE"),
                            (3, "NEGATIVE"),
                            (4, "PRESUMPTIVE POSITIVE"),
                            (5, "AWAITING"),
                            (6, "TEST INCONCLUSIVE"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "date_of_sample",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date at which sample tested"
                    ),
                ),
                (
                    "date_of_result",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date of result of sample"
                    ),
                ),
                (
                    "status_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date at which sample updated"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="patients.Patient",
                    ),
                ),
                (
                    "testing_lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labs",
                        to="facility.TestingLab",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
