# Generated by Django 2.2.11 on 2020-05-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_auto_20200524_2119"),
        ("patients", "0007_care_platform"),
    ]

    operations = []
