# Generated by Django 2.2.11 on 2020-05-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_merge_20200524_2233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portiecallingdetail",
            name="called_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
