# Generated by Django 2.2.11 on 2020-05-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_auto_20200530_2150"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="patient_search_id",),
    ]
