# Generated by Django 2.2.11 on 2020-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0012_remove_patient_patient_search_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatient",
            name="phone_number_belongs_to",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number_belongs_to",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
