# Generated by Django 2.2.11 on 2020-05-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20200531_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='facility',
        ),
    ]
