# Generated by Django 2.2.11 on 2020-05-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20200531_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='govt_id',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='icmr_id',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='govt_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='icmr_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
