# Generated by Django 2.2.11 on 2020-05-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0001_care_platform"),
    ]

    operations = [
        migrations.RemoveField(model_name="ownershiptype", name="active",),
        migrations.RemoveField(model_name="ownershiptype", name="created_at",),
        migrations.RemoveField(model_name="ownershiptype", name="updated_at",),
    ]
