from django.core.management import BaseCommand

from care.facility.models.patient_investigation import (
    PatientInvestigation,
    PatientInvestigationGroup,
)

investigations = [
    {
        "name": "Blood Group",
        "investigation_type": "Choice",
        "choices": "A-,A+,B+,B-,O+,O-,AB-,AB+",
        "category_id": "1",
    },
    {
        "name": "Total Count",
        "unit": "cell/cumm",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Neutrophil count",
        "unit": "cell/cumm",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Lymphocyte count Eosinophil count",
        "unit": "cell/cumm",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Eosinophil count",
        "unit": "cell/cumm",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Basophil count",
        "unit": "cell/cumm",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Monocyte count",
        "unit": "cell/cumm",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "neutrophil",
        "unit": "%",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "lymphocyte",
        "unit": "%",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "eosinophil",
        "unit": "%",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "basophile",
        "unit": "%",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "monocyte",
        "unit": "%",
        "ideal_value": "4500-11000 cells/cumm",
        "min_value": 4500.0,
        "max_value": 11000.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Hb",
        "unit": "gm%",
        "ideal_value": "men 14-17 gm% , woman 12-16 gm% ,children 12-14 gm%",
        "min_value": 12.0,
        "max_value": 17.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "PCV",
        "unit": "%",
        "ideal_value": "Men 38-51 gm% , Woman 36-47%",
        "min_value": 36.0,
        "max_value": 51.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "RBC count",
        "unit": "million/cumm",
        "ideal_value": "4.5-6.0 million/cumm",
        "min_value": 4.5,
        "max_value": 6.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "RDW",
        "unit": "%",
        "ideal_value": "11.8 - 16.1%",
        "min_value": 11.8,
        "max_value": 16.1,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Platelets",
        "unit": "lakhs/cumm",
        "ideal_value": "1.5-4.5 lakhs/cumm",
        "min_value": 1.5,
        "max_value": 4.5,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "MCV",
        "unit": "Fl",
        "ideal_value": "80-96 Fl",
        "min_value": 80.0,
        "max_value": 96.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "MCH",
        "unit": "pg",
        "ideal_value": "27-33 pg",
        "min_value": 27.0,
        "max_value": 33.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "MCHC",
        "unit": "g/dl",
        "ideal_value": "33.4-35.5 g/dl",
        "min_value": 33.4,
        "max_value": 35.5,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "ESR",
        "unit": "mm/hr",
        "ideal_value": "0-20 mm/hr",
        "min_value": 0.0,
        "max_value": 20.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {
        "name": "Peripheral blood smear",
        "investigation_type": "String",
        "category_id": "1",
    },
    {
        "name": "Reticulocyte count",
        "unit": "%",
        "ideal_value": "adults 0.5-1.5%, newborns 3-6%",
        "min_value": 0.5,
        "max_value": 6.0,
        "investigation_type": "Float",
        "category_id": "1",
    },
    {"name": "M P smear", "investigation_type": "String", "category_id": "1"},
    {
        "name": "FBS",
        "unit": "mg/dl",
        "ideal_value": "70-110 mg/dl",
        "min_value": 70.0,
        "max_value": 110.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "PPBS",
        "unit": "mg/dl",
        "ideal_value": "< 140 mg/dl",
        "min_value": 0.0,
        "max_value": 140.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "RBS",
        "unit": "mg/dl",
        "ideal_value": "80-120 mg/dl",
        "min_value": 80.0,
        "max_value": 120.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "T. Cholestrol",
        "unit": "mg/dl",
        "ideal_value": "150-220 mg/dl",
        "min_value": 150.0,
        "max_value": 220.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "LDL",
        "unit": "mg/dl",
        "ideal_value": "< 130 mg/dl",
        "min_value": 0.0,
        "max_value": 130.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "HDL",
        "unit": "mg/dl",
        "ideal_value": "male 35-80 mg/dl, female 40-88 mg/dl",
        "min_value": 35.0,
        "max_value": 88.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Triglycerides",
        "unit": "mg/dl",
        "ideal_value": "male 60-165 mg/dl, female 40-140 mg/dl",
        "min_value": 40.0,
        "max_value": 165.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "VLDL",
        "unit": "mg/dl",
        "ideal_value": "2-30 mg/dl",
        "min_value": 2.0,
        "max_value": 30.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Urea",
        "unit": "mg/dl",
        "ideal_value": "10-50 mg/dl",
        "min_value": 10.0,
        "max_value": 50.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Uric Acid",
        "unit": "mg/dl",
        "ideal_value": "male 3.5-7.2 mg/dl, female 2.6-6 mg/dl",
        "min_value": 2.6,
        "max_value": 7.2,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Creatinine",
        "unit": "mg/dl",
        "ideal_value": "male 0.7-1.4 mg/dl, female 0.6-1.2 mg/dl",
        "min_value": 0.6,
        "max_value": 1.4,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "CRP",
        "unit": "mg/l",
        "ideal_value": "upto 6 mg/l",
        "min_value": 0.0,
        "max_value": 6.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Sodium (Na+)",
        "unit": "mmol/l",
        "ideal_value": "135-155 mmol/l",
        "min_value": 135.0,
        "max_value": 155.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Potassium (K+)",
        "unit": "mmol/l",
        "ideal_value": "3.5 - 5.5 mmol/l",
        "min_value": 3.5,
        "max_value": 5.5,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Calcium",
        "unit": "mg/dl",
        "ideal_value": "8.8-10.2 mg/dl",
        "min_value": 8.8,
        "max_value": 10.2,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Phosphorus",
        "unit": "mg/dl",
        "ideal_value": "children 4-7 mg/dl, adult 2.5-4.5 mg/dl",
        "min_value": 2.5,
        "max_value": 7.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Chloride",
        "unit": "mmol/l",
        "ideal_value": "96-109 mmol/l",
        "min_value": 96.0,
        "max_value": 109.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Megnesium",
        "unit": "mg/dl",
        "ideal_value": "1.6-2.6 mg/dl",
        "min_value": 1.6,
        "max_value": 2.6,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Total Bilirubin",
        "unit": "mg/dl",
        "ideal_value": "adult upto 1.2 mg/dl, infant 0.2-8 mg/dl",
        "min_value": 0.2,
        "max_value": 8.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Direct Bilirubin",
        "unit": "mg/dl",
        "ideal_value": "upto 0.4 mg/dl",
        "min_value": 0.0,
        "max_value": 0.4,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "SGOT",
        "unit": "IU/L",
        "ideal_value": "upto 46 IU/L",
        "min_value": 0.0,
        "max_value": 46.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "SGPT",
        "unit": "IU/L",
        "ideal_value": "upto 49 IU/L",
        "min_value": 0.0,
        "max_value": 49.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "ALP",
        "unit": "IU/L",
        "ideal_value": "male 80-306 IU/L, female 64-306 IU/L",
        "min_value": 64.0,
        "max_value": 306.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Total Protein",
        "unit": "g/dl",
        "ideal_value": "6-8 g/dl",
        "min_value": 6.0,
        "max_value": 8.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Albumin",
        "unit": "g/dl",
        "ideal_value": "3.5-5.2 g/dl",
        "min_value": 3.5,
        "max_value": 5.2,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Globulin",
        "unit": "g/dl",
        "ideal_value": "1.5-2.5 g/dl",
        "min_value": 1.5,
        "max_value": 2.5,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "PT",
        "unit": "sec",
        "ideal_value": "9.1-12.1 seconds",
        "min_value": 9.1,
        "max_value": 12.1,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "INR",
        "unit": "sec",
        "ideal_value": "0.8-1.1 seconds",
        "min_value": 0.8,
        "max_value": 1.1,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "APTT",
        "unit": "sec",
        "ideal_value": "25.4-38.4 seconds",
        "min_value": 25.4,
        "max_value": 38.4,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "D-Dimer",
        "unit": "ug/l",
        "ideal_value": "< 0.5 ug/l",
        "min_value": 0.0,
        "max_value": 0.5,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Fibrinogen",
        "unit": "mg/dl",
        "ideal_value": "200-400 mg/dl",
        "min_value": 200.0,
        "max_value": 400.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "GCT",
        "unit": "mg/dl",
        "ideal_value": "< 140 mg/dl",
        "min_value": 0.0,
        "max_value": 140.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "GTT",
        "unit": "mg/dl",
        "ideal_value": "140-200 mg/dl",
        "min_value": 140.0,
        "max_value": 200.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "GGT",
        "unit": "U/L",
        "ideal_value": "11-50 U/L",
        "min_value": 11.0,
        "max_value": 50.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "HbA1C",
        "unit": "%",
        "ideal_value": "4-5.6 %",
        "min_value": 4.0,
        "max_value": 5.6,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Copper",
        "unit": "mcg/dl",
        "ideal_value": "85-180 mcg/dl",
        "min_value": 85.0,
        "max_value": 180.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum Lead",
        "unit": "mcg/dl",
        "ideal_value": "upto 10 mcg/dl",
        "min_value": 0.0,
        "max_value": 10.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Iron",
        "unit": "mcg/dl",
        "ideal_value": "60-170 mcg/dl",
        "min_value": 60.0,
        "max_value": 170.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "TIBC",
        "unit": "mcg/dl",
        "ideal_value": "250-450 mcg/dl",
        "min_value": 250.0,
        "max_value": 450.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Transferin Saturation",
        "unit": "%",
        "ideal_value": "15-50 %",
        "min_value": 15.0,
        "max_value": 50.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "IL6",
        "unit": "pg/ml",
        "ideal_value": "0-16.4 pg/ml",
        "min_value": 0.0,
        "max_value": 16.4,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Lactate",
        "unit": "mmol/l",
        "ideal_value": "0.5-1 mmol/l",
        "min_value": 0.5,
        "max_value": 1.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Ceruloplasmin",
        "unit": "mg/dl",
        "ideal_value": "14-40 mg/dl",
        "min_value": 14.0,
        "max_value": 40.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "ACP",
        "unit": "U/L",
        "ideal_value": "0.13-0.63 U/L",
        "min_value": 0.13,
        "max_value": 0.63,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Protein C",
        "unit": "IU dl 1",
        "ideal_value": "65-135 IU dl 1",
        "min_value": 65.0,
        "max_value": 135.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Protein S",
        "unit": "%",
        "ideal_value": "70-140 %",
        "min_value": 70.0,
        "max_value": 140.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "G6PD",
        "unit": "U/g Hb",
        "ideal_value": "neonate 10.15-14.71 U/g Hb, adult 6.75-11.95 U/g Hb",
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "ACCP",
        "unit": "EU/ml",
        "ideal_value": "< 20 EU/ml",
        "min_value": 0.0,
        "max_value": 20.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Ferritin",
        "unit": "ng/ml",
        "ideal_value": "20-250 ng/ml",
        "min_value": 20.0,
        "max_value": 250.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "LDH",
        "unit": "U/L",
        "ideal_value": "140-280 U/L",
        "min_value": 140.0,
        "max_value": 280.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Amylase",
        "unit": "U/L",
        "ideal_value": "60-180 U/L",
        "min_value": 60.0,
        "max_value": 180.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Lipase",
        "unit": "U/L",
        "ideal_value": "0-160 U/L",
        "min_value": 0.0,
        "max_value": 160.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Ammonia",
        "unit": "ug/dL",
        "ideal_value": "15-45 ug/dL",
        "min_value": 15.0,
        "max_value": 45.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "CKMB",
        "unit": "IU/L",
        "ideal_value": "5-25 IU/L",
        "min_value": 5.0,
        "max_value": 25.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "CK NAC",
        "unit": "U/L",
        "ideal_value": "male < 171 U/L, female < 145 U/L",
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "24hrs Urine Protein",
        "unit": "mg/dl",
        "ideal_value": "<10 mg/dl",
        "min_value": 0.0,
        "max_value": 10.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "24hrs Urine Uric Acid",
        "unit": "mg/24hr",
        "ideal_value": "250-750 mg/24hr",
        "min_value": 250.0,
        "max_value": 750.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "24 hrs Urine Oxalate",
        "unit": "mg/L",
        "ideal_value": "<15 mg/L",
        "min_value": 0.0,
        "max_value": 15.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Urine Microalbumin",
        "unit": "mg",
        "ideal_value": "< 30 mg",
        "min_value": 0.0,
        "max_value": 30.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Urine Sodium",
        "unit": "mEq/day",
        "ideal_value": "40-220 mEq/day",
        "min_value": 40.0,
        "max_value": 220.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "PCT",
        "unit": "ng/ml",
        "ideal_value": "< 0.15 ng/ml",
        "min_value": 0.0,
        "max_value": 0.15,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "T3",
        "unit": "ng/dl",
        "ideal_value": "80-220 ng/dl",
        "min_value": 80.0,
        "max_value": 220.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "T4",
        "unit": "ug/L",
        "ideal_value": "5-12 ug/L",
        "min_value": 5.0,
        "max_value": 12.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "TSH",
        "unit": "mIU/L",
        "ideal_value": "0.5-5 mIU/L",
        "min_value": 0.5,
        "max_value": 5.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "FT3",
        "unit": "ng/dl",
        "ideal_value": "60-180 ng/dl",
        "min_value": 60.0,
        "max_value": 180.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "FT4",
        "unit": "ng/dl",
        "ideal_value": "0.7-1.9 ng/dl",
        "min_value": 0.7,
        "max_value": 1.9,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Estradiol",
        "unit": "pg/ml",
        "ideal_value": "premenopausal women 30-400 pg/ml, post-menopausal women 0-30 pg/ml, men 10-50 pg/ml",
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Growth Hormone",
        "unit": "ng/ml",
        "ideal_value": "male 0.4-10 ng/ml, female 1-14 ng/ml",
        "min_value": 0.4,
        "max_value": 14.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Cortisol",
        "unit": "mcg/dl",
        "ideal_value": "5-25 ng/ml",
        "min_value": 5.0,
        "max_value": 25.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "PTH",
        "unit": "pg/ml",
        "ideal_value": "14-65 pg/ml",
        "min_value": 14.0,
        "max_value": 65.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Prolactine",
        "unit": "ng/ml",
        "ideal_value": "male <20 ng/ml, female <25 ng/ml, pregnant women <300 ng/ml",
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Pro BNP",
        "unit": "pg/ml",
        "ideal_value": "< 300 pg/ml",
        "min_value": 0.0,
        "max_value": 300.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Vitamine D3",
        "unit": "ng/ml",
        "ideal_value": "20-40 ng/ml",
        "min_value": 20.0,
        "max_value": 40.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Vitamine B12",
        "unit": "pg/ml",
        "ideal_value": "160-950 pg/ml",
        "min_value": 160.0,
        "max_value": 950.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "FSH",
        "unit": "IU/L",
        "ideal_value": "before puberty 0-4 IU/L, during puberty 0.36-10 IU/L, ",
        "min_value": 0.0,
        "max_value": 10.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "LH",
        "unit": "IU/L",
        "ideal_value": "before menopause 5-25 IU/L, after menopause 14.2-52.3 IU/L",
        "min_value": 5.0,
        "max_value": 52.3,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "PSA",
        "unit": "ng/ml",
        "ideal_value": "<4 ng/ml",
        "min_value": 0.0,
        "max_value": 4.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "ACTH",
        "unit": "pg/ml",
        "ideal_value": "10-60 pg/ml",
        "min_value": 10.0,
        "max_value": 60.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "CEA",
        "unit": "ng/ml",
        "ideal_value": "0-2.5 ng/ml",
        "min_value": 0.0,
        "max_value": 2.5,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "AFP",
        "unit": "ng/ml",
        "ideal_value": "10-20 ng/ml",
        "min_value": 10.0,
        "max_value": 20.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "CA125",
        "unit": "U/ml",
        "ideal_value": "< 46 U/ml",
        "min_value": 0.0,
        "max_value": 46.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "CA19.9",
        "unit": "U/ml",
        "ideal_value": "0-37 U/ml",
        "min_value": 0.0,
        "max_value": 37.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Testosterone ",
        "unit": "ng/dl",
        "ideal_value": "270-1070 ng/dl",
        "min_value": 270.0,
        "max_value": 1070.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Progestrone",
        "unit": "ng/ml",
        "ideal_value": "female pre ovulation, menupausal women, men <1 ng/ml, mid-cycle 5-20 ng/ml",
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum IgG",
        "unit": "g/L",
        "ideal_value": "6-16 g/L",
        "min_value": 6.0,
        "max_value": 16.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum IgE",
        "unit": "UL/ml",
        "ideal_value": "150-1000 UL/ml",
        "min_value": 150.0,
        "max_value": 1000.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum IgM",
        "unit": "g/L",
        "ideal_value": "0.4-2.5 g/L",
        "min_value": 0.4,
        "max_value": 2.5,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {
        "name": "Serum IgA",
        "unit": "G/L",
        "ideal_value": "0.8-3 g/L",
        "min_value": 0.8,
        "max_value": 3.0,
        "investigation_type": "Float",
        "category_id": "2",
    },
    {"name": "Colour", "investigation_type": "String", "category_id": "3"},
    {"name": "Appearence", "investigation_type": "String", "category_id": "3"},
    {"name": "Ph", "investigation_type": "String", "category_id": "3"},
    {"name": "Specific Gravity", "investigation_type": "String", "category_id": "3"},
    {"name": "Nitrite", "investigation_type": "String", "category_id": "3"},
    {"name": "Urobilinogen", "investigation_type": "String", "category_id": "3"},
    {"name": "Bile Salt", "investigation_type": "String", "category_id": "3"},
    {"name": "Bile Pigment", "investigation_type": "String", "category_id": "3"},
    {"name": "Acetone", "investigation_type": "String", "category_id": "3"},
    {"name": "Albumin", "investigation_type": "String", "category_id": "3"},
    {"name": "Sugar", "investigation_type": "String", "category_id": "3"},
    {"name": "Puscells", "investigation_type": "String", "category_id": "3"},
    {"name": "Epithetical Cells", "investigation_type": "String", "category_id": "3"},
    {"name": "RBC ", "investigation_type": "String", "category_id": "3"},
    {"name": "Cast", "investigation_type": "String", "category_id": "3"},
    {"name": "Crystal", "investigation_type": "String", "category_id": "3"},
    {"name": "others", "investigation_type": "String", "category_id": "3"},
    {"name": "UPT", "investigation_type": "String", "category_id": "3"},
    {"name": "Stool OB", "investigation_type": "String", "category_id": "3"},
    {"name": "Stool Microscopy", "investigation_type": "String", "category_id": "3"},
]

investigation_groups = [
    {"id": "1", "name": "Haematology"},
    {"id": "2", "name": "Biochemistry test"},
    {"id": "3", "name": "Urine Test"},
    {"id": "4", "name": "CBC"},
    {"id": "5", "name": "Differential white blood cell count"},
    {"id": "6", "name": "Liver Function Test"},
    {"id": "7", "name": "Kidney Function test"},
]


def none_or_float(val):
    if len(val.strip()) != 0:
        return float(val)
    return None


class Command(BaseCommand):
    """
    Populates Investigation seed data
    """

    help = "Seed Data for Investigations"

    def handle(self, *args, **options):
        investigation_group_dict = {}
        for investigation_group in investigation_groups:
            current_obj = PatientInvestigationGroup.objects.filter(
                name=investigation_group.get("name")
            ).first()
            if not current_obj:
                current_obj = PatientInvestigationGroup(
                    name=investigation_group.get("name")
                )
                current_obj.save()
            investigation_group_dict[investigation_group.get("id")] = current_obj

        for investigation in investigations:
            data = {
                "name": investigation["name"],
                "unit": investigation.get("unit", ""),
                "ideal_value": investigation.get("ideal_value", ""),
                "min_value": none_or_float(str(investigation.get("min_value", ""))),
                "max_value": none_or_float(str(investigation.get("max_value", ""))),
                "investigation_type": investigation["investigation_type"],
                "choices": investigation.get("choices", ""),
            }
            current_obj = PatientInvestigation.objects.filter(**data).first()
            if not current_obj:
                current_obj = PatientInvestigation(**data)
                current_obj.save()
            current_obj.groups.add(
                investigation_group_dict[investigation.get("category_id")]
            )
            current_obj.save()
