# Generated by Django 5.1.4 on 2025-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_migrate_default_role_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='rolemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name',), name='unique_name_if_not_deleted'),
        ),
    ]
