# Generated by Django 5.1.4 on 2025-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_rolemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
