# Generated by Django 6.0 on 2026-03-18 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_default_roles_contexts(apps, schema_editor):
    RoleModel = apps.get_model("security", "RoleModel")
    for roles in RoleModel.objects.all():
        roles.contexts = ["FACILITY" , "GOVT_ORG"]
        roles.save(update_fields=["contexts"])

class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_rolemodel_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='contexts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=list),
        ),
        migrations.RunPython(migrate_default_roles_contexts, reverse_code=migrations.RunPython.noop),
    ]
