# Generated by Django 2.2.11 on 2020-03-21 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_deleted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
