# Generated by Django 2.2.11 on 2020-03-27 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_restart_sequence_districts"),
        ("users", "0013_auto_20200326_2021"),
    ]

    operations = []
