# Generated by Django 2.2.11 on 2020-04-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_auto_20200328_2226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.District",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="local_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.LocalBody",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.State",
            ),
        ),
    ]
