# Generated by Django 2.2.11 on 2020-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_auto_20201011_1908"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pf_auth",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pf_endpoint",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pf_p256dh",
            field=models.TextField(default=None, null=True),
        ),
    ]
