# Generated by Django 2.2.11 on 2021-05-11 15:35

from django.db import migrations, models

import care.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0034_auto_20201122_2013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[care.users.models.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
