# Generated by Django 2.2.11 on 2021-06-16 12:51

import partial_index
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_auto_20210616_1634"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userskill",
            index=partial_index.PartialIndex(
                fields=["skill", "user"],
                name="users_users_skill_i_6ebc32_partial",
                unique=True,
                where=partial_index.PQ(deleted=False),
            ),
        ),
    ]
