# Generated by Django 2.2.11 on 2022-03-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0285_asset_asset_class"),
        ("users", "0040_auto_20210616_1821"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.Asset",
                unique=True,
            ),
        ),
    ]
