# Generated by Django 2.2.11 on 2022-06-24 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_user_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localbody",
            options={
                "verbose_name": "Local Body",
                "verbose_name_plural": "Local Bodies",
            },
        ),
    ]
