# Generated by Django 2.2.11 on 2021-04-26 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('WORKING', 'WORKING'), ('FAILED', 'FAILED'), ('STOPPED', 'STOPPED')], default='PENDING', max_length=100)),
                ('next_runtime', models.DateTimeField(auto_now_add=True)),
                ('periodicity', models.IntegerField(default=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('last_errors', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('data_id', models.IntegerField()),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('resource_type', models.TextField()),
                ('address', models.TextField()),
                ('phone_1', models.TextField()),
                ('phone_2', models.TextField()),
                ('email', models.TextField()),
                ('district', models.TextField()),
                ('state', models.TextField()),
                ('quantity_available', models.TextField()),
                ('price', models.TextField()),
                ('source_link', models.TextField()),
                ('comment', models.TextField()),
                ('created_by', models.TextField()),
                ('Verified_by', models.TextField()),
                ('last_verified_on', models.TextField()),
                ('downvotes', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='life.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
