# Generated by Django 2.2.11 on 2021-04-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
