# Generated by Django 2.2.11 on 2021-04-30 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_lifedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email_next_sendtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='email_periodicity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='job',
            name='suppress_emails',
            field=models.BooleanField(default=False),
        ),
    ]
