# Generated by Django 2.2.11 on 2021-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0010_auto_20210501_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifedata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifedata',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lifedata',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
