# Generated by Django 2.2.11 on 2020-03-19 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0002_auto_20200319_1244"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="bed_capacity",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="icu_capacity",
        ),
        migrations.RemoveField(
            model_name="facilitylocation",
            name="district",
        ),
        migrations.AddField(
            model_name="facility",
            name="district",
            field=models.IntegerField(
                choices=[
                    (1, "Thiruvananthapuram"),
                    (2, "Kollam"),
                    (3, "Pathanamthitta"),
                    (4, "Alappuzha"),
                    (5, "Kottayam"),
                    (6, "Idukki"),
                    (7, "Ernakulam"),
                    (8, "Thrissur"),
                    (9, "Palakkad"),
                    (10, "Malappuram"),
                    (11, "Kozhikode"),
                    (12, "Wayanad"),
                    (13, "Kannur"),
                    (14, "Kasaragod"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facility",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FacilityCapacity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.IntegerField(
                        choices=[(1, "Normal"), (10, "ICU"), (20, "ICCU")]
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.Facility",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
