# Generated by Django 2.2.11 on 2020-04-11 21:15
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0083_auto_20200411_1136"),
    ]

    operations = [TrigramExtension()]
