# Generated by Django 2.2.11 on 2022-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0303_patientconsultation_procedure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientconsultation",
            name="discharge_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REC", "Recovered"),
                    ("REF", "Referred"),
                    ("EXP", "Expired"),
                    ("LAMA", "LAMA"),
                ],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
    ]
