# Generated by Django 2.2.11 on 2022-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0312_patientconsultation_investigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="features",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "CT Scan Facility"),
                    (2, "Maternity Care"),
                    (3, "X-Ray facility"),
                    (4, "Neonatal care"),
                    (5, "Operation theater"),
                    (6, "Blood Bank"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
