# Generated by Django 2.2.11 on 2022-10-12 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0323_fileupload_archive_reason"),
        ("facility", "0322_patientconsultation_review_interval"),
    ]

    operations = []
