# Generated by Django 2.2.11 on 2022-10-15 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0324_merge_20221013_0053"),
        ("facility", "0316_auto_20220909_2331"),
    ]

    operations = []
