# Generated by Django 2.2.11 on 2022-11-27 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0326_auto_20221018_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="archived_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
