# Generated by Django 2.2.11 on 2023-01-12 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0332_auto_20230110_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="death_confirmed_doctor",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="death_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
