# Generated by Django 2.2.11 on 2023-01-13 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0332_patientconsultation_consultation_status"),
        ("facility", "0333_auto_20230112_2233"),
    ]

    operations = []
