# Generated by Django 2.2.11 on 2023-04-06 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0338_auto_20230323_1249"),
        ("facility", "0336_patientconsultation_op_no"),
    ]

    operations = []
