# Generated by Django 2.2.11 on 2023-04-07 08:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0341_auto_20230407_0346"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="discharge_prescription",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="discharge_prn_prescription",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
