# Generated by Django 2.2.11 on 2023-04-19 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0345_auto_20230414_2046"),
        ("facility", "0337_metaicd11diagnosis"),
    ]

    operations = []
