# Generated by Django 6.0 on 2026-05-28 18:55

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    replaces = [('users', '0027_user_cached_role_orgs')]

    dependencies = [
        ('users', '0001_squashed_02'),
        ('emr', '0001_squashed_02'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geo_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.organization'),
        ),
    ]
