# Generated by Django 6.0 on 2026-05-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_squashed_02'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveConstraint(
            model_name='userskill',
            name='unique_user_skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_facility',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_gender',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
