# Generated by Django 4.2.2 on 2023-07-13 09:06

from django.db import migrations


def fill_user_facility_allocation(apps, schema_editor):
    UserFacilityAllocation = apps.get_model("users", "UserFacilityAllocation")
    User = apps.get_model("users", "User")
    users = User.objects.filter(home_facility__isnull=False)

    to_create = [
        UserFacilityAllocation(
            user=user, facility=user.home_facility, start_date=user.date_joined
        )
        for user in users
    ]
    UserFacilityAllocation.objects.bulk_create(to_create, batch_size=2000)


def reverse_fill_user_facility_allocation(apps, schema_editor):
    UserFacilityAllocation = apps.get_model("users", "UserFacilityAllocation")
    UserFacilityAllocation.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userfacilityallocation"),
    ]

    operations = [
        migrations.RunPython(
            fill_user_facility_allocation, reverse_fill_user_facility_allocation
        ),
    ]
