# Generated by Django 4.2.2 on 2023-08-17 14:07

from django.db import migrations


def rename_skill_and_add_new(apps, schema_editor):
    Skill = apps.get_model("users", "Skill")
    Skill.objects.filter(name="Genreal Surgeon").update(name="General Surgeon")

    Skill.objects.get_or_create(name="General Medicine")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_alt_phone_number_alter_user_phone_number"),
    ]

    operations = [
        migrations.RunPython(rename_skill_and_add_new),
    ]
