# Generated by Django 4.2.5 on 2023-10-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_userfacilityallocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[
                    (2, "Transportation"),
                    (3, "Pharmacist"),
                    (5, "Volunteer"),
                    (7, "StaffReadOnly"),
                    (8, "Staff"),
                    (9, "NurseReadOnly"),
                    (10, "Nurse"),
                    (15, "Doctor"),
                    (20, "Reserved"),
                    (21, "WardAdmin"),
                    (23, "LocalBodyAdmin"),
                    (25, "DistrictLabAdmin"),
                    (29, "DistrictReadOnlyAdmin"),
                    (30, "DistrictAdmin"),
                    (35, "StateLabAdmin"),
                    (39, "StateReadOnlyAdmin"),
                    (40, "StateAdmin"),
                ]
            ),
        ),
    ]
