# Generated by Django 4.2.2 on 2023-09-26 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_user_type"),
        ("users", "0009_userfacilityallocation"),
    ]

    operations = []
