# Generated by Django 4.2.5 on 2023-12-15 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_merge_20230926_2015"),
        ("users", "0010_rename_skills"),
    ]

    operations = []
