# Generated by Django 4.2.6 on 2023-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="video_connect_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
