# Generated by Django 2.2.11 on 2020-03-25 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_map_users_to_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='new_district',
            new_name='district'
        ),
    ]
