# Generated by Django 4.2.5 on 2024-01-07 15:15

from django.db import migrations

from care.users.models import User



class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_user_type"),
    ]

    operations = [
    ]
