# Generated by Django 2.2.11 on 2020-03-27 06:44

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fixes issues caused by users.0010_populate_district
    Run only if the DB is PostgreSQL
    """

    dependencies = [
        ('users', '0013_auto_20200327_0437'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER SEQUENCE users_district_id_seq RESTART WITH 15;"
        )
    ]
