# Generated by Django 4.2.10 on 2024-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_upgrade_user_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
