# Generated by Django 4.2.10 on 2024-03-02 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_age_to_dateofbirth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
    ]
