# Generated by Django 5.1.1 on 2024-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_userflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
