# Generated by Django 5.1.1 on 2024-10-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_profile_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doctor_qualification',
            new_name='qualification',
        ),
    ]
