# Generated by Django 5.1.3 on 2024-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_plugconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
