# Generated by Django 5.1.4 on 2025-01-21 11:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_gender_user_old_gender_user_geo_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qualification',
            new_name='qualification_old',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='doctor_experience_commenced_on',
            new_name='doctor_experience_commenced_on_old',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='doctor_medical_council_registration',
            new_name='doctor_medical_council_registration_old',
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.JSONField(blank=False, default=dict),
        ),
    ]
