# Generated by Django 5.1.3 on 2024-12-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
