# Generated by Django 5.1.4 on 2025-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_gender_user_old_gender_user_geo_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
