# Generated by Django 5.1.4 on 2025-03-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_mfa_settings_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
