# Generated by Django 5.1.4 on 2025-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_prefix_user_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='odoo_agent_id',
            field=models.IntegerField(blank=True, help_text='Odoo agent ID for users', null=True),
        ),
    ]
