# Generated by Django 5.1.4 on 2025-05-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_prefix_user_suffix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFlag',
        ),
    ]
