# Generated by Django 5.1.4 on 2025-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
