# Generated by Django 6.0 on 2026-01-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_user_district_remove_localbody_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_account',
            field=models.BooleanField(default=False),
        ),
    ]
