# Generated by Django 6.0 on 2026-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cached_role_orgs',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
