# Generated by Django 6.0 on 2026-04-27 08:54

import care.utils.models.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_cached_role_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=14, validators=[care.utils.models.validators.PhoneNumberValidator(types=('mobile', 'landline'))])),
                ('otp', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
