# Generated by Django 2.2.11 on 2020-09-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_auto_20200927_1325"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.Ward",
            ),
        ),
    ]
