# Generated by Django 2.2.11 on 2020-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_user_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[
                    (2, "Transportation"),
                    (3, "Pharmacist"),
                    (5, "Volunteer"),
                    (9, "StaffReadOnly"),
                    (10, "Staff"),
                    (15, "Doctor"),
                    (20, "Reserved"),
                    (21, "WardAdmin"),
                    (23, "LocalBodyAdmin"),
                    (25, "DistrictLabAdmin"),
                    (29, "DistrictReadOnlyAdmin"),
                    (30, "DistrictAdmin"),
                    (35, "StateLabAdmin"),
                    (39, "StateReadOnlyAdmin"),
                    (40, "StateAdmin"),
                ]
            ),
        ),
    ]
