# Generated by Django 2.2.11 on 2021-06-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210605_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localbody',
            options={'verbose_name_plural': 'local bodies'},
        ),
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='users.Division'),
        ),
    ]
