# Generated by Django 2.2.11 on 2021-06-16 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_auto_20210616_1634"),
    ]

    operations = []
