# Generated by Django 2.2.11 on 2021-08-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210616_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.District')),
            ],
            options={
                'unique_together': {('district', 'name', 'number')},
            },
        ),
    ]
