# Generated by Django 2.2.11 on 2021-08-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_localbody_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Block'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(2, 'Transportation'), (3, 'Pharmacist'), (5, 'Volunteer'), (9, 'StaffReadOnly'), (10, 'Staff'), (15, 'Doctor'), (20, 'Reserved'), (21, 'WardAdmin'), (23, 'LocalBodyAdmin'), (24, 'BlockAdmin'), (25, 'DistrictLabAdmin'), (29, 'DistrictReadOnlyAdmin'), (30, 'DistrictAdmin'), (35, 'StateLabAdmin'), (39, 'StateReadOnlyAdmin'), (40, 'StateAdmin')]),
        ),
    ]
