# Generated by Django 2.2.11 on 2023-06-09 08:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0046_auto_20230204_1733"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
