# Generated by Django 2.2.11 on 2023-02-22 16:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import care.utils.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("hcx", "0004_auto_20230222_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="items",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "category": {"type": "string"},
                                        "id": {"type": "string"},
                                        "name": {"type": "string"},
                                        "price": {"type": "number"},
                                    },
                                    "required": ["id", "name", "price"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
