# Generated by Django 2.2.11 on 2023-03-23 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hcx", "0005_auto_20230222_2217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claim_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policy_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
