# Generated by Django 2.2.11 on 2023-03-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0005_auto_20230222_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='outcome',
            field=models.CharField(blank=True, choices=[('queued', 'QUEUED'), ('complete', 'COMPLETE'), ('error', 'ERROR'), ('partial', 'PARTIAL_PROCESSING')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='priority',
            field=models.CharField(choices=[('stat', 'IMMEDIATE'), ('normal', 'NORMAL'), ('deferred', 'DEFERRED')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED'), ('draft', 'DRAFT'), ('entered-in-error', 'ENTERED_IN_ERROR')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('institutional', 'INSTITUTIONAL'), ('oral', 'ORAL'), ('pharmacy', 'PHARMACY'), ('professional', 'PROFESSIONAL'), ('vision', 'VISION')], default='institutional', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='use',
            field=models.CharField(choices=[('claim', 'CLAIM'), ('preauthorization', 'PRE_AUTHORIZATION'), ('predetermination', 'PRE_DETERMINATION')], default='claim', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('queued', 'QUEUED'), ('complete', 'COMPLETE'), ('error', 'ERROR'), ('partial', 'PARTIAL_PROCESSING')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='priority',
            field=models.CharField(choices=[('stat', 'IMMEDIATE'), ('normal', 'NORMAL'), ('deferred', 'DEFERRED')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='purpose',
            field=models.CharField(choices=[('auth-requirements', 'AUTH_REQUIREMENTS'), ('benefits', 'BENEFITS'), ('discovery', 'DISCOVERY'), ('validation', 'VALIDATION')], default='benefits', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED'), ('draft', 'DRAFT'), ('entered-in-error', 'ENTERED_IN_ERROR')], default='active', max_length=20),
        ),
    ]
