# Generated by Django 4.2.2 on 2023-06-17 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hcx", "0002_alter_claim_id_alter_claim_items_alter_policy_id"),
        ("hcx", "0007_communication"),
    ]

    operations = []
