# Generated by Django 4.2.2 on 2023-06-17 07:23

from django.db import migrations, models

import care.utils.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("hcx", "0008_merge_20230617_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="content",
            field=models.JSONField(
                default=list,
                null=True,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "content": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "data": {"type": "string"},
                                        "type": {"type": "string"},
                                    },
                                    "required": ["type", "data"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
