# Generated by Django 4.2.5 on 2023-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hcx", "0009_alter_communication_content_alter_communication_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("queued", "Queued"),
                    ("complete", "Complete"),
                    ("error", "Error"),
                    ("partial", "Partial Processing"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("draft", "Draft"),
                    ("entered-in-error", "Entered In Error"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="type",
            field=models.CharField(
                choices=[
                    ("institutional", "Institutional"),
                    ("oral", "Oral"),
                    ("pharmacy", "Pharmacy"),
                    ("professional", "Professional"),
                    ("vision", "Vision"),
                ],
                default="institutional",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="use",
            field=models.CharField(
                choices=[
                    ("claim", "Claim"),
                    ("preauthorization", "Pre Authorization"),
                    ("predetermination", "Pre Determination"),
                ],
                default="claim",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("queued", "Queued"),
                    ("complete", "Complete"),
                    ("error", "Error"),
                    ("partial", "Partial Processing"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("auth-requirements", "Auth Requirements"),
                    ("benefits", "Benefits"),
                    ("discovery", "Discovery"),
                    ("validation", "Validation"),
                ],
                default="benefits",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("draft", "Draft"),
                    ("entered-in-error", "Entered In Error"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
