# Generated by Django 4.2.2 on 2023-08-03 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hcx", "0006_auto_20230324_1328"),
        ("hcx", "0009_alter_communication_content_alter_communication_id"),
    ]

    operations = []
