# Generated by Django 4.2.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('hospital_staff', 'Hospital Staff'), ('unknown', 'Unknown')], max_length=20)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='emr.patient')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_sessions',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('medication_reminder', 'Medication Reminder'), ('test_result', 'Test Result'), ('discharge_summary', 'Discharge Summary'), ('system_alert', 'System Alert'), ('custom', 'Custom')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notifications', to='emr.patient')),
            ],
            options={
                'db_table': 'whatsapp_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('location', 'Location'), ('contact', 'Contact')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='care_whatsapp_bot.whatsappsession')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('command', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('verify_otp', 'Verify OTP'), ('get_records', 'Get Records'), ('get_medications', 'Get Medications'), ('get_appointments', 'Get Appointments'), ('get_procedures', 'Get Procedures'), ('patient_search', 'Patient Search'), ('patient_info', 'Patient Info'), ('schedule_appointment', 'Schedule Appointment'), ('help', 'Help'), ('menu', 'Menu'), ('unknown', 'Unknown')], max_length=30)),
                ('command_args', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='care_whatsapp_bot.whatsappmessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='care_whatsapp_bot.whatsappsession')),
            ],
            options={
                'db_table': 'whatsapp_commands',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappnotification',
            index=models.Index(fields=['phone_number', 'status'], name='whatsapp_no_phone__b8e7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnotification',
            index=models.Index(fields=['scheduled_at'], name='whatsapp_no_schedul_7b4b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnotification',
            index=models.Index(fields=['notification_type'], name='whatsapp_no_notific_c8a9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['phone_number', 'direction'], name='whatsapp_me_phone__a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['timestamp'], name='whatsapp_me_timesta_d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['processed'], name='whatsapp_me_process_g7h8i9_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcommand',
            index=models.Index(fields=['phone_number', 'command'], name='whatsapp_co_phone__j0k1l2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcommand',
            index=models.Index(fields=['executed_at'], name='whatsapp_co_execute_m3n4o5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcommand',
            index=models.Index(fields=['success'], name='whatsapp_co_success_p6q7r8_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['phone_number', 'is_authenticated'], name='whatsapp_se_phone__s9t0u1_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['last_activity'], name='whatsapp_se_last_ac_v2w3x4_idx'),
        ),
    ]