# Generated by Django 5.1.4 on 2025-07-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappcommand',
            new_name='whatsapp_co_phone_n_bd3fc4_idx',
            old_name='whatsapp_co_phone__j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappcommand',
            new_name='whatsapp_co_execute_871b9c_idx',
            old_name='whatsapp_co_execute_m3n4o5_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappcommand',
            new_name='whatsapp_co_success_53f988_idx',
            old_name='whatsapp_co_success_p6q7r8_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_me_phone_n_4806cd_idx',
            old_name='whatsapp_me_phone__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_me_timesta_230754_idx',
            old_name='whatsapp_me_timesta_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_me_process_174473_idx',
            old_name='whatsapp_me_process_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappnotification',
            new_name='whatsapp_no_phone_n_b64d05_idx',
            old_name='whatsapp_no_phone__b8e7a5_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappnotification',
            new_name='whatsapp_no_schedul_30f8b6_idx',
            old_name='whatsapp_no_schedul_7b4b8e_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappnotification',
            new_name='whatsapp_no_notific_c6c784_idx',
            old_name='whatsapp_no_notific_c8a9b2_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappsession',
            new_name='whatsapp_se_phone_n_d43859_idx',
            old_name='whatsapp_se_phone__s9t0u1_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappsession',
            new_name='whatsapp_se_last_ac_1b89e2_idx',
            old_name='whatsapp_se_last_ac_v2w3x4_idx',
        ),
    ]
