# Generated by Django 2.2.11 on 2021-05-09 05:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=511)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(choices=[(1, 'insert'), (0, 'update'), (-1, 'delete')])),
                ('model', models.CharField(max_length=127)),
                ('entity_id', models.CharField(max_length=127)),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit_log.Request')),
            ],
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_id'], name='al_request__idx__request_id'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(fields=('request_id',), name='al_request__uniq__request_id'),
        ),
    ]
