global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "django"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:9000"]
