# Generated by Django 6.0 on 2026-05-28 18:14

import care.utils.models.validators
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('facility', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('facility_type', models.IntegerField(choices=[(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (9, 'Govt Labs'), (10, 'Private Labs'), (800, 'Primary Health Centres'), (802, 'Family Health Centres'), (803, 'Community Health Centres'), (830, 'Taluk Hospitals'), (840, 'Women and Child Health Centres'), (860, 'District Hospitals'), (870, 'Govt Medical College Hospitals'), (900, 'Co-operative hospitals'), (910, 'Autonomous healthcare facility'), (1010, 'COVID-19 Domiciliary Care Center'), (1100, 'First Line Treatment Centre'), (1200, 'Second Line Treatment Center'), (1300, 'Shifting Centre'), (1400, 'Covid Management Center'), (1500, 'Request Approving Center'), (1510, 'Request Fulfilment Center'), (1600, 'District War Room'), (3000, 'Clinical Non Governmental Organization'), (3001, 'Non Clinical Non Governmental Organization'), (4000, 'Community Based Organization')])),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(1, 'CT Scan Facility'), (2, 'Maternity Care'), (3, 'X-Ray Facility'), (4, 'Neonatal Care'), (5, 'Operation Theater'), (6, 'Blood Bank')]), blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('pincode', models.IntegerField(default=None, null=True)),
                ('address', models.TextField()),
                ('geo_organization_cache', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list)),
                ('internal_organization_cache', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list)),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[care.utils.models.validators.PhoneNumberValidator(types=('mobile', 'landline'))])),
                ('cover_image_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('middleware_address', models.CharField(default=None, max_length=200, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('print_templates', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('flag', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Facility Flag',
            },
        ),
        migrations.CreateModel(
            name='PatientMobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=14, validators=[care.utils.models.validators.PhoneNumberValidator(types=('mobile', 'landline'))])),
                ('otp', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
