# Generated by Django 6.0 on 2026-05-28 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('facility', '0378_consultationbedasset_consultationbed_assets'),
        ('facility', '0432_alter_fileupload_file_type'),
        ('facility', '0476_facility_default_internal_organization_and_more'),
        ('facility', '0478_facility_discount_codes_and_more'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    dependencies = [
        ('emr', '0001_squashed_02'),
        ('facility', '0001_squashed_02'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='default_internal_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_facilities', to='emr.facilityorganization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='geo_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.organization'),
        ),
        migrations.AddField(
            model_name='facilityflag',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='facilityflag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('facility', 'flag'), name='unique_facility_flag'),
        ),
    ]
