# Generated by Django 2.2.11 on 2023-06-14 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0002_auto_20230613_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientregistration",
            name="patient_search_id",
        ),
        migrations.DeleteModel(
            name="PatientSearch",
        ),
    ]
