# Generated by Django 2.2.11 on 2020-03-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0003_auto_20200319_1739"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="facilitycapacity",
            unique_together={("facility", "room_type")},
        ),
    ]
