# Generated by Django 2.2.11 on 2020-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0007_auto_20200320_1641"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name_plural": "Inventories"},
        ),
    ]
