# Generated by Django 2.2.11 on 2020-03-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0011_auto_20200321_0927"),
        ("facility", "0011_facility_phone_number"),
    ]

    operations = []
