# Generated by Django 2.2.11 on 2020-03-22 14:11

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0014_delete_facilitylocation'),
    ]

    operations = [
        # This migration is updated manually to prevent migrations errors while deprecating location field
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
