# Generated by Django 2.2.11 on 2020-03-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0015_facility_location"),
        ("facility", "0014_facility_oxygen_capacity"),
    ]

    operations = []
