# Generated by Django 2.2.11 on 2020-03-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0016_merge_20200322_1622'),
    ]

    operations = [
    ]
