# Generated by Django 2.2.11 on 2020-03-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0022_ambulance_ambulance_type'),
        ('facility', '0022_patientregistration_patientteleconsultation'),
    ]

    operations = [
    ]
