# Generated by Django 2.2.11 on 2020-03-26 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0024_auto_20200325_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientteleconsultation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientteleconsultation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='ambulancedriver',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='building',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='facilitycapacity',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='facilitystaff',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='facilityvolunteer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
        migrations.AlterField(
            model_name='staffroomallocation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 3, 20, 32, 409615)),
        ),
    ]
