# Generated by Django 2.2.11 on 2020-03-25 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('facility', '0026_map_to_district'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='ambulance',
            name='primary_district',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='secondary_district',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='third_district',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='district',
        ),

        migrations.RenameField(
            model_name='ambulance',
            old_name='new_primary_district',
            new_name='primary_district'
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='new_secondary_district',
            new_name='secondary_district'
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='new_third_district',
            new_name='third_district'
        ),

        migrations.RenameField(
            model_name='facility',
            old_name='new_district',
            new_name='district'
        ),

    ]
