# Generated by Django 2.2.11 on 2020-03-26 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0027_auto_20200326_1015"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hospitaldoctors",
            unique_together=set(),
        ),
    ]
