# Generated by Django 2.2.11 on 2020-03-26 17:05

import partial_index
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0027_auto_20200326_1015"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hospitaldoctors",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="hospitaldoctors",
            index=partial_index.PartialIndex(
                fields=["facility", "area"],
                name="facility_ho_facilit_ec08f4_partial",
                unique=True,
                where=partial_index.PQ(deleted=False),
            ),
        ),
    ]
