# Generated by Django 2.2.11 on 2020-03-26 17:06

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0028_auto_20200326_1705"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="facilitycapacity", unique_together=set(),),
        migrations.AddIndex(
            model_name="facilitycapacity",
            index=partial_index.PartialIndex(
                fields=["facility", "room_type"],
                name="facility_fa_facilit_ec2b0e_partial",
                unique=True,
                where=partial_index.PQ(deleted=False),
            ),
        ),
    ]
