# Generated by Django 2.2.11 on 2020-03-26 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0028_auto_20200326_1705"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="facilitycapacity",
            unique_together=set(),
        ),
    ]
