# Generated by Django 2.2.11 on 2020-03-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0029_auto_20200326_1706'),
        ('facility', '0028_auto_20200326_1752'),
    ]

    operations = [
    ]
