# Generated by Django 2.2.11 on 2020-03-27 06:20

from django.db import migrations


def change_kasargode_name(apps, *args):
    """
    Changing so that it matches with Kerala LSG data base
    """
    District = apps.get_model('users', 'District')
    District.objects.filter(name="Kasaragod").update(name="Kasargode")


def reverse_change_kasargode_name(apps, *args):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('facility', '0030_auto_20200327_0619'),
    ]

    operations = [
        migrations.RunPython(change_kasargode_name, reverse_code=reverse_change_kasargode_name)
    ]
