# Generated by Django 2.2.11 on 2020-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0032_merge_20200327_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='service_charge',
            field=models.IntegerField(default=0),
        ),
    ]
