# Generated by Django 2.2.11 on 2020-03-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0033_ambulance_service_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityPatientStatsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('entry_date', models.DateField()),
                ('num_patients_visited', models.IntegerField(default=0)),
                ('num_patients_home_quarantine', models.IntegerField(default=0)),
                ('num_patients_isolation', models.IntegerField(default=0)),
                ('num_patient_referred', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.Facility')),
            ],
            options={
                'unique_together': {('facility', 'entry_date')},
            },
        ),
    ]
