# Generated by Django 2.2.11 on 2020-03-27 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0033_ambulance_service_charge"),
    ]

    operations = [
        migrations.RemoveField(model_name="ambulance", name="service_charge",),
        migrations.AddField(
            model_name="ambulance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ambulance",
            name="has_free_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ambulance",
            name="price_per_km",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
