# Generated by Django 2.2.11 on 2020-03-27 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0034_auto_20200327_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.PatientRegistration')),
            ],
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=partial_index.PartialIndex(fields=['patient'], name='facility_pa_patient_579e8a_partial', unique=True, where=partial_index.PQ(is_active=True)),
        ),
        migrations.AddConstraint(
            model_name='patientadmission',
            constraint=models.CheckConstraint(check=models.Q(('is_active', True), ('discharge_date__isnull', False), _connector='OR'), name='active_or_discharged'),
        ),
    ]
