# Generated by Django 2.2.11 on 2020-03-28 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0034_auto_20200327_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='num_buildings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
