# Generated by Django 2.2.11 on 2020-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0035_auto_20200327_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
