# Generated by Django 2.2.11 on 2020-03-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0039_auto_20200328_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalHistory',
            new_name='Disease',
        ),
    ]
