# Generated by Django 2.2.11 on 2020-03-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0039_auto_20200328_1706'),
        ('facility', '0034_facilitypatientstatshistory'),
    ]

    operations = [
    ]
