# Generated by Django 2.2.11 on 2020-03-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0041_patientsampleflow'),
        ('facility', '0040_merge_20200328_1831'),
    ]

    operations = [
    ]
