# Generated by Django 2.2.11 on 2020-03-28 20:21

from django.db import migrations, transaction


def populate_facility_district(apps, *args):
    Facility = apps.get_model('facility', 'Facility')

    with transaction.atomic():
        for facility in Facility.objects.all().select_related("district"):
            facility.state = facility.district.state
            facility.save()


def reverse_populate(apps, *args):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('facility', '0042_auto_20200328_2018'),
    ]

    operations = [
        migrations.RunPython(populate_facility_district, reverse_code=reverse_populate)
    ]
