# Generated by Django 2.2.11 on 2020-03-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0045_auto_20200329_0757'),
        ('facility', '0044_patientsample_patientsampleflow'),
    ]

    operations = [
    ]
