# Generated by Django 2.2.11 on 2020-03-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0051_auto_20200330_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='created_by',
        ),
    ]
