# Generated by Django 2.2.11 on 2020-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0053_delete_duplicate_diseases"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
