# Generated by Django 2.2.11 on 2020-03-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0054_auto_20200331_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='primary_district_obj',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='secondary_district_obj',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='third_district_obj',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='primary_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_ambulances', to='users.District'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='secondary_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_ambulances', to='users.District'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='third_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_ambulances', to='users.District'),
        ),
    ]
