# Generated by Django 2.2.11 on 2020-04-01 18:20

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0057_auto_20200401_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='contact_with_carrier',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='contact_with_carrier',
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='address',
            field=fernet_fields.fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='contact_with_confirmed_carrier',
            field=models.BooleanField(default=False, verbose_name='Confirmed Contact with a Covid19 Carrier'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='contact_with_suspected_carrier',
            field=models.BooleanField(default=False, verbose_name='Suspected Contact with a Covid19 Carrier'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='countries_travelled',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='estimated_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='has_SARI',
            field=models.BooleanField(default=False, verbose_name='Does the Patient Suffer from SARI'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='past_travel',
            field=models.BooleanField(default=False, verbose_name='Travelled to Any Foreign Countries in the last 28 Days'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='present_health',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='address',
            field=fernet_fields.fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='contact_with_confirmed_carrier',
            field=models.BooleanField(default=False, verbose_name='Confirmed Contact with a Covid19 Carrier'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='contact_with_suspected_carrier',
            field=models.BooleanField(default=False, verbose_name='Suspected Contact with a Covid19 Carrier'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='countries_travelled',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='estimated_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='has_SARI',
            field=models.BooleanField(default=False, verbose_name='Does the Patient Suffer from SARI'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='past_travel',
            field=models.BooleanField(default=False, verbose_name='Travelled to Any Foreign Countries in the last 28 Days'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='present_health',
            field=models.TextField(default=''),
        ),
    ]
