# Generated by Django 2.2.11 on 2020-04-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0062_auto_20200402_1336'),
        ('facility', '0062_populate_facility_in_patient'),
    ]

    operations = [
    ]
