# Generated by Django 2.2.11 on 2020-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0064_auto_20200402_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='disease_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUSPECTED'), (2, 'POSITIVE'), (3, 'NEGATIVE'), (4, 'RECOVERY'), (5, 'RECOVERED'), (5, 'EXPIRED')], default=1),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='disease_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUSPECTED'), (2, 'POSITIVE'), (3, 'NEGATIVE'), (4, 'RECOVERY'), (5, 'RECOVERED'), (5, 'EXPIRED')], default=1),
        ),
        migrations.AlterField(
            model_name='dailyround',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyround',
            name='temperature_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
