# Generated by Django 2.2.11 on 2020-04-02 19:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0065_auto_20200402_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='admitted_to',
            field=models.CharField(choices=[(None, 'Not admitted'), ('Admitted to', ((1, 'Isolation Room'), (2, 'ICU'), (3, 'ICU with Ventilator')))], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='category',
            field=models.CharField(choices=[('Mild', 'Category-A'), ('Moderate', 'Category-B'), ('Severe', 'Category-C'), (None, 'No Category')], default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='other_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'NO'), (2, 'FEVER'), (3, 'SORE THROAT'), (4, 'COUGH'), (5, 'BREATHLESSNESS'), (6, 'MYALGIA'), (7, 'ABDOMINAL DISCOMFORT'), (8, 'VOMITING/DIARRHOEA'), (9, 'OTHERS')], default=1, max_length=17),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='symptoms_onset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientteleconsultation',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'NO'), (2, 'FEVER'), (3, 'SORE THROAT'), (4, 'COUGH'), (5, 'BREATHLESSNESS'), (6, 'MYALGIA'), (7, 'ABDOMINAL DISCOMFORT'), (8, 'VOMITING/DIARRHOEA'), (9, 'OTHERS')], max_length=17),
        ),
    ]
