# Generated by Django 2.2.11 on 2020-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0065_auto_20200402_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='number_of_aged_dependents',
            field=models.IntegerField(default=0, verbose_name='Number of people aged above 60 living with the patient'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='number_of_chronic_diseased_dependents',
            field=models.IntegerField(default=0, verbose_name='Number of people who have chronic diseases living with the patient'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='number_of_aged_dependents',
            field=models.IntegerField(default=0, verbose_name='Number of people aged above 60 living with the patient'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='number_of_chronic_diseased_dependents',
            field=models.IntegerField(default=0, verbose_name='Number of people who have chronic diseases living with the patient'),
        ),
    ]
