# Generated by Django 2.2.11 on 2020-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0066_auto_20200402_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, null=True, verbose_name='Blood Group of Patient'),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='countries_travelled',
            field=models.TextField(blank=True, default='', verbose_name='Countries Patient has Travelled to'),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='date_of_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return Date from the Last Country if Travelled'),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='disease_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUSPECTED'), (2, 'POSITIVE'), (3, 'NEGATIVE'), (4, 'RECOVERY'), (5, 'RECOVERED'), (5, 'EXPIRED')], default=1, verbose_name='Disease Status'),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='number_of_aged_dependents',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of people aged above 60 living with the patient'),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='number_of_chronic_diseased_dependents',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of people who have chronic diseases living with the patient'),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='present_health',
            field=models.TextField(blank=True, default='', verbose_name="Patient's Current Health Details"),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, null=True, verbose_name='Blood Group of Patient'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='countries_travelled',
            field=models.TextField(blank=True, default='', verbose_name='Countries Patient has Travelled to'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='date_of_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return Date from the Last Country if Travelled'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='disease_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUSPECTED'), (2, 'POSITIVE'), (3, 'NEGATIVE'), (4, 'RECOVERY'), (5, 'RECOVERED'), (5, 'EXPIRED')], default=1, verbose_name='Disease Status'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='number_of_aged_dependents',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of people aged above 60 living with the patient'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='number_of_chronic_diseased_dependents',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of people who have chronic diseases living with the patient'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='present_health',
            field=models.TextField(blank=True, default='', verbose_name="Patient's Current Health Details"),
        ),
    ]
