# Generated by Django 2.2.11 on 2020-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0070_auto_20200402_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='disease_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUSPECTED'), (2, 'POSITIVE'), (3, 'NEGATIVE'), (4, 'RECOVERY'), (5, 'RECOVERED'), (6, 'EXPIRED')], default=1, verbose_name='Disease Status'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='disease_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUSPECTED'), (2, 'POSITIVE'), (3, 'NEGATIVE'), (4, 'RECOVERY'), (5, 'RECOVERED'), (6, 'EXPIRED')], default=1, verbose_name='Disease Status'),
        ),
    ]
