# Generated by Django 2.2.11 on 2020-04-09 06:23
import datetime

from django.db import migrations


def populate_patient_search(apps, *args, **kwargs):
    PatientRegistration = apps.get_model('facility', 'PatientRegistration')
    PatientSearch = apps.get_model('facility', 'PatientSearch')
    if not PatientRegistration:
        # in future if the model is renamed / removed, migration should not throw exception
        return

    for patient in PatientRegistration.objects.all():
        patient.year_of_birth = patient.date_of_birth.year \
            if patient.date_of_birth is not None \
            else datetime.datetime.now().year - patient.age
        if patient.patient_search_id is None:
            ps = PatientSearch.objects.create(
                name=patient.name,
                gender=patient.gender,
                phone_number=patient.phone_number,
                date_of_birth=patient.date_of_birth,
                year_of_birth=patient.year_of_birth,
                state_id=patient.state_id,
                patient_id=patient.pk
            )
            patient.patient_search_id = ps.pk
            patient.save()
        else:
            ps = PatientSearch.objects.get(pk=patient.patient_search_id)
            ps.name = patient.name
            ps.gender = patient.gender
            ps.phone_number = patient.phone_number
            ps.date_of_birth = patient.date_of_birth
            ps.year_of_birth = patient.year_of_birth
            ps.state_id = patient.state_id
            ps.save()


def reverse_populate_patient_search(*args, **kwargs):
    # no need of reverting
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('facility', '0081_auto_20200409_1201'),
    ]

    operations = [
        migrations.RunPython(populate_patient_search, reverse_code=reverse_populate_patient_search)
    ]
