# Generated by Django 2.2.11 on 2020-04-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0084_install_trigram_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.IntegerField(choices=[(1, 'STUDENT'), (2, 'MEDICAL_WORKER'), (3, 'GOVT_EMPLOYEE'), (4, 'PRIVATE_EMPLOYEE'), (5, 'HOME_MAKER'), (6, 'WORKING_ABROAD'), (7, 'OTHERS')])),
                ('head_of_household', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='nearest_facility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facility.Facility'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='source',
            field=models.IntegerField(choices=[(10, 'CARE'), (20, 'COVID_TRACKER'), (30, 'STAY')], default=10),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='nearest_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearest_facility', to='facility.Facility'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='source',
            field=models.IntegerField(choices=[(10, 'CARE'), (20, 'COVID_TRACKER'), (30, 'STAY')], default=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.IntegerField(choices=[(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (8, 'Govt Hospital'), (200, 'Primary Health Centres'), (201, '24x7 Public Health Centres'), (202, 'Family Health Centres'), (203, 'Community Health Centres'), (220, 'Urban Primary Health Center'), (230, 'Taluk Hospitals'), (231, 'Taluk Headquarters Hospitals'), (240, 'Women and Child Health Centres'), (250, 'General hospitals'), (260, 'District Hospitals')]),
        ),
        migrations.CreateModel(
            name='PatientContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_with_patient', models.IntegerField(choices=[(1, 'FAMILY_MEMBER'), (2, 'FRIEND'), (3, 'RELATIVE'), (4, 'NEIGHBOUR'), (5, 'TRAVEL_TOGETHER'), (6, 'WHILE_AT_HOSPITAL'), (7, 'WHILE_AT_SHOP'), (8, 'WHILE_AT_OFFICE_OR_ESTABLISHMENT'), (9, 'WORSHIP_PLACE'), (10, 'OTHERS')])),
                ('mode_of_contact', models.IntegerField(choices=[(1, 'TOUCHED_BODY_FLUIDS'), (2, 'DIRECT_PHYSICAL_CONTACT'), (3, 'CLEANED_USED_ITEMS'), (4, 'LIVE_IN_SAME_HOUSEHOLD'), (5, 'CLOSE_CONTACT_WITHOUT_PRECAUTION'), (6, 'CO_PASSENGER_AEROPLANE'), (7, 'HEALTH_CARE_WITH_PPE'), (8, 'SHARED_SAME_SPACE_WITHOUT_HIGH_EXPOSURE'), (9, 'TRAVELLED_TOGETHER_WITHOUT_HIGH_EXPOSURE')])),
                ('date_of_first_contact', models.DateField(null=True)),
                ('date_of_last_contact', models.DateField(null=True)),
                ('is_primary', models.BooleanField(help_text='If false, then secondary contact')),
                ('condition_of_contact_is_symptomatic', models.BooleanField(help_text='While in contact, did the patient showing symptoms')),
                ('deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacted_patients', to='facility.PatientRegistration')),
                ('patient_in_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='facility.PatientRegistration')),
            ],
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='meta_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.PatientMetaInfo'),
        ),
    ]
