# Generated by Django 2.2.11 on 2020-04-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0087_add_users_to_facility_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsultationICMR',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facility.patientconsultation',),
        ),
        migrations.CreateModel(
            name='PatientIcmr',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facility.patientregistration',),
        ),
        migrations.CreateModel(
            name='PatientSampleICMR',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facility.patientsample',),
        ),
    ]
