# Generated by Django 2.2.11 on 2020-04-13 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_verify_users_with_facility'),
        ('facility', '0088_patientconsultationicmr_patienticmr_patientsampleicmr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='Please enter a valid pincode.', regex='^((\\d{6}$')])),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')])),
                ('testing_capacity_per_day', models.IntegerField(blank=True, default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.District')),
                ('local_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.LocalBody')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.State')),
            ],
        ),
    ]
