# Generated by Django 2.2.11 on 2020-04-13 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0088_patientconsultationicmr_patienticmr_patientsampleicmr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='owner_is_smart_phone',
            new_name='owner_has_smart_phone',
        ),
        migrations.RenameField(
            model_name='ambulancedriver',
            old_name='is_smart_phone',
            new_name='has_smart_phone',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='vehicle_number',
            field=models.CharField(db_index=True, help_text='Please Enter the vehicle number without spaces, eg: KL13AB1234', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vehicle_number', message='Please Enter the vehicle number without spaces, eg: KL13AB1234', regex='^[A-Za-z]{2}[0-9]{1,2}[A-Za-z]{0,2}[0-9]{1,4}$')]),
        ),
    ]
