# Generated by Django 2.2.11 on 2020-04-15 03:25

from django.db import migrations, models, transaction


def populate_date_of_information_in_patients(apps, *args, **kwargs):
    Patient = apps.get_model('facility', 'PatientRegistration')
    PatientHistory = apps.get_model('facility', 'HistoricalPatientRegistration')

    with transaction.atomic():
        for p in Patient.objects.all():
            p.date_of_receipt_of_information = p.created_date
            p.save()
        for h in PatientHistory.objects.all():
            h.date_of_receipt_of_information = h.created_date
            h.save()


def reverse_populate_date_of_information_in_patients(apps, *args):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('facility', '0092_recompute_facility_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='date_of_receipt_of_information',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Patient's information received date"),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='date_of_receipt_of_information',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Patient's information received date"),
        ),
        migrations.RunPython(
            populate_date_of_information_in_patients,
            reverse_code=reverse_populate_date_of_information_in_patients
        )
    ]
