# Generated by Django 2.2.11 on 2020-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0097_auto_20200417_1404'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patientsearch',
            constraint=models.UniqueConstraint(fields=('date_of_birth', 'phone_number'), name='unique patient'),
        ),
    ]
