# Generated by Django 2.2.11 on 2020-04-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0098_auto_20200418_1302"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpatientregistration",
            old_name="countries_travelled",
            new_name="countries_travelled_old",
        ),
        migrations.RenameField(
            model_name="patientregistration",
            old_name="countries_travelled",
            new_name="countries_travelled_old",
        ),
    ]
