# Generated by Django 2.2.11 on 2020-04-20 05:46

import care.utils.models.jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0101_populate_countries_travelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='states_travelled',
            field=care.utils.models.jsonfield.JSONField(blank=True, null=True, verbose_name='States Patient has Travelled to'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='states_travelled',
            field=care.utils.models.jsonfield.JSONField(blank=True, null=True, verbose_name='States Patient has Travelled to'),
        ),
    ]
