# Generated by Django 2.2.11 on 2020-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0116_facility_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientsample",
            name="icmr_category",
            field=models.IntegerField(
                choices=[
                    (0, "Cat 0"),
                    (10, "Cat 1"),
                    (20, "Cat 2"),
                    (30, "Cat 3"),
                    (40, "Cat 4"),
                    (50, "Cat 5a"),
                    (60, "Cat 5b"),
                ],
                default=0,
            ),
        ),
    ]
