# Generated by Django 2.2.11 on 2020-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0119_auto_20200617_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientsample",
            name="icmr_label",
            field=models.CharField(default="", max_length=200),
        ),
    ]
