# Generated by Django 2.2.11 on 2020-06-25 20:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0122_auto_20200624_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyround",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyround",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyround",
            name="external_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="dailyround",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
