# Generated by Django 2.2.11 on 2020-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0126_auto_20200626_0156"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientsearch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
