# Generated by Django 2.2.11 on 2020-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0130_auto_20200706_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="consultation_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientconsultation",
            name="suggestion",
            field=models.CharField(
                choices=[
                    ("HI", "HOME ISOLATION"),
                    ("A", "ADMISSION"),
                    ("R", "REFERRAL"),
                    ("OP", "OP CONSULTATION"),
                ],
                max_length=4,
            ),
        ),
    ]
