# Generated by Django 2.2.11 on 2020-07-18 01:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0136_auto_20200716_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityrelatedsummary',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
