# Generated by Django 2.2.11 on 2020-07-23 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0138_auto_20200720_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('emergency', models.BooleanField(default=False)),
                ('is_up_shift', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('vehicle_preference', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(10, 'PENDING'), (20, 'APPROVED'), (30, 'REJECTED'), (40, 'DESTINATION APPROVED'), (50, 'DESTINATION REJECTED'), (60, 'AWAITING TRANSPORTATION'), (70, 'TRANSFER IN PROGRESS'), (80, 'COMPLETED')], default=10)),
                ('assigned_facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_facility', to='facility.Facility')),
                ('orgin_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requesting_facility', to='facility.Facility')),
                ('shifting_approving_facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifting_approving_facility', to='facility.Facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
