# Generated by Django 2.2.11 on 2020-07-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0140_auto_20200723_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrelatedsummary',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
