# Generated by Django 2.2.11 on 2020-07-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0141_facilityrelatedsummary_modified_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftingrequest",
            name="patient",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="facility.PatientRegistration",
            ),
            preserve_default=False,
        ),
    ]
