# Generated by Django 2.2.11 on 2020-08-02 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0146_auto_20200801_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='address_new',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='name_new',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='phone_number_new',
            field=models.CharField(default='', max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='address_new',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='name_new',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='phone_number_new',
            field=models.CharField(default='', max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')]),
        ),
    ]
