# Generated by Django 2.2.11 on 2020-08-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0149_auto_20200802_2156"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpatientregistration",
            old_name="address_new",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="historicalpatientregistration",
            old_name="name_new",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="historicalpatientregistration",
            old_name="phone_number_new",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="patientregistration",
            old_name="address_new",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="patientregistration",
            old_name="name_new",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="patientregistration",
            old_name="phone_number_new",
            new_name="phone_number",
        ),
    ]
