# Generated by Django 2.2.11 on 2020-08-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0157_patientconsultation_ip_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="ip_no",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="ip_no",
        ),
    ]
