# Generated by Django 2.2.11 on 2020-09-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0170_patientconsultation_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='test_id',
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='test_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='test_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
