# Generated by Django 2.2.11 on 2020-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0171_auto_20200901_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientregistration",
            name="pincode",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="patientregistration",
            name="pincode",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
