# Generated by Django 2.2.11 on 2020-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0172_auto_20200903_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='is_migrant_worker',
            field=models.BooleanField(default=False, verbose_name='Is Patient a Migrant Worker'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='is_migrant_worker',
            field=models.BooleanField(default=False, verbose_name='Is Patient a Migrant Worker'),
        ),
    ]
