# Generated by Django 2.2.11 on 2020-09-16 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0176_auto_20200916_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftingrequest',
            name='refering_facility_contact_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shiftingrequest',
            name='refering_facility_contact_number',
            field=models.CharField(blank=True, default='', max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')]),
        ),
    ]
