# Generated by Django 2.2.11 on 2020-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0177_auto_20200916_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='date_of_test',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Patient's test Date"),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='srf_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='test_type',
            field=models.IntegerField(choices=[(10, 'UNK'), (20, 'ANTIGEN'), (30, 'RTPCR'), (40, 'CBNAT'), (50, 'TRUNAT')], default=10),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='date_of_test',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Patient's test Date"),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='srf_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='test_type',
            field=models.IntegerField(choices=[(10, 'UNK'), (20, 'ANTIGEN'), (30, 'RTPCR'), (40, 'CBNAT'), (50, 'TRUNAT')], default=10),
        ),
    ]
