# Generated by Django 2.2.11 on 2020-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0180_facility_ward"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpatientregistration",
            old_name="ward",
            new_name="ward_old",
        ),
        migrations.RenameField(
            model_name="patientregistration",
            old_name="ward",
            new_name="ward_old",
        ),
    ]
