# Generated by Django 2.2.11 on 2020-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0192_auto_20201004_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftingrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "PENDING"),
                    (15, "ON HOLD"),
                    (20, "APPROVED"),
                    (30, "REJECTED"),
                    (40, "DESTINATION APPROVED"),
                    (50, "DESTINATION REJECTED"),
                    (55, "TRANSPORTATION TO BE ARRANGED"),
                    (60, "PATIENT TO BE PICKED UP"),
                    (70, "TRANSFER IN PROGRESS"),
                    (80, "COMPLETED"),
                ],
                default=10,
            ),
        ),
    ]
