# Generated by Django 2.2.11 on 2020-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0196_auto_20201011_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitycapacity',
            name='room_type',
            field=models.IntegerField(choices=[(0, 'Total'), (1, 'General Bed'), (2, 'Hostel'), (3, 'Single Room with Attached Bathroom'), (10, 'ICU'), (20, 'Ventilator'), (30, 'Covid Beds'), (40, 'KASP Beds'), (50, 'KASP ICU beds')]),
        ),
        migrations.AlterField(
            model_name='historicalfacilitycapacity',
            name='room_type',
            field=models.IntegerField(choices=[(0, 'Total'), (1, 'General Bed'), (2, 'Hostel'), (3, 'Single Room with Attached Bathroom'), (10, 'ICU'), (20, 'Ventilator'), (30, 'Covid Beds'), (40, 'KASP Beds'), (50, 'KASP ICU beds')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.IntegerField(choices=[(0, 'Total'), (1, 'General Bed'), (2, 'Hostel'), (3, 'Single Room with Attached Bathroom'), (10, 'ICU'), (20, 'Ventilator'), (30, 'Covid Beds'), (40, 'KASP Beds'), (50, 'KASP ICU beds')]),
        ),
    ]
