# Generated by Django 2.2.11 on 2020-10-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0199_shiftingrequest_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyround",
            name="admitted_to",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Not admitted"),
                    (1, "Isolation Room"),
                    (2, "ICU"),
                    (3, "ICU with Non Invasive Ventilator"),
                    (4, "ICU with Oxygen Support"),
                    (5, "ICU with Invasive Ventilator"),
                    (20, "Home Isolation"),
                    (30, "Gynaecology Ward"),
                    (40, "Paediatric Ward"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
