# Generated by Django 2.2.11 on 2020-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0206_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(default=None, max_length=2000, null=True),
        ),
    ]
