# Generated by Django 2.2.11 on 2020-11-23 05:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0207_auto_20201123_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='caused_objects',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
