# Generated by Django 2.2.11 on 2020-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0208_notification_caused_objects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="caused_object_external_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
