# Generated by Django 2.2.11 on 2020-12-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0211_auto_20201214_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.IntegerField(choices=[(0, 'MESSAGE'), (20, 'PATIENT_CREATED'), (30, 'PATIENT_UPDATED'), (40, 'PATIENT_DELETED'), (50, 'PATIENT_CONSULTATION_CREATED'), (60, 'PATIENT_CONSULTATION_UPDATED'), (70, 'PATIENT_CONSULTATION_DELETED')], default=0),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=2000)),
                ('internal_name', models.CharField(max_length=2000)),
                ('associating_id', models.CharField(max_length=100)),
                ('upload_completed', models.BooleanField(default=False)),
                ('file_type', models.IntegerField(choices=[(1, 'PATIENT'), (2, 'CONSULTATION')], default=1)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
