# Generated by Django 2.2.11 on 2021-01-07 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0212_auto_20201223_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyround",
            name="admitted_to",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Not admitted"),
                    (1, "Isolation Room"),
                    (2, "ICU"),
                    (3, "ICU with Non Invasive Ventilator"),
                    (4, "ICU with Oxygen Support"),
                    (5, "ICU with Invasive Ventilator"),
                    (6, "Bed with Oxygen Support"),
                    (20, "Home Isolation"),
                    (30, "Gynaecology Ward"),
                    (40, "Paediatric Ward"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientconsultation",
            name="admitted_to",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Not admitted"),
                    (1, "Isolation Room"),
                    (2, "ICU"),
                    (3, "ICU with Non Invasive Ventilator"),
                    (4, "ICU with Oxygen Support"),
                    (5, "ICU with Invasive Ventilator"),
                    (6, "Bed with Oxygen Support"),
                    (20, "Home Isolation"),
                    (30, "Gynaecology Ward"),
                    (40, "Paediatric Ward"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
