# Generated by Django 2.2.11 on 2021-04-16 02:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0217_postcoviddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facility.PatientConsultation')),
            ],
        ),
    ]
