# Generated by Django 2.2.11 on 2021-04-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0218_auto_20210417_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinvestigation',
            old_name='group',
            new_name='groups',
        ),
    ]
