# Generated by Django 2.2.11 on 2021-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0218_auto_20210417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('Float', 'Float'), ('String', 'String')], default=None, max_length=10, null=True),
        ),
    ]
