# Generated by Django 2.2.11 on 2021-04-16 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0218_investigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigation',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
