# Generated by Django 2.2.11 on 2021-04-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0219_test_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='PatientTest',
        ),
        migrations.RenameField(
            model_name='patienttest',
            old_name='type',
            new_name='test_type',
        ),
    ]
