# Generated by Django 2.2.11 on 2021-04-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0220_populate_investigations"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="kasp_empanelled",
            field=models.BooleanField(default=False),
        ),
    ]
