# Generated by Django 2.2.11 on 2021-04-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0220_auto_20210416_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcoviddata',
            name='consultation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='facility.PatientConsultation'),
        ),
    ]
