# Generated by Django 2.2.11 on 2021-04-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0221_postcoviddata_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcoviddata',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facility.PatientConsultation'),
        ),
    ]
