# Generated by Django 2.2.11 on 2021-04-29 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0222_auto_20210427_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='number_of_doses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='vaccine_name',
            field=models.CharField(choices=[('CoviShield', 'COVISHIELD'), ('Covaxin', 'COVAXIN')], default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='number_of_doses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='vaccine_name',
            field=models.CharField(choices=[('CoviShield', 'COVISHIELD'), ('Covaxin', 'COVAXIN')], default=None, max_length=15, null=True),
        ),
    ]
