# Generated by Django 2.2.11 on 2021-04-16 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0222_auto_20210416_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcoviddata',
            name='antivirals_drugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
    ]
