# Generated by Django 2.2.11 on 2021-04-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0222_auto_20210427_0002"),
        ("facility", "0221_investigationsession_created_by"),
        ("facility", "0221_facility_kasp_empanelled"),
    ]

    operations = []
