# Generated by Django 2.2.11 on 2021-05-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0228_shiftingrequest_breathlessness_level"),
        ("facility", "0227_auto_20210505_2055"),
    ]

    operations = []
