# Generated by Django 2.2.11 on 2021-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0232_auto_20210510_1218'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shiftingrequest',
            index=models.Index(fields=['status', 'deleted'], name='facility_sh_status_2f7458_idx'),
        ),
    ]
