# Generated by Django 2.2.11 on 2021-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0237_dailyround_created_by_telemedicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="file_category",
            field=models.CharField(
                choices=[
                    ("UNSPECIFIED", "UNSPECIFIED"),
                    ("XRAY", "XRAY"),
                    ("AUDIO", "AUDIO"),
                    ("IDENTITY_PROOF", "IDENTITY_PROOF"),
                ],
                default="UNSPECIFIED",
                max_length=100,
            ),
        ),
    ]
