# Generated by Django 2.2.11 on 2021-05-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0242_auto_20210523_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='assigned_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='requested_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='sub_category',
            field=models.IntegerField(choices=[(110, 'LIQUID OXYGEN'), (120, 'B TYPE OXYGEN CYLINDER'), (120, 'C TYPE OXYGEN CYLINDER'), (120, 'JUMBO D TYPE OXYGEN CYLINDER'), (1000, 'UNSPECIFIED')], default=1000),
        ),
    ]
