# Generated by Django 2.2.11 on 2021-05-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0244_resourcerequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='sub_category',
            field=models.IntegerField(choices=[(110, 'LIQUID OXYGEN'), (120, 'B TYPE OXYGEN CYLINDER'), (130, 'C TYPE OXYGEN CYLINDER'), (140, 'JUMBO D TYPE OXYGEN CYLINDER'), (1000, 'UNSPECIFIED')], default=1000),
        ),
    ]
