# Generated by Django 2.2.11 on 2021-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0248_auto_20210529_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityinventoryunit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
