# Generated by Django 2.2.11 on 2021-06-02 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0249_auto_20210529_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='assigned_to',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_patient_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
