# Generated by Django 2.2.11 on 2021-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0256_assettransaction_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_working',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
