# Generated by Django 2.2.11 on 2021-07-10 12:12

import care.utils.models.validators
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0259_patientexternaltest_patient_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='cpk_mb',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Patient's CPK/MB"),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='cuff_pressure',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cuff Pressure in mmhg'),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='ett_tt',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='ETT/TT in mmid'),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='height',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Patient's Height in CM"),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='intubation_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='intubation_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='intubation_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='lines',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'items': [{'properties': {'site': {'type': 'string'}, 'start_date': {'pattern': '^(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2}):(\\d{2}):(\\d{2}(?:\\.\\d*)?)((-(\\d{2}):(\\d{2})|Z)?)$', 'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['start_date', 'types', 'site'], 'type': 'object'}], 'type': 'array'})]),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='operation',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='weight',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Patient's Weight in KG"),
        ),
    ]
