# Generated by Django 2.2.11 on 2021-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0262_auto_20210711_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyround',
            name='taken_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
