# Generated by Django 2.2.11 on 2021-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0263_auto_20210711_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='in_prone_position',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
