# Generated by Django 2.2.11 on 2021-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0267_dailyround_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='special_instruction',
            field=models.TextField(default=None, null=True),
        ),
    ]
