# Generated by Django 2.2.11 on 2021-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0267_dailyround_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='vaccine_name',
            field=models.CharField(choices=[('CoviShield', 'COVISHIELD'), ('Covaxin', 'COVAXIN'), ('Sputnik', 'SPUTNIK'), ('Moderna', 'MODERNA'), ('Pfizer', 'PFIZER'), ('Janssen', 'JANSSEN'), ('Sinovac', 'SINOVAC')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='vaccine_name',
            field=models.CharField(choices=[('CoviShield', 'COVISHIELD'), ('Covaxin', 'COVAXIN'), ('Sputnik', 'SPUTNIK'), ('Moderna', 'MODERNA'), ('Pfizer', 'PFIZER'), ('Janssen', 'JANSSEN'), ('Sinovac', 'SINOVAC')], default=None, max_length=15, null=True),
        ),
    ]
