# Generated by Django 2.2.11 on 2021-08-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0268_patientconsultation_special_instruction'),
        ('facility', '0268_auto_20210729_1327'),
    ]

    operations = [
    ]
