# Generated by Django 2.2.11 on 2021-08-15 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0269_merge_20210815_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_last_edited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
