# Generated by Django 2.2.11 on 2021-08-15 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0270_auto_20210815_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='support_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='support_phone',
            field=models.CharField(default='', max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
