# Generated by Django 2.2.11 on 2021-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0271_auto_20210815_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsample',
            name='sample_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'BA/ETA'), (2, 'TS/NPS/NS'), (3, 'Blood in EDTA'), (4, 'Acute Sera'), (5, 'Covalescent sera'), (6, 'Biopsy'), (7, 'AMR'), (8, 'Communicable'), (9, 'OTHER TYPE')], default=0),
        ),
    ]
