# Generated by Django 2.2.11 on 2021-08-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210824_1534'),
        ('facility', '0271_auto_20210815_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientexternaltest',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Block'),
        ),
    ]
