# Generated by Django 2.2.11 on 2021-09-20 12:41

import care.utils.models.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0274_auto_20210910_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsultation',
            name='lines',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'items': [{'additionalProperties': False, 'properties': {'other_type': {'type': 'string'}, 'site': {'type': 'string'}, 'start_date': {'pattern': '^(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2}):(\\d{2}):(\\d{2}(?:\\.\\d*)?)((-(\\d{2}):(\\d{2})|Z)?)$', 'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['start_date', 'type', 'site'], 'type': 'object'}], 'type': 'array'})]),
        ),
    ]
