# Generated by Django 2.2.11 on 2021-09-17 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0274_auto_20210910_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyround',
            name='resp',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
