# Generated by Django 2.2.11 on 2021-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0274_auto_20210910_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='test_type',
            field=models.IntegerField(choices=[(10, 'UNK'), (20, 'ANTIGEN'), (30, 'RTPCR'), (40, 'CBNAAT'), (50, 'TRUENAT'), (60, 'RTLAMP'), (70, 'POCPCR')], default=10),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='test_type',
            field=models.IntegerField(choices=[(10, 'UNK'), (20, 'ANTIGEN'), (30, 'RTPCR'), (40, 'CBNAAT'), (50, 'TRUENAT'), (60, 'RTLAMP'), (70, 'POCPCR')], default=10),
        ),
    ]
