# Generated by Django 2.2.11 on 2021-10-29 11:14

import care.utils.models.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0275_auto_20210917_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='camera',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'additionalProperties': False, 'properties': {'preset': {'type': 'number'}, 'url': {'type': 'string'}}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.IntegerField(choices=[(50, 'INTERNAL'), (100, 'EXTERNAL'), (150, 'CAMERA')], default=50),
        ),
    ]
