# Generated by Django 2.2.11 on 2021-10-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0276_auto_20210930_1451'),
        ('facility', '0275_auto_20210920_1811'),
        ('facility', '0275_auto_20210927_2033'),
    ]

    operations = [
    ]
