# Generated by Django 2.2.11 on 2021-10-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0276_auto_20211029_1644'),
        ('facility', '0278_asset_not_working_reason'),
    ]

    operations = [
    ]
