# Generated by Django 2.2.11 on 2021-12-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0279_auto_20211122_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='bed',
        ),
        migrations.AddField(
            model_name='dailyround',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.Bed'),
        ),
    ]
