# Generated by Django 2.2.11 on 2022-01-18 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0281_auto_20211214_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='pain',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
