# Generated by Django 2.2.11 on 2021-12-21 07:59

import care.utils.models.validators
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0281_auto_20211214_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='cuff_pressure',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cuff Pressure in mmhg'),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='ett_tt',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='ETT/TT in mmid'),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='intubation_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='intubation_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='lines',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'items': [{'additionalProperties': False, 'properties': {'other_type': {'type': 'string'}, 'site': {'type': 'string'}, 'start_date': {'pattern': '^(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2}):(\\d{2}):(\\d{2}(?:\\.\\d*)?)((-(\\d{2}):(\\d{2})|Z)?)$', 'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['start_date', 'type', 'site'], 'type': 'object'}], 'type': 'array'})]),
        ),
    ]
