# Generated by Django 2.2.11 on 2022-01-08 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0281_auto_20211214_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='last_daily_round',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.DailyRound'),
        ),
    ]
