# Generated by Django 2.2.11 on 2022-01-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0282_dailyround_pain'),
        ('facility', '0282_patientconsultation_last_daily_round'),
    ]

    operations = [
    ]
