# Generated by Django 2.2.11 on 2021-12-23 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0282_auto_20211221_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='cpk_mb',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Patient's CPK/MB"),
        ),
    ]
