# Generated by Django 2.2.11 on 2021-12-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0283_dailyround_cpk_mb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyround',
            name='intubation_end_date',
        ),
        migrations.RemoveField(
            model_name='dailyround',
            name='intubation_start_date',
        ),
    ]
