# Generated by Django 2.2.11 on 2022-01-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0283_populate_patientconsultation_last_daily_round'),
        ('facility', '0282_dailyround_pain'),
    ]

    operations = [
    ]
