# Generated by Django 2.2.11 on 2022-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0284_patientconsultation_hba1c"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_class",
            field=models.IntegerField(blank=True, choices=[("ONVIF", "onvif")], default=None, null=True),
        ),
    ]
