# Generated by Django 2.2.11 on 2022-03-16 14:34

import care.utils.models.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0285_asset_asset_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyround',
            name='feeds',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'items': [{'additionalProperties': False, 'properties': {'calories': {'type': 'number'}, 'name': {'type': 'string'}, 'quantity': {'type': 'number'}}, 'required': ['name', 'quantity'], 'type': 'object'}], 'type': 'array'})]),
        ),
        migrations.AlterField(
            model_name='dailyround',
            name='infusions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'items': [{'additionalProperties': False, 'properties': {'conc_unit': {'type': 'string'}, 'concentration': {'type': 'number'}, 'name': {'type': 'string'}, 'quantity': {'type': 'number'}}, 'required': ['name', 'quantity'], 'type': 'object'}], 'type': 'array'})]),
        ),
    ]
