# Generated by Django 2.2.11 on 2022-04-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0287_auto_20220415_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='current_bed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.ConsultationBed'),
        ),
    ]
