# Generated by Django 2.2.11 on 2022-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0289_merge_20220422_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='qr_code_id',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(qr_code_id__isnull=False), fields=('qr_code_id',), name='qr_code_unique_when_not_null'),
        ),
    ]
