# Generated by Django 2.2.11 on 2022-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0291_facility_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
