# Generated by Django 2.2.11 on 2022-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0292_auto_20220430_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsultation',
            name='ip_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
