# Generated by Django 2.2.11 on 2022-05-26 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0292_auto_20220430_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='number_of_doses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='number_of_doses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
