# Generated by Django 2.2.11 on 2022-05-13 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0292_auto_20220430_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('internal_name', models.CharField(max_length=2000)),
                ('upload_completed', models.BooleanField(default=False)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='facility.Facility')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
