# Generated by Django 2.2.11 on 2022-05-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0292_auto_20220430_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityinventoryitem',
            name='min_quantity',
        ),
    ]
