# Generated by Django 2.2.11 on 2022-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0292_auto_20220430_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='middleware_address',
            field=models.CharField(default=None, max_length=200, null=True, unique=True),
        ),
    ]
