# Generated by Django 2.2.11 on 2022-05-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0293_facilitycoverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitycoverimage',
            name='facility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='facility.Facility'),
        ),
    ]
