# Generated by Django 2.2.11 on 2022-05-25 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0293_auto_20220520_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='number_of_doses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='number_of_doses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
