# Generated by Django 2.2.11 on 2022-05-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0294_auto_20220526_0133'),
        ('facility', '0294_auto_20220523_1419'),
    ]

    operations = [
    ]
