# Generated by Django 2.2.11 on 2022-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0295_merge_20220527_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitycapacity',
            options={'verbose_name_plural': 'Facility Capacities'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.IntegerField(blank=True, choices=[('ONVIF', 'onvif'), ('HL7MONITOR', 'hl7monitor')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientmetainfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
