# Generated by Django 2.2.11 on 2022-05-27 17:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0295_merge_20220527_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitycapacity',
            options={'verbose_name_plural': 'Facility Capacities'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.IntegerField(blank=True, choices=[('ONVIF', 'onvif'), ('HL7MONITOR', 'hl7monitor')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='assetbed',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bed',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='consultationbed',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
