# Generated by Django 2.2.11 on 2022-06-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0296_auto_20220527_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='HBA1C',
        ),
    ]
