# Generated by Django 2.2.11 on 2022-07-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0298_auto_20220625_1627'),
        ('facility', '0298_facility_features'),
    ]

    operations = [
    ]
