# Generated by Django 2.2.11 on 2022-07-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0298_auto_20220630_1212'),
        ('facility', '0299_merge_20220704_0225'),
    ]

    operations = [
    ]
