# Generated by Django 2.2.11 on 2022-07-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0297_facility_location'),
        ('facility', '0299_merge_20220704_0225'),
    ]

    operations = [
    ]
