# Generated by Django 2.2.11 on 2022-07-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0300_merge_20220704_1658'),
        ('facility', '0300_merge_20220707_2339'),
    ]

    operations = [
    ]
