# Generated by Django 2.2.11 on 2022-07-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0301_auto_20220709_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="in_use",
            field=models.BooleanField(default=False),
        ),
    ]
