# Generated by Django 2.2.11 on 2022-07-23 15:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0301_auto_20220709_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="prn_prescription",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
