# Generated by Django 2.2.11 on 2022-08-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0308_auto_20220805_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyround',
            name='current_health',
        ),
    ]
