# Generated by Django 2.2.11 on 2022-08-11 11:16

from django.db import migrations, models


def populate_data(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")
    patient_consultations = PatientConsultation.objects.all()

    for patient_cons in patient_consultations:
        if patient_cons.patient.allergies is not None:
            patient_cons.has_allergy = True
            patient_cons.allergies = patient_cons.patient.allergies
        patient_cons.save()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0308_auto_20220805_2247"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="allergies",
            field=models.TextField(
                blank=True, default="", verbose_name="Patient's Known Allergies"
            ),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="has_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="allergies",
        ),
    ]
