# Generated by Django 2.2.11 on 2022-08-20 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0309_auto_20220818_1949"),
        ("facility", "0309_auto_20220820_1541"),
    ]

    operations = []
