# Generated by Django 2.2.11 on 2022-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0309_auto_20220811_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("UNK", "UNKNOWN"),
                ],
                max_length=4,
                null=True,
                verbose_name="Blood Group of Patient",
            ),
        ),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="blood_group",
        ),
    ]
