# Generated by Django 2.2.11 on 2022-08-11 11:36

from django.db import migrations, models


def populate_data(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")
    patient_consultations = PatientConsultation.objects.all()

    for patient_cons in patient_consultations:
        if patient_cons.patient.blood_group is not None:
            patient_cons.blood_group = patient_cons.patient.blood_group

        patient_cons.save()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0309_auto_20220811_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("UNK", "UNKNOWN"),
                ],
                max_length=4,
                null=True,
                verbose_name="Blood Group of Patient",
            ),
        ),
        migrations.RunPython(populate_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="blood_group",
        ),
    ]
