# Generated by Django 2.2.11 on 2022-08-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0310_auto_20220811_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='family_details',
            field=models.TextField(blank=True, default='', verbose_name="Patient's Family Details"),
        ),
    ]
