# Generated by Django 2.2.11 on 2022-08-21 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0310_merge_20220820_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='exudate_amount',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'LIGHT'), (2, 'MODERATE'), (3, 'HIGH')], default=0),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='length',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='push_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='tissue_type',
            field=models.IntegerField(choices=[(0, 'CLOSED'), (1, 'EPITHELIAL'), (2, 'GRANULATION'), (3, 'SLOUGH'), (4, 'NECROTIC')], default=0),
        ),
        migrations.AddField(
            model_name='dailyround',
            name='width',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
