# Generated by Django 2.2.11 on 2022-08-11 14:23

from django.db import migrations, models


def populate_data(apps, schema_editor):
    Consultation = apps.get_model("facility", "PatientConsultation")
    patient_consultations = Consultation.objects.all()

    for patient_cons in patient_consultations:
        if patient_cons.patient.present_health is not None:
            patient_cons.present_health = patient_cons.patient.present_health

        if patient_cons.patient.ongoing_medication is not None:
            patient_cons.ongoing_medication = patient_cons.patient.ongoing_medication

        patient_cons.save()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0311_patientconsultation_family_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="ongoing_medication",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Already pescribed medication if any",
            ),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="present_health",
            field=models.TextField(
                blank=True, default="", verbose_name="Patient's Current Health Details"
            ),
        ),
        migrations.RunPython(populate_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="ongoing_medication",
        ),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="present_health",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="ongoing_medication",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="present_health",
        ),
    ]
