# Generated by Django 2.2.11 on 2022-09-01 02:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0312_patientconsultation_investigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsultation',
            name='diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), blank=True, default=[], null=True, size=None),
        ),
    ]
