# Generated by Django 2.2.11 on 2022-08-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0312_patientconsultation_investigation'),
        ('facility', '0311_auto_20220831_0900'),
    ]

    operations = [
    ]
