# Generated by Django 2.2.11 on 2022-09-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0314_patientconsultation_icd11_diagnoses'),
        ('facility', '0313_merge_20220831_1553'),
    ]

    operations = [
    ]
