# Generated by Django 2.2.11 on 2022-09-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0314_patientconsultation_icd11_diagnoses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyround',
            old_name='patient_category',
            new_name='deprecated_covid_category',
        ),
        migrations.RenameField(
            model_name='patientconsultation',
            old_name='category',
            new_name='deprecated_covid_category',
        ),
    ]
