# Generated by Django 2.2.11 on 2022-09-06 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0314_patientconsultation_icd11_diagnoses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('called_at', models.DateTimeField(auto_now=True, null=True)),
                ('call_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_metrics_to_user', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_external_id', to='facility.PatientConsultation')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_metrics_from_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
