# Generated by Django 2.2.11 on 2022-09-06 11:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0314_patientconsultation_icd11_diagnoses'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='icd11_provisional_diagnoses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
    ]
