# Generated by Django 2.2.11 on 2022-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0315_auto_20220908_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='patient_category',
            field=models.CharField(choices=[('Comfort', 'Comfort Care'), ('Stable', 'Stable'), ('Moderate', 'Slightly Abnormal'), ('Critical', 'Critical')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='category',
            field=models.CharField(choices=[('Comfort', 'Comfort Care'), ('Stable', 'Stable'), ('Moderate', 'Slightly Abnormal'), ('Critical', 'Critical')], max_length=8, null=True),
        ),
    ]
