# Generated by Django 2.2.11 on 2022-09-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0315_patientconsultation_icd11_provisional_diagnoses'),
        ('facility', '0316_auto_20220908_1112'),
    ]

    operations = [
    ]
