# Generated by Django 2.2.11 on 2022-09-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0317_merge_20220915_2209'),
        ('facility', '0315_auto_20220909_0925'),
    ]

    operations = [
    ]
