# Generated by Django 2.2.11 on 2022-09-17 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0318_merge_20220917_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='medicine_administration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
