# Generated by Django 2.2.11 on 2022-09-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0319_file_upload_completed'),
        ('facility', '0320_merge_20220920_2114'),
    ]

    operations = [
    ]
