# Generated by Django 2.2.11 on 2022-09-30 12:55

from django.db import migrations, models
import django.db.models.deletion
import partial_index


def populate_data(apps, schema_editor):
    patient_consultation = apps.get_model("facility", "PatientConsultation")
    patients_cons = patient_consultation.objects.all()

    patient_consultation_symptom = apps.get_model(
        "facility", "PatientConsultationSymptom"
    )
    patient_symptom_objs = []
    for patient_cons in patients_cons:
        for patient_symptom in patient_cons.symptoms:
            patient_symptom_objs.append(
                patient_consultation_symptom(
                    consultation=patient_cons,
                    symptom=patient_symptom,
                    symptom_onset_date=patient_cons.symptoms_onset_date.date(),
                )
            )

    patient_consultation_symptom.objects.bulk_create(patient_symptom_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0321_merge_20220921_2255"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientConsultationSymptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symptom",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "ASYMPTOMATIC"),
                            (2, "FEVER"),
                            (3, "SORE THROAT"),
                            (4, "COUGH"),
                            (5, "BREATHLESSNESS"),
                            (6, "MYALGIA"),
                            (7, "ABDOMINAL DISCOMFORT"),
                            (8, "VOMITING/DIARRHOEA"),
                            (9, "OTHERS"),
                            (10, "SARI"),
                            (11, "SPUTUM"),
                            (12, "NAUSEA"),
                            (13, "CHEST PAIN"),
                            (14, "HEMOPTYSIS"),
                            (15, "NASAL DISCHARGE"),
                            (16, "BODY ACHE"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "symptom_onset_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_symptoms",
                        to="facility.PatientConsultation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="patientconsultationsymptom",
            index=partial_index.PartialIndex(
                fields=["consultation", "symptom"],
                name="facility_pa_consult_6f7ce1_partial",
                unique=True,
                where=partial_index.PQ(deleted=False),
            ),
        ),
        migrations.RunPython(populate_data, migrations.RunPython.noop),
        migrations.AddField(
            model_name="patientconsultation",
            name="is_asymptomatic",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="other_symptoms",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="symptoms_onset_date",
        ),
    ]
