# Generated by Django 2.2.11 on 2022-10-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0322_fileupload_is_archived'),
        ('facility', '0322_patienthealthdetails'),
    ]

    operations = [
    ]
