# Generated by Django 2.2.11 on 2022-10-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0322_fileupload_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="archive_reason",
            field=models.TextField(blank=True),
        ),
    ]
