# Generated by Django 2.2.11 on 2022-10-14 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import partial_index
import uuid
import care.facility.models.mixins.permissions.patient
from care.facility.models.patient_base import DISEASE_CHOICES


def create_medical_history(apps, schema_editor):
    patient_registration = apps.get_model("facility", "PatientRegistration")
    patients = patient_registration.objects.all()

    medical_history = apps.get_model("facility", "MedicalHistory")
    medical_history_objs = []
    for patient in patients:
        medical_history_objs.append(
            medical_history(
                patient=patient,
                ongoing_medication=patient.ongoing_medication,
                present_health=patient.present_health,
            )
        )

    medical_history.objects.bulk_create(medical_history_objs)


def link_data(apps, schema_editor):
    patient_consultation = apps.get_model("facility", "PatientConsultation")
    medical_history = apps.get_model("facility", "MedicalHistory")
    patient_cons_objs = patient_consultation.objects.all()

    for patient_cons in patient_cons_objs:
        patient_cons.last_medical_history = medical_history.objects.get(
            id=patient_cons.patient.id
        )
        patient_cons.save(update_fields=["last_medical_history"])


def create_disease_history(apps, schema_editor):
    disease_history = apps.get_model("facility", "Diseases")
    disease_model = apps.get_model("facility", "Disease")
    diseases = disease_model.objects.filter(deleted=False)

    disease_objs = []
    for disease in diseases:
        disease_objs.append(
            disease_history(
                patient=disease.patient,
                disease=DISEASE_CHOICES[disease.disease],
                details=disease.details,
                date=datetime.date.today(),
            )
        )

    disease_history.objects.bulk_create(disease_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0323_merge_20221005_1742"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, unique=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, null=True
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "ongoing_medication",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Already pescribed medication if any",
                    ),
                ),
                (
                    "present_health",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Patient's Current Health Details",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.PatientRegistration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                care.facility.models.mixins.permissions.patient.PatientRelatedPermissionMixin,
            ),
        ),
        migrations.CreateModel(
            name="Diseases",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("precision", models.IntegerField(default=0)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "medical_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_diseases",
                        to="facility.MedicalHistory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="last_medical_history",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facility.MedicalHistory",
            ),
        ),
        migrations.RunPython(
            create_medical_history, migrations.RunPython.noop
        ),
        migrations.RunPython(link_data, migrations.RunPython.noop),
        migrations.RunPython(
            create_disease_history, migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.AddIndex(
            model_name="diseases",
            index=partial_index.PartialIndex(
                fields=["medical_history", "disease"],
                name="facility_di_medical_1af9d2_partial",
                unique=True,
                where=partial_index.PQ(deleted=False),
            ),
        ),
    ]
