# Generated by Django 2.2.11 on 2022-10-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0324_auto_20221014_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.PatientConsultation'),
        ),
    ]
