# Generated by Django 2.2.11 on 2022-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0326_auto_20221018_1526'),
        ('facility', '0322_auto_20220930_1825'),
    ]

    operations = [
    ]
