# Generated by Django 2.2.11 on 2022-10-27 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0327_merge_20221027_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultationsymptom",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="patientconsultationsymptom",
            name="external_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, unique=True
            ),
        ),
        migrations.AddField(
            model_name="patientconsultationsymptom",
            name="modified_date",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True
            ),
        ),
    ]
