# Generated by Django 2.2.11 on 2023-01-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0330_auto_20221220_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsearch',
            name='state_id',
            field=models.IntegerField(null=True),
        ),
    ]
