# Generated by Django 2.2.11 on 2022-12-24 10:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import care.utils.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0330_auto_20221223_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "anyOf": [
                                {"$ref": "#/definitions/onvif"},
                                {"$ref": "#/definitions/hl7monitor"},
                                {"$ref": "#/definitions/empty"},
                            ],
                            "definitions": {
                                "empty": {
                                    "additionalProperties": False,
                                    "type": "object",
                                },
                                "hl7monitor": {
                                    "additionalProperties": False,
                                    "properties": {
                                        "asset_type": {"type": "string"},
                                        "insecure_connection": {"type": "boolean"},
                                        "local_ip_address": {"type": "string"},
                                        "middleware_hostname": {"type": "string"},
                                    },
                                    "required": ["local_ip_address"],
                                    "type": "object",
                                },
                                "onvif": {
                                    "additionalProperties": False,
                                    "properties": {
                                        "asset_type": {"type": "string"},
                                        "camera_access_key": {"type": "string"},
                                        "camera_type": {"type": "string"},
                                        "insecure_connection": {"type": "boolean"},
                                        "local_ip_address": {"type": "string"},
                                        "middleware_hostname": {"type": "string"},
                                    },
                                    "required": [
                                        "local_ip_address",
                                        "camera_access_key",
                                    ],
                                    "type": "object",
                                },
                            },
                        }
                    )
                ],
            ),
        ),
    ]
