# Generated by Django 2.2.11 on 2023-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0331_auto_20221224_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientconsultation",
            name="suggestion",
            field=models.CharField(
                choices=[
                    ("HI", "HOME ISOLATION"),
                    ("A", "ADMISSION"),
                    ("R", "REFERRAL"),
                    ("OP", "OP CONSULTATION"),
                    ("DC", "DOMICILIARY CARE"),
                    ("DD", "DECLARE DEATH"),
                ],
                max_length=4,
            ),
        ),
    ]
