# Generated by Django 2.2.11 on 2023-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0334_merge_20230113_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='predated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
