# Generated by Django 2.2.11 on 2023-03-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0335_auto_20230207_1914"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="op_no",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
