# Generated by Django 2.2.11 on 2023-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0343_auto_20230407_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientregistration",
            name="action",
            field=models.IntegerField(
                choices=[
                    (10, "PENDING"),
                    (30, "SPECIALIST_REQUIRED"),
                    (40, "PLAN_FOR_HOME_CARE"),
                    (50, "FOLLOW_UP_NOT_REQUIRED"),
                    (60, "COMPLETE"),
                    (70, "REVIEW"),
                    (80, "NOT_REACHABLE"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="patientregistration",
            name="action",
            field=models.IntegerField(
                choices=[
                    (10, "PENDING"),
                    (30, "SPECIALIST_REQUIRED"),
                    (40, "PLAN_FOR_HOME_CARE"),
                    (50, "FOLLOW_UP_NOT_REQUIRED"),
                    (60, "COMPLETE"),
                    (70, "REVIEW"),
                    (80, "NOT_REACHABLE"),
                ]
            ),
        ),
    ]
