# Generated by Django 2.2.11 on 2023-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0343_auto_20230407_1850"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftingrequest",
            name="assigned_facility_external",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
