# Generated by Django 2.2.11 on 2023-04-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0343_auto_20230407_1850'),
        ('facility', '0331_auto_20230130_1652'),
    ]

    operations = [
    ]
