# Generated by Django 2.2.11 on 2023-04-12 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0344_medicineadministration_pnrprescription_prescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PNRPrescription',
            new_name='PRNPrescription',
        ),
        migrations.RenameField(
            model_name='medicineadministration',
            old_name='pnr_prescription',
            new_name='prn_prescription',
        ),
    ]
