# Generated by Django 2.2.11 on 2023-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0345_auto_20230413_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='discontinued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='discontinued_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prnprescription',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prnprescription',
            name='discontinued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prnprescription',
            name='discontinued_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
