# Generated by Django 2.2.11 on 2023-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0346_auto_20230413_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineadministration',
            name='prn_prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_pn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='max_dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='min_hours_between_doses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PRNPrescription',
        ),
    ]
