# Generated by Django 2.2.11 on 2023-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0349_auto_20230417_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IV', 'IV'), ('IM', 'IM'), ('SC', 'S/C')], max_length=100, null=True),
        ),
    ]
