# Generated by Django 2.2.11 on 2023-04-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0351_auto_20230417_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_discharge',
            field=models.BooleanField(default=False),
        ),
    ]
