# Generated by Django 2.2.11 on 2023-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0351_assetservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='last_serviced_on',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
    ]
