# Generated by Django 2.2.11 on 2023-04-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0352_auto_20230426_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_service', to='facility.AssetService'),
        ),
    ]
