# Generated by Django 2.2.11 on 2023-04-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0352_prescription_is_discharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='is_discharge',
        ),
    ]
