# Generated by Django 2.2.11 on 2023-05-03 19:25

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    patient_notes_model = apps.get_model("facility", "PatientNotes")
    patient_notes = patient_notes_model.objects.all()
    for patient_note in patient_notes:
        if patient_note.patient.last_consultation:
            patient_note.consultation = patient_note.patient.last_consultation
            patient_note.save()


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0352_auto_20230428_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.PatientConsultation",
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
