# Generated by Django 2.2.11 on 2023-05-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0352_auto_20230428_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (1, "PATIENT"),
                    (2, "CONSULTATION"),
                    (3, "SAMPLE_MANAGEMENT"),
                    (4, "CLAIM"),
                    (5, "COMMUNICATION"),
                ],
                default=1,
            ),
        ),
    ]
