# Generated by Django 2.2.11 on 2023-04-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0353_remove_prescription_is_discharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineadministration',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='facility.Prescription'),
        ),
    ]
