# Generated by Django 2.2.11 on 2023-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0354_auto_20230417_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineadministration',
            name='administered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
