# Generated by Django 2.2.11 on 2023-04-18 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0355_medicineadministration_administered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineadministration',
            name='administered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
