# Generated by Django 2.2.11 on 2023-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0355_auto_20230429_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
