# Generated by Django 2.2.11 on 2023-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0356_auto_20230520_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(max_length=1023),
        ),
    ]
