# Generated by Django 2.2.11 on 2023-06-06 16:18

from django.db import migrations, models


def decrypt_patient_registration_fields(apps, schema_editor):
    PatientRegistration = apps.get_model("facility", "PatientRegistration")

    to_update = []
    for patient_registration in PatientRegistration.objects.all():
        patient_registration.patient_search_id_temp = (
            patient_registration.patient_search_id
        )
        to_update.append(patient_registration)

    PatientRegistration.objects.bulk_update(to_update, ["patient_search_id_temp"])


def decrypt_patient_search_fields(apps, schema_editor):
    PatientSearch = apps.get_model("facility", "PatientSearch")

    to_update = []
    for patient_search in PatientSearch.objects.all():
        patient_search.patient_id_temp = patient_search.patient_id
        patient_search.patient_external_id_temp = patient_search.patient_external_id
        to_update.append(patient_search)

    PatientSearch.objects.bulk_update(
        to_update, ["patient_id_temp", "patient_external_id_temp"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0359_auto_20230529_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientregistration",
            name="patient_search_id_temp",
            field=models.IntegerField(help_text="FKey to PatientSearch", null=True),
        ),
        migrations.AddField(
            model_name="patientregistration",
            name="patient_search_id_temp",
            field=models.IntegerField(help_text="FKey to PatientSearch", null=True),
        ),
        migrations.RunPython(
            decrypt_patient_registration_fields, migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="patientsearch",
            name="patient_external_id_temp",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patientsearch",
            name="patient_id_temp",
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(decrypt_patient_search_fields, migrations.RunPython.noop),
    ]
