# Generated by Django 2.2.11 on 2023-06-10 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0360_auto_20230608_1750"),
        ("facility", "0360_auto_20230608_1045"),
    ]

    operations = []
