# Generated by Django 2.2.11 on 2023-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0360_auto_20230608_1750"),
        ("facility", "0344_merge_20230413_1120"),
    ]

    operations = []
