# Generated by Django 2.2.11 on 2023-06-06 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0360_auto_20230606_2148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientregistration",
            name="patient_search_id",
        ),
        migrations.RemoveField(
            model_name="patientsearch",
            name="patient_external_id",
        ),
        migrations.RemoveField(
            model_name="patientsearch",
            name="patient_id",
        ),
        migrations.RenameField(
            model_name="patientregistration",
            old_name="patient_search_id_temp",
            new_name="patient_search_id",
        ),
        migrations.RenameField(
            model_name="patientsearch",
            old_name="patient_external_id_temp",
            new_name="patient_external_id",
        ),
        migrations.RenameField(
            model_name="patientsearch",
            old_name="patient_id_temp",
            new_name="patient_id",
        ),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="patient_search_id_temp",
        ),
    ]
