# Generated by Django 2.2.11 on 2023-06-08 16:14

from django.db import migrations, models


def set_patient_and_bed_count(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")

    facilities = Facility.objects.filter(deleted=False, is_active=True).annotate(
        annotated_patient_count=models.Count(
            "patientregistration",
            filter=models.Q(
                patientregistration__is_active=True, patientregistration__deleted=False
            ),
        ),
        annotated_bed_count=models.Count("bed", filter=models.Q(bed__deleted=False)),
    )

    updated_facilities = []
    for facility in facilities:
        facility.patient_count = facility.annotated_patient_count
        facility.bed_count = facility.annotated_bed_count
        updated_facilities.append(facility)

    Facility.objects.bulk_update(updated_facilities, ["patient_count", "bed_count"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0360_auto_20230608_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="bed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facility",
            name="patient_count",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            set_patient_and_bed_count, reverse_code=migrations.RunPython.noop
        ),
    ]
