# Generated by Django 2.2.11 on 2023-06-17 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0362_auto_20230608_1852"),
        ("facility", "0361_merge_20230610_2126"),
    ]

    operations = []
