# Generated by Django 4.2.2 on 2023-06-24 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0363_auto_20230621_1857"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcerequest",
            old_name="orgin_facility",
            new_name="origin_facility",
        ),
        migrations.RenameField(
            model_name="shiftingrequest",
            old_name="orgin_facility",
            new_name="origin_facility",
        ),
    ]
