# Generated by Django 2.2.11 on 2023-06-17 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0362_merge_20230617_1253"),
        ("facility", "0363_merge_20230617_1251"),
    ]

    operations = []
