# Generated by Django 4.2.2 on 2023-06-26 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "facility",
            "0364_alter_historicalpatientregistration_emergency_phone_number_and_more",
        ),
        (
            "facility",
            "0364_rename_orgin_facility_resourcerequest_origin_facility_and_more",
        ),
    ]

    operations = []
