# Generated by Django 4.2.2 on 2023-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0330_auto_20221220_2312"),
        ("facility", "0365_merge_20230626_1834"),
    ]

    operations = []
