# Generated by Django 4.2.2 on 2023-07-03 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0366_auto_20230627_1806"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientconsultation",
            name="HBA1C",
        ),
    ]
