# Generated by Django 4.2.2 on 2023-06-28 09:58

from django.core.management import call_command
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0367_prescription_medicine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medibasemedicine",
            name="external_id",
        ),
        migrations.AlterField(
            model_name="medibasemedicine",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: call_command("load_medicines_data"),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
