# Generated by Django 4.2.2 on 2023-06-28 09:58

from django.core.management import call_command
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0369_medibase_search_vectors_and_triggers"),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: call_command("load_medicines_data"),
            reverse_code=migrations.RunPython.noop,
        )
    ]
