# Generated by Django 4.2.2 on 2023-07-05 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0367_auto_20230704_1646"),
        ("facility", "0369_merge_0366_auto_20230627_1806_0368_populate_medibase"),
    ]

    operations = []
