# Generated by Django 4.2.2 on 2023-07-06 11:18

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0370_merge_20230705_1500"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="medibasemedicine",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "generic", "company", "contents", "cims_class"],
                name="search_idx",
            ),
        ),
    ]
