# Generated by Django 4.2.2 on 2023-07-05 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0370_merge_20230705_1500"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientconsultation",
            name="HBA1C",
        ),
    ]
