# Generated by Django 4.2.2 on 2023-07-14 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0371_assetavailabilityrecord"),
        ("facility", "0371_metaicd11diagnosis_chapter_and_more"),
    ]

    operations = []
