# Generated by Django 4.2.2 on 2023-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0372_merge_20230714_1912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetavailabilityrecord",
            name="timestamp",
            field=models.DateTimeField(unique=True),
        ),
    ]
