# Generated by Django 4.2.2 on 2023-07-19 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0372_assetavailabilityrecord"),
        ("facility", "0372_merge_20230719_1719"),
    ]

    operations = []
