# Generated by Django 4.2.2 on 2023-07-20 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0372_assetavailabilityrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientconsultation",
            name="HBA1C",
        ),
    ]
