# Generated by Django 4.2.2 on 2023-07-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0373_alter_assetavailabilityrecord_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetavailabilityrecord",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="assetavailabilityrecord",
            unique_together={("asset", "timestamp")},
        ),
    ]
