# Generated by Django 4.2.2 on 2023-07-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0374_historicalpatientregistration_abha_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.patientconsultation",
            ),
        ),
    ]
