# Generated by Django 4.2.2 on 2023-07-24 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0372_merge_20230714_1417"),
        ("facility", "0374_historicalpatientregistration_abha_number_and_more"),
    ]

    operations = []
