# Generated by Django 4.2.2 on 2023-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0374_historicalpatientregistration_abha_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="created_by_local_user",
            field=models.CharField(default="", max_length=25),
        )
    ]
