# Generated by Django 4.2.2 on 2023-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0375_alter_dailyround_resp"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="user_type",
            field=models.CharField(default="", max_length=25),
        ),
    ]
