# Generated by Django 4.2.2 on 2023-08-08 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0376_alter_ambulance_owner_phone_number_and_more"),
        ("facility", "0376_auto_20230807_2148"),
    ]

    operations = []
