# Generated by Django 4.2.2 on 2023-08-15 14:27
from django.db.models import F
from django.db import migrations

def convert_negative_to_positive(apps, schema_editor):
    HospitalDoctors = apps.get_model('care', 'HospitalDoctors')
    HospitalDoctors.objects.filter(count__lt=0).update(count=F('count') * -1)


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0376_alter_hospitaldoctors_count'),
        ('facility', '0376_auto_20230807_2148'),
    ]

    operations = [
        migrations.RunPython(convert_negative_to_positive),
    ]
