# Generated by Django 4.2.2 on 2023-08-09 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0377_merge_20230809_0009"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientconsultation",
            old_name="prescribed_medication",
            new_name="treatment_plan",
        ),
    ]
