# Generated by Django 4.2.2 on 2023-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0378_merge_20230809_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetservice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
