# Generated by Django 4.2.2 on 2023-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0378_consultationbedasset_consultationbed_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="user_type",
            field=models.CharField(default="", max_length=25),
        ),
    ]
