# Generated by Django 4.2.2 on 2023-08-25 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0381_merge_ip_op_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.patientconsultation",
            ),
        ),
    ]
