# Generated by Django 4.2.2 on 2023-09-05 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0379_consultationbed_privacy"),
        ("facility", "0382_assetservice_remove_asset_last_serviced_on_and_more"),
    ]

    operations = []
