# Generated by Django 4.2.2 on 2023-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0383_patientconsultation_icd11_principal_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaicd11diagnosis",
            name="chapter_short",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="metaicd11diagnosis",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
