# Generated by Django 4.2.2 on 2023-09-06 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0383_patientconsultation_icd11_principal_diagnosis"),
        ("facility", "0383_patientconsultation_verified_by"),
    ]

    operations = []
