# Generated by Django 4.2.2 on 2023-11-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0384_patientconsultation_verified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_locked",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="locked_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="waiting_users",
            field=models.ManyToManyField(
                related_name="waitingUsers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
