# Generated by Django 4.2.2 on 2023-09-11 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0384_metaicd11diagnosis_chapter_short_and_more"),
        ("facility", "0385_patientconsultation_is_readmission"),
        ("facility", "0386_auto_20230911_1726"),
    ]

    operations = []
