# Generated by Django 4.2.2 on 2023-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0387_merge_20230911_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetlocation",
            name="middleware_address",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
