# Generated by Django 4.2.2 on 2023-09-20 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0387_merge_20230911_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineadministration",
            name="archived_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicineadministration",
            name="archived_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
