# Generated by Django 4.2.5 on 2023-10-05 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0388_goal_goalentry_goalproperty_goalpropertyentry"),
        ("facility", "0388_icd11diagnosis"),
    ]

    operations = []
