# Generated by Django 4.2.5 on 2023-10-02 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0388_alter_historicalpatientregistration_action_and_more"),
        ("facility", "0388_goal_goalentry_goalproperty_goalpropertyentry"),
    ]

    operations = []
