# Generated by Django 4.2.5 on 2023-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0388_goal_goalentry_goalproperty_goalpropertyentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaHubSpokes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                (
                    "hub",
                    models.CharField(help_text="Hub hospital name", max_length=255),
                ),
                (
                    "spoke",
                    models.CharField(help_text="Spoke hospital name", max_length=255),
                ),
            ],
            options={
                "db_table": "meta_hub_spokes",
            },
        ),
    ]
