# Generated by Django 4.2.2 on 2023-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0388_goal_goalentry_goalproperty_goalpropertyentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetlocation",
            name="middleware_address",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
