# Generated by Django 4.2.6 on 2023-10-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0389_merge_20231005_2247"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="medico_legal_case",
            field=models.BooleanField(default=False),
        ),
    ]
