# Generated by Django 4.2.5 on 2023-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0389_merge_20231005_2247"),
    ]

    def clean_admission_time(apps, schema_editor):
        PatientConsultation = apps.get_model("facility", "PatientConsultation")

        # Remove time from admission_date
        queryset = PatientConsultation.objects.filter(admission_date__isnull=False)
        queryset.update(admission_date=models.F("admission_date__date"))

    operations = [
        migrations.RunPython(
            clean_admission_time,
            reverse_code=migrations.RunPython.noop,
        )
    ]
