# Generated by Django 4.2.5 on 2023-10-11 05:02

from django.db import migrations, models


def migrate_consciousness_level(apps, schema_editor):
    daily_round_model = apps.get_model("facility", "DailyRound")
    records = daily_round_model.objects.all()

    entries = []

    for record in records:
        consciousness_level = record.consciousness_level
        if consciousness_level == 25:
            record.consciousness_level = 0
            entries.append(record)
    daily_round_model.objects.bulk_update(entries, ["consciousness_level"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0389_merge_20231005_2247"),
    ]

    operations = [
        migrations.RunPython(migrate_consciousness_level, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dailyround",
            name="consciousness_level",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "ALERT"),
                    (10, "RESPONDS_TO_VOICE"),
                    (15, "RESPONDS_TO_PAIN"),
                    (20, "UNRESPONSIVE"),
                    (25, "AGITATED_OR_CONFUSED"),
                    (30, "ONSET_OF_AGITATION_AND_CONFUSION"),
                ],
                default=0,
            ),
        ),
    ]
