# Generated by Django 4.2.5 on 2023-10-16 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0389_assetlocation_middleware_address"),
        ("facility", "0389_medicineadministration_archived_by_and_more"),
        ("facility", "0389_merge_20231002_1802"),
        ("facility", "0390_patientconsultation_medico_legal_case"),
    ]

    operations = []
