# Generated by Django 4.2.5 on 2023-10-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0391_merge_20231016_1845"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientconsultation",
            old_name="consultation_status",
            new_name="deprecated_consultation_status",
        ),
        migrations.RenameField(
            model_name="patientconsultation",
            old_name="verified_by",
            new_name="treating_physician",
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="icu_admission_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="referred_by_external",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="referred_from_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.facility",
            ),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="referred_from_facility_external",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="route_to_facility",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (None, "(Unknown)"),
                    (10, "Outpatient/Emergency Room"),
                    (20, "Referred from another facility"),
                    (30, "Internal Transfer within the facility"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientconsultation",
            name="transferred_from_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.assetlocation",
            ),
        ),
    ]
