# Generated by Django 4.2.5 on 2023-10-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0392_alter_dailyround_consciousness_level"),
    ]

    def copy_prn_to_dosage_type(apps, schema_editor):
        Prescription = apps.get_model("facility", "Prescription")
        Prescription.objects.filter(is_prn=True).update(dosage_type="PRN")

    def reverse_copy_prn_to_dosage_type(apps, schema_editor):
        Prescription = apps.get_model("facility", "Prescription")
        Prescription.objects.filter(is_prn=False).update(dosage_type="REGULAR")

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="dosage",
            new_name="base_dosage",
        ),
        migrations.AddField(
            model_name="prescription",
            name="dosage_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "REGULAR"),
                    ("TITRATED", "TITRATED"),
                    ("PRN", "PRN"),
                ],
                default="REGULAR",
                max_length=100,
            ),
        ),
        migrations.RunPython(
            copy_prn_to_dosage_type, reverse_code=reverse_copy_prn_to_dosage_type
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="is_prn",
        ),
        migrations.AddField(
            model_name="prescription",
            name="instruction_on_titration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="target_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicineadministration",
            name="dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
