# Generated by Django 4.2.7 on 2023-11-15 18:13

from django.db import migrations, models

import care.facility.models.prescription


class Migration(migrations.Migration):
    dependencies = [
        (
            "facility",
            "0393_rename_diagnosis_patientconsultation_deprecated_diagnosis_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="dosage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[care.facility.models.prescription.DosageValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="max_dosage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[care.facility.models.prescription.DosageValidator()],
            ),
        ),
    ]
