# Generated by Django 4.2.5 on 2023-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "facility",
            "0393_rename_diagnosis_patientconsultation_deprecated_diagnosis_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="dosage",
            new_name="base_dosage",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="is_prn",
        ),
        migrations.AddField(
            model_name="medicineadministration",
            name="dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="dosage_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "REGULAR"),
                    ("TITRATED", "TITRATED"),
                    ("PRN", "PRN"),
                ],
                default="REGULAR",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="instruction_on_titration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="target_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
