# Generated by Django 4.2.5 on 2023-11-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "facility",
            "0393_rename_diagnosis_patientconsultation_deprecated_diagnosis_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetlocation",
            name="location_type",
            field=models.IntegerField(
                choices=[(1, "OTHER"), (10, "ICU"), (20, "WARD")], default=1
            ),
        ),
    ]
