# Generated by Django 4.2.2 on 2023-11-22 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0379_consultationbed_privacy"),
        ("facility", "0393_alter_notification_event"),
        ("facility", "0394_auto_20231114_2219"),
        ("facility", "0395_alter_patientconsultation_route_to_facility"),
    ]

    operations = []
