# Generated by Django 4.2.7 on 2023-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0396_merge_20231122_0240"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationbed",
            name="privacy",
            field=models.BooleanField(default=False),
        ),
    ]
