# Generated by Django 4.2.5 on 2023-11-27 07:00

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0396_merge_20231122_0240"),
    ]

    def clean_encounter_date(apps, schema_editor):
        PatientConsultation = apps.get_model("facility", "PatientConsultation")
        PatientConsultation.objects.exclude(suggestion__in=["A", "DC"]).update(
            encounter_date=None
        )

    operations = [
        migrations.RemoveConstraint(
            model_name="patientconsultation",
            name="if_admitted",
        ),
        migrations.RenameField(
            model_name="patientconsultation",
            old_name="admission_date",
            new_name="encounter_date",
        ),
        migrations.RunPython(
            clean_encounter_date,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="patientconsultation",
            name="encounter_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
