# Generated by Django 4.2.5 on 2023-11-27 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0395_assetlocationdutystaff_assetlocation_users"),
        ("facility", "0396_merge_20231122_0240"),
    ]

    operations = []
