# Generated by Django 4.2.5 on 2023-12-06 13:06

from django.db import migrations, models

import care.utils.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0397_truncate_discharge_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="dosage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[

                ],
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="max_dosage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                ],
            ),
        ),
    ]
