# Generated by Django 4.2.6 on 2023-10-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0397_truncate_discharge_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.patientconsultation",
            ),
        ),
    ]
