# Generated by Django 4.2.5 on 2023-12-07 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0394_alter_assetlocation_location_type"),
        ("facility", "0398_alter_prescription_dosage_and_more"),
        ("facility", "0399_populate_patientnotes_consultation"),
    ]

    operations = []
