# Generated by Django 4.2.5 on 2023-12-07 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0393_alter_hospitaldoctors_count"),
        ("facility", "0400_merge_20231208_0016"),
    ]

    operations = []
