# Generated by Django 4.2.5 on 2023-12-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0401_merge_20231208_0054"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityinventorysummary",
            name="min_quantity",
            field=models.FloatField(default=0),
        ),
    ]
