# Generated by Django 4.2.5 on 2023-12-09 12:12

import care.utils.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0401_merge_20231208_0054"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="dosage",
            new_name="base_dosage",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="is_prn",
        ),
        migrations.AddField(
            model_name="medicineadministration",
            name="dosage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    care.utils.models.validators.DenominationValidator(
                        allow_floats=True,
                        max_amount=5000,
                        min_amount=0.0001,
                        precision=4,
                        units={"g", "ml", "mg", "drop(s)", "tsp", "ampule(s)"},
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="dosage_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "REGULAR"),
                    ("TITRATED", "TITRATED"),
                    ("PRN", "PRN"),
                ],
                default="REGULAR",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="instruction_on_titration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="target_dosage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    care.utils.models.validators.DenominationValidator(
                        allow_floats=True,
                        max_amount=5000,
                        min_amount=0.0001,
                        precision=4,
                        units={"g", "ml", "mg", "drop(s)", "tsp", "ampule(s)"},
                    )
                ],
            ),
        ),
    ]
