# Generated by Django 4.2.5 on 2023-12-15 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0398_assetlocationdutystaff_assetlocation_users"),
        ("facility", "0402_patientconsultation_new_discharge_reason"),
    ]

    operations = []
