# Generated by Django 4.2.5 on 2023-12-20 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0402_delete_prescriptionsupplier"),
        ("facility", "0403_alter_dailyround_rounds_type"),
        ("facility", "0403_rename_admission_date_to_encounter_date_and_more"),
    ]

    operations = []
