# Generated by Django 4.2.5 on 2024-01-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0404_merge_20231220_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientregistration",
            name="date_of_delivery",
            field=models.DateField(
                default=None, null=True, verbose_name="Date of Delivery"
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientregistration",
            name="is_postpartum",
            field=models.BooleanField(
                default=False, verbose_name="Is the patient post partum (<6 weeks)?"
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientregistration",
            name="last_menstruation_start_date",
            field=models.DateField(
                default=None, null=True, verbose_name="Last Menstruation Start Date"
            ),
        ),
        migrations.AddField(
            model_name="patientregistration",
            name="date_of_delivery",
            field=models.DateField(
                default=None, null=True, verbose_name="Date of Delivery"
            ),
        ),
        migrations.AddField(
            model_name="patientregistration",
            name="is_postpartum",
            field=models.BooleanField(
                default=False, verbose_name="Is the patient post partum (<6 weeks)?"
            ),
        ),
        migrations.AddField(
            model_name="patientregistration",
            name="last_menstruation_start_date",
            field=models.DateField(
                default=None, null=True, verbose_name="Last Menstruation Start Date"
            ),
        ),
    ]
