# Generated by Django 4.2.5 on 2023-12-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0404_merge_20231220_2227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="max_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
