# Generated by Django 4.2.8 on 2023-12-24 04:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import care.utils.event_utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0404_merge_20231220_2227"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("model", models.CharField(db_index=True, max_length=50)),
                (
                    "fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="facility.eventtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientConsultationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(db_index=True)),
                ("object_model", models.CharField(db_index=True, max_length=50)),
                ("object_id", models.IntegerField()),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "meta",
                    models.JSONField(
                        default=dict, encoder=care.utils.event_utils.CustomJSONEncoder
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        default=dict, encoder=care.utils.event_utils.CustomJSONEncoder
                    ),
                ),
                (
                    "caused_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="facility.patientconsultation",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facility.eventtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["consultation", "is_latest"],
                        name="facility_pa_consult_7b22fe_idx",
                    )
                ],
            },
        ),
    ]
