# Generated by Django 4.2.8 on 2023-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0405_bed_name_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bed",
            constraint=models.UniqueConstraint(
                fields=("name", "location"), name="unique_bed_name_in_location"
            ),
        ),
    ]
