# Generated by Django 4.2.8 on 2023-12-27 05:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0405_bed_name_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bed",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("location"),
                name="unique_bed_name_per_location",
            ),
        ),
    ]
