# Generated by Django 4.2.8 on 2024-01-17 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0406_merge_20240116_2346"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetaICD11Diagnosis",
        ),
    ]
