# Generated by Django 4.2.8 on 2024-01-21 14:03

from care.facility.models.asset import Asset
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.core.exceptions import ObjectDoesNotExist


def forwards_func(apps, schema_editor):
    AssetAvailabilityRecord = apps.get_model("facility", "AssetAvailabilityRecord")
    AvailabilityRecord = apps.get_model("facility", "AvailabilityRecord")
    ContentType = apps.get_model("contenttypes", "ContentType")

    asset_content_type = ContentType.objects.get_for_model(Asset)

    for aar in AssetAvailabilityRecord.objects.all():
        AvailabilityRecord.objects.create(
            content_type=asset_content_type,
            object_external_id=aar.asset.external_id,
            status=aar.status,
            timestamp=aar.timestamp,
        )


def backwards_func(apps, schema_editor):
    AssetAvailabilityRecord = apps.get_model("facility", "AssetAvailabilityRecord")
    AvailabilityRecord = apps.get_model("facility", "AvailabilityRecord")
    ContentType = apps.get_model("contenttypes", "ContentType")

    asset_content_type = ContentType.objects.get_for_model(Asset)

    for ar in AvailabilityRecord.objects.filter(content_type=asset_content_type):
        try:
            AssetObject = Asset.objects.get(external_id=ar.object_external_id)
            AssetAvailabilityRecord.objects.create(
                asset=AssetObject,
                status=ar.status,
                timestamp=ar.timestamp,
            )
        except ObjectDoesNotExist:
            continue  # Skip if the asset was deleted

        ar.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("facility", "0407_alter_dailyround_additional_symptoms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("object_external_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Monitored", "Not Monitored"),
                            ("Operational", "Operational"),
                            ("Down", "Down"),
                            ("Under Maintenance", "Under Maintenance"),
                        ],
                        default="Not Monitored",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("object_external_id", "timestamp")},
            },
        ),
        migrations.AddIndex(
            model_name="availabilityrecord",
            index=models.Index(
                fields=["content_type", "object_external_id"],
                name="facility_av_content_ad9eff_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabilityrecord",
            unique_together={("object_external_id", "timestamp")},
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.DeleteModel(
            name="AssetAvailabilityRecord",
        ),
    ]
