# Generated by Django 4.2.2 on 2024-01-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0407_alter_dailyround_additional_symptoms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (1, "PATIENT"),
                    (2, "CONSULTATION"),
                    (3, "SAMPLE_MANAGEMENT"),
                    (4, "CLAIM"),
                    (5, "DISCHARGE_SUMMARY"),
                    (6, "COMMUNICATION"),
                    (7, "ABDM_HEALTH_INFORMATION"),
                ],
                default=1,
            ),
        ),
    ]
