# Generated by Django 4.2.8 on 2024-01-20 10:02

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    DailyRound = apps.get_model("facility", "DailyRound")
    daily_round_objects = DailyRound.objects.all()
    objects = []
    for obj in daily_round_objects:
        if obj.consciousness_level == 0:
            obj.consciousness_level = None
        if obj.left_pupil_light_reaction == 0:
            obj.left_pupil_light_reaction = None
        if obj.right_pupil_light_reaction == 0:
            obj.right_pupil_light_reaction = None
        if obj.limb_response_upper_extremity_left == 0:
            obj.limb_response_upper_extremity_left = None
        if obj.limb_response_upper_extremity_right == 0:
            obj.limb_response_upper_extremity_right = None
        if obj.limb_response_lower_extremity_left == 0:
            obj.limb_response_lower_extremity_left = None
        if obj.limb_response_lower_extremity_right == 0:
            obj.limb_response_lower_extremity_right = None
        if obj.rhythm == 0:
            obj.rhythm = None
        if obj.ventilator_mode == 0:
            obj.ventilator_mode = None
        if obj.ventilator_interface == 0:
            obj.ventilator_interface = None
        if obj.ventilator_oxygen_modality == 0:
            obj.ventilator_oxygen_modality = None
        if obj.insulin_intake_frequency == 0:
            obj.insulin_intake_frequency = None
        if obj.bp and obj.bp.get("systolic") and obj.bp.get("diastolic"):
            if obj.bp.get("systolic") < 0 and obj.bp.get("diastolic") < 0:
                obj.bp = {}
            else:
                if obj.bp.get("systolic") < 0:
                    obj.bp.update({"systolic": None})
                if obj.bp.get("diastolic") < 0:
                    obj.bp.update({"diastolic": None})
        objects.append(obj)

    DailyRound.objects.bulk_update(
        objects,
        [
            "consciousness_level",
            "left_pupil_light_reaction",
            "right_pupil_light_reaction",
            "limb_response_upper_extremity_left",
            "limb_response_upper_extremity_right",
            "limb_response_lower_extremity_left",
            "limb_response_lower_extremity_right",
            "rhythm",
            "ventilator_mode",
            "ventilator_interface",
            "ventilator_oxygen_modality",
            "insulin_intake_frequency",
            "bp",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0407_alter_dailyround_additional_symptoms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyround",
            name="consciousness_level",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "ALERT"),
                    (10, "RESPONDS_TO_VOICE"),
                    (15, "RESPONDS_TO_PAIN"),
                    (20, "UNRESPONSIVE"),
                    (25, "AGITATED_OR_CONFUSED"),
                    (30, "ONSET_OF_AGITATION_AND_CONFUSION"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="left_pupil_light_reaction",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "BRISK"),
                    (10, "SLUGGISH"),
                    (15, "FIXED"),
                    (20, "CANNOT_BE_ASSESSED"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="limb_response_lower_extremity_left",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "STRONG"),
                    (10, "MODERATE"),
                    (15, "WEAK"),
                    (20, "FLEXION"),
                    (25, "EXTENSION"),
                    (30, "NONE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="limb_response_lower_extremity_right",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "STRONG"),
                    (10, "MODERATE"),
                    (15, "WEAK"),
                    (20, "FLEXION"),
                    (25, "EXTENSION"),
                    (30, "NONE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="limb_response_upper_extremity_left",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "STRONG"),
                    (10, "MODERATE"),
                    (15, "WEAK"),
                    (20, "FLEXION"),
                    (25, "EXTENSION"),
                    (30, "NONE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="limb_response_upper_extremity_right",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "STRONG"),
                    (10, "MODERATE"),
                    (15, "WEAK"),
                    (20, "FLEXION"),
                    (25, "EXTENSION"),
                    (30, "NONE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="rhythm",
            field=models.IntegerField(
                choices=[(0, "UNKNOWN"), (5, "REGULAR"), (10, "IRREGULAR")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="right_pupil_light_reaction",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "BRISK"),
                    (10, "SLUGGISH"),
                    (15, "FIXED"),
                    (20, "CANNOT_BE_ASSESSED"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="ventilator_interface",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "INVASIVE"),
                    (10, "NON_INVASIVE"),
                    (15, "OXYGEN_SUPPORT"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="ventilator_mode",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "VCV"),
                    (10, "PCV"),
                    (15, "PRVC"),
                    (20, "APRV"),
                    (25, "VC_SIMV"),
                    (30, "PC_SIMV"),
                    (40, "PRVC_SIMV"),
                    (45, "ASV"),
                    (50, "PSV"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="ventilator_oxygen_modality",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (5, "NASAL_PRONGS"),
                    (10, "SIMPLE_FACE_MASK"),
                    (15, "NON_REBREATHING_MASK"),
                    (20, "HIGH_FLOW_NASAL_CANNULA"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="insulin_intake_frequency",
            field=models.IntegerField(
                choices=[(0, "UNKNOWN"), (5, "OD"), (10, "BD"), (15, "TD")],
                default=None,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
