# Generated by Django 4.2.8 on 2024-02-08 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0407_alter_dailyround_additional_symptoms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyround",
            name="resp",
            field=models.IntegerField(
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
    ]
