# Generated by Django 4.2.8 on 2024-02-10 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0406_bed_unique_bed_name_per_location"),
        ("facility", "0408_alter_dailyround_resp"),
        ("facility", "0408_delete_metaicd11diagnosis"),
        ("facility", "0408_historicalpatientregistration_date_of_delivery_and_more"),
    ]

    operations = []
