# Generated by Django 4.2.8 on 2024-01-21 14:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("facility", "0409_merge_20240210_1510"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("object_external_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Monitored", "Not Monitored"),
                            ("Operational", "Operational"),
                            ("Down", "Down"),
                            ("Under Maintenance", "Under Maintenance"),
                        ],
                        default="Not Monitored",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="availabilityrecord",
            index=models.Index(
                fields=["content_type", "object_external_id"],
                name="facility_av_content_ad9eff_idx",
            ),
        ),
        migrations.DeleteModel(
            name="AssetAvailabilityRecord",
        ),
    ]
