# Generated by Django 4.2.10 on 2024-02-13 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0408_patientnotesedit"),
        ("facility", "0410_availabilityrecord_delete_assetavailabilityrecord_and_more"),
        ("facility", "0410_eventtype_patientconsultationevent"),
    ]

    operations = []
