# Generated by Django 4.2.10 on 2024-03-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0414_remove_bed_old_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medibasemedicine",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="medibasemedicine",
            name="external_id",
        ),
    ]
