# Generated by Django 4.2.10 on 2024-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0414_remove_bed_old_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetlocation",
            name="middleware_address",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="middleware_address",
            field=models.CharField(
                db_index=True, default=None, max_length=200, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                models.F("meta__middleware_hostname"),
                name="asset_middleware_hostname_idx",
            ),
        ),
    ]
