# Generated by Django 4.2.10 on 2024-03-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0414_remove_bed_old_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="medibasemedicine",
            name="medical_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="new_medicine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medicine",
                to="facility.medibasemedicine",
            ),
        ),
    ]
