# Generated by Django 4.2.10 on 2024-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0414_remove_bed_old_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medibasemedicine",
            name="external_id",
        ),
        migrations.AlterField(
            model_name="medibasemedicine",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
