# Generated by Django 4.2.10 on 2024-03-04 16:27
import json

from django.db import migrations


def set_static_id(apps, schema_editor):
    MedibaseMedicine = apps.get_model("facility", "MedibaseMedicine")
    Prescription = apps.get_model("facility", "Prescription")

    if MedibaseMedicine.objects.count() == 0:
        return

    with open("data/medibase.json", "r") as f:
        data = json.load(f)

    for medicine in data:
        m = MedibaseMedicine.objects.get(name=medicine["name"])
        Prescription.objects.filter(medicine_id=m.id).update(medicine_id=medicine["id"])
        MedibaseMedicine.objects.filter(name=medicine["name"]).update(id=medicine["id"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_remove_medibasemedicine_external_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Update foreign key references in facility_prescription table
            UPDATE facility_prescription
            SET medicine_id = medicine_id + 100000
            WHERE medicine_id IN (
                SELECT id
                FROM facility_medibasemedicine
            )
            """
        ),
        migrations.RunSQL(
            """
            -- Update the id column in facility_medibasemedicine table
            UPDATE facility_medibasemedicine
            SET id = id + 100000
            """
        ),
        migrations.RunPython(
            set_static_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
