# Generated by Django 4.2.10 on 2024-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_auto_20240227_0130"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patientconsultation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("patient_no__isnull", False)),
                fields=("patient_no", "facility"),
                name="unique_patient_no_within_facility",
            ),
        ),
    ]
