# Generated by Django 4.2.10 on 2024-03-04 16:27
from django.core.management import call_command
from django.core.paginator import Paginator
from django.db import migrations
from django.db.models import F


def update_ids(apps, schema_editor):
    MedibaseMedicine = apps.get_model("facility", "MedibaseMedicine")
    offset = 100000
    batch_size = 5000

    medicines = MedibaseMedicine.objects.order_by("-id").annotate(
        new_id=F("id") + offset
    )

    paginator = Paginator(medicines, batch_size)

    for page_num in paginator.page_range:
        page = paginator.page(page_num)

        updated_medicines = []
        for medicine in page.object_list:
            medicine.id = medicine.new_id
            updated_medicines.append(medicine)

        MedibaseMedicine.objects.bulk_update(updated_medicines, ["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_remove_medibasemedicine_external_id_and_more"),
    ]

    operations = [
        migrations.RunPython(update_ids),
        migrations.RunPython(
            lambda apps, schema_editor: call_command("load_medicines_data"),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
