# Generated by Django 4.2.10 on 2024-03-01 14:59
from django.core.management import call_command
from django.db import migrations


def assign_fk_value(apps, schema_editor):
    Prescription = apps.get_model("facility", "Prescription")

    for obj in Prescription.objects.all():
        obj.new_medicine = obj.medicine
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0416_remove_medibasemedicine_medical_id_and_more"),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: call_command("load_medicines_data"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(assign_fk_value),
    ]
