# Generated by Django 4.2.10 on 2024-03-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0417_auto_20240301_2029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medibasemedicine",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicine",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="new_medicine",
            new_name="medicine",
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medicine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="facility.medibasemedicine",
            ),
        ),
    ]
