# Generated by Django 4.2.10 on 2024-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0418_alter_facility_facility_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientconsultation",
            name="patient_no",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Patient's unique number in the facility. IP number for inpatients and OP number for outpatients.",
                max_length=100,
                null=True,
            ),
        ),
    ]
