# Generated by Django 4.2.8 on 2024-03-12 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0419_alter_patientconsultation_patient_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="age",
        ),
    ]
