# Generated by Django 4.2.10 on 2024-03-12 17:48

from django.db import migrations

def double_pain_scale(apps, schema_editor):
    DailyRound = apps.get_model('facility', 'DailyRound')
    for daily_round in DailyRound.objects.all():
        if daily_round.pain_scale_enhanced:
            for item in daily_round.pain_scale_enhanced:
                if 'scale' in item:
                    item['scale'] *= 2
            daily_round.save()

def halve_pain_scale(apps, schema_editor):
    DailyRound = apps.get_model('facility', 'DailyRound')
    for daily_round in DailyRound.objects.all():
        if daily_round.pain_scale_enhanced:
            for item in daily_round.pain_scale_enhanced:
                if 'scale' in item:
                    item['scale'] /= 2
                    item['scale'] = round(item['scale'])
            daily_round.save()


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0419_alter_patientconsultation_patient_no"),
    ]

    operations = [
        migrations.RunPython(double_pain_scale, reverse_code=halve_pain_scale),
    ]
