# Generated by Django 4.2.8 on 2024-03-12 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0419_alter_patientconsultation_patient_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="age",
        ),
        migrations.AlterField(
            model_name="historicalpatientregistration",
            name="year_of_birth",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(1900)],
            ),
        ),
        migrations.AlterField(
            model_name="patientregistration",
            name="year_of_birth",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(1900)],
            ),
        ),
    ]
