# Generated by Django 4.2.10 on 2024-03-12 17:48

from math import ceil

from django.db import migrations


def double_pain_scale(apps, schema_editor):
    DailyRound = apps.get_model("facility", "DailyRound")
    records_to_update = []
    for daily_round in DailyRound.objects.filter(pain_scale_enhanced__isnull=False):
        scale = daily_round.pain_scale_enhanced.get("scale", None)
        if scale:
            daily_round.pain_scale_enhanced["scale"] *= 2

        records_to_update.append(daily_round)
    DailyRound.objects.bulk_update(records_to_update, ["pain_scale_enhanced"])


def halve_pain_scale(apps, schema_editor):
    DailyRound = apps.get_model("facility", "DailyRound")
    records_to_update = []
    for daily_round in DailyRound.objects.filter(pain_scale_enhanced__isnull=False):
        scale = daily_round.pain_scale_enhanced.get("scale", None)
        if scale:
            daily_round.pain_scale_enhanced["scale"] /= 2
            daily_round.pain_scale_enhanced["scale"] = ceil(
                daily_round.pain_scale_enhanced["scale"]
            )
        records_to_update.append(daily_round)
    DailyRound.objects.bulk_update(records_to_update, ["pain_scale_enhanced"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0419_alter_patientconsultation_patient_no"),
    ]

    operations = [
        migrations.RunPython(double_pain_scale, reverse_code=halve_pain_scale),
    ]
