# Generated by Django 4.2.10 on 2024-03-18 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_alter_dailyround_consciousness_level_and_more"),
        ("facility", "0415_consultationclinician_and_more"),
        ("facility", "0415_rename_dosage_prescription_base_dosage_and_more"),
        ("facility", "0420_migrate_shifting_facility_type"),
    ]

    operations = []
