# Generated by Django 4.2.10 on 2024-03-20 13:50

from django.db import migrations, models

OLD_TO_NEW_MAPPINGS = {
    20: 10,  # Ventilator => ICU
    30: 4,  # Covid Beds => Isolation beds
    100: 4,  # Covid Ventilators => Isolation beds
    110: 4,  # Covid ICU => Isolation beds
    120: 4,  # Covid Oxygen beds => Isolation beds
    2: 5,  # Hostel => Others
    3: 5,  # Single Room with Attached Bathroom => Others
    70: 50,  # KASP Ventilator beds => KASP ICU beds
}


def migrate_data(apps, schema_editor):
    Room = apps.get_model("facility", "Room")

    # Update Room instances
    rooms_to_update = []
    for room in Room.objects.all():
        if room.room_type in OLD_TO_NEW_MAPPINGS:
            room.room_type = OLD_TO_NEW_MAPPINGS[room.room_type]
            rooms_to_update.append(room)

    Room.objects.bulk_update(rooms_to_update, ["room_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0420_migrate_shifting_facility_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitycapacity",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (1, "General Bed"),
                    (4, "Isolation beds"),
                    (5, "Others"),
                    (10, "ICU"),
                    (150, "Oxygen beds"),
                    (0, "Total"),
                    (40, "KASP Beds"),
                    (50, "KASP ICU beds"),
                    (60, "KASP Oxygen beds"),
                    (70, "KASP Ventilator beds"),
                    (20, "Ventilator"),
                    (30, "Covid Beds"),
                    (100, "Covid Ventilators"),
                    (110, "Covid ICU"),
                    (120, "Covid Oxygen beds"),
                    (2, "Hostel"),
                    (3, "Single Room with Attached Bathroom"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacilitycapacity",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (1, "General Bed"),
                    (4, "Isolation beds"),
                    (5, "Others"),
                    (10, "ICU"),
                    (150, "Oxygen beds"),
                    (0, "Total"),
                    (40, "KASP Beds"),
                    (50, "KASP ICU beds"),
                    (60, "KASP Oxygen beds"),
                    (70, "KASP Ventilator beds"),
                    (20, "Ventilator"),
                    (30, "Covid Beds"),
                    (100, "Covid Ventilators"),
                    (110, "Covid ICU"),
                    (120, "Covid Oxygen beds"),
                    (2, "Hostel"),
                    (3, "Single Room with Attached Bathroom"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (1, "General Bed"),
                    (4, "Isolation beds"),
                    (5, "Others"),
                    (10, "ICU"),
                    (150, "Oxygen beds"),
                    (0, "Total"),
                    (40, "KASP Beds"),
                    (50, "KASP ICU beds"),
                    (60, "KASP Oxygen beds"),
                    (70, "KASP Ventilator beds"),
                    (20, "Ventilator"),
                    (30, "Covid Beds"),
                    (100, "Covid Ventilators"),
                    (110, "Covid ICU"),
                    (120, "Covid Oxygen beds"),
                    (2, "Hostel"),
                    (3, "Single Room with Attached Bathroom"),
                ]
            ),
        ),
        migrations.RunPython(migrate_data),
    ]
