# Generated by Django 4.2.10 on 2024-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0420_migrate_shifting_facility_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitycapacity",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (1, "General Bed"),
                    (4, "Isolation beds"),
                    (5, "Others"),
                    (10, "ICU"),
                    (150, "Oxygen beds"),
                    (0, "Total"),
                    (40, "KASP Beds"),
                    (50, "KASP ICU beds"),
                    (60, "KASP Oxygen beds"),
                    (70, "KASP Ventilator beds"),
                    (20, "Ventilator"),
                    (30, "Covid Beds"),
                    (100, "Covid Ventilators"),
                    (110, "Covid ICU"),
                    (120, "Covid Oxygen beds"),
                    (2, "Hostel"),
                    (3, "Single Room with Attached Bathroom"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacilitycapacity",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (1, "General Bed"),
                    (4, "Isolation beds"),
                    (5, "Others"),
                    (10, "ICU"),
                    (150, "Oxygen beds"),
                    (0, "Total"),
                    (40, "KASP Beds"),
                    (50, "KASP ICU beds"),
                    (60, "KASP Oxygen beds"),
                    (70, "KASP Ventilator beds"),
                    (20, "Ventilator"),
                    (30, "Covid Beds"),
                    (100, "Covid Ventilators"),
                    (110, "Covid ICU"),
                    (120, "Covid Oxygen beds"),
                    (2, "Hostel"),
                    (3, "Single Room with Attached Bathroom"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (1, "General Bed"),
                    (4, "Isolation beds"),
                    (5, "Others"),
                    (10, "ICU"),
                    (150, "Oxygen beds"),
                    (0, "Total"),
                    (40, "KASP Beds"),
                    (50, "KASP ICU beds"),
                    (60, "KASP Oxygen beds"),
                    (70, "KASP Ventilator beds"),
                    (20, "Ventilator"),
                    (30, "Covid Beds"),
                    (100, "Covid Ventilators"),
                    (110, "Covid ICU"),
                    (120, "Covid Oxygen beds"),
                    (2, "Hostel"),
                    (3, "Single Room with Attached Bathroom"),
                ]
            ),
        ),
    ]
