# Generated by Django 4.2.10 on 2024-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0421_merge_20240318_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="consent_records",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (1, "PATIENT"),
                    (2, "CONSULTATION"),
                    (3, "SAMPLE_MANAGEMENT"),
                    (4, "CLAIM"),
                    (5, "DISCHARGE_SUMMARY"),
                    (6, "COMMUNICATION"),
                    (7, "CONSENT_RECORD"),
                ],
                default=1,
            ),
        ),
    ]
