# Generated by Django 4.2.8 on 2024-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_patientconsultation_previous_consultation"),
        ("facility", "0421_merge_20240318_1434"),
    ]

    operations = []
