# Generated by Django 4.2.10 on 2024-03-22 12:16

from django.db import migrations


class Migration(migrations.Migration):
    def soft_delete_facility_assets(self, schema_editor):
        facility = self.get_model("facility", "Facility")
        asset = self.get_model("facility", "Asset")
        facilities = facility.objects.all().values_list("name", flat=True)
        asset.objects.exclude(current_location__facility__name__in=facilities).update(
            deleted=True
        )

    dependencies = [
        ("facility", "0421_merge_20240318_1434"),
    ]

    operations = [
        migrations.RunPython(soft_delete_facility_assets, migrations.RunPython.noop)
    ]
