# Generated by Django 4.2.10 on 2024-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0421_merge_20240318_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="consent_records",
            field=models.JSONField(default=list),
        ),
    ]
