# Generated by Django 4.2.8 on 2024-02-20 07:03

from django.db import migrations


def transfer_assigned_to_to_clinicians(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")
    ConsultationClinician = apps.get_model("facility", "ConsultationClinician")
    clinician_links = []

    consultations = PatientConsultation.objects.filter(
        assigned_to__isnull=False
    ).select_related("assigned_to")

    for consultation in consultations:
        link = ConsultationClinician(
            consultation=consultation, clinician=consultation.assigned_to
        )
        clinician_links.append(link)

    ConsultationClinician.objects.bulk_create(clinician_links)


def reverse_transfer(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")
    consultations_to_update = []

    for consultation in PatientConsultation.objects.prefetch_related(
        "assigned_clinicians"
    ).all():
        clinicians = list(consultation.assigned_clinicians.all())
        consultation.assigned_to = clinicians[0] if clinicians else None
        consultations_to_update.append(consultation)

    PatientConsultation.objects.bulk_update(consultations_to_update, ["assigned_to"])


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0421_merge_20240318_1434"),
    ]

    operations = [
        migrations.RunPython(transfer_assigned_to_to_clinicians, reverse_transfer),
    ]
