# Generated by Django 4.2.10 on 2024-03-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0421_merge_20240318_1434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="current_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.assetlocation"
            ),
        ),
        migrations.AlterField(
            model_name="assetlocation",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.facility"
            ),
        ),
    ]
