# Generated by Django 4.2.10 on 2024-03-27 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0422_merge_20240325_1411"),
        ("facility", "0422_patientconsultation_consent_records_and_more"),
    ]

    operations = []
