# Generated by Django 4.2.10 on 2024-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0422_alter_assetlocation_middleware_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyround",
            name="is_parsed_by_ocr",
            field=models.BooleanField(default=False),
        ),
    ]
