# Generated by Django 4.2.10 on 2024-03-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0422_alter_asset_current_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="last_service",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_service",
                to="facility.assetservice",
            ),
        ),
    ]
