# Generated by Django 4.2.10 on 2024-03-27 09:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import care.facility.models.ai


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0422_merge_20240325_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (1, "PATIENT"),
                    (2, "CONSULTATION"),
                    (3, "SAMPLE_MANAGEMENT"),
                    (4, "CLAIM"),
                    (5, "DISCHARGE_SUMMARY"),
                    (6, "COMMUNICATION"),
                    (7, "AI"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="AIFormFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[care.facility.models.ai.validate_json_schema],
                    ),
                ),
                ("transcript", models.TextField(blank=True, null=True)),
                ("ai_response", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("READY", "Ready"),
                            ("GENERATING_TRANSCRIPT", "Generating Transcript"),
                            ("GENERATING_AI_RESPONSE", "Generating Ai Response"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=50,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
