# Generated by Django 4.2.10 on 2024-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0423_patientconsultation_consent_records_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_category",
            field=models.CharField(
                choices=[
                    ("UNSPECIFIED", "Unspecified"),
                    ("XRAY", "Xray"),
                    ("AUDIO", "Audio"),
                    ("IDENTITY_PROOF", "Identity Proof"),
                ],
                default="UNSPECIFIED",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (0, "Other"),
                    (1, "Patient"),
                    (2, "Consultation"),
                    (3, "Sample Management"),
                    (4, "Claim"),
                    (5, "Discharge Summary"),
                    (6, "Communication"),
                    (7, "Consent Record"),
                ],
                default=1,
            ),
        ),
    ]
