# Generated by Django 4.2.10 on 2024-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0423_patientconsultation_consent_records_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="disease",
            field=models.IntegerField(
                choices=[
                    (1, "NO"),
                    (2, "Diabetes"),
                    (3, "Heart Disease"),
                    (4, "HyperTension"),
                    (5, "Chronic Renal Disease"),
                    (6, "Asthma"),
                    (7, "COPD"),
                    (8, "Bronchitis"),
                    (9, "Chronic Neurological Or Neuromuscular Disease"),
                    (10, "Immunocompromised Condition"),
                    (11, "Liver Disease"),
                    (12, "TB"),
                    (13, "Other Chronic Lung Diseases"),
                    (14, "Cancer"),
                    (15, "OTHER"),
                ]
            ),
        ),
    ]
