# Generated by Django 4.2.10 on 2024-03-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0423_alter_asset_last_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="current_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="facility.assetlocation"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_service",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_service",
                to="facility.assetservice",
            ),
        ),
        migrations.AlterField(
            model_name="assetlocation",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="facility.facility"
            ),
        ),
    ]
