# Generated by Django 4.2.10 on 2024-04-03 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0422_alter_facilityinventorylog_quantity_and_more"),
        (
            "facility",
            "0424_remove_patientregistration_age_and_add_patientregistration_death_datetime",
        ),
    ]

    operations = []
