# Generated by Django 4.2.10 on 2024-04-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0425_merge_20240403_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyround",
            name="is_parsed_by_ocr",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assetlocation",
            name="middleware_address",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="middleware_address",
            field=models.CharField(
                db_index=True, default=None, max_length=200, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                models.F("meta__middleware_hostname"),
                name="asset_middleware_hostname_idx",
            ),
        ),
    ]
