# Generated by Django 4.2.10 on 2024-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0425_merge_20240403_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyround",
            name="is_parsed_by_ocr",
            field=models.BooleanField(default=False),
        ),
    ]
