# Generated by Django 4.2.10 on 2024-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0425_merge_20240403_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (0, "OTHER"),
                    (1, "PATIENT"),
                    (2, "CONSULTATION"),
                    (3, "SAMPLE_MANAGEMENT"),
                    (4, "CLAIM"),
                    (5, "DISCHARGE_SUMMARY"),
                    (6, "COMMUNICATION"),
                    (7, "CONSENT_RECORD"),
                ],
                default=1,
            ),
        ),
    ]
