# Generated by Django 4.2.10 on 2024-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0425_merge_20240403_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmetainfo",
            name="occupation",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "STUDENT"),
                    (2, "BUSINESSMAN"),
                    (3, "HEALTH_CARE_WORKER"),
                    (4, "HEALTH_CARE_LAB_WORKER"),
                    (5, "ANIMAL_HANDLER"),
                    (6, "HEALTHCARE_PRACTITIONER"),
                    (7, "PARADEMICS"),
                    (8, "Business_related"),
                    (9, "ENGINEER"),
                    (10, "TEACHER"),
                    (11, "Other_Professions"),
                    (12, "OFFICE_ADMINISTRATIVE"),
                    (13, "CHEF"),
                    (14, "PROTECTIVE_SERVICE"),
                    (15, "HOSPITALITY"),
                    (16, "CUSTODIAL"),
                    (17, "CUSTOMER_SERVICE"),
                    (18, "SALES_SUPERVISOR"),
                    (19, "RETAIL_SALES_WORKER"),
                    (20, "INSURANCE_SALES_AGENT"),
                    (21, "SALES_REPRESENTATIVE"),
                    (22, "REAL_ESTATE"),
                    (23, "CONSTRUCTION_EXTRACTION"),
                    (24, "AGRI_NATURAL"),
                    (25, "PRODUCTION_OCCUPATION"),
                    (26, "PILOT_FLIGHT"),
                    (27, "VEHICLE_DRIVER"),
                    (28, "MILITARY"),
                    (29, "HOMEMAKER"),
                    (30, "OTHERS"),
                    (31, "UNKNOWN"),
                    (32, "NOT_APPLICABLE"),
                ],
                null=True,
            ),
        ),
    ]
