# Generated by Django 4.2.10 on 2024-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0426_alter_fileupload_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyround",
            name="is_parsed_by_ocr",
            field=models.BooleanField(default=False),
        ),
    ]
