# Generated by Django 4.2.10 on 2024-04-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0427_dailyround_is_parsed_by_ocr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmetainfo",
            name="occupation",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "STUDENT"),
                    (2, "BUSINESSMAN"),
                    (3, "HEALTH_CARE_WORKER"),
                    (4, "HEALTH_CARE_LAB_WORKER"),
                    (5, "ANIMAL_HANDLER"),
                    (6, "OTHERS"),
                    (7, "HEALTHCARE_PRACTITIONER"),
                    (8, "PARADEMICS"),
                    (9, "BUSINESS_RELATED"),
                    (10, "ENGINEER"),
                    (11, "TEACHER"),
                    (12, "OTHER_PROFESSIONAL_OCCUPATIONS"),
                    (13, "OFFICE_ADMINISTRATIVE"),
                    (14, "CHEF"),
                    (15, "PROTECTIVE_SERVICE"),
                    (16, "HOSPITALITY"),
                    (17, "CUSTODIAL"),
                    (18, "CUSTOMER_SERVICE"),
                    (19, "SALES_SUPERVISOR"),
                    (20, "RETAIL_SALES_WORKER"),
                    (21, "INSURANCE_SALES_AGENT"),
                    (22, "SALES_REPRESENTATIVE"),
                    (23, "REAL_ESTATE"),
                    (24, "CONSTRUCTION_EXTRACTION"),
                    (25, "AGRI_NATURAL"),
                    (26, "PRODUCTION_OCCUPATION"),
                    (27, "PILOT_FLIGHT"),
                    (28, "VEHICLE_DRIVER"),
                    (29, "MILITARY"),
                    (30, "HOMEMAKER"),
                    (31, "UNKNOWN"),
                    (32, "NOT_APPLICABLE"),
                ],
                null=True,
            ),
        ),
    ]
