# Generated by Django 4.2.10 on 2024-04-18 14:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_camerapreset(apps, schema_editor):
    CameraPreset = apps.get_model("facility", "CameraPreset")
    AssetBed = apps.get_model("facility", "AssetBed")
    User = apps.get_model("users", "User")

    presets = []
    for asset_bed in AssetBed.objects.all():
        unique_asset_bed = AssetBed.objects.filter(
            asset=asset_bed.asset, bed=asset_bed.bed
        ).first()
        presets.append(
            CameraPreset(
                asset_bed=unique_asset_bed,
                x=asset_bed.meta.get("x", 0),
                y=asset_bed.meta.get("y", 0),
                zoom=asset_bed.meta.get("zoom", 1),
                preset_name=asset_bed.meta.get("preset_name", "Unnamed Preset"),
                created_by=User.objects.first(),
                updated_by=User.objects.first(),
                created_date=asset_bed.created_date,
                modified_date=asset_bed.modified_date,
            )
        )

    CameraPreset.objects.bulk_create(presets)
    AssetBed.objects.exclude(
        id__in=AssetBed.objects.values("asset", "bed")
        .annotate(min_id=models.Min("id"))
        .values("min_id")
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0427_dailyround_is_parsed_by_ocr"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("zoom", models.FloatField()),
                ("preset_name", models.CharField(max_length=255)),
                (
                    "asset_bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="camera_presets",
                        to="facility.assetbed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="camera_presets_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="camera_presets_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(add_camerapreset, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="assetbed",
            name="meta",
        ),
    ]
