# Generated by Django 4.2.10 on 2024-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0426_double_pain_scale"),
        ("facility", "0428_alter_patientmetainfo_occupation"),
    ]

    operations = []
