# Generated by Django 4.2.8 on 2024-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0429_double_pain_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="thread",
            field=models.SmallIntegerField(
                choices=[(10, "DOCTORS"), (20, "NURSES")], db_index=True, default=10
            ),
        ),
    ]
