# Generated by Django 4.2.10 on 2024-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0430_alter_asset_support_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="thread",
            field=models.SmallIntegerField(
                choices=[(10, "DOCTORS"), (20, "NURSES")], db_index=True, default=10
            ),
        ),
    ]
