# Generated by Django 4.2.10 on 2024-05-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0431_patientnotes_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="facility.patientnotes",
            ),
        ),
    ]
