# Generated by Django 4.2.10 on 2024-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_auto_20240330_1516"),
        ("facility", "0431_patientnotes_thread"),
    ]

    operations = []
