# Generated by Django 4.2.10 on 2024-05-14 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0417_load_medibase"),
        ("facility", "0431_patientnotes_thread"),
    ]

    operations = []
