# Generated by Django 4.2.8 on 2024-05-14 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0432_alter_fileupload_file_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyround",
            name="current_health",
        ),
    ]
