# Generated by Django 4.2.10 on 2024-05-14 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0432_alter_fileupload_file_type"),
        ("facility", "0432_merge_0417_load_medibase_0431_patientnotes_thread"),
    ]

    operations = []
