# Generated by Django 4.2.10 on 2024-05-16 10:30

import uuid

import django.db.models.deletion
from django.db import migrations, models

import care.facility.models.mixins.permissions.patient


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0435_merge_20240515_1301"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "symptom",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASYMPTOMATIC", "Asymptomatic"),
                            ("FEVER", "Fever"),
                            ("SORE THROAT", "Sore Throat"),
                            ("COUGH", "Cough"),
                            ("BREATHLESSNESS", "Breathlessness"),
                            ("MYALGIA", "Myalgia"),
                            ("ABDOMINAL DISCOMFORT", "Abdominal Discomfort"),
                            ("VOMITING", "Vomiting"),
                            ("OTHERS", "Others"),
                            ("SPUTUM", "Sputum"),
                            ("NAUSEA", "Nausea"),
                            ("CHEST PAIN", "Chest Pain"),
                            ("HEMOPTYSIS", "Hemoptysis"),
                            ("NASAL DISCHARGE", "Nasal Discharge"),
                            ("BODY ACHE", "Body Ache"),
                            ("DIARRHOEA", "Diarrhoea"),
                            ("PAIN", "Pain"),
                            ("PEDAL EDEMA", "Pedal Edema"),
                            ("WOUND", "Wound"),
                            ("CONSTIPATION", "Constipation"),
                            ("HEAD ACHE", "Head Ache"),
                            ("BLEEDING", "Bleeding"),
                            ("DIZZINESS", "Dizziness"),
                            ("CHILLS", "Chills"),
                            ("GENERAL WEAKNESS", "General Weakness"),
                            ("IRRITABILITY", "Irritability"),
                            ("CONFUSION", "Confusion"),
                            ("ABDOMINAL PAIN", "Abdominal Pain"),
                            ("JOINT PAIN", "Joint Pain"),
                            ("REDNESS OF EYES", "Redness of Eyes"),
                            ("ANOREXIA", "Anorexia"),
                            ("NEW LOSS OF TASTE", "New Loss of Taste"),
                            ("NEW LOSS OF SMELL", "New Loss of Smell"),
                        ],
                    ),
                ),
                ("other_symptom", models.CharField(blank=True, default="")),
                ("onset_date", models.DateTimeField(blank=True, null=True)),
                ("cure_date", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptoms_timeline",
                        to="facility.patientconsultation",
                    ),
                ),
                (
                    "daily_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_round_symptoms",
                        to="facility.dailyround",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                care.facility.models.mixins.permissions.patient.ConsultationRelatedPermissionMixin,
            ),
        ),
    ]
