# Generated by Django 4.2.10 on 2024-05-15 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0417_load_medibase"),
        ("facility", "0435_merge_20240515_1301"),
    ]

    operations = []
