# Generated by Django 4.2.10 on 2024-05-21 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0437_alter_dailyround_rounds_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientTeleConsultation",
        ),
    ]
