# Generated by Django 4.2.10 on 2024-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0437_alter_dailyround_rounds_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyround",
            name="patient_category",
            field=models.CharField(
                choices=[
                    ("Comfort", "Comfort Care"),
                    ("Stable", "Mild"),
                    ("Moderate", "Moderate"),
                    ("Critical", "Critical"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientconsultation",
            name="category",
            field=models.CharField(
                choices=[
                    ("Comfort", "Comfort Care"),
                    ("Stable", "Mild"),
                    ("Moderate", "Moderate"),
                    ("Critical", "Critical"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
