# Generated by Django 4.2.10 on 2024-06-03 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_features_to_array(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")

    for facility in Facility.objects.all():
        if facility.old_features:
            facility.features = list(map(int, facility.old_features))
            facility.save()


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0437_alter_dailyround_rounds_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facility",
            old_name="features",
            new_name="old_features",
        ),
        migrations.AddField(
            model_name="facility",
            name="features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(
                    choices=[
                        (1, "CT Scan Facility"),
                        (2, "Maternity Care"),
                        (3, "X-Ray facility"),
                        (4, "Neonatal care"),
                        (5, "Operation theater"),
                        (6, "Blood Bank"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.RunPython(convert_features_to_array),
        migrations.RemoveField(
            model_name="facility",
            name="old_features",
        ),
    ]
