# Generated by Django 4.2.10 on 2024-04-21 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0438_alter_dailyround_patient_category_and_more"),
        ("abdm", "0013_abhanumber_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="abha_number",
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="abha_number",
        ),
    ]
