# Generated by Django 4.2.8 on 2024-05-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0438_alter_dailyround_patient_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="facility.patientnotes",
            ),
        ),
    ]
