# Generated by Django 4.2.10 on 2024-05-28 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0439_encounter_symptoms"),
        (
            "facility",
            "0439_historicalpatientregistration_ration_card_category_and_more",
        ),
    ]

    operations = []
