# Generated by Django 4.2.10 on 2024-06-02 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0440_merge_20240528_1613"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientTeleConsultation",
        ),
    ]
