# Generated by Django 4.2.10 on 2024-06-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0439_disease_duration_disease_status_disease_type_and_more"),
        ("facility", "0441_delete_patientteleconsultation"),
    ]

    operations = []
