# Generated by Django 4.2.8 on 2024-06-06 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "facility",
            "0442_remove_patientconsultation_unique_patient_no_within_facility",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_diagnosis",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_icd11_diagnoses",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_icd11_principal_diagnosis",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_icd11_provisional_diagnoses",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="discharge_advice",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="discharge_prescription",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="discharge_prn_prescription",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="prn_prescription",
        ),
    ]
