# Generated by Django 4.2.10 on 2024-06-24 16:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    def migrate_has_consents(apps, schema_editor):
        PatientConsultation = apps.get_model("facility", "PatientConsultation")
        FileUpload = apps.get_model("facility", "FileUpload")
        PatientConsent = apps.get_model("facility", "PatientConsent")

        files = FileUpload.objects.filter(
            file_type=7,
            is_archived=False,
        ).values_list("associating_id", flat=True)

        consents = PatientConsent.objects.filter(
            external_id__in=[uuid.UUID(file) for file in files], archived=False
        )

        consultations = PatientConsultation.objects.filter(
            consents__in=consents
        ).distinct()

        consultations.update(has_consents=True)

    dependencies = [
        ("facility", "0443_remove_patientconsultation_consent_records_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="has_consents",
            field=models.BooleanField(
                default=False, verbose_name="Patient has consent files"
            ),
        ),
        migrations.AlterField(
            model_name="patientconsent",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="facility.patientconsultation",
            ),
        ),
        migrations.RunPython(
            migrate_has_consents, reverse_code=migrations.RunPython.noop
        ),
    ]
