# Generated by Django 4.2.10 on 2024-06-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0442_merge_20240603_2159"),
        ("facility", "0443_remove_patientconsultation_consent_records_and_more"),
    ]

    operations = []
