# Generated by Django 4.2.10 on 2024-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0443_remove_patientconsultation_consent_records_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="disease",
            field=models.IntegerField(
                choices=[
                    (1, "NO"),
                    (2, "Diabetes"),
                    (3, "Heart Disease"),
                    (4, "HyperTension"),
                    (5, "Chronic Renal Disease"),
                    (6, "Other Chronic Lung Diseases"),
                    (7, "Cancer"),
                    (8, "OTHER"),
                    (9, "COPD"),
                    (10, "Bronchitis"),
                    (11, "Chronic Neurological Or Neuromuscular Disease"),
                    (12, "Immunocompromised Condition"),
                    (13, "Liver Disease"),
                    (14, "TB"),
                    (15, "Asthma"),
                ]
            ),
        ),
    ]
