# Generated by Django 4.2.10 on 2024-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    def migrate_has_consents(apps, schema_editor):
        PatientRegistration = apps.get_model("facility", "PatientRegistration")
        FileUpload = apps.get_model("facility", "FileUpload")
        PatientConsent = apps.get_model("facility", "PatientConsent")
        for patient_registration in PatientRegistration.objects.all():
            consents = PatientConsent.objects.filter(
                consultation__patient=patient_registration, archived=False
            ).values_list("external_id", flat=True)
            uuid_array = [str(uuid) for uuid in consents]
            has_consents = FileUpload.objects.filter(
                associating_id__in=uuid_array,
                file_type=7,
                is_archived=False,
            ).exists()
            patient_registration.has_consents = has_consents
            patient_registration.save()

    dependencies = [
        ("facility", "0443_remove_patientconsultation_consent_records_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatientregistration",
            name="has_consents",
            field=models.BooleanField(
                default=False, verbose_name="Patient has consent files"
            ),
        ),
        migrations.AddField(
            model_name="patientregistration",
            name="has_consents",
            field=models.BooleanField(
                default=False, verbose_name="Patient has consent files"
            ),
        ),
        migrations.RunPython(
            migrate_has_consents, reverse_code=migrations.RunPython.noop
        ),
    ]
