# Generated by Django 4.2.10 on 2024-07-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0444_alter_medicineadministration_dosage_and_more"),
        ("facility", "0445_alter_fileupload_file_type"),
    ]

    operations = []
