# Generated by Django 4.2.10 on 2024-08-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0446_merge_20240709_1859"),
        ("facility", "0447_patientconsultationevent_taken_at"),
    ]

    operations = []
