# Generated by Django 4.2.10 on 2024-08-13 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0447_patientconsultationevent_taken_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyround",
            old_name="ventilator_fi02",
            new_name="ventilator_fio2",
        ),
    ]
