# Generated by Django 4.2.10 on 2024-08-22 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0448_rename_features_facility_old_features"),
        ("facility", "0448_rename_ventilator_fi02_dailyround_ventilator_fio2"),
    ]

    operations = []
