# Generated by Django 4.2.10 on 2024-08-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0446_alter_hospitaldoctors_area"),
        ("facility", "0449_merge_20240822_1343"),
    ]

    operations = []
