# Generated by Django 4.2.10 on 2024-06-02 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0449_merge_20240822_1343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyround",
            name="deprecated_additional_symptoms",
        ),
        migrations.RemoveField(
            model_name="dailyround",
            name="deprecated_other_symptoms",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_other_symptoms",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_symptoms",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_symptoms_onset_date",
        ),
    ]
