# Generated by Django 4.2.10 on 2024-08-23 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0449_merge_20240822_1343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_diagnosis",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_icd11_diagnoses",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_icd11_principal_diagnosis",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="deprecated_icd11_provisional_diagnoses",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="discharge_advice",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="discharge_prescription",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="discharge_prn_prescription",
        ),
        migrations.RemoveField(
            model_name="patientconsultation",
            name="prn_prescription",
        ),
    ]
