# Generated by Django 4.2.10 on 2024-08-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0451_merge_20240823_1642"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyround",
            old_name="spo2",
            new_name="archived_spo2",
        ),
    ]
