# Generated by Django 4.2.10 on 2024-08-23 12:53

from django.db import migrations, models

import care.utils.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0451_merge_20240823_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyround",
            name="bp",
            field=models.JSONField(
                default=dict,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "additionalProperties": False,
                            "properties": {
                                "diastolic": {
                                    "maximum": 400,
                                    "minimum": 0,
                                    "type": "number",
                                },
                                "mean": {
                                    "maximum": 400,
                                    "minimum": 0,
                                    "type": "number",
                                },
                                "systolic": {
                                    "maximum": 400,
                                    "minimum": 0,
                                    "type": "number",
                                },
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="feeds",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "name": {"enum": ["Ryles Tube", "Normal Feed"]},
                                        "quantity": {"minimum": 0, "type": "number"},
                                    },
                                    "required": ["name", "quantity"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="infusions",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "name": {
                                            "enum": [
                                                "Adrenalin",
                                                "Nor-adrenalin",
                                                "Vasopressin",
                                                "Dopamine",
                                                "Dobutamine",
                                            ]
                                        },
                                        "quantity": {"minimum": 0, "type": "number"},
                                    },
                                    "required": ["name", "quantity"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="iv_fluids",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "name": {"enum": ["RL", "NS", "DNS"]},
                                        "quantity": {"minimum": 0, "type": "number"},
                                    },
                                    "required": ["name", "quantity"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="nursing",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "description": {"type": "string"},
                                        "procedure": {
                                            "enum": [
                                                "personal_hygiene",
                                                "positioning",
                                                "suctioning",
                                                "ryles_tube_care",
                                                "iv_sitecare",
                                                "nubulisation",
                                                "dressing",
                                                "dvt_pump_stocking",
                                                "restrain",
                                                "chest_tube_care",
                                                "tracheostomy_care",
                                                "stoma_care",
                                                "catheter_care",
                                            ]
                                        },
                                    },
                                    "required": ["procedure", "description"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="output",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "name": {
                                            "enum": [
                                                "Urine",
                                                "Ryles Tube Aspiration",
                                                "ICD",
                                                "Abdominal Drain",
                                            ]
                                        },
                                        "quantity": {"minimum": 0, "type": "number"},
                                    },
                                    "required": ["name", "quantity"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="pain_scale_enhanced",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "description": {"type": "string"},
                                        "region": {
                                            "enum": [
                                                "AnteriorHead",
                                                "AnteriorNeck",
                                                "AnteriorRightShoulder",
                                                "AnteriorRightChest",
                                                "AnteriorRightArm",
                                                "AnteriorRightForearm",
                                                "AnteriorRightHand",
                                                "AnteriorLeftHand",
                                                "AnteriorLeftChest",
                                                "AnteriorLeftShoulder",
                                                "AnteriorLeftArm",
                                                "AnteriorLeftForearm",
                                                "AnteriorRightFoot",
                                                "AnteriorLeftFoot",
                                                "AnteriorRightLeg",
                                                "AnteriorLowerChest",
                                                "AnteriorAbdomen",
                                                "AnteriorLeftLeg",
                                                "AnteriorRightThigh",
                                                "AnteriorLeftThigh",
                                                "AnteriorGroin",
                                                "PosteriorHead",
                                                "PosteriorNeck",
                                                "PosteriorLeftChest",
                                                "PosteriorRightChest",
                                                "PosteriorAbdomen",
                                                "PosteriorLeftShoulder",
                                                "PosteriorRightShoulder",
                                                "PosteriorLeftArm",
                                                "PosteriorLeftForearm",
                                                "PosteriorLeftHand",
                                                "PosteriorRightArm",
                                                "PosteriorRightForearm",
                                                "PosteriorRightHand",
                                                "PosteriorLeftThighAndButtock",
                                                "PosteriorRightThighAndButtock",
                                                "PosteriorLeftLeg",
                                                "PosteriorRightLeg",
                                                "PosteriorLeftFoot",
                                                "PosteriorRightFoot",
                                            ]
                                        },
                                        "scale": {
                                            "maximum": 10,
                                            "minimum": 1,
                                            "type": "number",
                                        },
                                    },
                                    "required": ["region", "scale"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyround",
            name="pressure_sore",
            field=models.JSONField(
                default=list,
                validators=[
                    care.utils.models.validators.JSONFieldSchemaValidator(
                        {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "description": {"type": "string"},
                                        "exudate_amount": {
                                            "enum": [
                                                "None",
                                                "Light",
                                                "Moderate",
                                                "Heavy",
                                            ]
                                        },
                                        "length": {"minimum": 0, "type": "number"},
                                        "push_score": {
                                            "maximum": 19,
                                            "minimum": 0,
                                            "type": "number",
                                        },
                                        "region": {
                                            "enum": [
                                                "AnteriorHead",
                                                "AnteriorNeck",
                                                "AnteriorRightShoulder",
                                                "AnteriorRightChest",
                                                "AnteriorRightArm",
                                                "AnteriorRightForearm",
                                                "AnteriorRightHand",
                                                "AnteriorLeftHand",
                                                "AnteriorLeftChest",
                                                "AnteriorLeftShoulder",
                                                "AnteriorLeftArm",
                                                "AnteriorLeftForearm",
                                                "AnteriorRightFoot",
                                                "AnteriorLeftFoot",
                                                "AnteriorRightLeg",
                                                "AnteriorLowerChest",
                                                "AnteriorAbdomen",
                                                "AnteriorLeftLeg",
                                                "AnteriorRightThigh",
                                                "AnteriorLeftThigh",
                                                "AnteriorGroin",
                                                "PosteriorHead",
                                                "PosteriorNeck",
                                                "PosteriorLeftChest",
                                                "PosteriorRightChest",
                                                "PosteriorAbdomen",
                                                "PosteriorLeftShoulder",
                                                "PosteriorRightShoulder",
                                                "PosteriorLeftArm",
                                                "PosteriorLeftForearm",
                                                "PosteriorLeftHand",
                                                "PosteriorRightArm",
                                                "PosteriorRightForearm",
                                                "PosteriorRightHand",
                                                "PosteriorLeftThighAndButtock",
                                                "PosteriorRightThighAndButtock",
                                                "PosteriorLeftLeg",
                                                "PosteriorRightLeg",
                                                "PosteriorLeftFoot",
                                                "PosteriorRightFoot",
                                            ]
                                        },
                                        "scale": {
                                            "maximum": 5,
                                            "minimum": 1,
                                            "type": "number",
                                        },
                                        "tissue_type": {
                                            "enum": [
                                                "Closed",
                                                "Epithelial",
                                                "Granulation",
                                                "Slough",
                                                "Necrotic",
                                            ]
                                        },
                                        "width": {"minimum": 0, "type": "number"},
                                    },
                                    "required": ["region", "width", "length"],
                                    "type": "object",
                                }
                            ],
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
