# Generated by Django 4.2.10 on 2024-08-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0450_corrections_for_io_balance_fields"),
        ("facility", "0452_remove_patientconsultation_deprecated_diagnosis_and_more"),
    ]

    operations = []
