# Generated by Django 4.2.10 on 2024-08-23 07:55

import uuid

import django.db.models.deletion
from django.db import migrations, models

import care.facility.models.mixins.permissions.facility


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0453_merge_20240824_2040"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityHubSpoke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "relationship",
                    models.IntegerField(choices=[(1, "Tele ICU Hub")], default=1),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_set",
                        to="facility.facility",
                    ),
                ),
                (
                    "spoke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spoke_set",
                        to="facility.facility",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                care.facility.models.mixins.permissions.facility.FacilityRelatedPermissionMixin,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="hubs",
            field=models.ManyToManyField(
                related_name="spokes",
                through="facility.FacilityHubSpoke",
                to="facility.facility",
            ),
        ),
    ]
