# Generated by Django 4.2.10 on 2024-08-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0453_merge_20240824_2040"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyround",
            old_name="spo2",
            new_name="archived_spo2",
        ),
    ]
