# Generated by Django 4.2.15 on 2024-09-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0454_remove_historicalpatientregistration_abha_number_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patientconsultationevent",
            name="facility_pa_consult_7b22fe_idx",
        ),
        migrations.AlterField(
            model_name="patientconsultationevent",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="patientconsultationevent",
            index=models.Index(
                condition=models.Q(("is_latest", True)),
                fields=[
                    "consultation_id",
                    "is_latest",
                    "event_type_id",
                    "object_model",
                    "taken_at",
                ],
                name="consultation_events_latest_idx",
            ),
        ),
    ]
