# Generated by Django 4.2.15 on 2024-09-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0454_remove_historicalpatientregistration_abha_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="old_features",
        ),
    ]
