# Generated by Django 4.2.10 on 2024-09-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0455_remove_facility_old_features"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyround",
            old_name="spo2",
            new_name="archived_spo2",
        ),
    ]
