# Generated by Django 4.2.10 on 2024-09-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0457_facilityflag"),
        ("facility", "0457_patientmetainfo_domestic_healthcare_support_and_more"),
    ]

    operations = []
