# Generated by Django 5.1.1 on 2024-09-21 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0459_remove_bed_unique_bed_name_per_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="facility.patientnotes",
            ),
        ),
    ]
