# Generated by Django 4.2.2 on 2024-09-02 09:42

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0463_patientnotes_reply_to"),
    ]


    operations = [
        migrations.AlterField(
            model_name="facilitycapacity",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (100, "ICU Bed"),
                    (200, "Ordinary Bed"),
                    (300, "Oxygen Bed"),
                    (400, "Isolation Bed"),
                    (500, "Others"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacilitycapacity",
            name="room_type",
            field=models.IntegerField(
                choices=[
                    (100, "ICU Bed"),
                    (200, "Ordinary Bed"),
                    (300, "Oxygen Bed"),
                    (400, "Isolation Bed"),
                    (500, "Others"),
                ]
            ),
        ),
    ]
