# Generated by Django 5.1.1 on 2024-09-23 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0465_merge_20240923_1043"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patientconsultationevent",
            name="facility_pa_consult_7b22fe_idx",
        ),
        migrations.AlterField(
            model_name="patientconsultationevent",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="patientconsultationevent",
            index=models.Index(
                condition=models.Q(("is_latest", True)),
                fields=[
                    "consultation_id",
                    "is_latest",
                    "event_type_id",
                    "object_model",
                    "taken_at",
                ],
                name="consultation_events_latest_idx",
            ),
        ),
    ]
