# Generated by Django 5.1.1 on 2024-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0465_merge_20240923_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbed',
            name='is_privacy_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
