# Generated by Django 5.1.1 on 2024-10-22 03:50

import care.utils.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0466_camera_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbed',
            name='boundary',
            field=models.JSONField(null=True, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'additionalProperties': False, 'properties': {'x0': {'type': 'number'}, 'x1': {'type': 'number'}, 'y0': {'type': 'number'}, 'y1': {'type': 'number'}}, 'required': ['x0', 'y0', 'x1', 'y1'], 'type': 'object'})]),
        ),
    ]
