# Generated by Django 5.1.1 on 2024-10-24 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0466_alter_fileupload_file_type_alter_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotes',
            name='parent_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_notes', to='facility.patientnotes'),
        ),
    ]
