# Generated by Django 5.1.3 on 2024-12-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilitypatientstatshistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facilitypatientstatshistory',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityrelatedsummary',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='localbodyscopedsummary',
            name='lsg',
        ),
        migrations.DeleteModel(
            name='DistrictScopedSummary',
        ),
        migrations.DeleteModel(
            name='FacilityPatientStatsHistory',
        ),
        migrations.DeleteModel(
            name='FacilityRelatedSummary',
        ),
        migrations.DeleteModel(
            name='LocalBodyScopedSummary',
        ),
    ]
