# Generated by Django 5.1.3 on 2024-12-06 08:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyround',
            name='pco2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10')), django.core.validators.MaxValueValidator(Decimal('200'))]),
        ),
        migrations.AlterField(
            model_name='dailyround',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
        migrations.AlterField(
            model_name='dailyround',
            name='po2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10')), django.core.validators.MaxValueValidator(Decimal('400'))]),
        ),
    ]
