# Generated by Django 5.1.2 on 2024-11-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='insurer_id',
            field=models.CharField(default='', help_text='Unique identifier for the insurance provider', max_length=20, verbose_name='Insurer ID'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='insurer_name',
            field=models.CharField(default='', help_text='Name of the insurance provider', max_length=100, verbose_name='Insurer Name'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='member_id',
            field=models.CharField(default='', help_text='Unique identifier assigned to the insured member', max_length=50, verbose_name='Insurance Member ID'),
        ),
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='policy_id',
            field=models.CharField(default='', help_text='Unique identifier for the insurance policy', max_length=50, verbose_name='Insurance Policy ID'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='insurer_id',
            field=models.CharField(default='', help_text='Unique identifier for the insurance provider', max_length=20, verbose_name='Insurer ID'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='insurer_name',
            field=models.CharField(default='', help_text='Name of the insurance provider', max_length=100, verbose_name='Insurer Name'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='member_id',
            field=models.CharField(default='', help_text='Unique identifier assigned to the insured member', max_length=50, verbose_name='Insurance Member ID'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='policy_id',
            field=models.CharField(default='', help_text='Unique identifier for the insurance policy', max_length=50, verbose_name='Insurance Policy ID'),
        ),
    ]
