# Generated by Django 5.1.2 on 2024-11-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0466_schedulableresource_schedule_availability_and_more'),
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
    ]
