# Generated by Django 5.1.2 on 2024-12-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0470_tokenslot_tokenbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbooking',
            name='reason_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tokenslot',
            constraint=models.CheckConstraint(condition=models.Q(('tokens_remaining__gte', 0)), name='tokens_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tokenslot',
            constraint=models.UniqueConstraint(fields=('resource', 'start_datetime'), name='unique_resource_slot'),
        ),
    ]
