# Generated by Django 5.1.4 on 2025-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0476_facility_default_internal_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="facility_avatar_url",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
