# Generated by Django 5.1.4 on 2025-05-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0476_facility_default_internal_organization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilityFlag',
        ),
    ]
