# Generated by Django 5.1.4 on 2025-04-24 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models, transaction




class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0476_facility_default_internal_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
