# Generated by Django 5.1.4 on 2025-05-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0476_facility_default_internal_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='discount_codes',
            field=models.JSONField(default=list),
        ),
    ]
