# Generated by Django 5.1.4 on 2025-04-24 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models, transaction

from care.emr.resources.template.spec import FacilityReportTemplateType
from care.utils.reports.load_default_report_config import load_default_discharge_summary_config


def add_default_summary_report_config_to_facility(apps, schema_editor):
    Facility               = apps.get_model("facility", "Facility")
    FacilityReportTemplate = apps.get_model("facility", "FacilityReportTemplate")

    with transaction.atomic():
        for facility in Facility.objects.all():
            FacilityReportTemplate.objects.create(facility=facility,type=FacilityReportTemplateType.discharge_summary,config=load_default_discharge_summary_config())



class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0476_facility_default_internal_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_default_summary_report_config_to_facility),
    ]
