# Generated by Django 5.1.4 on 2025-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0477_facility_discount_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='discount_monetory_components',
            field=models.JSONField(default=list),
        ),
    ]
