# Generated by Django 5.1.4 on 2025-05-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0478_facility_discount_monetory_components'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='discount_monetory_components',
            new_name='discount_monetary_components',
        ),
    ]
