# Generated by Django 5.1.4 on 2025-01-21 08:41
import logging
from django.db import migrations
from django.core.management import call_command

logger = logging.getLogger(__name__)

MIGRATION_ID = 158445695202


def _get_org(Organization, obj):
    state = None
    district = None
    local_body = None
    ward = None
    if obj.state:
        state = Organization.objects.filter(
            name=obj.state.name, root_org__isnull=True, level_cache=0
        ).first()
    if obj.district:
        query = {
            "name": obj.district.name,
            "level_cache": 1,
        }
        if state:
            query["root_org"] = state
        district = Organization.objects.filter(**query).first()
    if obj.local_body:
        query = {
            "name": obj.local_body.name,
            "level_cache": 2,
        }
        if state:
            query["root_org"] = state
        if district:
            query["parent"] = district
        local_body = Organization.objects.filter(**query).first()
    if obj.ward:
        query = {
            "name": obj.ward.name,
            "level_cache": 3,
        }
        if state:
            query["root_org"] = state
        if local_body:
            query["parent"] = local_body
        ward = Organization.objects.filter(**query).first()
    return ward or local_body or district or state or None


def migrate_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Organization = apps.get_model("emr", "Organization")
    logger.debug("Migrating Users")
    call_command("sync_permissions_roles")
    bulk_update = []
    for user in User.objects.filter(geo_organization__isnull=True).select_related(
        "state", "district", "local_body", "ward"
    ):
        if user.geo_organization:
            continue
        geo_org = _get_org(Organization, user)
        if not geo_org:
            continue
        user.geo_organization = geo_org
        logger.debug(f"User: {user.id=}, {geo_org.name=}")
        bulk_update.append(user)
    User.objects.bulk_update(bulk_update, ["geo_organization"])


def reverse_migrate_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(geo_organization__meta__migration_id=MIGRATION_ID).update(
        geo_organization=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0478_migrate_organizations"),
        ("users", "0021_rename_gender_user_old_gender_user_geo_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_users, reverse_migrate_users),
    ]
