# Generated by Django 5.1.4 on 2025-01-21 08:42
from functools import lru_cache
import logging
from django.db import migrations
from traitlets import default

logger = logging.getLogger(__name__)

MIGRATION_ID = 158445695203

USER_TYPE_TO_ROLE = {
    2: "Staff",  # Transportation
    3: "Staff",  # Pharmacist
    5: "Staff",  # Volunteer
    9: "Staff Read Only",  # StaffReadOnly
    10: "Staff",  # Staff
    13: "Nurse Read Only",  # NurseReadOnly
    14: "Nurse",  # Nurse
    15: "Doctor",  # Doctor
    20: "Doctor",  # Reserved
    21: "Geo Admin",  # WardAdmin
    23: "Geo Admin",  # LocalBodyAdmin
    25: "Geo Admin",  # DistrictLabAdmin
    29: "Geo Admin Read Only",  # DistrictReadOnlyAdmin
    30: "Geo Admin",  # DistrictAdmin
    35: "Geo Admin",  # StateLabAdmin
    39: "Geo Admin Read Only",  # StateReadOnlyAdmin
    40: "Geo Admin",  # StateAdmin
}


@lru_cache
def get_role_for_user_type(RoleModel, user_type):
    role_name = USER_TYPE_TO_ROLE.get(user_type)
    return RoleModel.objects.filter(name=role_name).first() if role_name else None


def _get_org(Organization, obj):
    state = None
    district = None
    local_body = None
    ward = None
    if obj.state:
        state = Organization.objects.filter(
            name=obj.state.name, root_org__isnull=True, level_cache=0
        ).first()
    if obj.district:
        query = {
            "name": obj.district.name,
            "level_cache": 1,
        }
        if state:
            query["root_org"] = state
        district = Organization.objects.filter(**query).first()
    if obj.local_body:
        query = {
            "name": obj.local_body.name,
            "level_cache": 2,
        }
        if state:
            query["root_org"] = state
        if district:
            query["parent"] = district
        local_body = Organization.objects.filter(**query).first()
    if obj.ward:
        query = {
            "name": obj.ward.name,
            "level_cache": 3,
        }
        if state:
            query["root_org"] = state
        if local_body:
            query["parent"] = local_body
        ward = Organization.objects.filter(**query).first()
    return ward or local_body or district or state or None


def migrate_facilities(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    Organization = apps.get_model("emr", "Organization")
    bulk_update = []
    for facility in Facility.objects.filter(
        geo_organization__isnull=True
    ).select_related("state", "district", "local_body", "ward"):
        if facility.geo_organization:
            continue
        geo_org = _get_org(Organization, facility)
        if not geo_org:
            continue
        facility.geo_organization = geo_org
        bulk_update.append(facility)
    Facility.objects.bulk_update(bulk_update, ["geo_organization"])


def reverse_migrate_facilities(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    Facility.objects.filter(geo_organization__meta__migration_id=MIGRATION_ID).update(
        geo_organization=None
    )


def migrate_facility_users(apps, schema_editor):
    from care.emr.models.organization import FacilityOrganization
    from care.emr.models.organization import FacilityOrganizationUser

    Facility = apps.get_model("facility", "Facility")
    RoleModel = apps.get_model("security", "RoleModel")

    for facility in Facility.objects.all().order_by("id").prefetch_related("users"):
        root_org, _ = FacilityOrganization.objects.get_or_create(
            org_type="root",
            name="Administration",
            facility_id=facility.id,
            defaults={
                "system_generated": True,
                "parent": None,
                "deleted": facility.deleted,
                "meta": {"migration_id": MIGRATION_ID},
                "created_by_id": facility.created_by_id,
                "created_date": facility.created_date,
            },
        )
        if not facility.default_internal_organization:
            facility.default_internal_organization_id = root_org.id
            facility.save(update_fields=["default_internal_organization_id"])
        for facility_user in facility.users.all():
            role = get_role_for_user_type(RoleModel, facility_user.old_user_type)
            if not role:
                logger.warning(
                    f"Could not find role for user {facility_user.id} with type {facility_user.old_user_type}"
                )
                continue

            FacilityOrganizationUser.objects.get_or_create(
                organization_id=root_org.id,
                user_id=facility_user.id,
                role_id=role.id,
                defaults={
                    "deleted": facility.deleted,
                    "meta": {"migration_id": MIGRATION_ID},
                    "created_by_id": facility_user.created_by_id,
                    "created_date": facility.created_date,
                },
            )


def reverse_migrate_facility_users(apps, schema_editor):
    FacilityOrganization = apps.get_model("emr", "FacilityOrganization")
    FacilityOrganization.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0479_migrate_users"),
    ]

    operations = [
        migrations.RunPython(migrate_facilities, reverse_migrate_facilities),
        migrations.RunPython(migrate_facility_users, reverse_migrate_facility_users),
    ]
