# Generated by Django 5.1.4 on 2025-01-21 08:42
import logging
from django.db import migrations

logger = logging.getLogger(__name__)

MIGRARION_ID = 413370


def _get_org(Organization, obj):
    state = None
    district = None
    local_body = None
    ward = None
    if obj.state:
        state = Organization.objects.filter(
            name=obj.state.name,
            root_org__isnull=True,
            level_cache=0
        ).first()
    if obj.district:
        query = {
            "name": obj.district.name,
            "level_cache": 1,
        }
        if state:
            query["root_org"] = state
        district = Organization.objects.filter(**query).first()
    if obj.local_body:
        query = {
            "name": obj.local_body.name,
            "level_cache": 2,
        }
        if state:
            query["root_org"] = state
        if district:
            query["parent"] = district
        local_body = Organization.objects.filter(**query).first()
    if obj.ward:
        query = {
            "name": obj.ward.name,
            "level_cache": 3,
        }
        if state:
            query["root_org"] = state
        if local_body:
            query["parent"] = local_body
        ward = Organization.objects.filter(**query).first()
    return ward or local_body or district or state or None


def migrate_facilities(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    Organization = apps.get_model("emr", "Organization")
    bulk_update = []
    for facility in Facility.objects.filter(geo_organization__isnull=True).select_related("state", "district", "local_body", "ward"):
        if facility.geo_organization:
            continue
        geo_org = _get_org(Organization, facility)
        if not geo_org:
            continue
        facility.geo_organization = geo_org
        #TODO: create facility organization
        bulk_update.append(facility)
    Facility.objects.bulk_update(bulk_update, ["geo_organization"])


def reverse_migrate_facilities(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    Facility.objects.filter(
        geo_organization__meta__migration_id=MIGRARION_ID
    ).update(
        geo_organization=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0479_migrate_users'),
    ]

    operations = [
        migrations.RunPython(migrate_facilities, reverse_migrate_facilities),
    ]
