# Generated by Django 5.1.4 on 2025-01-21 08:42
import logging
from django.db import migrations
from care.security.models import RoleModel

logger = logging.getLogger(__name__)

MIGRATION_ID = 158445695203

USER_TYPE_TO_ROLE = {
    5: "Volunteer",  # Volunteer
    10: "Staff",  # Staff
    14: "Nurse",  # Nurse
    15: "Doctor",  # Doctor
    30: "Facility Admin",  # DistrictAdmin
    40: "Facility Admin",  # StateAdmin
}


def get_role_for_user_type(user_type):
    if role_name := USER_TYPE_TO_ROLE.get(user_type):
        if role := RoleModel.objects.filter(name=role_name).first():
            return role.id


def _get_org(Organization, obj):
    state = None
    district = None
    local_body = None
    ward = None
    if obj.state:
        state = Organization.objects.filter(
            name=obj.state.name, root_org__isnull=True, level_cache=0
        ).first()
    if obj.district:
        query = {
            "name": obj.district.name,
            "level_cache": 1,
        }
        if state:
            query["root_org"] = state
        district = Organization.objects.filter(**query).first()
    if obj.local_body:
        query = {
            "name": obj.local_body.name,
            "level_cache": 2,
        }
        if state:
            query["root_org"] = state
        if district:
            query["parent"] = district
        local_body = Organization.objects.filter(**query).first()
    if obj.ward:
        query = {
            "name": obj.ward.name,
            "level_cache": 3,
        }
        if state:
            query["root_org"] = state
        if local_body:
            query["parent"] = local_body
        ward = Organization.objects.filter(**query).first()
    return ward or local_body or district or state or None


def migrate_facilities(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    Organization = apps.get_model("emr", "Organization")
    bulk_update = []
    for facility in Facility.objects.filter(
        geo_organization__isnull=True
    ).select_related("state", "district", "local_body", "ward"):
        if facility.geo_organization:
            continue
        geo_org = _get_org(Organization, facility)
        if not geo_org:
            continue
        facility.geo_organization = geo_org
        facility.geo_organization_cache = [*geo_org.parent_cache, geo_org.id]
        bulk_update.append(facility)
    Facility.objects.bulk_update(
        bulk_update, ["geo_organization", "geo_organization_cache"]
    )


def reverse_migrate_facilities(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    Facility.objects.filter(geo_organization__meta__migration_id=MIGRATION_ID).update(
        geo_organization=None
    )


def migrate_facility_users(apps, schema_editor):
    from care.emr.models.organization import FacilityOrganization
    from care.emr.models.organization import FacilityOrganizationUser

    Facility = apps.get_model("facility", "Facility")
    FacilityUser = apps.get_model("facility", "FacilityUser")

    remote_doctor_role, _ = RoleModel.objects.get_or_create(
        name="Remote Doctor",
        defaults={
            "description": "Hub doctor with remote access to the patient",
            "is_system": False,
            "temp_deleted": False,
        },
    )

    for facility in Facility.objects.all().order_by("id").prefetch_related("users"):
        facility_root_org, _ = FacilityOrganization.objects.get_or_create(
            org_type="root",
            name="Administration",
            facility_id=facility.id,
            defaults={
                "system_generated": True,
                "parent": None,
                "deleted": facility.deleted,
                "meta": {"migration_id": MIGRATION_ID},
                "created_by_id": facility.created_by_id,
                "created_date": facility.created_date,
            },
        )

        root_org, _ = FacilityOrganization.objects.get_or_create(
            org_type="root",
            name="ICU",
            facility_id=facility.id,
            defaults={
                "system_generated": True,
                "parent": None,
                "deleted": facility.deleted,
                "meta": {"migration_id": MIGRATION_ID},
                "created_by_id": facility.created_by_id,
                "created_date": facility.created_date,
            },
        )

        for facility_user_obj in FacilityUser.objects.filter(
            facility_id=facility.id
        ).prefetch_related("user"):
            facility_user = facility_user_obj.user
            if (
                facility_user.home_facility_id == facility.id
                or facility_user.old_user_type in (30, 40)
            ):
                # link users as their roles if they are associated with the facility
                # or if they are admin users
                role_id = get_role_for_user_type(facility_user.old_user_type)
                if not role_id:
                    logger.warning(
                        f"Could not find role for user {facility_user.id} with type {facility_user.old_user_type}"
                    )
                    continue
            elif facility_user.old_user_type == 15:
                    # if the user is only associated with the facility as a doctor, we need to create a new user
                    role_id = remote_doctor_role.id
            else:
                # skip invalid associations
                logger.warning(
                    f"User {facility_user.id} is not associated with the facility {facility.id}"
                )
                continue

            FacilityOrganizationUser.objects.get_or_create(
                organization_id=root_org.id,
                user_id=facility_user.id,
                role_id=role_id,
                defaults={
                    "deleted": facility.deleted,
                    "meta": {"migration_id": MIGRATION_ID},
                    "created_by_id": facility_user.created_by_id,
                    "created_date": facility.created_date,
                },
            )

            if facility_user.old_user_type in (30, 40):
                # link admin role to the facility root org as well
                FacilityOrganizationUser.objects.get_or_create(
                    organization_id=facility_root_org.id,
                    user_id=facility_user.id,
                    role_id=role_id,
                    defaults={
                        "deleted": facility.deleted,
                        "meta": {"migration_id": MIGRATION_ID},
                        "created_by_id": facility_user.created_by_id,
                        "created_date": facility.created_date,
                    },
                )

        if not facility.default_internal_organization:
            facility.default_internal_organization_id = facility_root_org.id
            facility.internal_organization_cache = [facility_root_org.id, root_org.id]
            facility.save(
                update_fields=[
                    "default_internal_organization_id",
                    "internal_organization_cache",
                ]
            )


def reverse_migrate_facility_users(apps, schema_editor):
    FacilityOrganization = apps.get_model("emr", "FacilityOrganization")
    FacilityOrganization.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0479_migrate_users"),
    ]

    operations = [
        migrations.RunPython(migrate_facilities, reverse_migrate_facilities),
        migrations.RunPython(migrate_facility_users, reverse_migrate_facility_users),
    ]
