# Generated by Django 5.1.4 on 2025-01-28 09:13
from django.db import migrations
from django.core.paginator import Paginator

MIGRATION_ID = 158445695204

location_type_map = {
    1: "other",
    10: "icu",
    20: "ward",
}

bed_type_map = {
    1: "isolation",
    2: "icu",
    3: "icu_with_non_invasive_ventilator",
    4: "icu_with_oxygen_support",
    5: "icu_with_invasive_ventilator",
    6: "bed_with_oxygen_support",
    7: "regular",
}


def migrate_location_beds(apps, schema_editor):
    from care.facility.utils import disable_auto_time
    from care.emr.models import (
        FacilityLocation,
        FacilityOrganization,
        FacilityLocationOrganization,
    )

    enable_auto_time = disable_auto_time(
        FacilityLocation,
        FacilityOrganization,
        FacilityLocationOrganization,
    )
    AssetLocation = apps.get_model("facility", "AssetLocation")
    Bed = apps.get_model("facility", "Bed")

    query = (
        AssetLocation.objects.filter(migrated_emr_location_id__isnull=True)
        .prefetch_related("bed_set")
        .order_by("id")
    )
    paginator = Paginator(query, 1000)

    bulk_update_location_reference = []
    bulk_update_bed_reference = []
    for page in paginator.page_range:
        for asset_location in paginator.page(page):
            bulk_org_relation = []
            root_org = FacilityOrganization._base_manager.filter(
                org_type="root",
                name="Administration",
                facility_id=asset_location.facility_id,
            ).first()
            location = FacilityLocation.objects.create(
                status="active",
                # operational_status="U",
                name=asset_location.name,
                availability_status="available",
                description=asset_location.description,
                mode="kind",
                form="wa",
                facility_id=asset_location.facility_id,
                external_id=asset_location.external_id,
                created_date=asset_location.created_date,
                modified_date=asset_location.modified_date,
                deleted=asset_location.deleted,
                metadata={
                    "location_type": location_type_map.get(
                        asset_location.location_type, "other"
                    ),
                },
                meta={
                    "migration_id": MIGRATION_ID,
                    "middleware_address": asset_location.middleware_address,
                },
            )

            bulk_org_relation.append(location.id)
            bulk_update_location_reference.append((asset_location.id, location.id))

            for old_bed in asset_location.bed_set.all():
                if old_bed.migrated_emr_bed_id:
                    continue
                bed = FacilityLocation.objects.create(
                    parent=location,
                    status="active",
                    operational_status="U",
                    name=old_bed.name,
                    availability_status="available",
                    description=old_bed.description,
                    mode="instance",
                    form="bd",
                    facility_id=asset_location.facility_id,
                    external_id=old_bed.external_id,
                    created_date=old_bed.created_date,
                    modified_date=old_bed.modified_date,
                    deleted=old_bed.deleted,
                    metadata={
                        "bed_type": bed_type_map.get(old_bed.bed_type, "regular"),
                    },
                    meta={
                        "migration_id": MIGRATION_ID,
                    },
                )
                bulk_org_relation.append(bed.id)
                bulk_update_bed_reference.append((old_bed.id, bed.id))
            FacilityLocationOrganization.objects.bulk_create(
                [
                    FacilityLocationOrganization(
                        location_id=location_id,
                        organization_id=root_org.id,
                        deleted=location.deleted,
                    )
                    for location_id in bulk_org_relation
                ]
            )

    AssetLocation.objects.bulk_update(
        [
            AssetLocation(id=id, migrated_emr_location_id=new_location_id)
            for id, new_location_id in bulk_update_location_reference
        ],
        ["migrated_emr_location_id"],
    )

    Bed.objects.bulk_update(
        [
            Bed(id=id, migrated_emr_bed_id=new_bed_id)
            for id, new_bed_id in bulk_update_bed_reference
        ],
        ["migrated_emr_bed_id"],
    )

    enable_auto_time()


def reverse_migrate_location_beds(apps, schema_editor):
    FacilityLocation = apps.get_model("emr", "FacilityLocation")
    FacilityLocation.objects.filter(meta__migration_id=MIGRATION_ID).delete()

    AssetLocation = apps.get_model("facility", "AssetLocation")
    AssetLocation.objects.filter(migrated_emr_location_id__isnull=False).update(
        migrated_emr_location_id=None
    )
    Bed = apps.get_model("facility", "Bed")
    Bed.objects.filter(migrated_emr_bed_id__isnull=False).update(
        migrated_emr_bed_id=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0480_migrate_facilities"),
    ]

    operations = [
        migrations.RunPython(migrate_location_beds, reverse_migrate_location_beds),
    ]
