# Generated by Django 5.1.4 on 2025-01-21 08:44
import logging
from uuid import uuid4
from django.db import migrations
from django.core.paginator import Paginator

from care.emr.resources.questionnaire.utils import convert_to_observation_spec

logger = logging.getLogger(__name__)

MIGRATION_ID = 413370

occupation_map = {
    1: "Student",
    2: "Businessman",
    3: "Health Care Worker",
    4: "Health Care Lab Worker",
    5: "Animal Handler",
    6: "Others",
    7: "Healthcare Practitioner",
    8: "Paramedics",
    9: "Business Related",
    10: "Engineer",
    11: "Teacher",
    12: "Other Professional Occupations",
    13: "Office Administrative",
    14: "Chef",
    15: "Protective Service",
    16: "Hospitality",
    17: "Custodial",
    18: "Customer Service",
    19: "Sales Supervisor",
    20: "Retail Sales Worker",
    21: "Insurance Sales Agent",
    22: "Sales Representative",
    23: "Real Estate",
    24: "Construction Extraction",
    25: "Agri Natural",
    26: "Production Occupation",
    27: "Pilot Flight",
    28: "Vehicle Driver",
    29: "Military",
    30: "Homemaker",
    31: "Unknown",
    32: "Not Applicable",
}

socioeconomic_status_map = {
    10: "Very Poor",
    20: "Poor",
    30: "Middle Class",
    40: "Well Off",
}

domestic_healthcare_support_map = {
    0: "No Support",
    10: "Family Member",
    20: "Paid Caregiver",
}

gender_map = {
    1: "male",
    2: "female",
    3: "non_binary",
}

blood_group_map = {
    "A+": "A_positive",
    "A-": "A_negative",
    "B+": "B_positive",
    "B-": "B_negative",
    "AB+": "AB_positive",
    "AB-": "AB_negative",
    "O+": "O_positive",
    "O-": "O_negative",
    "UNK": "unknown",
}

disease_choices_map = {
    2: "Diabetes",
    3: "Heart Disease",
    4: "HyperTension",
    5: "Kidney Diseases",
    6: "Lung Diseases/Asthma",
    7: "Cancer",
    8: "Other Disease/Condition",
}


def _get_org(Organization, obj):
    state = None
    district = None
    local_body = None
    ward = None
    if obj.state:
        state = Organization.objects.filter(
            name=obj.state.name, root_org__isnull=True, level_cache=0
        ).first()
    if obj.district:
        query = {
            "name": obj.district.name,
            "level_cache": 1,
        }
        if state:
            query["root_org"] = state
        district = Organization.objects.filter(**query).first()
    if obj.local_body:
        query = {
            "name": obj.local_body.name,
            "level_cache": 2,
        }
        if state:
            query["root_org"] = state
        if district:
            query["parent"] = district
        local_body = Organization.objects.filter(**query).first()
    if obj.ward:
        query = {
            "name": obj.ward.name,
            "level_cache": 3,
        }
        if state:
            query["root_org"] = state
        if local_body:
            query["parent"] = local_body
        ward = Organization.objects.filter(**query).first()
    return ward or local_body or district or state or None


def migrate_patient_registrations(apps, schema_editor):
    PatientRegistration = apps.get_model("facility", "PatientRegistration")
    Patient = apps.get_model("emr", "Patient")
    Organization = apps.get_model("emr", "Organization")
    Questionnaire = apps.get_model("emr", "Questionnaire")
    QuestionnaireResponse = apps.get_model("emr", "QuestionnaireResponse")
    QuestionnaireOrganization = apps.get_model("emr", "QuestionnaireOrganization")
    NoteThread = apps.get_model("emr", "NoteThread")
    NoteMessage = apps.get_model("emr", "NoteMessage")

    meta_info_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="patient_meta_information_internal_a2e6ef7e",
        defaults={
            "title": "Patient Meta Information",
            "description": "Patient Meta Information",
            "subject_type": "patient",
            "meta": {
                "migration_id": MIGRATION_ID,
            },
            "status": "retired",
            "questions": [
                {
                    "id": "91b29d71-a2a4-4a98-bfb7-69188170c960",
                    "link_id": "1.1",
                    "question": "Occupation",
                    "type": "choice",
                    "required": False,
                    "answer_options": [
                        {"initial_selected": False, "value": v}
                        for v in occupation_map.values()
                    ],
                },
                {
                    "id": "a41c5beb-9b33-4d32-8b04-335bf8a91d28",
                    "link_id": "1.2",
                    "question": "Socioeconomic Status",
                    "type": "choice",
                    "required": False,
                    "answer_options": [
                        {"initial_selected": False, "value": v}
                        for v in socioeconomic_status_map.values()
                    ],
                },
                {
                    "id": "176e29eb-f80b-42cc-a11f-5f9f997989a2",
                    "link_id": "1.3",
                    "question": "Domestic Healthcare Support",
                    "type": "choice",
                    "required": False,
                    "answer_options": [
                        {"initial_selected": False, "value": v}
                        for v in domestic_healthcare_support_map.values()
                    ],
                },
                {
                    "id": "c5b95c32-c2d1-41fd-805b-6062edd52cee",
                    "link_id": "1.4",
                    "question": "Head of Household",
                    "type": "boolean",
                    "required": False,
                },
            ],
        },
    )

    if created:
        root_orgs = Organization.objects.filter(root_org__isnull=True)
        for org in root_orgs:
            QuestionnaireOrganization.objects.get_or_create(
                questionnaire=meta_info_questionnaire,
                organization=org,
            )

    logger.debug("Migrating Patient Registrations")
    patient_registrations = (
        PatientRegistration.objects.filter(migrated_emr_patient_id__isnull=True)
        .select_related("state", "district", "local_body", "ward", "meta_info")
        .prefetch_related("medical_history")
        .exclude(deleted=True)
        .order_by("id")
    )
    paginator = Paginator(patient_registrations, 2000)

    bulk = []
    for page_number in paginator.page_range:
        for patient_registration in paginator.page(page_number).object_list:
            patient = Patient.objects.create(
                name=patient_registration.name,
                gender=gender_map.get(patient_registration.gender, ""),
                phone_number=patient_registration.phone_number,
                emergency_phone_number=patient_registration.emergency_phone_number,
                address=patient_registration.address,
                permanent_address=patient_registration.permanent_address,
                pincode=patient_registration.pincode,
                date_of_birth=patient_registration.date_of_birth,
                year_of_birth=patient_registration.year_of_birth,
                deceased_datetime=patient_registration.death_datetime,
                blood_group=blood_group_map.get(patient_registration.blood_group, ""),
                geo_organization=_get_org(Organization, patient_registration),
                meta={
                    "migration_id": MIGRATION_ID,
                },
                created_by=patient_registration.created_by,
                created_date=patient_registration.created_date,
                modified_date=patient_registration.modified_date,
            )
            if meta_info := patient_registration.meta_info:
                responses = []
                if meta_info.occupation is not None:
                    responses.append(
                        {
                            "question": "91b29d71-a2a4-4a98-bfb7-69188170c960",
                            "answer": occupation_map[meta_info.occupation],
                        }
                    )
                if meta_info.socioeconomic_status is not None:
                    responses.append(
                        {
                            "question": "a41c5beb-9b33-4d32-8b04-335bf8a91d28",
                            "answer": socioeconomic_status_map[
                                meta_info.socioeconomic_status
                            ],
                        }
                    )
                if meta_info.domestic_healthcare_support is not None:
                    responses.append(
                        {
                            "question": "176e29eb-f80b-42cc-a11f-5f9f997989a2",
                            "answer": domestic_healthcare_support_map[
                                meta_info.domestic_healthcare_support
                            ],
                        }
                    )
                if meta_info.head_of_household is not None:
                    responses.append(
                        {
                            "question": "c5b95c32-c2d1-41fd-805b-6062edd52cee",
                            "answer": bool(meta_info.head_of_household),
                        }
                    )
                QuestionnaireResponse.objects.create(
                    questionnaire=meta_info_questionnaire,
                    patient=patient,
                    subject_id=str(patient.external_id),
                    responses=[{"values": responses}],
                    created_by=patient_registration.created_by,
                    created_date=patient_registration.created_date,
                    modified_date=patient_registration.modified_date,
                    meta={
                        "migration_id": MIGRATION_ID,
                    },
                )

            note_thread, created = NoteThread.objects.get_or_create(
                title="Patient Health Information",
                patient=patient,
                defaults={
                    "meta": {
                        "migration_id": MIGRATION_ID,
                    },
                    # "created_by": patient_registration.created_by,
                    "created_date": patient_registration.created_date,
                    # "modified_date": patient_registration.modified_date,
                },
            )

            if created:
                messages = []
                if patient_registration.allergies:
                    messages.append(
                        f"Reported Allergies: {patient_registration.allergies}"
                    )
                if patient_registration.present_health:
                    messages.append(
                        f"Present Health: {patient_registration.present_health}"
                    )
                if patient_registration.ongoing_medication:
                    messages.append(
                        f"Ongoing Medication: {patient_registration.ongoing_medication}"
                    )
                for item in patient_registration.medical_history.all():
                    if item.deleted or item.disease == 1:
                        continue
                    message = disease_choices_map.get(item.disease, 'Other Disease/Condition')
                    if item.details:
                        message += f": {item.details}"
                    messages.append(message)
                NoteMessage.objects.bulk_create(
                    [
                        NoteMessage(
                            message=message,
                            thread=note_thread,
                            meta={
                                "migration_id": MIGRATION_ID,
                            },
                            created_date=patient.created_date,
                            modified_date=patient.modified_date,
                            created_by=patient.created_by,
                            updated_by=patient.created_by,
                        )
                        for message in messages
                    ]
                )

            patient_registration.migrated_emr_patient_id = patient.id
            bulk.append((patient_registration.id, patient.id))
            logger.debug(f"Created Patient: {patient.name=}")
    PatientRegistration.objects.bulk_update(
        [
            PatientRegistration(id=id, migrated_emr_patient_id=patient_id)
            for id, patient_id in bulk
        ],
        ["migrated_emr_patient_id"],
    )


def reverse_migrate_patient_registrations(apps, schema_editor):
    PatientRegistration = apps.get_model("facility", "PatientRegistration")
    Patient = apps.get_model("emr", "Patient")
    NoteThread = apps.get_model("emr", "NoteThread")
    Questionnaire = apps.get_model("emr", "Questionnaire")
    Questionnaire.objects.filter(meta__migration_id=MIGRATION_ID).delete()
    NoteThread.objects.filter(meta__migration_id=MIGRATION_ID).delete()
    PatientRegistration.objects.update(migrated_emr_patient_id=None)
    Patient.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0480_migrate_facilities"),
    ]

    operations = [
        migrations.RunPython(
            migrate_patient_registrations, reverse_migrate_patient_registrations
        ),
    ]
