# Generated by Django 5.1.4 on 2025-01-21 08:46
from datetime import UTC
import logging
from django.db import migrations
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)

MIGRARION_ID = 413370


def _create_encounter(apps, consultation):
    Encounter = apps.get_model("emr", "Encounter")
    period = {
        "start": consultation.encounter_date.replace(tzinfo=UTC).isoformat(),
        "end": (
            consultation.discharge_date.replace(tzinfo=UTC).isoformat()
            if consultation.discharge_date
            else None
        ),
    }
    encounter = Encounter.objects.create(
        status="completed" if consultation.discharge_date else "in-progress",
        patient_id=consultation.patient.migrated_emr_patient_id,
        external_identifier=consultation.patient_no,
        period=period,
        facility=consultation.facility,
        meta={
            "migration_id": MIGRARION_ID,
        },
        created_by=consultation.created_by,
        updated_by=consultation.last_edited_by,
        created_date=consultation.created_date,
        modified_date=consultation.modified_date,
    )
    return encounter


def migrate_consultations(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")

    paginator = Paginator(
        PatientConsultation.objects.filter(migrated_emr_encounter_id__isnull=True)
        .select_related("patient")
        .exclude(deleted=True, patient__deleted=True)
        .order_by("id"),
        2000,
    )
    bulk = []
    for page_number in paginator.page_range:
        for patient_consultation in paginator.page(page_number).object_list:
            encounter = _create_encounter(apps, patient_consultation)
            patient_consultation.migrated_emr_encounter_id = encounter.id
            bulk.append((patient_consultation.id, encounter.id))
            logger.debug(f"Created Encounter: {encounter.id=}")
    PatientConsultation.objects.bulk_update(
        [
            PatientConsultation(id=pc_id, migrated_emr_encounter_id=encounter_id)
            for pc_id, encounter_id in bulk
        ],
        ["migrated_emr_encounter_id"],
    )


def reverse_migrate_consultations(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")
    Encounter = apps.get_model("emr", "Encounter")
    PatientConsultation.objects.update(migrated_emr_encounter_id=None)
    Encounter.objects.filter(meta__migration_id=MIGRARION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0481_migrate_patient_reg"),
    ]

    operations = [
        migrations.RunPython(migrate_consultations, reverse_migrate_consultations),
    ]
