# Generated by Django 5.1.4 on 2025-01-21 08:46
from datetime import UTC
import logging
from django.db import migrations
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)

MIGRARION_ID = 413370


def _get_org(Organization, obj):
    state = None
    district = None
    local_body = None
    ward = None
    if obj.state:
        state = Organization.objects.filter(
            name=obj.state.name,
            root_org__isnull=True,
            level_cache=0
        ).first()
    if obj.district:
        query = {
            "name": obj.district.name,
            "level_cache": 1,
        }
        if state:
            query["root_org"] = state
        district = Organization.objects.filter(**query).first()
    if obj.local_body:
        query = {
            "name": obj.local_body.name,
            "level_cache": 2,
        }
        if state:
            query["root_org"] = state
        if district:
            query["parent"] = district
        local_body = Organization.objects.filter(**query).first()
    if obj.ward:
        query = {
            "name": obj.ward.name,
            "level_cache": 3,
        }
        if state:
            query["root_org"] = state
        if local_body:
            query["parent"] = local_body
        ward = Organization.objects.filter(**query).first()
    return ward or local_body or district or state or None


def _create_encounter(Encounter, consultation):
    period = {
        "start": consultation.encounter_date.replace(tzinfo=UTC).isoformat(),
        "end": consultation.discharge_date.replace(tzinfo=UTC).isoformat() if consultation.discharge_date else None,
    }
    return Encounter.objects.create(
            status="completed" if consultation.discharge_date else "in-progress",
            patient_id=consultation.patient.migrated_emr_patient_id,
            external_identifier=consultation.patient_no,
            period=period,
            facility=consultation.facility,
            meta={
                "migration_id": MIGRARION_ID,
            },
            created_by=consultation.created_by,
            updated_by=consultation.last_edited_by,
            created_date=consultation.created_date,
            modified_date=consultation.modified_date,
        )


def migrate_consultations(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")
    Encounter = apps.get_model("emr", "Encounter")

    paginator = Paginator(
        PatientConsultation.objects.all().select_related("patient").order_by("id"),
        2000
    )
    for page_number in paginator.page_range:
        page = paginator.page(page_number)
        bulk = []
        for patient_consultation in page.object_list:
            encounter = _create_encounter(Encounter, patient_consultation)
            patient_consultation.migrated_emr_encounter_id = encounter.id
            bulk.append(patient_consultation)
            logger.debug(f"Created Encounter: {encounter.id=}")
        PatientConsultation.objects.bulk_update(bulk, ["migrated_emr_encounter_id"])


def reverse_migrate_consultations(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0481_migrate_patient_reg'),
    ]

    operations = [
        migrations.RunPython(migrate_consultations, reverse_migrate_consultations),
    ]
