# Generated by Django 6.0 on 2026-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0481_delete_asset_delete_assetbed_delete_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='print_templates',
            field=models.JSONField(default=list),
        ),
    ]
