# Generated by Django 5.1.4 on 2025-01-21 07:24

import logging

from django.db import migrations, models
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)

MIGRATION_ID = 413380


def migrate_patient_notes(apps, schema_editor):
    logger.debug("Migrating Patient Notes")
    PatientNotes = apps.get_model("facility", "PatientNotes")
    NoteThread = apps.get_model("emr", "NoteThread")
    NoteMessage = apps.get_model("emr", "NoteMessage")
    DOCTORS = 10

    query = (
        PatientNotes.objects.filter(
            patient__migrated_emr_patient_id__isnull=False,
        )
        .exclude(
            note__isnull=True,
            note__exact="",
            meta__migration_id=MIGRATION_ID,
        )
        .select_related("patient", "consultation")
        .prefetch_related("edits")
        .order_by("id")
    )
    paginator = Paginator(
        query,
        1000,
    )

    for page_number in paginator.page_range:
        for patient_note in paginator.page(page_number).object_list:
            thread_name = (
                patient_note.thread == DOCTORS
                and "Doctors Discussion"
                or "Nurses Discussion"
            )
            note_thread, created = NoteThread.objects.get_or_create(
                title=thread_name,
                patient_id=patient_note.patient.migrated_emr_patient_id,
                encounter_id=(
                    patient_note.consultation.migrated_emr_encounter_id
                    if patient_note.consultation
                    else None
                ),
                defaults={
                    "meta": {
                        "migration_id": MIGRATION_ID,
                    },
                    "created_date": patient_note.created_date,
                    "modified_date": patient_note.modified_date,
                    "created_by": patient_note.created_by,
                    "updated_by": patient_note.created_by,
                },
            )
            history = []
            for edit in patient_note.edits.all():
                if patient_note.note != edit.note:
                    continue
                history.append(
                    {
                        "message": edit.note,
                        "created_by": {
                            "username": edit.edited_by.username,
                            "external_id": str(edit.edited_by.external_id),
                        },
                        "edited_at": str(edit.edited_date),
                        "created_at": str(patient_note.created_date),
                    }
                )
            NoteMessage.objects.create(
                thread=note_thread,
                message=patient_note.note,
                message_history={"history": history} if history else {},
                meta={
                    "migration_id": MIGRATION_ID,
                },
                created_date=patient_note.created_date,
                modified_date=patient_note.modified_date,
                created_by=patient_note.created_by,
                updated_by=patient_note.created_by,
            )
    query.update(meta={"migration_id": MIGRATION_ID})
    logger.debug("Migrating Patient Notes Done")


def reverse_migrate_patient_notes(apps, schema_editor):
    logger.debug("Reversing Migration Patient Notes")
    NoteThread = apps.get_model("emr", "NoteThread")
    NoteThread.objects.filter(meta__migration_id=MIGRATION_ID).delete()
    PatientNotes = apps.get_model("facility", "PatientNotes")
    PatientNotes.objects.filter(meta__migration_id=MIGRATION_ID).update(meta={})


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0482_migrate_patient_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientnotes",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(migrate_patient_notes, reverse_migrate_patient_notes),
    ]
