# Generated by Django 6.0 on 2026-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0482_facility_print_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='corona_testing',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='expected_oxygen_requirement',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='expected_type_b_cylinders',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='expected_type_c_cylinders',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='expected_type_d_cylinders',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='oxygen_capacity',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type_b_cylinders',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type_c_cylinders',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type_d_cylinders',
        )
    ]
