# Generated by Django 5.1.4 on 2025-01-21 06:21

from datetime import UTC
from django.db import migrations
from care.emr.resources.condition.spec import ClinicalStatusChoices, VerificationStatusChoices
from care.facility.models.encounter_symptom import ClinicalImpressionStatus, Symptom as SymptomChoices
import logging
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)

MIGRATION_ID = 413380

def migrate_symptoms(apps, schema_editor):
    Symptom = apps.get_model("facility", "EncounterSymptom")
    Condition  = apps.get_model("emr", "Condition")

    symptom_sct_map = {
        SymptomChoices.FEVER: "386661006",
        SymptomChoices.SORE_THROAT: "267102003",
        SymptomChoices.COUGH: "49727002",
        SymptomChoices.BREATHLESSNESS: "267036007",
        SymptomChoices.MYALGIA: "68962001",
        SymptomChoices.ABDOMINAL_DISCOMFORT: "43364001",
        SymptomChoices.VOMITING: "249497008",
        SymptomChoices.SPUTUM: "248596009",
        SymptomChoices.NAUSEA: "422587007",
        SymptomChoices.CHEST_PAIN: "29857009",
        SymptomChoices.HEMOPTYSIS: "66857006",
        SymptomChoices.NASAL_DISCHARGE: "64531003",
        SymptomChoices.BODY_ACHE: "82991003",
        SymptomChoices.DIARRHOEA: "62315008",
        SymptomChoices.PAIN: "22253000",
        SymptomChoices.PEDAL_EDEMA: "102576009",
        SymptomChoices.WOUND: "225552003",
        SymptomChoices.CONSTIPATION: "14760008",
        SymptomChoices.HEADACHE: "25064002",
        SymptomChoices.BLEEDING: "131148009",
        SymptomChoices.DIZZINESS: "404640003",
        SymptomChoices.CHILLS: "43724002",
        SymptomChoices.GENERAL_WEAKNESS: "13791008",
        SymptomChoices.IRRITABILITY: "55929007",
        SymptomChoices.CONFUSION: "40917007",
        SymptomChoices.ABDOMINAL_PAIN: "21522001",
        SymptomChoices.JOINT_PAIN: "57676002",
        SymptomChoices.REDNESS_OF_EYES: "703630003",
        SymptomChoices.ANOREXIA: "79890006",
        SymptomChoices.NEW_LOSS_OF_TASTE: "36955009",
        SymptomChoices.NEW_LOSS_OF_SMELL: "44169009",
        SymptomChoices.OTHERS: "404684003",
    }

    clinical_status_map = {
        ClinicalImpressionStatus.IN_PROGRESS: {
            "clinical_status": ClinicalStatusChoices.active,
            "verification_status": VerificationStatusChoices.provisional,
        },
        ClinicalImpressionStatus.COMPLETED: {
            "clinical_status": ClinicalStatusChoices.resolved,
            "verification_status": VerificationStatusChoices.confirmed,
        },
        ClinicalImpressionStatus.ENTERED_IN_ERROR: {
            "clinical_status": None,
            "verification_status": VerificationStatusChoices.entered_in_error,
        },
    }

    logger.debug("Migrating Patient Registrations")
    symptoms = Symptom.objects.filter(
        # consultation__migrated_emr_encounter_id__isnull=False,
    ).order_by("id").select_related("consultation__patient", "consultation")
    paginator = Paginator(symptoms, 2000)

    for page_number in paginator.page_range:
        page = paginator.page(page_number)
        bulk = []
        for symptom in page.object_list:
            if symptom.consultation.deleted:
                print("consultation deleted", symptom.consultation.id)
                continue
            if symptom.consultation.patient.deleted:
                print("patient deleted", symptom.consultation.patient.id)
                continue
            condition = Condition(
                **clinical_status_map.get(symptom.clinical_impression_status, {}),
                category="problem_list_item",
                code={
                    "system": "http://snomed.info/sct",
                    "code": symptom_sct_map.get(symptom.symptom, "404684003")
                },
                note=symptom.other_symptom,
                onset={
                    "onset_datetime": symptom.onset_date.replace(tzinfo=UTC).isoformat() if symptom.onset_date else None,
                    "onset_age": None,
                    "onset_string": None,
                    "note": None,
                },
                severity=None,
                body_site={},
                recorded_date=None,
                patient_id=symptom.consultation.patient.migrated_emr_patient_id,
                encounter_id=symptom.consultation.migrated_emr_encounter_id,
                created_by=symptom.created_by,
                updated_by=symptom.updated_by,
                created_date=symptom.created_date,
                modified_date=symptom.modified_date,
                meta={
                    "migration_id": MIGRATION_ID,
                    "cured_date": symptom.cure_date.replace(tzinfo=UTC).isoformat() if symptom.cure_date else None,
                }
            )
            if symptom.cure_date:
                condition.clinical_status = ClinicalStatusChoices.resolved
                condition.verification_status = VerificationStatusChoices.confirmed
            bulk.append(condition)
            logger.debug(f"Created Condition: {condition.id}")

        Condition.objects.bulk_create(bulk)

def reverse_migrate_symptoms(apps, schema_editor):
    Condition = apps.get_model("emr", "Condition")
    Condition.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0483_migrate_patientnotes'),
        ('emr', '0013_enable_auto_time'),
    ]

    operations = [
        migrations.RunPython(migrate_symptoms, migrations.RunPython.noop),
    ]
