# Generated by Django 6.0 on 2026-03-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0483_remove_facility_corona_testing_and_more'),
        ('emr', '0074_facilitymonetoryconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='discount_codes',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='discount_monetary_components',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='invoice_number_expression',
        ),
    ]
