# Generated by Django 6.0 on 2026-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmobileotp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='patientmobileotp',
            index=models.Index(condition=models.Q(('deleted', False)), fields=['phone_number', '-created_date'], name='pmo_phone_created_active_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmobileotp',
            index=models.Index(condition=models.Q(('deleted', False)), fields=['phone_number', '-modified_date'], name='pmo_phone_modified_active_idx'),
        ),
    ]
