# Generated by Django 6.0 on 2026-05-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0484_remove_facility_discount_codes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmobileotp",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
