# Generated by Django 6.0 on 2026-03-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='pincode',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
    ]
