# Generated by Django 5.1.4 on 2025-01-22 13:08
import logging
import re
from datetime import UTC

from django.core.paginator import Paginator
from django.db import migrations
from django.db.models import F, Value, Func
from django.db.models.fields.json import JSONField

from care.emr.models.medication_request import MedicationRequest
from care.emr.models.medication_administration import MedicationAdministration
from care.facility.utils import disable_auto_time


disable_auto_time([MedicationRequest, MedicationAdministration])

logger = logging.getLogger(__name__)

MIGRATION_ID = 158445695209

ROUTE_MAP = {
    "ORAL": {
        "code": "26643006",
        "display": "Oral route",
        "system": "http://snomed.info/sct",
    },
    "IV": {
        "code": "47625008",
        "display": "Intravenous route",
        "system": "http://snomed.info/sct",
    },
    "IM": {
        "code": "78421000",
        "display": "Intramuscular route",
        "system": "http://snomed.info/sct",
    },
    "SC": {
        "code": "34206005",
        "display": "Subcutaneous route",
        "system": "http://snomed.info/sct",
    },
    "S/C": {
        "code": "34206005",
        "display": "Subcutaneous route",
        "system": "http://snomed.info/sct",
    },
    "INHALATION": {
        "code": "447694001",
        "display": "Respiratory tract route",
        "system": "http://snomed.info/sct",
    },
    "NASOGASTRIC": {
        "code": "127492001",
        "display": "Nasogastric route",
        "system": "http://snomed.info/sct",
    },
    "INTRATHECAL": {
        "code": "72607000",
        "display": "Intrathecal route",
        "system": "http://snomed.info/sct",
    },
    "TRANSDERMAL": {
        "code": "45890007",
        "display": "Transdermal route",
        "system": "http://snomed.info/sct",
    },
    "RECTAL": {
        "code": "37161004",
        "display": "Rectal route",
        "system": "http://snomed.info/sct",
    },
    "SUBLINGUAL": {
        "code": "37839007",
        "display": "Sublingual route",
        "system": "http://snomed.info/sct",
    },
}

DOSAGE_UNITS_MAP = {
    "mg": {
        "code": "mg",
        "display": "Milligram",
        "system": "http://unitsofmeasure.org",
    },
    "g": {
        "code": "g",
        "display": "Gram",
        "system": "http://unitsofmeasure.org",
    },
    "ml": {
        "code": "mL",
        "display": "Milliliter",
        "system": "http://unitsofmeasure.org",
    },
    "drop(s)": {
        "code": "[drp]",
        "display": "Drop",
        "system": "http://unitsofmeasure.org",
    },
    "tsp": {
        "code": "[tsp_m]",
        "display": "Teaspoon",
        "system": "http://unitsofmeasure.org",
    },
    "mcg": {
        "code": "ug",
        "display": "Microgram",
        "system": "http://unitsofmeasure.org",
    },
    "ampule(s)": {
        "code": "[amp]",
        "display": "Ampule",
        "system": "http://care.ohc.network",
    },
    # TOOD: confirm this
    # "unit(s)": {
    #     "code": "U",
    #     "display": "Unit",
    #     "system": "http://care.ohc.network"
    # },
}

FREQUENCY_MAP = {
    "OD": {
        "repeat": {
            "frequency": 1,
            "period": 1,
            "period_unit": "d",
            "bounds_duration": {"value": 1, "unit": "d"},
        },
        "code": {
            "code": "QD",
            "display": "Once a day",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "HS": {
        "repeat": {
            "frequency": 1,
            "period": 1,
            "period_unit": "d",
            "bounds_duration": {"value": 1, "unit": "d"},
        },
        "code": {
            "code": "BED",
            "display": "Bedtime",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "BD": {
        "repeat": {
            "frequency": 2,
            "period": 1,
            "period_unit": "d",
            "bounds_duration": {"value": 1, "unit": "d"},
        },
        "code": {
            "code": "BID",
            "display": "Two times a day",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "TID": {
        "repeat": {
            "frequency": 1,
            "period": 8,
            "period_unit": "h",
            "bounds_duration": {
                "value": 1,
                "unit": "d",
            },
        },
        "code": {
            "code": "Q8H",
            "display": "Every 8 hours",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "QID": {
        "repeat": {
            "frequency": 1,
            "period": 6,
            "period_unit": "h",
            "bounds_duration": {"value": 1, "unit": "d"},
        },
        "code": {
            "code": "Q6H",
            "display": "Every 6 hours",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "Q4H": {
        "repeat": {
            "frequency": 1,
            "period": 4,
            "period_unit": "h",
            "bounds_duration": {"value": 1, "unit": "d"},
        },
        "code": {
            "code": "Q4H",
            "display": "Every 4 hours",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "QOD": {
        "repeat": {
            "frequency": 1,
            "period": 2,
            "period_unit": "d",
            "bounds_duration": {"value": 2, "unit": "d"},
        },
        "code": {
            "code": "QOD",
            "display": "Alternate days",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
    "QWK": {
        "repeat": {
            "frequency": 1,
            "period": 1,
            "period_unit": "wk",
            "bounds_duration": {"value": 1, "unit": "wk"},
        },
        "code": {
            "code": "WK",
            "display": "Weekly",
            "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
        },
    },
}


def parse_dosage_str(dosage_str):
    # Match patterns like "1mg", "2.2mg", "1 mg"
    pattern = r"^(\d+(?:\.\d+)?)\s*([a-zA-Z\(\)]+)$"
    match = re.match(pattern, dosage_str)

    if not match:
        raise ValueError(f"Invalid dosage format: {dosage_str}")

    value, unit = match.groups()
    unit = unit.lower()  # Normalize unit to lowercase for matching

    if unit not in DOSAGE_UNITS_MAP:
        raise ValueError(f"Unsupported unit: {unit}")

    return {
        "value": float(value),
        "unit": DOSAGE_UNITS_MAP[unit],
    }


def get_medication_request_medication(prescription):
    medicine = (
        prescription.medicine.name
        if prescription.medicine
        else prescription.medicine_old
    )
    return {
        "system": "http://care.ohc.network",
        "code": medicine,
        "display": medicine,
    }


def get_medication_request_category(prescription):
    if prescription.prescription_type == "DISCHARGE":
        return "discharge"
    if prescription.consultation.suggestion == "A":
        return "inpatient"
    if prescription.consultation.suggestion == "OP":
        return "outpatient"


def get_dosage_instruction_timing(prescription):
    if prescription.dosage_type == "PRN":
        return None
    if prescription.frequency in FREQUENCY_MAP:
        timing = FREQUENCY_MAP[prescription.frequency]
        if prescription.days:
            timing["repeat"]["bounds_duration"] = {
                "value": prescription.days,
                "unit": "d",
            }
        return timing


def migrate_medication_request(MedicationRequest, prescription):
    meta = {
        **prescription.meta,
        "migration_id": MIGRATION_ID,
    }
    status, priority = "active", "routine"
    medication = get_medication_request_medication(prescription)
    category = get_medication_request_category(prescription)
    dosage_instruction = {}

    if prescription.instruction_on_titration:
        meta["instruction_on_titration"] = prescription.instruction_on_titration

    if prescription.route:
        try:
            dosage_instruction["route"] = ROUTE_MAP[prescription.route]
        except KeyError:
            dosage_instruction["route"] = {
                "code": prescription.route,
                "display": prescription.route,
                "system": "http://care.ohc.network",
            }

    try:
        base_dosage = parse_dosage_str(prescription.base_dosage)
    except (ValueError, TypeError) as e:
        base_dosage = None

    dosage_instruction["dose_and_rate"] = {"type": "ordered"}
    if prescription.dosage_type == "TITRATED":
        dosage_instruction["text"] = (
            f"{prescription.base_dosage} to {prescription.target_dosage}"
        )
        try:
            target_dosage = parse_dosage_str(prescription.target_dosage)
        except (ValueError, TypeError):
            target_dosage = None
        low, high = base_dosage, target_dosage
        # if the units are the same and the low value is greater than the high value, swap them
        if (
            low
            and high
            and low["unit"]["code"] == high["unit"]["code"]
            and low["value"] > high["value"]
        ):
            low, high = high, low
        dosage_instruction["dose_and_rate"]["dose_range"] = {
            "low": low,
            "high": high,
        }
    else:
        dosage_instruction["text"] = prescription.base_dosage
        dosage_instruction["dose_and_rate"]["dose_quantity"] = base_dosage

    if prescription.dosage_type == "PRN":
        dosage_instruction["as_needed_boolean"] = True
        dosage_instruction["as_needed_for"] = {
            "system": "http://care.ohc.network",
            "code": prescription.indicator,
            "display": prescription.indicator,
        }
        if prescription.max_dosage:
            meta["max_dosage_in_24_hours"] = prescription.max_dosage
        if prescription.min_hours_between_doses:
            meta["min_hours_between_doses"] = prescription.min_hours_between_doses
    else:
        dosage_instruction["timing"] = get_dosage_instruction_timing(prescription)
        if prescription.frequency == "STAT":
            priority = "stat"

    if prescription.discontinued:
        status = "ended"
        if prescription.discontinued_reason:
            meta["discontinued_reason"] = prescription.discontinued_reason
        if discontinued_date := prescription.discontinued_date:
            meta["discontinued_date"] = discontinued_date.astimezone(UTC).isoformat()
    obj = MedicationRequest.objects.create(
        status=status,
        intent="order",
        category=category,
        priority=priority,
        do_not_perform=prescription.discontinued,
        method=None,
        medication=medication,
        patient_id=prescription.consultation.patient.migrated_emr_patient_id,
        encounter_id=prescription.consultation.migrated_emr_encounter_id,
        dosage_instruction=[dosage_instruction],
        note=prescription.notes,
        authored_on=prescription.created_date,
        requester_id=prescription.prescribed_by_id,
        created_date=prescription.created_date,
        modified_date=prescription.modified_date,
        meta=meta,
    )
    return obj


def _get_administration_objects(
    MedicationAdministration, prescription, medication_request
):
    objects = []
    for administration in prescription.administrations.all():
        status = "completed"
        meta = {
            "migration_id": MIGRATION_ID,
        }
        dosage_instruction = medication_request.dosage_instruction[0]
        dosage = {
            "site": dosage_instruction.get("site"),
            "route": dosage_instruction.get("route"),
            "method": dosage_instruction.get("method"),
        }
        try:
            dosage["dose"] = parse_dosage_str(administration.dosage)
        except (ValueError, TypeError):
            dosage["text"] = administration.dosage
        if administration.archived_on:
            status = "entered-in-error"
            meta["archived_on"] = administration.archived_on.astimezone(UTC).isoformat()
            meta["archived_by"] = str(administration.archived_by.external_id)
        objects.append(
            MedicationAdministration(
                status=status,
                category="inpatient",
                medication=medication_request.medication,
                patient_id=medication_request.patient_id,
                encounter_id=medication_request.encounter_id,
                request_id=medication_request.id,
                authored_on=medication_request.authored_on,
                occurrence_period_start=administration.administered_date,
                occurrence_period_end=administration.administered_date,
                recorded=administration.created_date,
                performer=[],
                dosage=dosage,
                note=administration.notes,
                meta=meta,
            )
        )
    return objects


def migrate_prescriptions_and_administrations(apps, schema_editor):
    logger.debug("Migrating Prescriptions")
    Prescription = apps.get_model("facility", "Prescription")
    paginator = Paginator(
        Prescription.objects.filter(meta__migration_id__isnull=True)
        .select_related(
            "consultation", "consultation__patient", "medicine", "prescribed_by"
        )
        .prefetch_related("administrations")
        .order_by("id"),
        1000,
    )
    for page_num in paginator.page_range:
        page = paginator.page(page_num)
        administrations = []
        for prescription in page.object_list:
            medication_request = migrate_medication_request(
                MedicationRequest, prescription
            )
            administrations += _get_administration_objects(
                MedicationAdministration, prescription, medication_request
            )
            logger.debug(
                f"Migrated Prescription {prescription.id} -> {medication_request.id}"
            )
        MedicationAdministration.objects.bulk_create(administrations)
    # add migration_id to the exting meta of prescriptions

    Prescription.objects.update(
        meta=Func(
            F("meta"),
            Value('{"migration_id"}'),
            Value(MIGRATION_ID, output_field=JSONField()),
            Value(True),
            function="jsonb_set",
        )
    )
    logger.debug("Migrating Prescriptions and Medicine Administrations Done")


def reverse_migrate_prescriptions_and_administrations(apps, schema_editor):
    logger.debug("Reversing Migration of Prescriptions")
    MedicationRequest = apps.get_model("emr", "MedicationRequest")
    MedicationRequest.objects.filter(meta__migration_id=MIGRATION_ID).delete()
    Prescription = apps.get_model("facility", "Prescription")
    Prescription.objects.filter(meta__migration_id=MIGRATION_ID).update(
        meta__migration_id=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0484_migrate_patient_notes"),
    ]

    operations = [
        migrations.RunPython(
            migrate_prescriptions_and_administrations,
            reverse_code=reverse_migrate_prescriptions_and_administrations,
        ),
    ]
