# Generated by Django 6.0 on 2026-05-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0485_patientmobileotp_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientMobileOTP',
            new_name='MobileOTP',
        ),
    ]
