# Generated by Django 5.1.4 on 2025-01-21 06:21

from datetime import UTC
from django.db import migrations
import logging
from django.core.paginator import Paginator


logger = logging.getLogger(__name__)

MIGRATION_ID = 158445695210


def migrate_symptoms(apps, schema_editor):
    from care.emr.models import Condition
    from care.facility.utils import disable_auto_time
    from care.emr.resources.condition.spec import (
        ClinicalStatusChoices,
        VerificationStatusChoices,
    )
    from care.facility.models.encounter_symptom import (
        ClinicalImpressionStatus,
        Symptom as SymptomChoices,
    )

    enable_auto_time = disable_auto_time(Condition)
    Symptom = apps.get_model("facility", "EncounterSymptom")

    symptom_sct_map = {
        SymptomChoices.FEVER: ("386661006", "Fever"),
        SymptomChoices.SORE_THROAT: ("267102003", "Sore throat"),
        SymptomChoices.COUGH: ("49727002", "Cough"),
        SymptomChoices.BREATHLESSNESS: ("267036007", "Breathlessness"),
        SymptomChoices.MYALGIA: ("68962001", "Myalgia"),
        SymptomChoices.ABDOMINAL_DISCOMFORT: ("43364001", "Abdominal discomfort"),
        SymptomChoices.VOMITING: ("249497008", "Vomiting"),
        SymptomChoices.SPUTUM: ("248596009", "Sputum"),
        SymptomChoices.NAUSEA: ("422587007", "Nausea"),
        SymptomChoices.CHEST_PAIN: ("29857009", "Chest pain"),
        SymptomChoices.HEMOPTYSIS: ("66857006", "Hemoptysis"),
        SymptomChoices.NASAL_DISCHARGE: ("64531003", "Nasal discharge"),
        SymptomChoices.BODY_ACHE: ("82991003", "Body ache"),
        SymptomChoices.DIARRHOEA: ("62315008", "Diarrhea"),
        SymptomChoices.PAIN: ("22253000", "General pain"),
        SymptomChoices.PEDAL_EDEMA: ("102576009", "Pedal edema"),
        SymptomChoices.WOUND: ("225552003", "Wound"),
        SymptomChoices.CONSTIPATION: ("14760008", "Constipation"),
        SymptomChoices.HEADACHE: ("25064002", "Headache"),
        SymptomChoices.BLEEDING: ("131148009", "Bleeding"),
        SymptomChoices.DIZZINESS: ("404640003", "Dizziness"),
        SymptomChoices.CHILLS: ("43724002", "Chills"),
        SymptomChoices.GENERAL_WEAKNESS: ("13791008", "General weakness"),
        SymptomChoices.IRRITABILITY: ("55929007", "Irritability"),
        SymptomChoices.CONFUSION: ("40917007", "Confusion"),
        SymptomChoices.ABDOMINAL_PAIN: ("21522001", "Abdominal pain"),
        SymptomChoices.JOINT_PAIN: ("57676002", "Joint pain"),
        SymptomChoices.REDNESS_OF_EYES: ("703630003", "Redness of eyes"),
        SymptomChoices.ANOREXIA: ("79890006", "Anorexia"),
        SymptomChoices.NEW_LOSS_OF_TASTE: ("36955009", "Loss of taste"),
        SymptomChoices.NEW_LOSS_OF_SMELL: ("44169009", "Loss of smell"),
        SymptomChoices.OTHERS: ("404684003", "Others"),
    }

    clinical_status_map = {
        ClinicalImpressionStatus.IN_PROGRESS: {
            "clinical_status": ClinicalStatusChoices.active,
            "verification_status": VerificationStatusChoices.provisional,
        },
        ClinicalImpressionStatus.COMPLETED: {
            "clinical_status": ClinicalStatusChoices.resolved,
            "verification_status": VerificationStatusChoices.confirmed,
        },
        ClinicalImpressionStatus.ENTERED_IN_ERROR: {
            "clinical_status": None,
            "verification_status": VerificationStatusChoices.entered_in_error,
        },
    }

    logger.debug("Migrating Patient Registrations")
    symptoms = (
        Symptom.objects.filter(
            consultation__migrated_emr_encounter_id__isnull=False,
        )
        .order_by("id")
        .select_related("consultation__patient", "consultation")
    )
    paginator = Paginator(symptoms, 3000)

    for page_number in paginator.page_range:
        page = paginator.page(page_number)
        bulk = []
        for symptom in page.object_list:
            if symptom.consultation.deleted:
                print("consultation deleted", symptom.consultation.id)
                continue
            if symptom.consultation.patient.deleted:
                print("patient deleted", symptom.consultation.patient.id)
                continue
            condition = Condition(
                **clinical_status_map.get(symptom.clinical_impression_status, {}),
                external_id=symptom.external_id,
                category="problem_list_item",
                code={
                    "system": "http://snomed.info/sct",
                    "code": symptom_sct_map.get(
                        symptom.symptom, symptom_sct_map[SymptomChoices.OTHERS]
                    )[0],
                    "display": symptom_sct_map.get(
                        symptom.symptom, symptom_sct_map[SymptomChoices.OTHERS]
                    )[1],
                },
                note=symptom.other_symptom,
                onset={
                    "onset_datetime": (
                        symptom.onset_date.replace(tzinfo=UTC).isoformat()
                        if symptom.onset_date
                        else None
                    ),
                    "onset_age": None,
                    "onset_string": None,
                    "note": None,
                },
                abatement={
                    "abatement_datetime": (
                        symptom.cure_date.replace(tzinfo=UTC).isoformat()
                        if symptom.cure_date
                        else None
                    ),
                    "abatement_age": None,
                    "abatement_string": None,
                    "note": None,
                },
                severity=None,
                body_site={},
                recorded_date=symptom.created_date,
                patient_id=symptom.consultation.patient.migrated_emr_patient_id,
                encounter_id=symptom.consultation.migrated_emr_encounter_id,
                created_by_id=symptom.created_by_id,
                updated_by_id=symptom.updated_by_id or symptom.created_by_id,
                created_date=symptom.created_date,
                modified_date=symptom.modified_date,
                meta={
                    "migration_id": MIGRATION_ID,
                },
            )
            if symptom.cure_date:
                condition.clinical_status = ClinicalStatusChoices.resolved
                condition.verification_status = VerificationStatusChoices.confirmed
            bulk.append(condition)
            logger.debug(f"Created Condition: {condition.id}")

        Condition.objects.bulk_create(bulk)

    enable_auto_time()


def reverse_migrate_symptoms(apps, schema_editor):
    Condition = apps.get_model("emr", "Condition")
    Condition.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0485_migrate_prescriptions_and_medicineadministrations"),
    ]

    operations = [
        migrations.RunPython(migrate_symptoms, migrations.RunPython.noop),
    ]
