# Generated by Django 5.1.4 on 2025-01-28 09:13

from django.db import migrations
from django.core.paginator import Paginator


MIGRATION_ID = 413390


def migrate_file_uploads(apps, schema_editor):
    OldFileUpload = apps.get_model("facility", "FileUpload")
    PatientRegistration = apps.get_model("facility", "PatientRegistration")
    PatientConsultation = apps.get_model("facility", "PatientConsultation")

    NewFileUpload = apps.get_model("emr", "FileUpload")


    #TODO: make idempotent
    paginator = Paginator(OldFileUpload.objects.filter(
        # upload_completed=True,
    ), 1000)

    for page_num in paginator.page_range:
        page = paginator.get_page(page_num)
        bulk_create_data = []
        for old_file_upload in page:
            if old_file_upload.type == 1: # patient
                file_category = "unspecified"
                file_type = "patient"
                try:
                    associating_id = PatientRegistration.objects.get(
                        id=old_file_upload.associating_id
                    ).external_id
                except PatientRegistration.DoesNotExist:
                    continue
            elif old_file_upload.type == 2: # consultation
                file_category = "unspecified"
                file_type = "encounter"
                try:
                    associating_id = PatientConsultation.objects.get(
                        id=old_file_upload.associating_id
                    ).external_id
                except PatientConsultation.DoesNotExist:
                    continue
            elif old_file_upload.type == 5: # discharge_summary
                file_category = "discharge_summary"
                file_type = "encounter"
                try:
                    associating_id = PatientConsultation.objects.get(
                        id=old_file_upload.associating_id
                    ).external_id
                except PatientConsultation.DoesNotExist:
                    continue
            elif old_file_upload.type == 7: # consent_record
                #TODO: add migration for consents
                continue
            else:
                continue

            bulk_create_data.append(
                NewFileUpload(
                    name=old_file_upload.name,
                    internal_name=old_file_upload.internal_name,
                    file_type=file_type,
                    file_category=file_category,
                    associating_id=associating_id,
                    archived_by=old_file_upload.archived_by,
                    archived_datetime=old_file_upload.archived_datetime,
                    is_archived=old_file_upload.is_archived,
                    archived_reason=old_file_upload.archived_reason,
                    upload_completed=old_file_upload.upload_completed,
                    created_by=old_file_upload.uploaded_by,
                    created_date=old_file_upload.created_date,
                    modified_date=old_file_upload.modified_date,
                    meta={"migration_id": MIGRATION_ID},
                )
            )
        NewFileUpload.objects.bulk_create(bulk_create_data)


def reverse_migrate_file_uploads(apps, schema_editor):
    NewFileUpload = apps.get_model("emr", "FileUpload")
    NewFileUpload.objects.filter(meta__contains={"migration_id": MIGRATION_ID}).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0485_migrate_prescriptions_and_medicineadministrations'),
    ]

    operations = [
        migrations.RunPython(migrate_file_uploads, reverse_migrate_file_uploads),
    ]
