# Generated by Django 6.0 on 2026-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0486_mobileotp_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='extensions',
            field=models.JSONField(default=dict),
        ),
    ]
