# Generated by Django 5.1.4 on 2025-01-28 09:13
import json
from pathlib import Path
from django.db import migrations
import logging
from django.core.paginator import Paginator

from care.emr.resources.condition.spec import VerificationStatusChoices
from care.facility.models.icd11_diagnosis import ConditionVerificationStatus
from care.emr.models import Condition
from care.facility.utils import disable_auto_time


disable_auto_time([Condition])

logger = logging.getLogger(__name__)


MIGRATION_ID = 158445695211


def load_diagnosis_map():
    pass


def migrate_diagnosis(apps, schema_editor):

    ConsultationDiagnosis = apps.get_model("facility", "ConsultationDiagnosis")

    verification_status_map = {
        ConditionVerificationStatus.UNCONFIRMED: VerificationStatusChoices.unconfirmed.value,
        ConditionVerificationStatus.PROVISIONAL: VerificationStatusChoices.provisional.value,
        ConditionVerificationStatus.DIFFERENTIAL: VerificationStatusChoices.differential.value,
        ConditionVerificationStatus.CONFIRMED: VerificationStatusChoices.confirmed.value,
        ConditionVerificationStatus.REFUTED: VerificationStatusChoices.refuted.value,
        ConditionVerificationStatus.ENTERED_IN_ERROR: VerificationStatusChoices.entered_in_error.value,
    }

    # TODO: add the last missing one
    icd11_to_icd10_map_file = Path(__file__).parent / "icd11toicd10.json"
    with icd11_to_icd10_map_file.open() as f:
        icd11_to_icd10_map = json.load(f)

    icd11_to_icd10_map = {int(k): v for k, v in icd11_to_icd10_map.items()}

    logger.debug("Migrating Patient Registrations")
    symptoms = (
        ConsultationDiagnosis.objects.filter(
            consultation__migrated_emr_encounter_id__isnull=False,
        )
        .exclude(consultation__deleted=True)
        .order_by("id")
        .select_related("consultation__patient", "consultation")
    )
    paginator = Paginator(symptoms, 2000)

    for page_number in paginator.page_range:
        page = paginator.page(page_number)
        bulk = []
        for diagnosis in page.object_list:
            if diagnosis.consultation.deleted:
                print("consultation deleted", diagnosis.consultation.id)
                continue
            if diagnosis.consultation.patient.deleted:
                print("patient deleted", diagnosis.consultation.patient.id)
                continue
            icd10 = icd11_to_icd10_map.get(diagnosis.diagnosis_id)
            condition = Condition(
                verification_status=verification_status_map.get(
                    diagnosis.verification_status
                ),
                clinical_status="unknown",
                external_id=diagnosis.external_id,  # if you are very unlucky, comment this line
                category="encounter_diagnosis",
                code={
                    "system": "http://hl7.org/fhir/sid/icd-10",
                    "code": icd10["c"],
                    "display": icd10["t"],
                },
                onset={},
                abatement={},
                severity=None,
                body_site={},
                recorded_date=diagnosis.created_date,
                patient_id=diagnosis.consultation.patient.migrated_emr_patient_id,
                encounter_id=diagnosis.consultation.migrated_emr_encounter_id,
                created_by_id=diagnosis.created_by_id
                # handling case for migrated data
                or diagnosis.consultation.created_by_id,
                updated_by_id=diagnosis.created_by_id
                # handling case for migrated data
                or diagnosis.consultation.created_by_id,
                created_date=diagnosis.created_date,
                modified_date=diagnosis.modified_date,
                meta={
                    "migration_id": MIGRATION_ID,
                },
            )
            bulk.append(condition)
            logger.debug(f"Created Condition: {condition.id}")
        Condition.objects.bulk_create(bulk)


def reverse_migrate_diagnosis(apps, schema_editor):
    Condition = apps.get_model("emr", "Condition")
    Condition.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0486_migrate_symptoms"),
    ]

    operations = [
        migrations.RunPython(migrate_diagnosis, reverse_migrate_diagnosis),
    ]
