# Generated by Django 5.1.4 on 2025-01-28 09:13
import uuid
import re
from django.db import migrations
from django.core.paginator import Paginator
from care.emr.models import FileUpload as NewFileUpload
from care.facility.utils import disable_auto_time


disable_auto_time([NewFileUpload])

MIGRATION_ID = 158445695212


def filter_id(id):
    try:
        return {"external_id": uuid.UUID(id)}
    except ValueError:
        try:
            return {"id": int(id)}
        except ValueError:
            return {}


def migrate_file_uploads(apps, schema_editor):
    OldFileUpload = apps.get_model("facility", "FileUpload")
    PatientRegistration = apps.get_model("facility", "PatientRegistration")
    PatientConsultation = apps.get_model("facility", "PatientConsultation")

    paginator = Paginator(
        OldFileUpload.objects.filter(
            # upload_completed=True,
        ).order_by("id"),
        3000,
    )

    for page_num in paginator.page_range:
        page = paginator.get_page(page_num)
        bulk_create_data = []
        for old_file_upload in page:
            if old_file_upload.file_type == 1:  # patient
                file_category = "unspecified"
                file_type = "patient"
                try:
                    associating_id = PatientRegistration.objects.get(
                        **filter_id(old_file_upload.associating_id)
                    ).external_id
                except PatientRegistration.DoesNotExist:
                    continue
            elif old_file_upload.file_type == 2:  # consultation
                file_category = "unspecified"
                file_type = "encounter"
                try:
                    associating_id = PatientConsultation.objects.get(
                        **filter_id(old_file_upload.associating_id)
                    ).external_id
                except PatientConsultation.DoesNotExist:
                    continue
            elif old_file_upload.file_type == 5:  # discharge_summary
                file_category = "discharge_summary"
                file_type = "encounter"
                try:
                    associating_id = PatientConsultation.objects.get(
                        external_id=old_file_upload.associating_id
                    ).external_id
                except PatientConsultation.DoesNotExist:
                    continue
            elif old_file_upload.file_type == 7:  # consent_record
                # TODO: add migration for consents
                continue
            else:  # Nobody uses these: other, sample_management, claim, communication, abdm_health_information
                continue

            file_name: str = old_file_upload.name
            # remove the double pdf extension
            file_name = file_name.removesuffix(".pdf")
            # replace banned character on windows and unix using regex with _
            file_name = re.sub(r'[<>:"/\\|?*]', "_", file_name)
            bulk_create_data.append(
                NewFileUpload(
                    external_id=old_file_upload.external_id,
                    name=file_name,
                    internal_name=old_file_upload.internal_name,
                    file_type=file_type,
                    file_category=file_category,
                    associating_id=associating_id,
                    archived_by_id=old_file_upload.archived_by_id,
                    archived_datetime=old_file_upload.archived_datetime,
                    is_archived=old_file_upload.is_archived,
                    archive_reason=old_file_upload.archive_reason,
                    upload_completed=old_file_upload.upload_completed,
                    created_by_id=old_file_upload.uploaded_by_id,
                    created_date=old_file_upload.created_date,
                    modified_date=old_file_upload.modified_date,
                    meta={"migration_id": MIGRATION_ID},
                )
            )
        NewFileUpload.objects.bulk_create(
            bulk_create_data,
            # ignore_conflicts=True, # uncomment this line if for some reason you want to run this migration again without reverse migration
        )


def reverse_migrate_file_uploads(apps, schema_editor):
    NewFileUpload = apps.get_model("emr", "FileUpload")
    NewFileUpload.objects.filter(meta__contains={"migration_id": MIGRATION_ID}).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0487_migrate_diagnosis"),
    ]

    operations = [
        migrations.RunPython(migrate_file_uploads, reverse_migrate_file_uploads),
    ]
