# Generated by Django 5.1.4 on 2025-01-28 09:13
import uuid
import re
from django.db import migrations
from django.core.paginator import Paginator
import logging
logger = logging.getLogger(__name__)


MIGRATION_ID = 158445695212


def filter_id(id):
    """
    Convert an identifier to a dictionary with a UUID or integer value.
    
    This function first attempts to convert the provided id to a UUID and returns it under the
    'external_id' key. If that conversion fails, it then attempts to convert the id to an integer,
    returning it under the 'id' key. If both conversions fail, an empty dictionary is returned.
    
    Parameters:
        id: The identifier to convert, typically a string representing a UUID or a numeric value.
        
    Returns:
        A dictionary containing the converted identifier, or an empty dictionary if conversion fails.
    """
    try:
        return {"external_id": uuid.UUID(id)}
    except ValueError:
        try:
            return {"id": int(id)}
        except ValueError:
            return {}


def is_valid_uuid(val):
    """
    Checks if the given value is a valid UUID.
    
    This function converts the input to a string and attempts to create a UUID object
    from it. It returns True if the conversion is successful, and False if a ValueError
    is raised during the conversion.
    """
    try:
        uuid.UUID(str(val))
        return True
    except ValueError:
        return False


def migrate_file_uploads(apps, schema_editor):
    """
    Migrates legacy file uploads to the new FileUpload model.
    
    Processes legacy file uploads in batches by retrieving records from the old model,
    determining each file's category and type based on its file_type, and associating it
    with the corresponding patient or consultation record. File names are sanitized by
    replacing banned characters before new records are bulk-created in the new model.
    Auto timestamping is temporarily disabled during this migration to preserve
    original timestamps, and records lacking valid associations or containing invalid
    identifiers are skipped.
    """
    from care.emr.models import FileUpload as NewFileUpload
    from care.facility.utils import disable_auto_time

    enable_auto_time = disable_auto_time(NewFileUpload)

    OldFileUpload = apps.get_model("facility", "FileUpload")
    PatientRegistration = apps.get_model("facility", "PatientRegistration")
    PatientConsultation = apps.get_model("facility", "PatientConsultation")

    paginator = Paginator(
        OldFileUpload.objects.filter(
            # upload_completed=True,
        ).order_by("id"),
        3000,
    )

    for page_num in paginator.page_range:
        page = paginator.get_page(page_num)
        bulk_create_data = []
        for old_file_upload in page:
            file_name: str = old_file_upload.name

            if old_file_upload.file_type == 1:  # patient
                file_category = "unspecified"
                file_type = "patient"
                try:
                    associating_id = PatientRegistration.objects.get(
                        **filter_id(old_file_upload.associating_id)
                    ).external_id
                except PatientRegistration.DoesNotExist:
                    continue
            elif old_file_upload.file_type == 2:  # consultation
                file_category = "unspecified"
                file_type = "encounter"
                try:
                    associating_id = PatientConsultation.objects.get(
                        **filter_id(old_file_upload.associating_id)
                    ).external_id
                except PatientConsultation.DoesNotExist:
                    continue
            elif old_file_upload.file_type == 5:  # discharge_summary
                # remove the double pdf extension
                file_name = file_name.removesuffix(".pdf")
                file_category = "discharge_summary"
                file_type = "encounter"
                try:
                    associating_id = PatientConsultation.objects.get(
                        external_id=old_file_upload.associating_id
                    ).external_id
                except PatientConsultation.DoesNotExist:
                    continue
            elif old_file_upload.file_type == 7:  # consent_record
                # the actual consent records will be migrated later
                if not is_valid_uuid(old_file_upload.associating_id):
                    # bad values with associating id in this format: consent-1717910XXXXXX
                    logger.warning(
                        f"Consent FileUpload {old_file_upload.id} has invalid associating_id {old_file_upload.associating_id}"
                    )
                    continue
                file_category = "consent_attachment"
                file_type = "encounter"
                associating_id = old_file_upload.associating_id
            else:  # Nobody uses these: other, sample_management, claim, communication, abdm_health_information
                continue

            # replace banned character on windows and unix using regex with _
            file_name = re.sub(r'[<>:"/\\|?*]', "_", file_name)
            bulk_create_data.append(
                NewFileUpload(
                    external_id=old_file_upload.external_id,
                    name=file_name,
                    internal_name=old_file_upload.internal_name,
                    file_type=file_type,
                    file_category=file_category,
                    associating_id=associating_id,
                    archived_by_id=old_file_upload.archived_by_id,
                    archived_datetime=old_file_upload.archived_datetime,
                    is_archived=old_file_upload.is_archived,
                    archive_reason=old_file_upload.archive_reason,
                    upload_completed=old_file_upload.upload_completed,
                    created_by_id=old_file_upload.uploaded_by_id,
                    created_date=old_file_upload.created_date,
                    modified_date=old_file_upload.modified_date,
                    meta={"migration_id": MIGRATION_ID},
                )
            )
        NewFileUpload.objects.bulk_create(
            bulk_create_data,
            # ignore_conflicts=True, # uncomment this line if for some reason you want to run this migration again without reverse migration
        )

    enable_auto_time()


def reverse_migrate_file_uploads(apps, schema_editor):
    """
    Reverses file uploads migration.
    
    Deletes FileUpload records created during the migration by filtering for entries 
    with a metadata field containing the migration ID.
    """
    NewFileUpload = apps.get_model("emr", "FileUpload")
    NewFileUpload.objects.filter(meta__contains={"migration_id": MIGRATION_ID}).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0487_migrate_diagnosis"),
    ]

    operations = [
        migrations.RunPython(migrate_file_uploads, reverse_migrate_file_uploads),
    ]
