# Generated by Django 5.1.4 on 2025-01-28 09:13
from decimal import Decimal
from typing import TYPE_CHECKING
import uuid

from django.db import migrations
from django.core.paginator import Paginator
from django.utils import timezone

from care.emr.resources.observation.spec import ObservationSpec, ObservationStatus
from care.emr.resources.questionnaire.spec import QuestionType

if TYPE_CHECKING:
    from care.facility.models.daily_round import DailyRound as DailyRoundModel


MIGRATION_ID = 158445695208

category_to_priority_map = {
    "Comfort": "as_needed",
    "Stable": "routine",
    "Moderate": "urgent",
    "Critical": "stat",
    "ActivelyDying": "as_needed",
}
taken_at = {
    "id": "ea98c82c-d4d0-4939-9637-40905569abf7",
    "link_id": "taken_at",
    "text": "Measured At",
    "type": "datetime",
}
temperature = {
    "id": "6dff0726-6e03-4353-ad8a-7f9563912c75",
    "link_id": "temperature",
    "text": "Temperature",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "8329-5",
        "display": "Body temperature - Core",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "degF",
        "display": "Degrees Fahrenheit",
    },
}
physical_examination_info = {
    "id": "ab54a7bc-f7dd-4dcf-bc55-7fafb7cfa9d3",
    "link_id": "physical_examination_info",
    "text": "Physical Examination Info",
    "type": "text",
}
other_details = {
    "id": "85cdf90b-20ff-40b0-bba0-1948a21367de",
    "link_id": "other_details",
    "text": "Other Details",
    "type": "text",
}
bowel_issue_map = {
    0: "No Difficulty",
    1: "Constipation",
    2: "Diarrhea",
}
bowel_issue = {
    "id": "70461562-8cc5-4da0-b725-3863b9b82b6b",
    "link_id": "bowel_issue",
    "text": "Bowel Finding",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "249562008",
        "display": "Bowel finding",
    },
    "answer_options": [{"value": v} for v in bowel_issue_map.values()],
}
bladder_drainage_map = {
    1: "Normal",
    2: "Condom Catheter",
    3: "Diaper",
    4: "Intermittent Catheter",
    5: "Continuous Indwelling Catheter",
    6: "Continuous Suprapubic Catheter",
    7: "Urostomy",
}
bladder_drainage = {
    "id": "75b2b346-857a-439a-a304-ba6b8b9ae163",
    "link_id": "bladder_drainage",
    "text": "Drainage of urinary bladder (procedure)",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "274423009",
        "display": "Drainage of urinary bladder (procedure)",
    },
    "answer_options": [{"value": v} for v in bladder_drainage_map.values()],
}
bladder_issue_map = {
    0: "No Issues",
    1: "Incontinence",
    2: "Retention",
    3: "Hesitancy",
}
bladder_issue = {
    "id": "f66e885f-7eb9-4664-adf2-55171190f104",
    "link_id": "bladder_issue",
    "text": "Urinary bladder finding",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "249585009",
        "display": "Urinary bladder finding",
    },
    "answer_options": [{"value": v} for v in bladder_issue_map.values()],
}
is_experiencing_dysuria = {
    "id": "9ae65acc-b85a-4704-a75a-5de5e4da3c19",
    "link_id": "is_experiencing_dysuria",
    "text": "Dysuria (finding)",
    "type": "boolean",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "49650001",
        "display": "Dysuria (finding)",
    },
}
urination_frequency_map = {
    1: "Normal",
    2: "Decreased",
    3: "Increased",
}
urination_frequency = {
    "id": "20d65439-7682-4f34-a015-694bb7932cbe",
    "link_id": "urination_frequency",
    "text": "Frequency of urination",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "364198000",
        "display": "Frequency of urination",
    },
    "answer_options": [{"value": v} for v in urination_frequency_map.values()],
}
sleep_map = {
    1: "Excessive",
    2: "Satisfactory",
    3: "Unsatisfactory",
    4: "No Sleep",
}
sleep = {
    "id": "23d05c4a-dd03-487b-82e5-210a060b645f",
    "link_id": "sleep",
    "text": "Sleep",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "247950007",
        "display": "Sleep behavior finding (finding)",
    },
    "answer_options": [{"value": v} for v in sleep_map.values()],
}
nutrition_route_map = {
    1: "Oral",
    2: "Ryles Tube",
    3: "Gastrostomy Or Jejunostomy",
    4: "Peg",
    5: "Parenteral Tubing Fluid",
    6: "Parenteral Tubing Tpn",
}
nutrition_route = {
    "id": "21427838-bb96-411a-abb3-b183411e99c2",
    "link_id": "nutrition_route",
    "text": "Management of route of enteral nutrition (procedure)",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "441421000124104",
        "display": "Management of route of enteral nutrition (procedure)",
    },
    "answer_options": [{"value": v} for v in nutrition_route_map.values()],
}
oral_issue_map = {
    0: "No Issue",
    1: "Dysphagia",
    2: "Odynophagia",
}
oral_issue = {
    "id": "ed4b195a-7858-44d4-9d43-da9579e4fcfb",
    "link_id": "oral_issue",
    "text": "Oral cavity problem (finding)",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "300255008",
        "display": "Oral cavity problem (finding)",
    },
    "answer_options": [{"value": v} for v in oral_issue_map.values()],
}
appetite_map = {
    1: "Increased",
    2: "Satisfactory",
    3: "Reduced",
    4: "No Taste For Food",
    5: "Cannot Be Assessed",
}
appetite = {
    "id": "be9f0a80-2bf3-49cf-a94a-ca5115aae5f8",
    "link_id": "appetite",
    "text": "Food appetite (function)",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "33911006",
        "display": "Food appetite (function)",
    },
    "answer_options": [{"value": v} for v in appetite_map.values()],
}
consciousness_level_map = {
    5: {"system": "http://snomed.info/sct", "code": "248234008", "display": "Alert"},
    10: {
        "system": "http://snomed.info/sct",
        "code": "300202002",
        "display": "Responds to Voice",
    },
    15: {
        "system": "http://snomed.info/sct",
        "code": "450847001",
        "display": "Responds to Pain",
    },
    20: {
        "system": "http://snomed.info/sct",
        "code": "422768004",
        "display": "Unresponsive",
    },
    25: {
        "system": "http://snomed.info/sct",
        "code": "40917007",
        "display": "Agitated or Confused",
    },
    30: {
        "system": "http://snomed.info/sct",
        "code": "225440008",
        "display": "Onset of Agitation and Confusion",
    },
}
consciousness_level = {
    "id": "04519e27-4db4-45db-8147-c3328c7da040",
    "link_id": "consciousness_level",
    "text": "Level of consciousness",
    "type": "string",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "80288-4",
        "display": "Level of consciousness",
    },
}
in_prone_position = {
    "id": "761f129d-37ce-4833-ac99-c50de1f0bd13",
    "link_id": "in_prone_position",
    "text": "Prone body position (finding)",
    "type": "boolean",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "1240000",
        "display": "Prone body position (finding)",
    },
}
left_pupil_size = {
    "id": "84beb4d5-6e70-4969-a971-9e6ad4a96211",
    "link_id": "left_pupil_size",
    "text": "Left pupil size",
    "type": "integer",
    "is_observation": True,
    "code": {
        "system": "http://snomed.info/sct",
        "code": "363953003",
        "display": "Size of Pupil",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm",
        "display": "millimeter",
    },
}
right_pupil_size = {
    "id": "c3ebfb80-de7a-4fea-83b9-28e85dadf7d0",
    "link_id": "right_pupil_size",
    "text": "Right pupil size",
    "type": "integer",
    "is_observation": True,
    "code": {
        "system": "http://snomed.info/sct",
        "code": "363953003",
        "display": "Size of Pupil",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm",
        "display": "millimeter",
    },
}
pupil_reaction_map = {
    0: "Unknown",
    5: "Brisk",
    10: "Sluggish",
    15: "Fixed",
    20: "Cannot Be Assessed",
}
left_pupil_light_reaction = {
    "id": "9c63e833-7a79-4168-85dc-25dce8b779ee",
    "link_id": "left_pupil_light_reaction",
    "text": "Left pupil light reaction",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "271733001",
        "display": "Pupil reaction",
    },
    "answer_options": [{"value": v} for v in pupil_reaction_map.values()],
}
right_pupil_light_reaction = {
    "id": "dba96650-ceb1-4f33-b6d9-7de9713ff85f",
    "link_id": "right_pupil_light_reaction",
    "text": "Right pupil light reaction",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "271733001",
        "display": "Pupil reaction",
    },
    "answer_options": [{"value": v} for v in pupil_reaction_map.values()],
}
glasgow_eye_open = {
    "id": "0c9f829a-d53f-4063-abb4-da36dc67a85f",
    "link_id": "glasgow_eye_open",
    "text": "Glasgow Coma Eye Opening Response",
    "type": "integer",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "281395000",
        "display": "Glasgow Coma Score eye opening subscore",
    },
}
glasgow_verbal_response = {
    "id": "4e0877c6-06f7-466b-a660-5f2a48cac383",
    "link_id": "glasgow_verbal_response",
    "text": "Glasgow Coma Verbal Response",
    "type": "integer",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "281397008",
        "display": "Glasgow Coma Score verbal response subscore",
    },
}
glasgow_motor_response = {
    "id": "91a37cc8-a69f-4908-82d0-53187a6bd258",
    "link_id": "glasgow_motor_response",
    "text": "Glasgow Coma Score Motor Response",
    "type": "integer",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "281396004",
        "display": "Glasgow Coma Score motor response subscore",
    },
}
glasgow_total_calculated = {
    "id": "a6f30654-fba2-40c1-84c7-aa3931818241",
    "link_id": "glasgow_total_calculated",
    "text": "Glasgow Coma Score",
    "type": "integer",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "248241002",
        "display": "Glasgow coma score",
    },
}
limb_response_map = {
    0: "Unknown",
    5: "Strong",
    10: "Moderate",
    15: "Weak",
    20: "Flexion",
    25: "Extension",
    30: "None",
}
limb_response_upper_extremity_left = {
    "id": "63940bbc-b78e-4f1a-810c-c01239cde60f",
    "link_id": "limb_response_upper_extremity_left",
    "text": "Limb Response Upper Extremity Left",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "249948009",
        "display": " Grade of muscle power",
    },
    "answer_options": [{"value": v} for v in limb_response_map.values()],
}
limb_response_upper_extremity_right = {
    "id": "00ad1c4e-cb86-4862-b984-f8f2062f47cd",
    "link_id": "limb_response_upper_extremity_right",
    "text": "Limb Response Upper Extremity Right",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "249948009",
        "display": " Grade of muscle power",
    },
    "answer_options": [{"value": v} for v in limb_response_map.values()],
}
limb_response_lower_extremity_left = {
    "id": "b0958d7f-4033-44c0-98bf-b6d49a060667",
    "link_id": "limb_response_lower_extremity_left",
    "text": "Limb Response Lower Extremity Left",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "249948009",
        "display": " Grade of muscle power",
    },
    "answer_options": [{"value": v} for v in limb_response_map.values()],
}
limb_response_lower_extremity_right = {
    "id": "da6c8868-48bc-403c-bb6c-9fefdf21e542",
    "link_id": "limb_response_lower_extremity_right",
    "text": "Limb Response Lower Extremity Right",
    "type": "choice",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "249948009",
        "display": " Grade of muscle power",
    },
    "answer_options": [{"value": v} for v in limb_response_map.values()],
}
bp_systolic = {
    "id": "479b1a64-6397-4f10-80b2-5541e831ee1",
    "link_id": "bp.systolic",
    "text": "Systolic",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://snomed.info/sct",
        "code": "271649006",
        "display": "Systolic blood pressure",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm[Hg]",
        "display": "mm[Hg]",
    },
}
bp_diastolic = {
    "id": "7c7ffea6-e236-4b03-8eed-1ebc0aa2c28c",
    "link_id": "bp.diastolic",
    "text": "Diastolic",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://snomed.info/sct",
        "code": "271650006",
        "display": "Diastolic blood pressure",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm[Hg]",
        "display": "mm[Hg]",
    },
}
bp = {
    "id": "90da957f-d4b7-4faa-9295-989faa5f0cb6",
    "link_id": "bp",
    "text": "Blood Pressure",
    "type": "group",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "35094-2",
        "display": "Blood Pressure Panel",
    },
    "questions": [bp_systolic, bp_diastolic],
}
pulse = {
    "id": "4e6d3fa8-72e2-4465-99e7-46eafb43186a",
    "link_id": "pulse",
    "text": "Pulse",
    "type": "integer",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "8867-4",
        "display": "Heart rate",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "{beats}/min",
        "display": "Beats / minute",
    },
}
resp = {
    "id": "952adb24-8915-4c7c-a086-b6105cdcb5d6",
    "link_id": "resp",
    "text": "Respiratory Rate",
    "type": "integer",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "9279-1",
        "display": "Respiratory rate",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "{breaths}/min",
        "display": "Breaths / minute",
    },
}
ventilator_spo2 = {
    "id": "601652b2-fd5a-47ff-96a7-3fb2d4f5505f",
    "link_id": "ventilator_spo2",
    "text": "SpO2 (Measurement)",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://snomed.info/sct",
        "code": "431314004",
        "display": "SpO2 (Measurement)",
    },
    "unit": {"system": "http://unitsofmeasure.org", "code": "%", "display": "%"},
}
rhythm_map = {
    0: {"system": "http://snomed.info/sct", "code": "261665006", "display": "Unknown"},
    5: {"system": "http://snomed.info/sct", "code": "17854005", "display": "Regular"},
    10: {
        "system": "http://snomed.info/sct",
        "code": "49608001",
        "display": "Irregular",
    },
}
rhythm = {
    "id": "a1c46a19-f2c1-4e46-a13d-7829588b8a49",
    "link_id": "rhythm",
    "text": "Rhythm",
    "type": "choice",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "67519-9",
        "display": "Cardiac Rhythm",
    },
}
ventilator_interface_map = {
    0: "Unknown",
    5: "Invasive",
    10: "Non Invasive",
    15: "Oxygen Support",
}
ventilator_interface = {
    "id": "007f9aa0-52e6-47cf-8ce9-b85e7237ece8",
    "link_id": "ventilator_interface",
    "text": "Ventilator interface",
    "type": "choice",
    "answer_options": [{"value": v} for v in ventilator_interface_map.values()],
}
ventilator_mode_map = {
    0: "Unknown",
    5: "VCV",
    10: "PCV",
    15: "PRVC",
    20: "APRV",
    25: "VC SIMV",
    30: "PC SIMV",
    40: "PRVC SIMV",
    45: "ASV",
    50: "PSV",
}
ventilator_mode = {
    "id": "a9c590cd-c696-45e6-be9b-7d5e1910b096",
    "link_id": "ventilator_mode",
    "text": "Ventilator mode",
    "type": "choice",
    "answer_options": [{"value": v} for v in ventilator_mode_map.values()],
}
ventilator_peep = {
    "id": "3637b296-6e8b-4d9f-a4c4-4aa962c49c96",
    "link_id": "ventilator_peep",
    "text": "Ventilator PEEP",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "250854009",
        "display": "Positive end expiratory pressure",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "cm[H2O]",
        "display": "cm[H2O]",
    },
}
ventilator_pip = {
    "id": "c8c832c5-1463-49fc-9556-c308d27cfe5d",
    "link_id": "ventilator_pip",
    "text": "Ventilator PIP",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "27913002",
        "display": "Maximum inspiratory pressure",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "cm[H2O]",
        "display": "cm[H2O]",
    },
}
ventilator_mean_airway_pressure = {
    "id": "c104e988-5ad1-4deb-ab7b-8f3df7564382",
    "link_id": "ventilator_mean_airway_pressure",
    "text": "Ventilator Mean Airway Pressure",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "698821009",
        "display": "Mean inspiratory airway pressure",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "cm[H2O]",
        "display": "cm[H2O]",
    },
}
ventilator_resp_rate = {
    "id": "d26b0041-cc21-4c48-bb68-f70eafef2269",
    "link_id": "ventilator_resp_rate",
    "text": "Ventilator Resp Rate",
    "type": "integer",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "250876000",
        "display": "Ventilator rate",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "{breaths}/min",
        "display": "Breaths / minute",
    },
}
ventilator_pressure_support = {
    "id": "e0c75a3b-9c69-415a-90b1-c85b0f0653ae",
    "link_id": "ventilator_pressure_support",
    "text": "Ventilator Pressure Support",
    "type": "integer",
}
ventilator_tidal_volume = {
    "id": "5011f08d-9a53-4b9b-95c1-ce015cf35ba3",
    "link_id": "ventilator_tidal_volume",
    "text": "Ventilator Tidal Volume",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "250874002",
        "display": "Ventilator delivered tidal volume",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL",
        "display": "milliliter",
    },
}
ventilator_oxygen_modality_map = {
    0: "Unknown",
    5: "Nasal Prongs",
    10: "Simple Face Mask",
    15: "Non Rebreathing Mask",
    20: "High Flow Nasal Cannula",
}
ventilator_oxygen_modality = {
    "id": "44505bfa-1fde-4051-a035-bbfa137379c0",
    "link_id": "ventilator_oxygen_modality",
    "text": "Oxygen Modality",
    "type": "choice",
    "answer_options": [{"value": v} for v in ventilator_oxygen_modality_map.values()],
}
ventilator_oxygen_modality_oxygen_rate = {
    "id": "199a0af3-3662-4d41-8c3b-03e28f02ecb3",
    "link_id": "ventilator_oxygen_modality_oxygen_rate",
    "text": "Ventilator Oxygen Modality Oxygen Rate",
    "type": "integer",
}
ventilator_oxygen_modality_flow_rate = {
    "id": "9f8380ad-d97f-4ce4-a9e3-da96a8d626fa",
    "link_id": "ventilator_oxygen_modality_flow_rate",
    "text": "Ventilator Oxygen Modality Flow Rate",
    "type": "integer",
}
ventilator_fio2 = {
    "id": "82cabbbf-ed73-4eb5-8c0d-897c8e1759e7",
    "link_id": "ventilator_fio2",
    "text": "Ventilator FiO2",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "250774007",
        "display": "Inspired oxygen concentration",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "%",
        "display": "%",
    },
}
etco2 = {
    "id": "99371031-2c2e-4852-8fbf-dff63ddec941",
    "link_id": "etco2",
    "text": "End Tidal CO2",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "250790007",
        "display": "End tidal carbon dioxide tension",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm[Hg]",
        "display": "mm[Hg]",
    },
}
bilateral_air_entry = {
    "id": "955cbbf6-8a62-4d93-9a6c-02b61eef79d6",
    "link_id": "bilateral_air_entry",
    "text": "Bilateral Air Entry",
    "type": "boolean",
}
ph = {
    "id": "432269bb-079c-4b57-90e0-8a90026bd0f3",
    "link_id": "ph",
    "text": "pH",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://snomed.info/sct",
        "code": "27051004",
        "display": "pH (Measurement)",
    },
}
pco2 = {
    "id": "8e1dff8c-1bb2-4586-8f43-540a1e1c5f98",
    "link_id": "pco2",
    "text": "pCO2",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "2019-8",
        "display": "Carbon dioxide [Partial pressure] in Arterial blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm[Hg]",
        "display": "mm[Hg]",
    },
}
po2 = {
    "id": "66d1687e-3dd4-4182-bd13-6513aeb862a5",
    "link_id": "po2",
    "text": "pO2",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "2703-7",
        "display": "Oxygen [Partial pressure] in Arterial blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mm[Hg]",
        "display": "mm[Hg]",
    },
}
hco3 = {
    "id": "8ed7e75a-d09f-4386-8116-0b5a6dd6711a",
    "link_id": "hco3",
    "text": "HCO3",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "1960-4",
        "display": "Bicarbonate [Moles/volume] in Arterial blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mmol/L",
        "display": "mmol/L",
    },
}
base_excess = {
    "id": "5e88df2f-1ea9-4151-bd33-fefca6d95866",
    "link_id": "base_excess",
    "text": "Base Excess",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "1925-7",
        "display": "Base excess in Arterial blood by calculation",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mmol/L",
        "display": "mmol/L",
    },
}
lactate = {
    "id": "cde12210-c247-4ebf-9416-3ae4d542e5ed",
    "link_id": "lactate",
    "text": "Lactate",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "30242-2",
        "display": "Lactate [Mass/volume] in Arterial blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mmol/L",
        "display": "mmol/L",
    },
}
sodium = {
    "id": "c0573cf3-4072-4354-8e87-4a5640afd739",
    "link_id": "sodium",
    "text": "Sodium",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "32717-1",
        "display": "Sodium [Moles/volume] in Arterial blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mmol/L",
        "display": "mmol/L",
    },
}
potassium = {
    "id": "72042085-b0c4-42e5-be3b-ebc16bea1a48",
    "link_id": "potassium",
    "text": "Potassium",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "32713-0",
        "display": "Potassium [Moles/volume] in Arterial blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mmol/L",
        "display": "mmol/L",
    },
}
blood_sugar_level = {
    "id": "03b3d263-a4d4-4d82-935e-0901c6b9722a",
    "link_id": "blood_sugar_level",
    "text": "Blood Sugar Level",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "2339-0",
        "display": "Glucose [Mass/volume] in Blood",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mg/dL",
        "display": "mg/dL",
    },
}
insulin_intake_frequency_map = {
    0: "Unknown",
    5: "Once a day",
    10: "Twice a day",
    15: "Thrice a day",
}
insulin_intake_dose = {
    "id": "b3b6da97-a79e-4757-93da-aa4d121b0308",
    "link_id": "insulin_intake_dose",
    "text": "Insulin Intake Dose",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "4287-9",
        "display": "Insulin regular [Mass] of Dose",
    },
}
infusions_map = {
    "Adrenalin": {
        "system": "http://snomed.info/sct",
        "code": "387362001",
        "display": "Adrenalin (Epinephrine (substance))",
    },
    "Noradrenalin": {
        "system": "http://snomed.info/sct",
        "code": "45555007",
        "display": "Noradrenlin (Norepinephrine (substance))",
    },
    "Vasopressin": {
        "system": "http://snomed.info/sct",
        "code": "77671006",
        "display": "Vasopression (Antidiuretic hormone (substance))",
    },
    "Dopamine": {
        "system": "http://snomed.info/sct",
        "code": "412383006",
        "display": "Dopamine (substance)",
    },
    "Dobutamine": {
        "system": "http://snomed.info/sct",
        "code": "387145002",
        "display": "Dobutamine (substance)",
    },
}
infusions = {
    "id": "117bb3c9-1bb0-48c0-9bed-a3a8cdd6d4d2",
    "link_id": "infusions",
    "text": "Infusions",
    "type": "quantity",
    "is_observation": True,
    "repeats": True,
    "code": {
        "system": "http://loinc.org",
        "code": "8982-1",
        "display": "Type of Fluid intake intravascular substance",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL",
        "display": "ml",
    },
}
iv_fluids_map = {
    "RL": {
        "system": "http://snomed.info/sct",
        "code": "1197547008",
        "display": "RL Infusion",
    },
    "NS": {
        "system": "http://snomed.info/sct",
        "code": "313418004",
        "display": "NS (Continuous infusion of normal saline (procedure))",
    },
    "DNS": {
        "system": "http://snomed.info/sct",
        "code": "313419007",
        "display": "DNS (Continuous infusion of dextrose saline (procedure))",
    },
}
iv_fluids = {
    "id": "18746744-4998-4179-8140-6d94712315ff",
    "link_id": "iv_fluids",
    "text": "IV Fluids",
    "type": "decimal",
    "is_observation": True,
    "repeats": True,
    "code": {
        "system": "http://loinc.org",
        "code": "8982-1",
        "display": "Type of Fluid intake intravascular substance",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL",
        "display": "ml",
    },
}
feeds_map = {
    "Ryles Tube": {
        "system": "http://care.ohc.network",
        "code": "Ryles Tube",
        "display": "Ryles Tube",
    },
    "Normal Feed": {
        "system": "http://care.ohc.network",
        "code": "Normal Feed",
        "display": "Normal Feed",
    },
}
feeds = {
    "id": "e18f56b7-6cff-47f2-b408-48b9b26864a3",
    "link_id": "feeds",
    "text": "Feeds",
    "type": "decimal",
    "is_observation": True,
    "repeats": True,
    "code": {
        "system": "http://loinc.org",
        "code": "8933-4",
        "display": "Type of Enteral tube",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL",
        "display": "ml",
    },
}
total_intake_calculated = {
    "id": "eebff1a7-768d-447f-a35f-d79542565326",
    "link_id": "total_intake_calculated",
    "text": "Total Intake",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "9103-3",
        "display": "Fluid intake total Measured",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL",
        "display": "ml",
    },
}
output_map = {
    "Urine": {
        "system": "http://care.ohc.network",
        "code": "Urine",
        "display": "Urine",
    },
    "Ryles Tube Aspiration": {
        "system": "http://care.ohc.network",
        "code": "Ryles Tube Aspiration",
        "display": "Ryles Tube Aspiration",
    },
    "ICD": {
        "system": "http://care.ohc.network",
        "code": "ICD",
        "display": "ICD",
    },
    "Abdominal Drain": {
        "system": "http://care.ohc.network",
        "code": "Abdominal Drain",
        "display": "Abdominal Drain",
    },
}
output = {
    "id": "49c3ee39-0bcb-44e8-88ec-2286f88164e1",
    "link_id": "output",
    "text": "Output",
    "type": "decimal",
    "is_observation": True,
    "repeats": True,
    "code": {
        "system": "http://loinc.org",
        "code": "9263-5",
        "display": "Fluid output route",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL",
        "display": "ml",
    },
}
total_output_calculated = {
    "id": "c7885353-ac40-42bb-9cfa-f7098d7e37c7",
    "link_id": "total_output_calculated",
    "text": "Total Output",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "9257-7",
        "display": "Fluid output total Measured",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL/h",
        "display": "mL/h",
    },
}
dialysis_fluid_balance = {
    "id": "30fc0c49-959b-40e4-ae9d-64164cc9afe8",
    "link_id": "dialysis_fluid_balance",
    "text": "Dialysis Fluid Balance",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "251856003",
        "display": "Fluid balance status (observable entity)",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL/h",
        "display": "mL/h",
    },
}
dialysis_net_balance = {
    "id": "a2946db5-992a-4ba9-94c7-9baf4732d3a6",
    "link_id": "dialysis_net_balance",
    "text": "Dialysis Net Balance",
    "type": "decimal",
    "code": {
        "system": "http://snomed.info/sct",
        "code": "251856003",
        "display": "Fluid balance status (observable entity)",
    },
    "unit": {
        "system": "http://unitsofmeasure.org",
        "code": "mL/h",
        "display": "mL/h",
    },
}
total_output_calculated = {
    "id": "3e6eb374-4cb1-4389-bd3e-086c0145a896",
    "link_id": "total_output_calculated",
    "text": "Total Output",
    "type": "decimal",
    "is_observation": True,
    "code": {
        "system": "http://loinc.org",
        "code": "9257-7",
        "display": "Fluid output total Measured",
    },
}
human_body_map = {  # TODO: complete the rest of the values
    "AnteriorHead": {
        "system": "http://snomed.info/sct",
        "code": "69536005",
        "display": "Head structure",
    },
    "AnteriorNeck": {
        "system": "http://snomed.info/sct",
        "code": "45048000",
        "display": "Neck structure",
    },
    "AnteriorRightShoulder": {
        "system": "http://snomed.info/sct",
        "code": "368106002",
        "display": "Entire right shoulder region",
    },
    "AnteriorRightChest": {
        "system": "http://snomed.info/sct",
        "code": "771319006",
        "display": "Structure of right half of chest wall",
    },
    "AnteriorRightArm": {
        "system": "http://snomed.info/sct",
        "code": "59126009",
        "display": "Entire right upper arm",
    },
    "AnteriorRightForearm": {
        "system": "http://snomed.info/sct",
        "code": "368224007",
        "display": "Entire right forearm",
    },
    "AnteriorRightHand": {
        "system": "http://snomed.info/sct",
        "code": "78791008",
        "display": "Structure of right hand",
    },
    "AnteriorLeftHand": {
        "system": "http://snomed.info/sct",
        "code": "368456002",
        "display": "Entire left hand",
    },
    "AnteriorLeftChest": {
        "system": "http://snomed.info/sct",
        "code": "771318003",
        "display": "Structure of left half of chest wall",
    },
    "AnteriorLeftShoulder": {
        "system": "http://snomed.info/sct",
        "code": "368107006",
        "display": "Entire left shoulder region",
    },
    "AnteriorLeftArm": {
        "system": "http://snomed.info/sct",
        "code": "72098002",
        "display": "Entire left upper arm",
    },
    "AnteriorLeftForearm": {
        "system": "http://snomed.info/sct",
        "code": "368225008",
        "display": "Entire left forearm",
    },
    "AnteriorRightFoot": {
        "system": "http://snomed.info/sct",
        "code": "239830003",
        "display": "Entire right foot",
    },
    "AnteriorLeftFoot": {
        "system": "http://snomed.info/sct",
        "code": "239919000",
        "display": "Entire left foot",
    },
    "AnteriorRightLeg": {
        "system": "http://snomed.info/sct",
        "code": "213289002",
        "display": "Entire right lower leg",
    },
    "AnteriorLowerChest": {
        "system": "http://snomed.info/sct",
        "code": "731489009",
        "display": "Entire lower chest wall",
    },
    "AnteriorAbdomen": {
        "system": "http://snomed.info/sct",
        "code": "302553009",
        "display": "Entire abdomen",
    },
    "AnteriorLeftLeg": {
        "system": "http://snomed.info/sct",
        "code": "213384005",
        "display": "Entire left lower leg",
    },
    "AnteriorRightThigh": None,
    "AnteriorLeftThigh": {
        "system": "http://snomed.info/sct",
        "code": "209672000",
        "display": "Entire left thigh",
    },
    "AnteriorGroin": {
        "system": "http://snomed.info/sct",
        "code": "26893007",
        "display": "Inguinal region structure",
    },
    "PosteriorHead": None,
    "PosteriorNeck": None,
    "PosteriorLeftChest": None,
    "PosteriorRightChest": None,
    "PosteriorAbdomen": None,
    "PosteriorLeftShoulder": None,
    "PosteriorRightShoulder": None,
    "PosteriorLeftArm": None,
    "PosteriorLeftForearm": None,
    "PosteriorLeftHand": None,
    "PosteriorRightArm": None,
    "PosteriorRightForearm": None,
    "PosteriorRightHand": None,
    "PosteriorLeftThighAndButtock": {
        "system": "http://snomed.info/sct",
        "code": "209672000+723979003",
        "display": "Entire left thigh + Structure of left buttock",
    },
    "PosteriorRightThighAndButtock": {
        "system": "http://snomed.info/sct",
        "code": "209570001+723980000",
        "display": "Entire right thigh + Structure of right buttock",
    },
    "PosteriorLeftLeg": None,
    "PosteriorRightLeg": None,
    "PosteriorLeftFoot": None,
    "PosteriorRightFoot": None,
}
pain_scale_enhanced = {
    "id": "486ae997-ff3e-4a6b-8d7d-2102bf8ec6b9",
    "link_id": "pain_scale_enhanced",
    "text": "Pain Scale Enhanced",
    "type": "decimal",
    "is_observation": True,
    "repeats": True,
    "code": {
        "system": "http://loinc.org",
        "code": "38208-5",
        "display": "Pain severity",
    },
}
# TODO: add pressure sore and nursing
# pressure_sore = {
#     "id": "5b34b0d3-12a0-4fc4-9f86-d5bdd3d61bb8",
# }
# nursing = {
#     "id": "ae7139f5-ce54-4819-a680-e612f410ec57",
# }


brief_update_questions = [
    taken_at,
    physical_examination_info,
    other_details,
    {
        "id": "6e3d332e-f013-47bd-b80c-e7da636ddf16",
        "link_id": "vitals",
        "text": "Vitals",
        "type": "group",
        "questions": [
            bp,
            pulse,
            ventilator_spo2,
            temperature,
            resp,
            rhythm,
            consciousness_level,
        ],
    },
]


def create_observation_spec(questionnaire, responses, parent_id=None):
    spec = {}
    spec["status"] = ObservationStatus.final.value
    spec["value_type"] = questionnaire["type"]
    if "category" in questionnaire:
        spec["category"] = questionnaire["category"]
    if "code" in questionnaire:
        spec["main_code"] = questionnaire["code"]
    if questionnaire["type"] == QuestionType.group.value:
        spec["id"] = str(uuid.uuid4())
        spec["effective_datetime"] = timezone.now()
        spec["value"] = {}
        return [spec]
    observations = []
    if (
        responses
        and questionnaire["id"] in responses
        and responses[questionnaire["id"]].values
        and responses[questionnaire["id"]].values[0]
    ):
        for value in responses[questionnaire["id"]].values:
            observation = spec.copy()
            observation["id"] = str(uuid.uuid4())
            if questionnaire["type"] == QuestionType.choice.value and value.code:
                observation["value"] = value.value_code.model_dump(
                    exclude_defaults=True
                )

            elif (
                questionnaire["type"] == QuestionType.quantity.value
                and value.value_quantity
            ):
                observation["value"] = value.value_quantity.model_dump(
                    exclude_defaults=True
                )
            elif value:
                observation["value"] = {"value": value.value}
                if "unit" in questionnaire:
                    observation["value"]["unit"] = questionnaire["unit"]
            if responses[questionnaire["id"]].note:
                observation["note"] = responses[questionnaire["id"]].note
        if parent_id:
            observation["parent"] = parent_id
        observation["effective_datetime"] = timezone.now()
        observations.append(observation)
    return observations


def convert_to_observation_spec(questionnaire_obj, responses, parent_id=None):
    constructed_observation_mapping = []
    for question in questionnaire_obj.get("questions", []):
        if question["type"] == QuestionType.group.value:
            observation = create_observation_spec(question, responses, parent_id)
            sub_mapping = convert_to_observation_spec(
                question, responses, observation[0]["id"]
            )
            if sub_mapping:
                constructed_observation_mapping.extend(observation)
                constructed_observation_mapping.extend(sub_mapping)
        elif question.get("code"):
            constructed_observation_mapping.extend(
                create_observation_spec(question, responses, parent_id)
            )

    return constructed_observation_mapping


def null_or_empty(value):
    return value is None or value == ""


def migrate_daily_rounds(apps, schema_editor):
    from care.facility.utils import disable_auto_time
    from care.emr.models import (
        Questionnaire,
        QuestionnaireResponse,
        Observation,
        Encounter,
        QuestionnaireOrganization,
        Organization,
        QuestionnaireTag,
    )

    enable_auto_time = disable_auto_time(
        Questionnaire,
        QuestionnaireResponse,
        Observation,
        Encounter,
        QuestionnaireOrganization,
        Organization,
        QuestionnaireTag,
    )

    DailyRound = apps.get_model("facility", "DailyRound")

    # TODO: create questionnaire tags and link to these
    # I dont know why these are hardcoded in frontend, but it doesn't work without it so we will also hardcode it here
    encounter_actions_tag, _ = QuestionnaireTag.objects.get_or_create(
        slug="encounter_actions",
        defaults={
            "name": "Encounter Actions",
        },
    )
    questionnaire_defaults = {
        "status": "retired",
        "subject_type": "encounter",
        "tags": [encounter_actions_tag.id],
        "meta": {
            "migration_id": MIGRATION_ID,
        },
    }
    bulk_questionnaire_root_link = []
    automated_log_update_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="automated_daily_round_53187a6bd",
        defaults={
            **questionnaire_defaults,
            "title": "Automated Log Update",
            "description": "Automated Log Update",
            "questions": [
                taken_at,
                {
                    "id": "6e3d332e-f013-47bd-b80c-e7da636ddf16",
                    "link_id": "vitals",
                    "text": "Vitals",
                    "type": "group",
                    "questions": [bp, pulse, ventilator_spo2, temperature, resp],
                },
            ],
        },
    )
    if created:
        bulk_questionnaire_root_link.append(automated_log_update_questionnaire.id)

    brief_update_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="brief_update_d4d49188",
        defaults={
            **questionnaire_defaults,
            "title": "Brief Update",
            "description": "Brief Update",
            "questions": brief_update_questions,
        },
    )

    if created:
        bulk_questionnaire_root_link.append(brief_update_questionnaire.id)

    doctors_log_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="doctors_log_ca980364",
        defaults={
            **questionnaire_defaults,
            "title": "Progress Note",
            "description": "Progress Note",
            "questions": brief_update_questions,
        },
    )

    if created:
        bulk_questionnaire_root_link.append(doctors_log_questionnaire.id)

    telemedicine_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="telemedicine_6102db82",
        defaults={
            **questionnaire_defaults,
            "title": "Tele-medicine Log",
            "description": "Tele-medicine Log",
            "questions": brief_update_questions,
        },
    )

    community_nurse_log_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="community_nurse_log_17984f92",
        defaults={
            **questionnaire_defaults,
            "title": "Community Nurse's Log",
            "description": "Community Nurse's Log",
            "questions": [
                taken_at,
                physical_examination_info,
                other_details,
                {
                    "id": "b3f117b0-70fd-4360-a56c-8de2aca3368b",
                    "link_id": "routine",
                    "text": "Routine",
                    "type": "group",
                    "questions": [
                        sleep,
                        bowel_issue,
                        {
                            "id": "e80e74ca-ff1f-4616-8362-78fe6e1ede5f",
                            "link_id": "bladder",
                            "text": "Bladder",
                            "type": "group",
                            "questions": [
                                bladder_drainage,
                                bladder_issue,
                                is_experiencing_dysuria,
                                urination_frequency,
                            ],
                        },
                        {
                            "id": "2d073b3a-cf59-49c3-9a20-994525f5bccc",
                            "link_id": "nutrition",
                            "text": "Nutrition",
                            "type": "group",
                            "questions": [
                                nutrition_route,
                                oral_issue,
                                appetite,
                            ],
                        },
                    ],
                },
                {
                    "id": "6e3d332e-f013-47bd-b80c-e7da636ddf16",
                    "link_id": "vitals",
                    "text": "Vitals",
                    "type": "group",
                    "questions": [bp, pulse, ventilator_spo2, blood_sugar_level],
                },
                # nursing, #TODO: enable this
            ],
        },
    )

    if created:
        bulk_questionnaire_root_link.append(community_nurse_log_questionnaire.id)

    detailed_update_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="detailed_log_update_1dee545a",
        defaults={
            **questionnaire_defaults,
            "title": "Detailed Update",
            "description": "Detailed Update",
            "questions": [
                taken_at,
                {
                    "id": "1ce721d5-1223-44cc-b44d-382b68479ad2",
                    "link_id": "basic_details",
                    "text": "Basic Details",
                    "type": "group",
                    "questions": [
                        physical_examination_info,
                        other_details,
                    ],
                },
                {
                    "id": "6e3d332e-f013-47bd-b80c-e7da636ddf16",
                    "link_id": "vitals",
                    "text": "Vitals",
                    "type": "group",
                    "questions": [
                        bp,
                        pulse,
                        ventilator_spo2,
                        temperature,
                        resp,
                        rhythm,
                        pain_scale_enhanced,
                    ],
                },
                {
                    "id": "755d760d-7abe-46ae-a244-fa7d0a5cbc9f",
                    "link_id": "neurological_monitoring",
                    "text": "Neurological Monitoring",
                    "type": "group",
                    "questions": [
                        in_prone_position,
                        consciousness_level,
                        {
                            "id": "26c512df-b5cd-4e4b-ad14-cfb3526d3132",
                            "link_id": "pupil",
                            "text": "Pupil",
                            "type": "group",
                            "questions": [
                                left_pupil_size,
                                left_pupil_light_reaction,
                                right_pupil_size,
                                right_pupil_light_reaction,
                            ],
                        },
                        {
                            "id": "b8f7809b-e0f0-4b72-9a6a-8bb1b368987e",
                            "link_id": "glasgow_coma_scale",
                            "text": "Glasgow Coma Scale",
                            "type": "group",
                            "questions": [
                                glasgow_eye_open,
                                glasgow_verbal_response,
                                glasgow_motor_response,
                                glasgow_total_calculated,
                            ],
                        },
                        {
                            "id": "ff987ceb-2c22-417b-8fd9-55d066125021",
                            "link_id": "limb_response",
                            "text": "Limb Response",
                            "type": "group",
                            "questions": [
                                limb_response_upper_extremity_left,
                                limb_response_upper_extremity_right,
                                limb_response_lower_extremity_left,
                                limb_response_lower_extremity_right,
                            ],
                        },
                    ],
                },
                {
                    "id": "c9a2739f-2e7e-4aaa-923c-89f161b1c87c",
                    "link_id": "respiratory_support",
                    "text": "Respiratory Support",
                    "type": "group",
                    "questions": [
                        bilateral_air_entry,
                        etco2,
                        ventilator_interface,
                        ventilator_mode,
                        ventilator_peep,
                        ventilator_pip,
                        ventilator_mean_airway_pressure,
                        ventilator_resp_rate,
                        ventilator_pressure_support,
                        ventilator_tidal_volume,
                        ventilator_oxygen_modality,
                        ventilator_oxygen_modality_oxygen_rate,
                        ventilator_oxygen_modality_flow_rate,
                        ventilator_fio2,
                    ],
                },
                {
                    "id": "d54e8e6a-ce52-4838-a650-3f51e827d8cd",
                    "link_id": "abg",
                    "text": "Arterial Blood Gas Analysis",
                    "type": "group",
                    "questions": [
                        po2,
                        pco2,
                        ph,
                        hco3,
                        base_excess,
                        lactate,
                        sodium,
                        potassium,
                    ],
                },
                {
                    "id": "fb65f595-1d4e-45f3-a9e3-49ebe7d882d8",
                    "link_id": "blood_sugar",
                    "text": "Blood Sugar",
                    "type": "group",
                    "questions": [
                        blood_sugar_level,
                        insulin_intake_dose,
                    ],
                },
                {
                    "id": "37039dc3-424e-4b9e-97e6-468cbdfcdd80",
                    "link_id": "io_balance",
                    "text": "I/O Balance",
                    "type": "group",
                    "questions": [
                        {
                            "id": "ba7c7cc2-2539-4b81-b1a0-de45a401c857",
                            "link_id": "intake",
                            "text": "Intake",
                            "type": "group",
                            "questions": [
                                infusions,
                                iv_fluids,
                                feeds,
                                total_intake_calculated,
                            ],
                        },
                        {
                            "id": "1911643c-1665-4b48-9a9e-d2140ac2c2e5",
                            "link_id": "output",
                            "text": "Output",
                            "type": "group",
                            "questions": [
                                output,
                                total_output_calculated,
                            ],
                        },
                    ],
                },
                {
                    "id": "8f77f2c8-74e8-4199-9378-ebd25e298b06",
                    "link_id": "dialysis",
                    "text": "Dialysis",
                    "type": "group",
                    "questions": [
                        dialysis_fluid_balance,
                        dialysis_net_balance,
                    ],
                },
                # pressure_sore, #TODO: enable this
                # nursing,
            ],
        },
    )

    if created:
        bulk_questionnaire_root_link.append(detailed_update_questionnaire.id)

    if bulk_questionnaire_root_link:
        root_orgs = Organization.objects.filter(root_org__isnull=True).values_list(
            "id", flat=True
        )
        for org_id in root_orgs:
            for questionnaire_id in bulk_questionnaire_root_link:
                QuestionnaireOrganization.objects.get_or_create(
                    questionnaire_id=questionnaire_id,
                    organization_id=org_id,
                )

    query = (
        DailyRound.objects.select_related("consultation")
        .exclude(
            consultation__migrated_emr_encounter_id__isnull=True,
            meta__migration_id=MIGRATION_ID,
        )
        .order_by("id")
    )

    paginator = Paginator(query, 1000)
    for page in paginator.page_range:
        for daily_round in paginator.page(page):
            daily_round: DailyRoundModel

            encounter = Encounter.objects.select_related("patient").get(
                id=daily_round.consultation.migrated_emr_encounter_id
            )

            patient_category = category_to_priority_map.get(
                daily_round.patient_category, "routine"
            )
            if encounter.priority != patient_category:
                encounter.priority = patient_category
                encounter.save()

            # these fields are calculated fields, by default they are 0 so we can safely set them to None
            daily_round.total_intake_calculated = (
                daily_round.total_intake_calculated or None
            )
            daily_round.total_output_calculated = (
                daily_round.total_output_calculated or None
            )

            questionnaire_responses = {}
            # fmt: off
            simple_fields = [
                ("temperature", temperature),
                ("is_experiencing_dysuria", is_experiencing_dysuria),
                ("in_prone_position", in_prone_position),
                ("glasgow_eye_open", glasgow_eye_open),
                ("glasgow_verbal_response", glasgow_verbal_response),
                ("glasgow_motor_response", glasgow_motor_response),
                ("glasgow_total_calculated", glasgow_total_calculated),
                ("limb_response_upper_extremity_left", limb_response_upper_extremity_left),
                ("limb_response_upper_extremity_right", limb_response_upper_extremity_right),
                ("limb_response_lower_extremity_left", limb_response_lower_extremity_left),
                ("limb_response_lower_extremity_right", limb_response_lower_extremity_right),
                ("pulse", pulse),
                ("resp", resp),
                ("ventilator_peep", ventilator_peep),
                ("ventilator_pip", ventilator_pip),
                ("ventilator_mean_airway_pressure", ventilator_mean_airway_pressure),
                ("ventilator_resp_rate", ventilator_resp_rate),
                ("ventilator_pressure_support", ventilator_pressure_support),
                ("ventilator_tidal_volume", ventilator_tidal_volume),
                ("ventilator_oxygen_modality_oxygen_rate", ventilator_oxygen_modality_oxygen_rate),
                ("ventilator_oxygen_modality_flow_rate", ventilator_oxygen_modality_flow_rate),
                ("ventilator_fio2", ventilator_fio2),
                ("ventilator_spo2", ventilator_spo2),
                ("etco2", etco2),
                ("bilateral_air_entry", bilateral_air_entry),
                ("ph", ph),
                ("pco2", pco2),
                ("po2", po2),
                ("hco3", hco3),
                ("base_excess", base_excess),
                ("lactate", lactate),
                ("sodium", sodium),
                ("potassium", potassium),
                ("blood_sugar_level", blood_sugar_level),
                ("dialysis_fluid_balance", dialysis_fluid_balance),
                ("dialysis_net_balance", dialysis_net_balance),
            ]
            for attr, question_obj in simple_fields:
                value = getattr(daily_round, attr)
                if value is not None:
                    if isinstance(value, Decimal):
                        value = float(value)
                    questionnaire_responses[question_obj["id"]] = {
                        "question_id": question_obj["id"],
                        "values": [{"value": value}],
                    }

            less_simple_fields = [
                ("bowel_issue", bowel_issue, bowel_issue_map),
                ("bladder_drainage", bladder_drainage, bladder_drainage_map),
                ("bladder_issue", bladder_issue, bladder_issue_map),
                ("urination_frequency", urination_frequency, urination_frequency_map),
                ("sleep", sleep, sleep_map),
                ("nutrition_route", nutrition_route, nutrition_route_map),
                ("oral_issue", oral_issue, oral_issue_map),
                ("appetite", appetite, appetite_map),
                ("ventilator_interface", ventilator_interface, ventilator_interface_map),
                ("ventilator_mode", ventilator_mode, ventilator_mode_map),
                ("ventilator_oxygen_modality", ventilator_oxygen_modality, ventilator_oxygen_modality_map),
            ]
            for attr, question_obj, map_obj in less_simple_fields:
                value = getattr(daily_round, attr)
                if value is not None:
                    if value_text := map_obj.get(value):
                        questionnaire_responses[question_obj["id"]] = {
                            "question_id": question_obj["id"],
                            "values": [{"value": value_text}],
                        }
            # fmt: on

            if not null_or_empty(daily_round.physical_examination_info):
                questionnaire_responses[physical_examination_info["id"]] = {
                    "question_id": physical_examination_info["id"],
                    "values": [{"value": daily_round.physical_examination_info}],
                }

            if not null_or_empty(daily_round.other_details):
                questionnaire_responses[other_details["id"]] = {
                    "question_id": other_details["id"],
                    "values": [{"value": daily_round.other_details}],
                }

            if daily_round.taken_at is not None:
                questionnaire_responses[taken_at["id"]] = {
                    "question_id": taken_at["id"],
                    "values": [{"value": daily_round.taken_at.isoformat()}],
                }

            if (
                daily_round.consciousness_level is not None
                or daily_round.consciousness_level_detail
            ):
                questionnaire_responses[consciousness_level["id"]] = {
                    "question_id": consciousness_level["id"],
                    "values": [
                        {
                            "value": consciousness_level_map.get(
                                daily_round.consciousness_level
                            )
                        }
                    ],
                    "note": daily_round.consciousness_level_detail or None,
                }

            if (
                daily_round.left_pupil_size is not None
                or daily_round.left_pupil_size_detail
            ):
                questionnaire_responses[left_pupil_size["id"]] = {
                    "question_id": left_pupil_size["id"],
                    "values": [{"value": daily_round.left_pupil_size}],
                    "note": daily_round.left_pupil_size_detail or None,
                }

            if (
                daily_round.right_pupil_size is not None
                or daily_round.right_pupil_size_detail
            ):
                questionnaire_responses[right_pupil_size["id"]] = {
                    "question_id": right_pupil_size["id"],
                    "values": [{"value": daily_round.right_pupil_size}],
                    "note": daily_round.right_pupil_size_detail or None,
                }

            if (
                daily_round.left_pupil_light_reaction is not None
                or daily_round.left_pupil_light_reaction_detail
            ):
                questionnaire_responses[left_pupil_light_reaction["id"]] = {
                    "question_id": left_pupil_light_reaction["id"],
                    "values": [{"value": daily_round.left_pupil_light_reaction}],
                    "note": daily_round.left_pupil_light_reaction_detail or None,
                }

            if (
                daily_round.right_pupil_light_reaction is not None
                or daily_round.right_pupil_light_reaction_detail
            ):
                questionnaire_responses[right_pupil_light_reaction["id"]] = {
                    "question_id": right_pupil_light_reaction["id"],
                    "values": [{"value": daily_round.right_pupil_light_reaction}],
                    "note": daily_round.right_pupil_light_reaction_detail or None,
                }

            if (
                daily_round.insulin_intake_dose is not None
                or daily_round.insulin_intake_frequency
            ):
                questionnaire_responses[insulin_intake_dose["id"]] = {
                    "question_id": insulin_intake_dose["id"],
                    "values": [{"value": float(daily_round.insulin_intake_dose)}],
                    "note": insulin_intake_frequency_map.get(
                        daily_round.insulin_intake_frequency
                    ),
                }

            if daily_round.rhythm is not None or daily_round.rhythm_detail:
                questionnaire_responses[rhythm["id"]] = {
                    "question_id": rhythm["id"],
                    "values": [
                        # TODO: update the key when the spec is updated
                        {"value": {"value_code": rhythm_map.get(daily_round.rhythm)}}
                    ],
                    "note": daily_round.rhythm_detail or None,
                }

            if daily_round.bp:
                if bp_systolic_value := daily_round.bp.get("systolic"):
                    questionnaire_responses[bp_systolic["id"]] = {
                        "question_id": bp_systolic["id"],
                        "values": [{"value": bp_systolic_value}],
                    }

                if bp_diastolic_value := daily_round.bp.get("diastolic"):
                    questionnaire_responses[bp_diastolic["id"]] = {
                        "question_id": bp_diastolic["id"],
                        "values": [{"value": bp_diastolic_value}],
                    }

            # TODO: update the value keys when the spec is updated
            if daily_round.infusions:
                values = []
                for daily_round_infusion in daily_round.infusions:
                    if infusion := daily_round_infusion.get("infusion"):
                        values.append(
                            {
                                "value_code": infusions_map[infusion],
                                "value_quantity": daily_round_infusion.get("quantity"),
                            }
                        )
                if values:
                    questionnaire_responses[infusions["id"]] = {
                        "question_id": infusions["id"],
                        "values": values,
                    }
            if daily_round.iv_fluids:
                values = []
                for daily_round_iv_fluid in daily_round.iv_fluids:
                    if iv_fluid := daily_round_iv_fluid.get("iv_fluid"):
                        values.append(
                            {
                                "value_code": iv_fluids_map[iv_fluid],
                                "value_quantity": daily_round_iv_fluid.get("quantity"),
                            }
                        )

                if values:
                    questionnaire_responses[iv_fluids["id"]] = {
                        "question_id": iv_fluids["id"],
                        "values": values,
                    }
            if daily_round.feeds:
                values = []
                for daily_round_feed in daily_round.feeds:
                    if feed := daily_round_feed.get("feed"):
                        values.append(
                            {
                                "value_code": feeds_map[feed],
                                "value_quantity": daily_round_feed.get("quantity"),
                            }
                        )
                if values:
                    questionnaire_responses[feeds["id"]] = {
                        "question_id": feeds["id"],
                        "values": values,
                    }
            if daily_round.output:
                values = []
                for daily_round_output in daily_round.output:
                    if output_name := daily_round_output.get("name"):
                        values.append(
                            {
                                "value_code": output_map[output_name],
                                "value_quantity": daily_round_output.get("quantity"),
                            }
                        )
                if values:
                    questionnaire_responses[output["id"]] = {
                        "question_id": output["id"],
                        "values": values,
                    }

            # TODO: nursing, pressure_sore, pain_scale_enhanced
            # TODO: review json fields like infusions, iv_fluids, feeds, output

            if not questionnaire_responses:
                continue

            if daily_round.rounds_type == 0:  # NORMAL
                selected_questionnaire = brief_update_questionnaire
            elif daily_round.rounds_type == 30:  # COMMUNITY_NURSES_LOG
                selected_questionnaire = community_nurse_log_questionnaire
            elif daily_round.rounds_type == 50:  # DOCTORS_LOG
                selected_questionnaire = doctors_log_questionnaire
            elif daily_round.rounds_type == 300:  # AUTOMATED
                selected_questionnaire = automated_log_update_questionnaire
            elif daily_round.rounds_type == 400:  # TELEMEDICINE
                selected_questionnaire = telemedicine_questionnaire
            else:  # VENTILATOR, ICU
                selected_questionnaire = detailed_update_questionnaire

            responses = list(questionnaire_responses.values())
            questionnaire_response = QuestionnaireResponse.objects.create(
                questionnaire=selected_questionnaire,
                encounter=encounter,
                patient=encounter.patient,
                responses=responses,
                subject_id=encounter.external_id,
                created_by_id=daily_round.created_by_id,
                updated_by_id=daily_round.last_edited_by_id,
                created_date=daily_round.created_date,
                modified_date=daily_round.modified_date,
                meta={
                    "created_by_telemedicine": daily_round.created_by_telemedicine,
                    "last_updated_by_telemedicine": daily_round.last_updated_by_telemedicine,
                    "migration_id": MIGRATION_ID,
                },
            )

            observations = convert_to_observation_spec(
                {"questions": selected_questionnaire.questions}, responses
            )
            observations_objects = []
            for observation in observations:
                pydantic_observation = ObservationSpec(
                    **observation,
                    subject_type=selected_questionnaire.subject_type,
                    data_entered_by_id=daily_round.last_edited_by_id,
                    created_by_id=daily_round.created_by_id,
                    updated_by_id=daily_round.last_edited_by_id,
                )
                observations_obj = pydantic_observation.de_serialize()
                observations_obj.questionnaire_response = questionnaire_response
                observations_obj.encounter_id = encounter.id
                observations_obj.patient_id = encounter.patient_id
                observations_obj.subject_id = encounter.external_id
                observations_objects.append(observations_obj)
            Observation.objects.bulk_create(observations_objects)

    enable_auto_time()


def reverse_migrate_daily_rounds(apps, schema_editor):
    Questionnaire = apps.get_model("emr", "Questionnaire")
    Observation = apps.get_model("emr", "Observation")
    Questionnaire.objects.filter(meta__migration_id=MIGRATION_ID).delete()
    Observation.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0488_migrate_file_uploads"),
    ]

    operations = [
        migrations.RunPython(migrate_daily_rounds, reverse_migrate_daily_rounds)
    ]
