# Generated by Django 5.1.4 on 2025-01-28 09:13
from datetime import datetime
from django.db import migrations
from django.core.paginator import Paginator
from django.db import models


MIGRATION_ID = 158445695209


care_type_map = {
    "ONVIF": "camera",
    "HL7MONITOR":"vitals-observation",
    "VENTILATOR":"vitals-observation",
}

sub_type_map = {
    "HL7MONITOR": "HL7-Monitor",
    "VENTILATOR": "Ventilator",
}

def migrate_assets(apps, schema_editor):
    from care.emr.models import (
        Device,
        DeviceEncounterHistory,
        DeviceLocationHistory,
        DeviceServiceHistory,
    )
    from care.facility.utils import disable_auto_time

    enable_auto_time = disable_auto_time(
        Device,
        DeviceEncounterHistory,
        DeviceLocationHistory,
        DeviceServiceHistory,
    )

    Asset = apps.get_model("facility", "Asset")
    AssetTransaction = apps.get_model("facility", "AssetTransaction")
    AssetService = apps.get_model("facility", "AssetService")
    AssetServiceEdit = apps.get_model("facility", "AssetServiceEdit")
    ConsultationBedAsset = apps.get_model("facility", "ConsultationBedAsset")

    query = (
        Asset.objects.filter(
            migrated_emr_device_id__isnull=True,
        )
        .select_related("current_location", "current_location__facility")
        .order_by("id")
    )
    paginator = Paginator(query, 1000)
    bulk_asset_device_reference = []
    for page in paginator.page_range:
        for asset in paginator.page(page):
            contact = []
            if asset.vendor_name:
                contact.append(
                    {
                        "system": "other",
                        "value": asset.vendor_name,
                        "use": "work",
                    }
                )
            if asset.support_name:
                contact.append(
                    {
                        "system": "other",
                        "value": asset.support_name,
                        "use": "work",
                    }
                )
            if asset.support_phone:
                contact.append(
                    {
                        "system": "phone",
                        "value": asset.support_phone,
                        "use": "work",
                    }
                )
            if asset.support_email:
                contact.append(
                    {
                        "system": "email",
                        "value": asset.support_email,
                        "use": "work",
                    }
                )
            metadata = {}
            if sub_type:= sub_type_map.get(asset.asset_class):
                metadata["type"] = sub_type
            if endpoint_address := asset.meta.get("local_ip_address"):
                metadata["endpoint_address"] = endpoint_address
            try:
                metadata["username"], metadata["password"], metadata["stream_id"] = (
                    asset.meta.get.get("camera_access_key", "").split(":")
                )
            except ValueError:
                pass
            device = Device.objects.create(
                external_id=asset.external_id,
                identifier=asset.serial_number,
                care_type=care_type_map.get(asset.asset_class),
                status="active",
                availability_status="available" if asset.is_working else "damaged",
                manufacturer=asset.manufacturer or "",
                expiration_date=asset.warranty_amc_end_of_validity,
                serial_number=asset.serial_number,
                registered_name=asset.name,
                user_friendly_name=asset.name,
                contact=contact,
                facility_id=asset.current_location.facility_id,
                managing_organization_id=asset.current_location.facility.default_internal_organization_id,
                current_location_id=asset.current_location.migrated_emr_location_id,
                created_date=asset.created_date,
                modified_date=asset.modified_date,
                metadata=metadata,
                meta={
                    "migration_id": MIGRATION_ID,
                    "not_working_reason": asset.not_working_reason,
                    "warranty_details": asset.warranty_details,
                    "qr_code_id": asset.qr_code_id,
                    "class": asset.asset_class,
                },
            )
            bulk_asset_device_reference.append((asset.id, device.id))

            bulk_device_history = []
            for consultation_bed_asset in ConsultationBedAsset.objects.filter(
                asset_id=asset.id
            ).select_related(
                "consultation_bed",
                "consultation_bed__consultation",
            ):
                consultation_bed = consultation_bed_asset.consultation_bed
                bulk_device_history.append(
                    DeviceEncounterHistory(
                        device_id=device.id,
                        encounter_id=consultation_bed.consultation.migrated_emr_encounter_id,
                        start=consultation_bed.start_date,
                        end=consultation_bed.end_date,
                        created_date=consultation_bed.created_date,
                        modified_date=consultation_bed.modified_date,
                        meta={
                            "migration_id": MIGRATION_ID,
                        },
                    )
                )
                if not consultation_bed.end_date:
                    device.current_encounter_id = (
                        consultation_bed.consultation.migrated_emr_encounter_id
                    )

            DeviceEncounterHistory.objects.bulk_create(bulk_device_history)
            device.save(update_fields=["current_encounter_id"])

            bulk_device_location_history = []
            for asset_service in AssetService.objects.filter(asset_id=asset.id):
                history = []
                modified_date = asset_service.modified_date
                for edit in AssetServiceEdit.objects.filter(
                    asset_service_id=asset_service.id
                ):
                    edit_serviced_on = datetime(
                        year=edit.serviced_on.year,
                        month=edit.serviced_on.month,
                        day=edit.serviced_on.day,
                        tzinfo=asset_service.created_date.tzinfo
                    ).isoformat() if edit.serviced_on else None
                    history.append(
                        {
                            "updated_by": edit.edited_by_id,
                            "serviced_on": edit_serviced_on,
                            "note": edit.note,
                        }
                    )
                    modified_date = max(modified_date, edit.edited_on)

                serviced_on = datetime(
                    year=asset_service.serviced_on.year,
                    month=asset_service.serviced_on.month,
                    day=asset_service.serviced_on.day,
                    tzinfo=asset_service.created_date.tzinfo
                ) if asset_service.serviced_on else None
                bulk_device_location_history.append(
                    DeviceServiceHistory(
                        device_id=device.id,
                        serviced_on=serviced_on,
                        note=asset_service.note,
                        created_date=asset_service.created_date,
                        modified_date=modified_date,
                        edit_history=history,
                        meta={
                            "migration_id": MIGRATION_ID,
                        },
                    )
                )
            DeviceServiceHistory.objects.bulk_create(bulk_device_location_history)

            bulk_history_records = []
            asset_transactions = list(AssetTransaction.objects.filter(
                asset_id=asset.id
            ).order_by("created_date", "id"))

            if asset_transactions:
                first_tx = asset_transactions[0]
                initial_history = DeviceLocationHistory(
                    device=device,
                    location_id=first_tx.from_location.migrated_emr_location_id,
                    start=asset.created_date,
                    end=first_tx.created_date,
                )
                bulk_history_records.append(initial_history)

                previous_history = initial_history
                for asset_tx in asset_transactions[1:]:
                    new_history = DeviceLocationHistory(
                        device=device,
                        location_id=asset_tx.to_location.migrated_emr_location_id,
                        start=asset_tx.created_date,
                        end=None,
                    )
                    # assuming the from_location of the current transaction is the
                    # same as the to_location of the previous transaction
                    previous_history.end = asset_tx.created_date
                    previous_history = new_history
                    bulk_history_records.append(new_history)
            else:
                bulk_history_records.append(DeviceLocationHistory(
                    device=device,
                    location_id=asset.current_location.migrated_emr_location_id,
                    start=asset.created_date,
                    end=None,
                ))

            DeviceLocationHistory.objects.bulk_create(bulk_history_records)

    Asset.objects.bulk_update(
        [
            Asset(id=id, migrated_emr_device_id=new_device_id)
            for id, new_device_id in bulk_asset_device_reference
        ],
        ["migrated_emr_device_id"],
    )

    enable_auto_time()


def reverse_migrate_assets(apps, schema_editor):
    DeviceServiceHistory = apps.get_model("emr", "DeviceServiceHistory")
    Device = apps.get_model("emr", "Device")
    Asset = apps.get_model("facility", "Asset")
    Asset.objects.update(migrated_emr_device_id=None)
    DeviceServiceHistory.objects.filter(meta__migration_id=MIGRATION_ID).delete()
    Device.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0489_migrate_daily_rounds"),
        ("emr", "0018_consent_device_deviceencounterhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="migrated_emr_device_id",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_assets, reverse_migrate_assets),
    ]
