# Generated by Django 5.1.4 on 2025-01-28 09:13
from django.db import migrations
from django.core.paginator import Paginator
from django.db import models


MIGRATION_ID = 158445695209


class ConsentType(models.IntegerChoices):
    CONSENT_FOR_ADMISSION = 1, "Consent for Admission"
    PATIENT_CODE_STATUS = 2, "Patient Code Status"
    CONSENT_FOR_PROCEDURE = 3, "Consent for Procedure"
    HIGH_RISK_CONSENT = 4, "High Risk Consent"
    OTHERS = 5, "Others"


class PatientCodeStatusType(models.IntegerChoices):
    NOT_SPECIFIED = 0, "Not Specified"
    DNH = 1, "Do Not Hospitalize"
    DNR = 2, "Do Not Resuscitate"
    COMFORT_CARE = 3, "Comfort Care Only"
    ACTIVE_TREATMENT = 4, "Active Treatment"


consent_map = {
    1: "treatment", # consent_for_admission
    3: "treatment", # consent_for_procedure
    4: "adr", # high_risk_consent
    5: "consent_document", # others
}

code_status_map = {
    0: "consent_document", # not_specified
    1: "consent_document", # dnh, not used
    2: "dnr", # dnr
    3: "comfort_care",
    4: "acd", # active_treatment
}


def get_consent_category(patient_consent):
    """
    Return the consent category for a patient consent record.
    
    If the consent type indicates a patient code status (i.e. type equals 2), the
    function returns a category based on the patient code status, defaulting to
    "unknown_code_status" if no mapping exists. For other consent types, it retrieves
    the category from a different mapping, defaulting to "unknown".
      
    Args:
        patient_consent: An object with 'type' and 'patient_code_status' attributes used
            to determine the appropriate consent category.
      
    Returns:
        A string representing the consent category.
    """
    if patient_consent.type == 2:
        return code_status_map.get(
            patient_consent.patient_code_status, "unknown_code_status"
        )
    return consent_map.get(patient_consent.type, "unknown")


def format_note(patient_consent):
    """
    Generate a formatted note detailing archival information for a patient consent.
    
    This function constructs a note string that includes the username of the person who archived the consent record. If an archival date is present, it appends the date formatted as 'dd/mm/YYYY HH:MM'.
    """
    note = f"Archived by: {patient_consent.archived_by.username}\n"
    if patient_consent.archived_date:
        note += f"Archived on: {patient_consent.archived_date.strftime('%d/%m/%Y %H:%M')}\n"
    return note


def migrate_consent_records(apps, schema_editor):
    """
    Migrates PatientConsent records to the Consent model.
    
    Processes PatientConsent entries in batches and creates corresponding Consent
    records with mapped fields such as encounter ID, status, category, date, creator, and
    associated metadata. Automatic timestamping is disabled on the Consent model during
    the migration to optimize bulk creation and re-enabled once processing is complete.
    """
    from care.emr.models.consent import Consent
    from care.facility.utils import disable_auto_time

    enable_auto_time = disable_auto_time(Consent)

    PatientConsent = apps.get_model("facility", "PatientConsent")

    paginator = Paginator(
        PatientConsent.objects.filter().select_related("consultation").order_by("id"),
        3000,
    )

    for page_num in paginator.page_range:
        bulk_create_data = []
        for patient_consent in paginator.get_page(page_num):
            consent = Consent(
                encounter_id=patient_consent.consultation.migrated_emr_encounter_id,
                status="active" if not patient_consent.archived else "inactive",
                category=get_consent_category(patient_consent),
                date=patient_consent.created_date,
                period={},
                created_by_id=patient_consent.created_by_id,
                meta={
                    "migration_id": MIGRATION_ID,
                },
                note=format_note(patient_consent) if patient_consent.archived else None,
            )
            bulk_create_data.append(consent)
        Consent.objects.bulk_create(bulk_create_data)

    enable_auto_time()


def reverse_migrate_consent_records(apps, schema_editor):
    """
    Reverses the consent records migration.
    
    Deletes Consent records created during the migration process by filtering on the
    migration identifier (MIGRATION_ID). This rollback operation removes only those
    entries that were added during the forward migration.
    """
    Consent = apps.get_model("emr", "Consent")
    Consent.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0490_migrate_assets"),
    ]

    operations = [
        migrations.RunPython(migrate_consent_records, reverse_migrate_consent_records),
    ]
