# Generated by Django 5.1.4 on 2025-01-28 09:13
from django.db import migrations
from django.core.paginator import Paginator
from django.db import models


MIGRATION_ID = 158445695209


class ConsentType(models.IntegerChoices):
    CONSENT_FOR_ADMISSION = 1, "Consent for Admission"
    PATIENT_CODE_STATUS = 2, "Patient Code Status"
    CONSENT_FOR_PROCEDURE = 3, "Consent for Procedure"
    HIGH_RISK_CONSENT = 4, "High Risk Consent"
    OTHERS = 5, "Others"


class PatientCodeStatusType(models.IntegerChoices):
    NOT_SPECIFIED = 0, "Not Specified"
    DNH = 1, "Do Not Hospitalize"
    DNR = 2, "Do Not Resuscitate"
    COMFORT_CARE = 3, "Comfort Care Only"
    ACTIVE_TREATMENT = 4, "Active Treatment"


consent_map = {
    1: "treatment", # consent_for_admission
    3: "treatment", # consent_for_procedure
    4: "adr", # high_risk_consent
    5: "consent_document", # others
}

code_status_map = {
    0: "consent_document", # not_specified
    1: "consent_document", # dnh, not used
    2: "dnr", # dnr
    3: "comfort_care",
    4: "acd", # active_treatment
}


def get_consent_category(patient_consent):
    if patient_consent.type == 2:
        return code_status_map.get(
            patient_consent.patient_code_status, "unknown_code_status"
        )
    return consent_map.get(patient_consent.type, "unknown")


def format_note(patient_consent):
    note = f"Archived by: {patient_consent.archived_by.username}\n"
    if patient_consent.archived_date:
        note += f"Archived on: {patient_consent.archived_date.strftime('%d/%m/%Y %H:%M')}\n"
    return note


def migrate_consent_records(apps, schema_editor):
    from care.emr.models.consent import Consent
    from care.facility.utils import disable_auto_time

    enable_auto_time = disable_auto_time(Consent)

    PatientConsent = apps.get_model("facility", "PatientConsent")

    paginator = Paginator(
        PatientConsent.objects.filter().select_related("consultation").order_by("id"),
        3000,
    )

    for page_num in paginator.page_range:
        bulk_create_data = []
        for patient_consent in paginator.get_page(page_num):
            consent = Consent(
                encounter_id=patient_consent.consultation.migrated_emr_encounter_id,
                status="active" if not patient_consent.archived else "inactive",
                category=get_consent_category(patient_consent),
                date=patient_consent.created_date,
                period={},
                created_by_id=patient_consent.created_by_id,
                meta={
                    "migration_id": MIGRATION_ID,
                },
                note=format_note(patient_consent) if patient_consent.archived else None,
            )
            bulk_create_data.append(consent)
        Consent.objects.bulk_create(bulk_create_data)

    enable_auto_time()


def reverse_migrate_consent_records(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0490_migrate_assets"),
    ]

    operations = [
        migrations.RunPython(migrate_consent_records, reverse_migrate_consent_records),
    ]
