# Generated by Django 5.1.4 on 2025-04-08 13:27
import logging

from django.db import migrations
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)

def migrate_treating_physician(apps, schema_editor):
    Encoutner = apps.get_model("emr", "Encounter")
    PatientConsultation = apps.get_model("facility", "PatientConsultation")

    default_role_code = {"code":"158965000","display":"Medical practitioner","system":"http://snomed.info/sct"}

    paginator = Paginator(
        PatientConsultation.objects.filter(
            migrated_emr_encounter_id__isnull=False,
            treating_physician_id__isnull=False,
            deleted=False,
        )
        .order_by("id"),
        2000,
    )
    bulk = []
    for page_number in paginator.page_range:
        for consultation in paginator.page(page_number).object_list:
            try:
                encounter = Encoutner.objects.get(
                    id=consultation.migrated_emr_encounter_id
                )
                encounter.care_team = [
                    {"user_id": consultation.treating_physician_id, "role": default_role_code}
                ]
                bulk.append(encounter)
            except Encoutner.DoesNotExist:
                logger.warning(
                    f"Encounter with id {consultation.migrated_emr_encounter_id} does not exist"
                )
        Encoutner.objects.bulk_update(
            bulk,
            ["care_team"],
        )

class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0491_migrate_consent_records"),
        ("emr", "0028_alter_encounter_care_team"),
    ]

    operations = [
        migrations.RunPython(
            migrate_treating_physician,
            migrations.RunPython.noop,
        ),
    ]
