# Generated by Django 5.1.4 on 2025-05-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0477_alter_facility_facility_type_and_more"),
        ("facility", "0492_migrate_treating_physician"),
    ]

    operations = []
