# Generated by Django 5.1.4 on 2025-06-26 07:05
from datetime import datetime
import logging
import uuid

from django.db import migrations
from django.db.models import Prefetch
from django.core.paginator import Paginator
from django.utils import timezone
from pydantic import UUID4

from care.emr.resources.observation.spec import BaseObservationSpec

logger = logging.getLogger(__name__)

MIGRATION_ID = 158445695209


def deterministic_uuid(string):
    """
    Generates a UUID based on the provided string.

    Args:
        string (str): The input string to generate a UUID from.

    Returns:
        str: A UUID generated from the input string.
    """
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, string))


def get_ucum_code(u):
    if u is None:
        return None
    return {"system": "http://unitsofmeasure.org", "code": u[0], "display": u[1]}


class ObservationSpec(BaseObservationSpec):
    data_entered_by_id: int
    created_by_id: int
    updated_by_id: int
    encounter_id: int
    patient_id: int
    subject_id: UUID4
    created_date: datetime
    modified_date: datetime
    meta: dict
    questionnaire_response_id: int

    def perform_extra_deserialization(self, is_update, obj):
        obj.external_id = self.id
        obj.data_entered_by_id = self.data_entered_by_id
        obj.created_by_id = self.created_by_id
        obj.updated_by_id = self.updated_by_id
        obj.encounter_id = self.encounter_id
        obj.patient_id = self.patient_id
        obj.subject_id = self.subject_id
        obj.created_date = self.created_date
        obj.modified_date = self.modified_date
        obj.meta = self.meta or {}
        obj.questionnaire_response_id = self.questionnaire_response_id

        self.meta.pop("data_entered_by_id", None)
        if not is_update:
            obj.id = None


def create_observation_spec(questionnaire, responses, parent_id=None):
    spec = {
        "status": "final",
        "value_type": questionnaire["type"],
    }
    if "category" in questionnaire:
        spec["category"] = questionnaire["category"]
    if "code" in questionnaire:
        spec["main_code"] = questionnaire["code"]
    if questionnaire["type"] == "group":
        spec["id"] = str(uuid.uuid4())
        spec["effective_datetime"] = timezone.now()
        spec["value"] = {}
        return [spec]
    observations = []
    response = responses.get(questionnaire["id"])
    if response and len(response.get("values", [])) > 0:
        observation = {}
        for value in response["values"]:
            observation = spec.copy()
            observation["id"] = str(uuid.uuid4())
            if questionnaire["type"] == "choice" and value.get("code"):
                observation["value"] = {
                    "coding": value.get("coding"),
                }
            elif value:
                observation["value"] = {
                    "value": str(value.get("value")),
                    "unit": questionnaire.get("unit"),
                    "coding": value.get("coding"),
                }

            if response.get("note"):
                observation["note"] = response.get("note")
        if parent_id:
            observation["parent"] = parent_id
        observation["effective_datetime"] = timezone.now()
        observations.append(observation)
    return observations


def convert_to_observation_spec(
    questionnaire, responses, parent_id=None, is_component=False
):
    constructed_observation_mapping = []
    for question in questionnaire.get("questions", []):
        if question["type"] == "group":
            observation = create_observation_spec(question, responses, parent_id)
            sub_mapping = convert_to_observation_spec(
                question, responses, observation[0]["id"]
            )
            if sub_mapping:
                constructed_observation_mapping.extend(observation)
                constructed_observation_mapping.extend(sub_mapping)
        elif question.get("code"):
            constructed_observation_mapping.extend(
                create_observation_spec(question, responses, parent_id)
            )

    return constructed_observation_mapping


haematology_group = {
    "Blood Group": {
        "code": {
            "system": "http://loinc.org",
            "code": "882-1",
            "display": "ABO and Rh group [Type] in Blood (34599-7)",
        }
    },
    "Total Count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        }
    },
    "Neutrophil count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "751-8",
            "display": "Neutrophils [#/volume] in Blood",
        },
    },
    "Lymphocyte count Eosinophil count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "26474-7",
            "display": "Lymphocytes [#/volume] in Blood",
        },
    },
    "Eosinophil count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "26449-9",
            "display": "Eosinophils [#/volume] in Blood (generic 713-8)",
        },
    },
    "Basophil count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "704-7",
            "display": "Basophils [#/volume] in Blood (generic 704-7)",
        },
    },
    "Monocyte count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "742-7",
            "display": "Monocytes [#/volume] in Blood",
        },
    },
    "neutrophil": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "770-8",
            "display": "Neutrophils/100 leukocytes in Blood by Automated count",
        },
    },
    "lymphocyte": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "736-9",
            "display": "Lymphocytes/100 leukocytes in Blood by Automated count",
        },
    },
    "eosinophil": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "713-8",
            "display": "Eosinophils/100 leukocytes in Blood by Automated count",
        },
    },
    "basophile": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "6692-8",
            "display": "Basophils/100 leukocytes in Blood by Automated count",
        },
    },
    "monocyte": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "26485-3",
            "display": "Monocytes/100 leukocytes in Blood by Automated count",
        },
    },
    "Hb": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/dL",
            "display": "grams per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "718-7",
            "display": "Hemoglobin [Mass/volume] in Blood",
        },
    },
    "PCV": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "20570-8",
            "display": "Hematocrit [Volume Fraction] of Blood",
        },
    },
    "RBC count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "10*6/uL",
            "display": "million per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "26453-1",
            "display": "Red blood cells [#/volume] in Blood",
        },
    },
    "RDW": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "788-0",
            "display": "Erythrocyte distribution width [Ratio]",
        },
    },
    "Platelets": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "{cells}/uL",
            "display": "cells per microliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "777-3",
            "display": "Platelets [#/volume] in Blood",
        },
    },
    "MCV": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "fL",
            "display": "femtoliters",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "787-2",
            "display": "MCV [Entitic volume] by Automated count",
        },
    },
    "MCH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg",
            "display": "picograms",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "785-6",
            "display": "MCH [Entitic mass]",
        },
    },
    "MCHC": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/dL",
            "display": "grams per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "786-4",
            "display": "MCHC [Mass/volume]",
        },
    },
    "ESR": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mm/h",
            "display": "millimeters per hour",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "4537-7",
            "display": "Erythrocyte sedimentation rate by Westergren",
        },
    },
    "Peripheral blood smear": {
        "code": {
            "system": "http://loinc.org",
            "code": "38542-2",
            "display": "Peripheral blood smear comment",
        }
    },
    "Reticulocyte count": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "14196-0",
            "display": "Reticulocytes [#/100 RBC] in Blood",
        },
    },
    "M P smear": {
        "code": {
            "system": "http://loinc.org",
            "code": "51587-4",
            "display": "Malaria screen [Presence] in Blood by Light microscopy",
        }
    },
}

biochemistry_group = {
    "FBS": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1558-6",
            "display": "Glucose [Mass/volume] in Serum or Plasma -Fasting",
        },
    },
    "PPBS": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "6689-4",
            "display": "Glucose [Mass/volume] in Serum or Plasma -2 hours postprandial",
        },
    },
    "RBS": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2339-0",
            "display": "Glucose [Mass/volume] in Blood -Random",
        },
    },
    "T. Cholestrol": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2093-3",
            "display": "Cholesterol [Mass/volume] in Serum or Plasma",
        },
    },
    "LDL": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2089-1",
            "display": "Low density lipoprotein cholesterol [Mass/volume] in Serum or Plasma by calculation",
        },
    },
    "HDL": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2085-9",
            "display": "High density lipoprotein cholesterol [Mass/volume] in Serum or Plasma",
        },
    },
    "Triglycerides": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2571-8",
            "display": "Triglyceride [Mass/volume] in Serum or Plasma",
        },
    },
    "VLDL": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2091-7",
            "display": "Very low density lipoprotein cholesterol [Mass/volume] in Serum or Plasma by calculation",
        },
    },
    "Urea": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3092-4",
            "display": "Urea [Mass/volume] in Serum or Plasma",
        },
    },
    "Uric Acid": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3084-1",
            "display": "Uric acid [Mass/volume] in Serum or Plasma",
        },
    },
    "Creatinine": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2160-0",
            "display": "Creatinine [Mass/volume] in Serum or Plasma",
        },
    },
    "CRP": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/L",
            "display": "milligram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1988-5",
            "display": "C reactive protein [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum Sodium (Na+)": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mmol/L",
            "display": "millimole per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2951-2",
            "display": "Sodium [Moles/volume] in Serum or Plasma",
        },
    },
    "Serum Potassium (K+)": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mmol/L",
            "display": "millimole per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "6298-4",
            "display": "Potassium [Moles/volume] in Serum or Plasma",
        },
    },
    "Serum Calcium": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "17861-6",
            "display": "Calcium [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum Phosphorus": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2777-1",
            "display": "Phosphate [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum Chloride": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mmol/L",
            "display": "millimole per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2075-0",
            "display": "Chloride [Moles/volume] in Serum or Plasma",
        },
    },
    "Serum Megnesium": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "19123-9",
            "display": "Magnesium [Mass/volume] in Serum or Plasma",
        },
    },
    "Total Bilirubin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1975-2",
            "display": "Bilirubin.total [Mass/volume] in Serum or Plasma",
        },
    },
    "Direct Bilirubin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1968-7",
            "display": "Bilirubin.direct [Mass/volume] in Serum or Plasma",
        },
    },
    "SGOT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/L",
            "display": "international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1920-8",
            "display": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "SGPT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/L",
            "display": "international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1742-6",
            "display": "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "ALP": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/L",
            "display": "international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "6768-6",
            "display": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "Total Protein": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/dL",
            "display": "gram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2885-2",
            "display": "Protein.total [Mass/volume] in Serum or Plasma",
        },
    },
    "Albumin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/dL",
            "display": "gram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1751-7",
            "display": "Albumin [Mass/volume] in Serum or Plasma",
        },
    },
    "Albumin_1": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/dL",
            "display": "gram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1751-7",
            "display": "Albumin [Mass/volume] in Serum or Plasma",
        },
    },
    "Globulin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/dL",
            "display": "gram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "10834-0",
            "display": "Globulin [Mass/volume] in Serum or Plasma by calculation",
        },
    },
    "PT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "s",
            "display": "second",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "5964-2",
            "display": "Prothrombin time (PT) in Platelet poor plasma by Coagulation assay",
        },
    },
    "INR": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "s",
            "display": "second",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "6301-6",
            "display": "INR in Platelet poor plasma by Coagulation assay",
        },
    },
    "APTT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "s",
            "display": "second",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "14979-9",
            "display": "Activated partial thromboplastin time (APTT) in Platelet poor plasma by Coagulation assay",
        },
    },
    "D-Dimer": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/L",
            "display": "microgram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "48067-3",
            "display": "D-Dimer FEU [Mass/volume] in Platelet poor plasma by Immunoassay",
        },
    },
    "Fibrinogen": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3255-7",
            "display": "Fibrinogen [Mass/volume] in Platelet poor plasma by Coagulation assay",
        },
    },
    "GCT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        }
    },
    "GTT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        }
    },
    "GGT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/L",
            "display": "enzyme unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2324-2",
            "display": "Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "HbA1C": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "4548-4",
            "display": "Hemoglobin A1c [Mass/volume] in Blood (commonly reported % DCCT)",
        },
    },
    "Serum Copper": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/dL",
            "display": "microgram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "5631-7",
            "display": "Copper [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum Lead": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/dL",
            "display": "microgram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "10912-4",
            "display": "Lead [Mass/volume] in Serum or Plasma",
        },
    },
    "Iron": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/dL",
            "display": "microgram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2498-4",
            "display": "Iron [Mass/volume] in Serum or Plasma",
        },
    },
    "TIBC": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/dL",
            "display": "microgram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2500-7",
            "display": "Iron binding capacity.total [Mass/volume] in Serum or Plasma",
        },
    },
    "Transferin Saturation": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "14801-5",
            "display": "Iron binding capacity.saturation [Mass fraction] in Serum or Plasma",
        },
    },
    "IL6": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg/mL",
            "display": "picogram per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "26881-3",
            "display": "Interleukin 6 [Mass/volume] in Serum or Plasma",
        },
    },
    "Lactate": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mmol/L",
            "display": "millimole per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2524-7",
            "display": "Lactic acid [Moles/volume] in Serum or Plasma",
        },
    },
    "Ceruloplasmin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2064-4",
            "display": "Ceruloplasmin [Mass/volume] in Serum or Plasma",
        },
    },
    "ACP": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/L",
            "display": "enzyme unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1715-2",
            "display": "Acid phosphatase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "Protein C": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/dL",
            "display": "InternationalUnit per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "4671-4",
            "display": "Protein C activity in Platelet poor plasma by Coagulation assay",
        },
    },
    "Protein S": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "%",
            "display": "percent",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "72337-9",
            "display": "Protein S activity in Platelet poor plasma by Coagulation assay",
        },
    },
    "G6PD": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mU/g{Hgb}",
            "display": "milliUnit / gram Hgb",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "32546-4",
            "display": "Glucose-6-phosphate dehydrogenase [Enzymatic activity/volume] in RBC",
        },
    },
    "ACCP": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/mL",
            "display": "enzyme unit per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "53027-9",
            "display": "Cyclic citrullinated peptide Ab [Units/volume] in Serum",
        },
    },
    "Ferritin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "14723-1",
            "display": "Ferritin [Mass/volume] in Serum or Plasma",
        },
    },
    "LDH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/L",
            "display": "enzyme unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "42929-0",
            "display": "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "Amylase": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/L",
            "display": "enzyme unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1798-8",
            "display": "Amylase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "Lipase": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/L",
            "display": "enzyme unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3040-3",
            "display": "Lipase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "Ammonia": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/dL",
            "display": "microgram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "16362-6",
            "display": "Ammonia [Moles/volume] in Blood (commonly measured as µmol/L in plasma)",
        },
    },
    "CKMB": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/L",
            "display": "international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "32673-6",
            "display": "Creatine kinase.MB [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "CK NAC": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/L",
            "display": "enzyme unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2157-6",
            "display": "Creatine kinase [Enzymatic activity/volume] in Serum or Plasma",
        },
    },
    "24hrs Urine Protein": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/dL",
            "display": "milligram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2889-4",
            "display": "Protein [Mass/time] in 24 hour Urine",
        },
    },
    "24hrs Urine Uric Acid": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/(24.h)",
            "display": "milligram per 24 hours",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3095-7",
            "display": "Uric acid [Mass/time] in 24 hour Urine",
        },
    },
    "24 hrs Urine Oxalate": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg/L",
            "display": "milligram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2701-1",
            "display": "Oxalate [Mass/time] in 24 hour Urine (if truly 24hr total)",
        },
    },
    "Urine Microalbumin": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "mg",
            "display": "milligram",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "14957-5",
            "display": "Albumin [Mass/volume] in Urine (If it's just concentration)",
        },
    },
    "Urine Sodium": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "meq/(24.h)",
            "display": "milliequivalent per 24 hour",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2956-1",
            "display": "Sodium [Moles/time] in 24 hour Urine",
        },
    },
    "PCT": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "33959-8",
            "display": "Procalcitonin [Mass/volume] in Serum or Plasma",
        },
    },
    "T3": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/dL",
            "display": "nanogram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3053-6",
            "display": "Triiodothyronine (T3) total [Mass/volume] in Serum or Plasma",
        },
    },
    "T4": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/L",
            "display": "microgram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3026-2",
            "display": "Thyroxine (T4) total [Mass/volume] in Serum or Plasma",
        },
    },
    "TSH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "m[IU]/L",
            "display": "milli international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3016-3",
            "display": "Thyrotropin (TSH) [Units/volume] in Serum or Plasma",
        },
    },
    "FT3": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/dL",
            "display": "nanogram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "14928-6",
            "display": "Triiodothyronine (T3).free [Mass/volume] in Serum or Plasma",
        },
    },
    "FT4": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/dL",
            "display": "nanogram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "3024-7",
            "display": "Thyroxine (T4).free [Mass/volume] in Serum or Plasma",
        },
    },
    "Estradiol": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg/mL",
            "display": "picogram per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2243-4",
            "display": "Estradiol [Mass/volume] in Serum or Plasma",
        },
    },
    "Growth Hormone": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2963-7",
            "display": "Growth hormone [Mass/volume] in Serum or Plasma",
        },
    },
    "Cortisol": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ug/dL",
            "display": "microgram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2143-6",
            "display": "Cortisol [Mass/volume] in Serum or Plasma",
        },
    },
    "PTH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg/mL",
            "display": "picogram per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2731-8",
            "display": "Parathyroid hormone.intact [Mass/volume] in Serum or Plasma",
        },
    },
    "Prolactine": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "51441-4",
            "display": "Prolactin [Mass/volume] in Serum or Plasma",
        },
    },
    "Pro BNP": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg/mL",
            "display": "picogram per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "33762-6",
            "display": "N-Terminal pro-B-type natriuretic peptide [Mass/volume] in Serum or Plasma",
        },
    },
    "Vitamine D3": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1990-1",
            "display": "25-Hydroxyvitamin D2 and D3 [Mass/volume] in Serum or Plasma (Total 25-OH D)",
        },
    },
    "Vitamine B12": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg/mL",
            "display": "picogram per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2132-9",
            "display": "Vitamin B12 [Mass/volume] in Serum or Plasma",
        },
    },
    "FSH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/L",
            "display": "international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "15067-2",
            "display": "Follicle stimulating hormone [Units/volume] in Serum or Plasma",
        },
    },
    "LH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "[IU]/L",
            "display": "international unit per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "10501-5",
            "display": "Luteinizing hormone [Units/volume] in Serum or Plasma",
        },
    },
    "PSA": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "19195-7",
            "display": "Prostate specific Ag [Mass/volume] in Serum or Plasma",
        },
    },
    "ACTH": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "pg/mL",
            "display": "picogram per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2141-0",
            "display": "Adrenocorticotropin [Mass/volume] in Serum or Plasma",
        },
    },
    "CEA": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2039-6",
            "display": "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma",
        },
    },
    "AFP": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "1834-1",
            "display": "Alpha-1-fetoprotein [Mass/volume] in Serum or Plasma",
        },
    },
    "CA125": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/mL",
            "display": "enzyme unit per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "10334-1",
            "display": "Cancer Ag 125 [Units/volume] in Serum or Plasma",
        },
    },
    "CA19.9": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/mL",
            "display": "enzyme unit per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2009-9",
            "display": "Cancer Ag 19-9 [Units/volume] in Serum or Plasma",
        },
    },
    "Testosterone ": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/dL",
            "display": "nanogram per deciliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2986-8",
            "display": "Testosterone [Mass/volume] in Serum or Plasma",
        },
    },
    "Progestrone": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "ng/mL",
            "display": "nanogram per millliiter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2839-9",
            "display": "Progesterone [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum IgG": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/L",
            "display": "gram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2465-3",
            "display": "Immunoglobulin G [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum IgE": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "U/mL",
            "display": "enzyme unit per milliliter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "19113-0",
            "display": "Immunoglobulin E [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum IgM": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/L",
            "display": "gram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2472-9",
            "display": "Immunoglobulin M [Mass/volume] in Serum or Plasma",
        },
    },
    "Serum IgA": {
        "unit": {
            "system": "http://unitsofmeasure.org",
            "code": "g/L",
            "display": "gram per liter",
        },
        "code": {
            "system": "http://loinc.org",
            "code": "2458-8",
            "display": "Immunoglobulin A [Mass/volume] in Serum or Plasma",
        },
    },
}

urine_test = {
    "Colour": {
        "code": {
            "system": "http://loinc.org",
            "code": "5778-6",
            "display": "Color of Urine",
        }
    },
    "Appearence": {
        "code": {
            "system": "http://loinc.org",
            "code": "5767-9",
            "display": "Appearance of Urine",
        }
    },
    "Ph": {
        "code": {
            "system": "http://loinc.org",
            "code": "2756-5",
            "display": "pH of Urine",
        }
    },
    "Specific Gravity": {
        "code": {
            "system": "http://loinc.org",
            "code": "2965-2",
            "display": "Specific gravity of Urine",
        }
    },
    "Nitrite": {
        "code": {
            "system": "http://loinc.org",
            "code": "5802-4",
            "display": "Nitrite [Presence] in Urine by Test strip",
        }
    },
    "Urobilinogen": {
        "code": {
            "system": "http://loinc.org",
            "code": "3107-0",
            "display": "Urobilinogen [Semi-quantitative] in Urine by Test strip",
        }
    },
    "Bile Salt": {},
    "Bile Pigment": {
        "code": {
            "system": "http://loinc.org",
            "code": "5770-3",
            "display": "Bilirubin.total [Presence] in Urine by Test strip",
        }
    },
    "Acetone": {
        "code": {
            "system": "http://loinc.org",
            "code": "33903-6",
            "display": "Ketones [Presence] in Urine by Test strip",
        }
    },
    "Sugar": {
        "code": {
            "system": "http://loinc.org",
            "code": "2345-7",
            "display": "Glucose [Mass/volume] in Serum or Plasma (when not otherwise specified)",
        }
    },
    "Puscells": {
        "code": {
            "system": "http://loinc.org",
            "code": "5821-4",
            "display": "Leukocytes [#/area] in Urine sediment by Microscopy (HPF)",
        }
    },
    "Epithetical Cells": {
        "code": {
            "system": "http://loinc.org",
            "code": "105113-5",
            "display": "Epithelial cells [#/area] in Urine sediment by Microscopy (HPF)",
        }
    },
    "RBC ": {},
    "Cast": {
        "code": {
            "system": "http://loinc.org",
            "code": "58436-7",
            "display": "Casts [Type] in Urine sediment by Microscopy",
        }
    },
    "Crystal": {},
    "others": {},
    "UPT": {
        "code": {
            "system": "http://loinc.org",
            "code": "2106-3",
            "display": "Chorionic gonadotropin [Presence] in Urine by Test strip",
        }
    },
    "Stool OB": {
        "code": {
            "system": "http://loinc.org",
            "code": "50196-5",
            "display": "Occult blood [Presence] in Stool by Guaiac",
        }
    },
    "Stool Microscopy": {
        "code": {
            "system": "http://loinc.org",
            "code": "8250-3",
            "display": "Ova and parasites identified in Stool by Light microscopy",
        }
    },
}


def get_questions(group):
    return [
        {
            "id": deterministic_uuid(test),
            "link_id": f"1.{i+1}",
            "text": test,
            "type": "decimal" if detail.get("unit", None) else "string",
            "code": detail.get("code", None),
            "unit": detail.get("unit", None),
        }
        for i, (test, detail) in enumerate(group.items())
    ]


def migrate_investigations(apps, schema_editor):
    from care.facility.utils import disable_auto_time
    from care.emr.models import (
        Questionnaire,
        QuestionnaireResponse,
        Observation,
        QuestionnaireOrganization,
        Organization,
        Encounter,
    )

    enable_auto_time = disable_auto_time(
        Questionnaire,
        QuestionnaireResponse,
        Observation,
        QuestionnaireOrganization,
        Organization,
    )

    InvestigationValue = apps.get_model("facility", "InvestigationValue")
    InvestigationSession = apps.get_model("facility", "InvestigationSession")
    User = apps.get_model("users", "User")
    fallback_care_user, _ = User.objects.get_or_create(
        username="careuser",
        defaults={
            "first_name": "Care",
            "last_name": "User",
            "user_type": "care_user",
            "email": "careuser@ohc.network",
            "phone_number": "",
            "is_active": False,
        },
    )

    questionnaire_defaults = {
        "status": "retired",
        "subject_type": "encounter",
        "meta": {
            "migration_id": MIGRATION_ID,
        },
    }

    bulk_questionnaire_root_link = []

    haematology_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="haematology_investigation",
        defaults={
            **questionnaire_defaults,
            "title": "Haematology Investigation",
            "description": "A questionnaire for Haematology Investigation",
            "questions": get_questions(haematology_group),
        },
    )
    if created:
        bulk_questionnaire_root_link.append(haematology_questionnaire.id)

    biochemistry_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="biochemistry_investigation",
        defaults={
            **questionnaire_defaults,
            "title": "Biochemistry Investigation",
            "description": "A questionnaire for Biochemistry Investigation",
            "questions": get_questions(biochemistry_group),
        },
    )
    if created:
        bulk_questionnaire_root_link.append(biochemistry_questionnaire.id)

    urine_test_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="urine_test_investigation",
        defaults={
            **questionnaire_defaults,
            "title": "Urine Test Investigation",
            "description": "A questionnaire for Urine Test Investigation",
            "questions": get_questions(urine_test),
        },
    )
    if created:
        bulk_questionnaire_root_link.append(urine_test_questionnaire.id)

    if bulk_questionnaire_root_link:
        root_orgs = Organization.objects.filter(
            root_org__isnull=True, org_type="role"
        ).values_list("id", flat=True)
        for org_id in root_orgs:
            for questionnaire_id in bulk_questionnaire_root_link:
                QuestionnaireOrganization.objects.get_or_create(
                    questionnaire_id=questionnaire_id,
                    organization_id=org_id,
                )

    query = (
        InvestigationSession.objects.filter()
        .prefetch_related(
            Prefetch(
                "investigationvalue_set",
                queryset=InvestigationValue.objects.select_related(
                    "consultation",
                    "group",
                    "investigation",
                ).order_by("id"),
            )
        )
        .order_by("id")
    )

    paginator = Paginator(query, 500)

    for page_number in paginator.page_range:
        for session in paginator.page(page_number).object_list:

            haematology_responses = {}
            biochemistry_responses = {}
            urine_test_responses = {}
            value = None
            encounter_id = None
            for value in session.investigationvalue_set.all():
                encounter_id = value.consultation.migrated_emr_encounter_id
                investigation_name = value.investigation.name
                if investigation_name == "Platelets":
                    # fixing for platelets value as they are currently in lakhs/uL
                    try:
                        val = int(value.value)
                        if val < 100:
                            value.value = str(val * 1_00_000)
                    except ValueError:
                        pass
                if investigation_name in haematology_group:
                    haematology_responses[deterministic_uuid(investigation_name)] = {
                        "question_id": deterministic_uuid(investigation_name),
                        "values": [{"value": value.value}],
                        "note": value.notes or None,
                    }
                elif investigation_name in biochemistry_group:
                    biochemistry_responses[deterministic_uuid(investigation_name)] = {
                        "question_id": deterministic_uuid(investigation_name),
                        "values": [{"value": value.value}],
                        "note": value.notes or None,
                    }
                elif investigation_name in urine_test:
                    urine_test_responses[deterministic_uuid(investigation_name)] = {
                        "question_id": deterministic_uuid(investigation_name),
                        "values": [{"value": value.value}],
                        "note": value.notes or None,
                    }
            if not value:
                logger.warning(
                    f"Skipping session {session.id} as it has no investigation values"
                )
                continue
            encounter = Encounter.objects.get(id=encounter_id)
            responses_obj_defaults = dict(
                patient_id=encounter.patient_id,
                encounter_id=encounter.id,
                created_by_id=session.created_by_id or fallback_care_user.id,
                updated_by_id=session.created_by_id or fallback_care_user.id,
                created_date=session.created_date,
                modified_date=session.modified_date,
                subject_id=encounter.external_id,
                meta={"migration_id": MIGRATION_ID},
            )
            observation_defaults = dict(
                subject_type="encounter",
                effective_datetime=session.created_date,
                data_entered_by_id=session.created_by_id or fallback_care_user.id,
                created_by_id=session.created_by_id or fallback_care_user.id,
                updated_by_id=session.created_by_id or fallback_care_user.id,
                encounter_id=encounter.id,
                patient_id=encounter.patient_id,
                subject_id=encounter.external_id,
                created_date=session.created_date,
                modified_date=session.created_date,
                meta={"migration_id": MIGRATION_ID},
            )

            observations_objects = []

            if haematology_responses:
                haematology_questionnaire_response = (
                    QuestionnaireResponse.objects.create(
                        **responses_obj_defaults,
                        questionnaire_id=haematology_questionnaire.id,
                        responses=list(haematology_responses.values()),
                    )
                )
                haematology_observations = convert_to_observation_spec(
                    {"questions": haematology_questionnaire.questions},
                    haematology_responses,
                )
                for observation in haematology_observations:
                    observation.update(observation_defaults)
                    try:
                        observations_objects.append(
                            ObservationSpec(
                                **observation,
                                questionnaire_response_id=haematology_questionnaire_response.id,
                            ).de_serialize()
                        )
                    except Exception as e:
                        print(e, observation)
                        raise e

            if biochemistry_responses:
                biochemistry_questionnaire_response = (
                    QuestionnaireResponse.objects.create(
                        **responses_obj_defaults,
                        questionnaire_id=biochemistry_questionnaire.id,
                        responses=list(biochemistry_responses.values()),
                    )
                )
                biochemistry_observations = convert_to_observation_spec(
                    {"questions": biochemistry_questionnaire.questions},
                    biochemistry_responses,
                )
                for observation in biochemistry_observations:
                    observation.update(observation_defaults)
                    try:
                        observations_objects.append(
                            ObservationSpec(
                                **observation,
                                questionnaire_response_id=biochemistry_questionnaire_response.id,
                            ).de_serialize()
                        )
                    except Exception as e:
                        print(e, observation)
                        raise e

            if urine_test_responses:
                urine_test_questionnaire_response = (
                    QuestionnaireResponse.objects.create(
                        **responses_obj_defaults,
                        questionnaire_id=urine_test_questionnaire.id,
                        responses=list(urine_test_responses.values()),
                    )
                )
                urine_test_observations = convert_to_observation_spec(
                    {"questions": urine_test_questionnaire.questions},
                    urine_test_responses,
                )
                for observation in urine_test_observations:
                    observation.update(observation_defaults)
                    try:
                        observations_objects.append(
                            ObservationSpec(
                                **observation,
                                questionnaire_response_id=urine_test_questionnaire_response.id,
                            ).de_serialize()
                        )
                    except Exception as e:
                        print(e, observation)
                        raise e

            if observations_objects:
                Observation.objects.bulk_create(observations_objects)

    enable_auto_time()


def reverse_migrate_investigations(apps, schema_editor): ...


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0493_merge_20250522_1240"),
    ]

    operations = [
        migrations.RunPython(
            migrate_investigations,
            reverse_migrate_investigations,
        ),
    ]
