# Generated by Django 5.1.4 on 2025-07-01 06:21

import uuid
from django.db import migrations


MIGRATION_ID = 158445695210


def deterministic_uuid(string):
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, string))


shifting_status_map = {
    10: "Pending",
    15: "On hold",
    20: "Approved",
    30: "Rejected",
    40: "Destination approved",
    50: "Destination rejected",
    55: "Transportation to be arranged",
    60: "Patient to be picked up",
    70: "Transfer in progress",
    80: "Completed",
    90: "Patient expired",
    100: "Cancelled",
}


questions = [
    {
        "id": deterministic_uuid("origin_facility"),
        "link_id": "origin_facility",
        "text": "Current facility",
        "type": "string",
    },
    {
        "id": deterministic_uuid("assigned_facility"),
        "link_id": "assigned_facility",
        "text": "Destination facility",
        "type": "string",
    },
    {
        "id": deterministic_uuid("emergency"),
        "link_id": "emergency",
        "text": "Is Emergency shifting",
        "type": "boolean",
    },
    {
        "id": deterministic_uuid("is_up_shift"),
        "link_id": "is_up_shift",
        "text": "Up-shift to higher care level",
        "type": "boolean",
    },
    {
        "id": deterministic_uuid("reason"),
        "link_id": "reason",
        "text": "Reason for shifting",
        "type": "string",
    },
    {
        "id": deterministic_uuid("comments"),
        "link_id": "comments",
        "text": "Additional notes",
        "type": "string",
    },
    {
        "id": deterministic_uuid("refering_facility_contact_name"),
        "link_id": "refering_facility_contact_name",
        "text": "Contact person name",
        "type": "string",
    },
    {
        "id": deterministic_uuid("refering_facility_contact_number"),
        "link_id": "refering_facility_contact_number",
        "text": "Contact phone number",
        "type": "string",
    },
    {
        "id": deterministic_uuid("status"),
        "link_id": "status",
        "text": "Shifting status",
        "type": "string",
    },
    {
        "id": deterministic_uuid("ambulance_driver_name"),
        "link_id": "ambulance_driver_name",
        "text": "Ambulance driver name",
        "type": "string",
    },
    {
        "id": deterministic_uuid("ambulance_phone_number"),
        "link_id": "ambulance_phone_number",
        "text": "Ambulance driver phone",
        "type": "string",
    },
    {
        "id": deterministic_uuid("ambulance_number"),
        "link_id": "ambulance_number",
        "text": "Ambulance registration number",
        "type": "string",
    },
]


def migrate_shifting_request(apps, schema_editor):
    from care.facility.utils import disable_auto_time
    from care.emr.models import (
        Questionnaire,
        QuestionnaireResponse,
        QuestionnaireOrganization,
        Organization,
        Patient,
    )

    enable_auto_time = disable_auto_time(
        Questionnaire,
        QuestionnaireResponse,
    )

    ShiftingRequest = apps.get_model("facility", "ShiftingRequest")

    User = apps.get_model("users", "User")
    fallback_care_user, _ = User.objects.get_or_create(
        username="careuser",
        defaults={
            "first_name": "Care",
            "last_name": "User",
            "user_type": "care_user",
            "email": "careuser@ohc.network",
            "phone_number": "",
            "is_active": False,
        },
    )

    referral_questionnaire, created = Questionnaire.objects.get_or_create(
        slug="referral_4c5b",
        defaults={
            "title": "Referral",
            "description": "Patient referral form",
            "status": "retired",
            "subject_type": "patient",
            "meta": {
                "migration_id": MIGRATION_ID,
            },
            "questions": questions,
        },
    )

    if created:
        root_orgs = Organization.objects.filter(
            root_org__isnull=True, org_type="role"
        ).values_list("id", flat=True)
        for org_id in root_orgs:
            QuestionnaireOrganization.objects.get_or_create(
                questionnaire_id=referral_questionnaire.id,
                organization_id=org_id,
            )

    query = ShiftingRequest.objects.select_related(
        "patient",
        "origin_facility",
        "assigned_facility",
    ).all()

    char_fields = [
        "reason",
        "comments",
        "refering_facility_contact_name",
        "refering_facility_contact_number",
        "ambulance_driver_name",
        "ambulance_phone_number",
        "ambulance_number",
    ]

    bool_fields = [
        "emergency",
        "is_up_shift",
    ]

    bulk_responses = []
    for shifting_request in query:
        patient = Patient.objects.get(
            id=shifting_request.patient.migrated_emr_patient_id
        )
        responses = []
        for field in char_fields:
            value = getattr(shifting_request, field, "")
            if value:
                responses.append(
                    {
                        "question_id": deterministic_uuid(field),
                        "values": [{"value": value}],
                    }
                )
        for field in bool_fields:
            value = getattr(shifting_request, field)
            if value is not None:
                responses.append(
                    {
                        "question_id": deterministic_uuid(field),
                        "values": [{"value": value}],
                    }
                )
        responses.append(
            {
                "question_id": deterministic_uuid("status"),
                "values": [
                    {
                        "value": shifting_status_map.get(
                            getattr(shifting_request, "status", 10), "Pending"
                        )
                    }
                ],
            }
        )
        if shifting_request.origin_facility:
            responses.append(
                {
                    "question_id": deterministic_uuid("assigned_facility"),
                    "values": [
                        {
                            "value": str(shifting_request.origin_facility.name)
                        }
                    ],
                }
            )

        if shifting_request.assigned_facility_external:
            responses.append(
                {
                    "question_id": deterministic_uuid("assigned_facility"),
                    "values": [
                        {
                            "value": str(shifting_request.assigned_facility_external)
                        }
                    ],
                }
            )
        elif shifting_request.assigned_facility:
            responses.append(
                {
                    "question_id": deterministic_uuid("assigned_facility"),
                    "values": [
                        {
                            "value": str(shifting_request.assigned_facility.name)
                        }
                    ],
                }
            )

        bulk_responses.append(
            QuestionnaireResponse(
                questionnaire=referral_questionnaire,
                patient_id=patient.id,
                subject_id=patient.external_id,
                created_by_id=shifting_request.created_by_id or fallback_care_user.id,
                updated_by_id=shifting_request.last_edited_by_id or fallback_care_user.id,
                created_date=shifting_request.created_date,
                modified_date=shifting_request.modified_date,
                meta={"migration_id": MIGRATION_ID},
                questionnaire_id=referral_questionnaire.id,
                responses=responses,
            )
        )
    QuestionnaireResponse.objects.bulk_create(bulk_responses)

    enable_auto_time()


def reverse_migrate_shifting_request(apps, schema_editor):
    Questionnaire = apps.get_model("emr", "Questionnaire")
    Questionnaire.objects.filter(meta__migration_id=MIGRATION_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0494_migrate_investigations"),
    ]

    operations = [
        migrations.RunPython(
            migrate_shifting_request,
            reverse_code=reverse_migrate_shifting_request,
            atomic=True,
        ),
    ]
