import environ

env = environ.Env()

MAX_APPOINTMENTS_PER_PATIENT = env.int("MAX_APPOINTMENTS_PER_PATIENT", default=10)

MAX_ACTIVE_ENCOUNTERS_PER_PATIENT = env.int(
    "MAX_ACTIVE_ENCOUNTERS_PER_PATIENT", default=5
)

# Maximum file upload size in MB
MAX_FILE_UPLOAD_SIZE = env.int("MAX_FILE_UPLOAD_SIZE", default=5)

LOCATION_MAX_DEPTH = env.int("LOCATION_MAX_DEPTH", default=10)

ORGANIZATION_MAX_DEPTH = env.int("ORGANIZATION_MAX_DEPTH", default=10)

FACILITY_ORGANIZATION_MAX_DEPTH = env.int("FACILITY_ORGANIZATION_MAX_DEPTH", default=10)

MAX_LOCATION_IN_FACILITY = env.int("MAX_LOCATION_IN_FACILITY", default=1000)

MAX_ORGANIZATION_IN_FACILITY = env.int("MAX_ORGANIZATION_IN_FACILITY", default=1000)

MAX_SLOTS_PER_AVAILABILITY = env.int("MAX_SLOTS_PER_AVAILABILITY", default=30)

MAX_QUESTIONNAIRE_TEXT_RESPONSE_SIZE = env.int(
    "MAX_QUESTIONNAIRE_TEXT_RESPONSE_SIZE", default=500
)
