# Generated by Django 4.2.2 on 2023-07-20 17:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("abdm", "0001_initial"),
        ("abdm", "0002_auto_20221220_2312"),
        ("abdm", "0003_auto_20221220_2321"),
        ("abdm", "0004_auto_20221220_2325"),
        ("abdm", "0005_auto_20221220_2327"),
        ("abdm", "0006_auto_20230208_0915"),
        ("abdm", "0007_alter_abhanumber_id"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbhaNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("abha_number", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("first_name", models.TextField(blank=True, null=True)),
                ("health_id", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField(blank=True, null=True)),
                ("middle_name", models.TextField(blank=True, null=True)),
                ("profile_photo", models.TextField(blank=True, null=True)),
                ("txn_id", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.TextField(blank=True, null=True)),
                ("district", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("pincode", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
