# Generated by Django 2.2.11 on 2022-12-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abhanumber",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="first_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="last_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="middle_name",
            field=models.CharField(max_length=512),
        ),
    ]
