# Generated by Django 2.2.11 on 2022-12-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0002_auto_20221220_2312"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abhanumber",
            name="password",
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="profile_photo",
            field=models.TextField(),
        ),
    ]
