# Generated by Django 2.2.11 on 2022-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0003_auto_20221220_2321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abhanumber",
            name="abha_number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="health_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="last_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="middle_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="refresh_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="abhanumber",
            name="txn_id",
            field=models.TextField(),
        ),
    ]
