# Generated by Django 2.2.11 on 2023-02-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0005_auto_20221220_2327"),
    ]

    operations = [
        migrations.AddField(
            model_name="abhanumber",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abhanumber",
            name="date_of_birth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abhanumber",
            name="district",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abhanumber",
            name="gender",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abhanumber",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abhanumber",
            name="pincode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abhanumber",
            name="state",
            field=models.TextField(blank=True, null=True),
        ),
    ]
