# Generated by Django 4.2.2 on 2023-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0006_auto_20230208_0915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abhanumber",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
