# Generated by Django 4.2.2 on 2023-08-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0001_initial_squashed_0007_alter_abhanumber_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="abhanumber",
            name="new",
            field=models.BooleanField(default=False),
        ),
    ]
