# Generated by Django 4.2.2 on 2023-08-21 09:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0378_consultationbedasset_consultationbed_assets"),
        ("abdm", "0008_abhanumber_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("hf_id", models.CharField(max_length=50, unique=True)),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facility.facility",
                        to_field="external_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
