# Generated by Django 4.2.2 on 2023-08-30 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0008_consent"),
        ("abdm", "0009_healthfacility"),
    ]

    operations = []
