# Generated by Django 4.2.2 on 2023-09-26 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0010_alter_abhanumber_abha_number_and_more"),
        ("abdm", "0010_healthfacility_registered"),
    ]

    operations = []
