# Generated by Django 4.2.10 on 2024-04-21 17:40

# This is a replacement migration for abdm.0013 that omits the RunPython operation (reverse_patient_abhanumber_relation) and facility migration dependency.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0012_consentrequest_status"),
    ]

    replaces = [
        ("abdm", "0013_abhanumber_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="abhanumber",
            name="patient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="abha_number",
                to="facility.patientregistration",
            ),
        ),
    ]
