# Generated by Django 5.1.3 on 2025-01-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=35),
        ),
    ]
