# Generated by Django 5.1.3 on 2025-01-08 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_questionnaire_tags_questionnairetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairetag',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
