# Generated by Django 5.1.3 on 2025-01-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_alter_patient_gender'),
        ('emr', '0003_questionnairetag_slug'),
    ]

    operations = [
    ]
