# Generated by Django 5.1.4 on 2025-01-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_alter_patient_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationrequest',
            name='authored_on',
        ),
        migrations.RemoveField(
            model_name='medicationrequest',
            name='status_changed',
        ),
    ]
