# Generated by Django 5.1.4 on 2025-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_remove_medicationrequest_authored_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequest',
            name='medication',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
