# Generated by Django 5.1.4 on 2025-01-21 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_medicationrequest_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequest',
            name='authored_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
