# Generated by Django 5.1.4 on 2025-01-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0011_medicationrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.encounter'),
        ),
    ]
