# Generated by Django 5.1.4 on 2025-02-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0015_facilitylocation_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyintolerance',
            name='copied_from',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
