# Generated by Django 5.1.4 on 2025-02-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0016_allergyintolerance_copied_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitylocation',
            name='availability_status',
        ),
        migrations.AddField(
            model_name='facilitylocation',
            name='current_encounter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.encounter'),
        ),
    ]
