# Generated by Django 5.1.4 on 2025-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0017_device_deviceencounterhistory_devicelocationhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='care_type',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=16),
        ),
    ]
