# Generated by Django 5.1.4 on 2025-02-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0018_consent_device_deviceencounterhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
