# Generated by Django 5.1.4 on 2025-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0019_consent_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='component',
            field=models.JSONField(default=list),
        ),
    ]
