# Generated by Django 5.1.4 on 2025-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0021_metaartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylocation',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
