# Generated by Django 5.1.4 on 2025-03-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0022_facilitylocation_sort_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyintolerance',
            name='type',
            field=models.CharField(default='allergy', max_length=100),
        ),
        migrations.AddField(
            model_name='encounter',
            name='discharge_summary_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
