# Generated by Django 5.1.4 on 2025-03-24 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0024_merge_20250320_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='treating_doctors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
    ]
