# Generated by Django 5.1.4 on 2025-04-02 08:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0025_alter_tokenbooking_token_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='treating_doctors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
