# Generated by Django 5.1.4 on 2025-04-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0026_encounter_treating_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='treating_doctors',
            new_name='care_team',
        ),
    ]
