# Generated by Django 5.1.4 on 2025-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0027_rename_treating_doctors_encounter_care_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='care_team',
        ),
        migrations.AddField(
            model_name='encounter',
            name='care_team',
            field=models.JSONField(default=dict),
        )
    ]
