# Generated by Django 5.1.4 on 2025-04-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0028_alter_encounter_care_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='discharge_summary_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
