# Generated by Django 5.1.4 on 2025-04-02 11:36

from django.db import migrations, models
from django.core.paginator import Paginator

def fill_encounter_identifiers(apps, schema_editor):
    Encounter = apps.get_model('emr', 'Encounter')
    queryset = Encounter.objects.exclude(
        external_identifier__isnull=True,
        external_identifier__exact='',
    ).order_by('id')
    paginator = Paginator(queryset, 1000)
    for page in paginator.page_range:
        bulk = []
        encounters = paginator.page(page).object_list
        for encounter in encounters:
            encounter.identifiers = [
                {
                    "value": encounter.external_identifier,
                    "use": "official",
                    "type": {
                        #TODO: update to use the correct code available in snowstorm
                        "system": "http://snomed.info/sct",
                        "code": "MR",
                        "display": "Medical record number",
                    },
                }
            ]
            bulk.append(encounter)
        Encounter.objects.bulk_update(bulk, ['identifiers'])

class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0028_alter_encounter_care_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="identifiers",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(fill_encounter_identifiers, reverse_code=migrations.RunPython.noop),
    ]
