# Generated by Django 5.1.4 on 2025-05-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0029_encounter_discharge_summary_advice"),
        ("facility", "0477_alter_facility_facility_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="facility.facility",
            ),
        ),
    ]
