# Generated by Django 5.1.4 on 2025-06-20 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0029_encounter_discharge_summary_advice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenbooking",
            name="token_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="emr.tokenslot",
            ),
        ),
    ]
