# Generated by Django 5.1.4 on 2025-06-20 08:07

from django.db import migrations

def add_display_to_answer_options(apps, schema_editor):
    Questionnaire = apps.get_model("emr", "Questionnaire")

    for questionnaire in Questionnaire.objects.all():
        updated = False
        questions = questionnaire.questions

        def update_question(question):
            nonlocal updated

            # If answer_option exists
            if "answer_option" in question:
                for option in question["answer_option"]:
                    if "display" not in option:
                        option["display"] = option["value"]
                        updated = True

            # If there are nested questions
            for child in question.get("questions", []):
                update_question(child)

        for question in questions:
            update_question(question)

        if updated:
            questionnaire.questions = questions
            questionnaire.save(update_fields=["questions"])


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0029_encounter_discharge_summary_advice'),
    ]

    operations = [
        migrations.RunPython(add_display_to_answer_options),
    ]
