# Generated by Django 5.1.4 on 2025-04-29 05:59

from django.db import migrations, transaction

from care.emr.resources.template.spec import FacilityReportTemplateType
from care.utils.reports.load_default_report_config import load_default_discharge_summary_config


def add_default_summary_report_config_to_facility(apps, schema_editor):
    Facility = apps.get_model("facility", "Facility")
    FacilityReportTemplate = apps.get_model("emr", "FacilityReportTemplate")

    default_config = load_default_discharge_summary_config()

    batch_size = 100
    facilities = Facility.objects.all()
    total_facilities = facilities.count()

    for i in range(0, total_facilities, batch_size):
        batch_facilities = facilities[i:i+batch_size]
        with transaction.atomic():
            for facility in batch_facilities:
                FacilityReportTemplate.objects.get_or_create(
                    facility=facility,
                    type=FacilityReportTemplateType.discharge_summary,
                    defaults={"config": default_config},)

class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0030_facilityreporttemplate'),
    ]

    operations = [
        migrations.RunPython(add_default_summary_report_config_to_facility, migrations.RunPython.noop),
    ]
