# Generated by Django 5.1.4 on 2025-07-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0030_encounter_tags_medicationrequest_dispense_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tokenbooking",
            old_name="reason_for_visit",
            new_name="note",
        ),
    ]
