# Generated by Django 5.1.4 on 2025-08-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0032_tokenbooking_associated_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdefinition',
            name='qualified_ranges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
