# Generated by Django 5.1.4 on 2025-05-24 20:58
from django.db import migrations

def move_discharge_summary_to_report(apps, schema_editor):
    FileUpload = apps.get_model('emr', 'FileUpload')
    Report = apps.get_model('emr', 'Report')

    discharge_summaries = FileUpload.objects.filter(file_category="discharge_summary")

    reports = []
    for discharge_summary in discharge_summaries:
        reports.append(Report(
            file_type="discharge_summary",
            associating_id=discharge_summary.associating_id,
            name=discharge_summary.name,
            internal_name=discharge_summary.internal_name,
            original_name=discharge_summary.original_name,
            upload_completed=discharge_summary.upload_completed,
            is_archived=discharge_summary.is_archived,
            archive_reason=discharge_summary.archive_reason,
            archived_datetime=discharge_summary.archived_datetime,
            archived_by=discharge_summary.archived_by,
            meta=discharge_summary.meta,
            created_by=discharge_summary.created_by,
            created_date=discharge_summary.created_date,
            updated_by=discharge_summary.updated_by,
            updated_date=discharge_summary.updated_date,
        ))

    Report.objects.bulk_create(reports)
    discharge_summaries.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0031_report'),
    ]

    operations = [
        migrations.RunPython(move_discharge_summary_to_report, migrations.RunPython.noop),
    ]
