# Generated by Django 5.1.4 on 2025-04-21 17:53

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0031_alter_observationdefinition_body_site_and_more'),
        ('facility', '0476_facility_default_internal_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdefinition',
            name='body_site',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='component',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='method',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='permitted_unit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('slug', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1024)),
                ('subtitle', models.CharField(max_length=1024)),
                ('category', models.JSONField(blank=True, null=True)),
                ('derived_from_uri', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('purpose', models.TextField()),
                ('usage', models.TextField()),
                ('kind', models.CharField(max_length=100)),
                ('code', models.JSONField(blank=True, null=True)),
                ('body_site', models.JSONField(blank=True, null=True)),
                ('specimen_requirement', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('observation_result_requirement', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
