# Generated by Django 5.1.4 on 2025-08-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0032_tokenbooking_associated_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareservice',
            name='managing_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.facilityorganization'),
        ),
    ]
