# Generated by Django 5.1.4 on 2025-08-18 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0033_healthcareservice_managing_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulableuserresource',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.healthcareservice'),
        ),
        migrations.AddField(
            model_name='schedulableuserresource',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.facilitylocation'),
        ),
        migrations.AddField(
            model_name='schedulableuserresource',
            name='resource_type',
            field=models.CharField(default='practitioner', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulableuserresource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
