# Generated by Django 5.1.4 on 2025-09-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0034_token_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagconfig',
            name='slug',
        ),
    ]
