# Generated by Django 5.1.4 on 2025-08-18 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0034_schedulableuserresource_healthcare_service_and_more'),
        ('facility', '0478_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchedulableUserResource',
            new_name='SchedulableResource',
        ),
    ]
