# Generated by Django 5.1.4 on 2025-08-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0034_servicerequest_requestor'),
        ('emr', '0035_rename_schedulableuserresource_schedulableresource'),
    ]

    operations = [
    ]
