# Generated by Django 5.1.4 on 2025-04-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0035_healthcareservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='category',
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.healthcareservice'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.healthcareservice'),
        ),
    ]
