# Generated by Django 5.1.4 on 2025-09-28 10:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_orders(apps, schema_editor):
    DeliveryOrder = apps.get_model('emr', 'DeliveryOrder')
    RequestOrder = apps.get_model('emr', 'RequestOrder')
    SupplyRequest = apps.get_model('emr', 'SupplyRequest')
    SupplyDelivery = apps.get_model('emr', 'SupplyDelivery')

    for supply_request in SupplyRequest.objects.filter(order__isnull=False):
        order = RequestOrder.objects.create(
            name="Migrated Order",
            status="completed",
            supplier=supply_request.supplier,
            origin=supply_request.deliver_from,
            destination=supply_request.deliver_to,
            intent=supply_request.intent,
            category=supply_request.category,
            priority=supply_request.priority,
            reason=supply_request.reason,
        )
        supply_request.order = order
        supply_request.save()
    for supply_delivery in SupplyDelivery.objects.filter(order__isnull=False):
        order = DeliveryOrder.objects.create(
            name="Migrated Order",
            status="completed",
            supplier=supply_delivery.supplier,
            origin=supply_delivery.origin,
            destination=supply_delivery.destination
        )
        supply_delivery.order = order
        supply_delivery.save()



class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0036_deliveryorder_supplydelivery_order_dispenseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='destination_delivery_orders', to='emr.facilitylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_delivery_orders', to='emr.facilitylocation'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.organization'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='destination_request_orders', to='emr.facilitylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='intent',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_request_orders', to='emr.facilitylocation'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='priority',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='reason',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.organization'),
        ),
        migrations.RemoveField(
            model_name='requestorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='location',
        ),
        migrations.RunPython(migrate_orders, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='supplydelivery',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='supplydelivery',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='supplydelivery',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='deliver_from',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='deliver_to',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='supplier',
        ),
    ]
