# Generated by Django 5.1.4 on 2025-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0036_remove_servicerequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(default="unk", max_length=255),
            preserve_default=False,
        ),
    ]
