# Generated by Django 5.1.4 on 2025-09-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0037_deliveryorder_destination_deliveryorder_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.facilitylocation'),
        ),
    ]
