# Generated by Django 5.1.4 on 2025-08-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0038_merge_20250821_1820'),
        ('facility', '0478_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensubqueue',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
            preserve_default=False,
        ),
    ]
