# Generated by Django 5.1.4 on 2025-04-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0038_servicerequest_activity_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='accession_identifier',
        ),
        migrations.AddField(
            model_name='specimen',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.servicerequest'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='specimen_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.specimendefinition'),
        ),
    ]
