# Generated by Django 5.1.4 on 2025-11-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0039_formsubmission_questionnaireresponse_form_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='interpretation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
