# Generated by Django 5.1.4 on 2025-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0039_tokensubqueue_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencategory',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
