# Generated by Django 5.1.4 on 2025-04-24 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0039_remove_specimen_accession_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='accession_identifier',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
