# Generated by Django 5.1.4 on 2025-08-22 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0040_tokencategory_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbooking',
            name='token',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.token'),
        ),
    ]
