# Generated by Django 5.1.4 on 2025-12-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0040_alter_observation_interpretation'),
        ('emr', '0041_template_options'),
    ]

    operations = [
    ]
