# Generated by Django 5.1.4 on 2025-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0041_remove_specimen_accession_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='accession_identifier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
