# Generated by Django 5.1.4 on 2025-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0041_rename_format_to_default_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='context_config',
        ),
        migrations.AddField(
            model_name='template',
            name='context',
            field=models.CharField(default='encounter_base', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
