# Generated by Django 5.1.4 on 2025-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0042_merge_20251209_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_billable_charge_items',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
