# Generated by Django 5.1.4 on 2025-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0042_specimen_accession_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='accession_identifier',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
