# Generated by Django 5.1.4 on 2025-08-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0043_remove_token_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.patient'),
        ),
    ]
