# Generated by Django 5.1.4 on 2025-08-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0044_token_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='charge_item_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.chargeitemdefinition'),
        ),
    ]
