# Generated by Django 5.1.4 on 2025-12-12 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0044_chargeitem_paid_on'),
        ('facility', '0481_delete_asset_delete_assetbed_delete_bed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenseorder',
            name='alternate_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='dispenseorder',
            constraint=models.UniqueConstraint(fields=('alternate_identifier', 'patient', 'location'), name='unique_alternate_identifier_encounter_location'),
        ),
    ]
