# Generated by Django 5.1.4 on 2025-04-26 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0044_diagnosticreport_observation_diagnostic_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='encounter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emr.encounter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='service_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emr.servicerequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='data_entered_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations_entered', to=settings.AUTH_USER_MODEL),
        ),
    ]
