# Generated by Django 5.1.4 on 2025-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0045_dispenseorder_alternate_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenseorder',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
