# Generated by Django 5.1.4 on 2025-08-25 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0045_schedule_charge_item_definition'),
        ('facility', '0478_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedulableresource',
            constraint=models.UniqueConstraint(fields=('facility', 'resource_type', 'user'), name='unique_facility_resource_user'),
        ),
        migrations.AddConstraint(
            model_name='schedulableresource',
            constraint=models.UniqueConstraint(fields=('facility', 'resource_type', 'location'), name='unique_facility_resource_location'),
        ),
        migrations.AddConstraint(
            model_name='schedulableresource',
            constraint=models.UniqueConstraint(fields=('facility', 'resource_type', 'healthcare_service'), name='unique_facility_resource_healthcare_service'),
        ),
    ]
