# Generated by Django 5.1.4 on 2025-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0046_observation_observation_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='effective_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
