# Generated by Django 5.1.4 on 2025-08-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0046_schedulableresource_unique_facility_resource_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbooking',
            name='charge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.chargeitem'),
        ),
        migrations.AddField(
            model_name='tokensubqueue',
            name='current_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.token'),
        ),
        migrations.AddField(
            model_name='tokensubqueue',
            name='status',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.encounter'),
        ),
    ]
