# Generated by Django 5.1.4 on 2025-12-12 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0046_alter_dispenseorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
