# Generated by Django 5.1.4 on 2025-09-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0047_tokenbooking_charge_item_tokensubqueue_current_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='revisit_allowed_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='revisit_charge_item_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_revisit_charge_item_definition', to='emr.chargeitemdefinition'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='charge_item_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_charge_item_definition', to='emr.chargeitemdefinition'),
        ),
    ]
