# Generated by Django 5.1.4 on 2025-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0047_account_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
