# Generated by Django 5.1.4 on 2025-12-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0048_product_additional_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='additional_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='additional_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
