# Generated by Django 5.1.4 on 2025-12-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0049_deliveryorder_additional_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryorder',
            old_name='additional_metadata',
            new_name='extensions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='additional_metadata',
            new_name='extensions',
        ),
        migrations.RenameField(
            model_name='supplydelivery',
            old_name='additional_metadata',
            new_name='extensions',
        ),
    ]
