# Generated by Django 5.1.4 on 2025-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0050_rename_additional_metadata_deliveryorder_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lock_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
