# Generated by Django 5.1.4 on 2025-04-26 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0050_alter_chargeitemdefinition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='charge_item_definitions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
