# Generated by Django 5.1.4 on 2025-09-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0050_resourcecategory_resource_sub_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydefinition',
            old_name='category',
            new_name='classification',
        ),
        migrations.AddField(
            model_name='productknowledge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.resourcecategory'),
        ),
    ]
