# Generated by Django 5.1.4 on 2025-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0050_resourcecategory_resource_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdefinition',
            name='qualified_ranges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
