# Generated by Django 6.0 on 2026-01-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0051_invoice_lock_history_invoice_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='extensions',
            field=models.JSONField(default=dict),
        ),
    ]
