# Generated by Django 5.1.4 on 2025-09-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0051_rename_category_activitydefinition_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.resourcecategory'),
        ),
    ]
