# Generated by Django 5.1.4 on 2025-04-28 14:57

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0052_chargeitem'),
        ('facility', '0476_facility_default_internal_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=100)),
                ('cancelled_reason', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('charge_items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('total_price_component', models.JSONField(default=dict)),
                ('total_net', models.FloatField(default=0)),
                ('total_gross', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.account')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.patient')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('reconciliation_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('issuer_type', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('disposition', models.TextField(blank=True, null=True)),
                ('payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('authorization', models.CharField(blank=True, max_length=1024, null=True)),
                ('tendered_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retruned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.facility')),
                ('target_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.invoice')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
