# Generated by Django 5.1.4 on 2026-01-12 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0052_account_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='chargeitem',
            name='performer_actor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='extensions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='extensions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='supplied_item_pack_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='supplied_item_pack_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
