# Generated by Django 5.1.4 on 2025-09-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0051_observationdefinition_qualified_ranges'),
        ('emr', '0052_activitydefinition_category'),
    ]

    operations = [
    ]
