# Generated by Django 5.1.4 on 2025-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0053_invoice_paymentreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargeitem',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
