# Generated by Django 5.1.4 on 2025-09-11 12:30

from django.db import migrations, models



def round_values(apps, schema_editor):
    Invoice = apps.get_model("emr", "Invoice")

    bulk = []
    for invoice in Invoice.objects.all().only("id", "total_net", "total_gross"):
        invoice.total_net = round(invoice.total_net, 2)
        invoice.total_gross = round(invoice.total_gross, 2)
        bulk.append(invoice)

    Invoice.objects.bulk_update(bulk, ["total_net", "total_gross"])


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0054_userresourcefavorites'),
    ]

    operations = [
        migrations.RunPython(round_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
