# Generated by Django 5.1.4 on 2025-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0054_chargeitem_description_chargeitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='diagnostic_report_codes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
