# Generated by Django 5.1.4 on 2026-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0054_product_standard_pack_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='calculated_monetary_components',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='configured_monetary_components',
            field=models.JSONField(default=list),
        ),
    ]
