# Generated by Django 5.1.4 on 2025-04-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0055_activitydefinition_diagnostic_report_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreconciliation',
            old_name='retruned_amount',
            new_name='returned_amount',
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='emr.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='target_invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.invoice'),
        ),
    ]
