# Generated by Django 6.0 on 2026-01-15 17:17
from care.emr.resources.charge_item.sync_charge_item_costs import sync_charge_item_costs

from django.db import migrations
from decimal import Decimal
from django.core.paginator import Paginator


def convert_to_decimal(value):
    if value is None:
        return None
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, float):
        return str(Decimal(str(value)))
    return str(Decimal(value))


def reverse_convert_to_float(value):
    if value is None:
        return None
    return float(value)


def forward_monetary_component(component):
    component["factor"] = convert_to_decimal(component.get("factor"))
    component["amount"] = convert_to_decimal(component.get("amount"))
    component["tax_included_amount"] = convert_to_decimal(
        component.get("tax_included_amount")
    )
    return component


def reverse_monetary_component(component):
    component["factor"] = reverse_convert_to_float(component.get("factor"))
    component["amount"] = reverse_convert_to_float(component.get("amount"))
    component["tax_included_amount"] = reverse_convert_to_float(
        component.get("tax_included_amount")
    )
    return component


def update_charge_item_definition_price_components(apps, schema_editor):
    print("Starting: Update ChargeItemDefinition price_components to decimal")
    ChargeItemDefinition = apps.get_model("emr", "ChargeItemDefinition")
    paginator = Paginator(
        ChargeItemDefinition.objects.order_by("id").only("id", "price_components"), 1000
    )
    for page_number in paginator.page_range:
        print(f"Processing ChargeItemDefinition page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for cid in paginator.page(page_number).object_list:
            if not cid.price_components:
                continue
            components = []
            for component in cid.price_components:
                components.append(forward_monetary_component(component))
            cid.price_components = components
            bulk_update_list.append(cid)
        ChargeItemDefinition.objects.bulk_update(bulk_update_list, ["price_components"])
    print("Done: Update ChargeItemDefinition price_components to decimal")


def reverse_update_charge_item_definition_price_components(apps, schema_editor):
    print("Starting: Reverse ChargeItemDefinition price_components to float")
    ChargeItemDefinition = apps.get_model("emr", "ChargeItemDefinition")
    paginator = Paginator(
        ChargeItemDefinition.objects.order_by("id").only("id", "price_components"), 1000
    )
    for page_number in paginator.page_range:
        print(f"Processing ChargeItemDefinition page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for cid in paginator.page(page_number).object_list:
            if not cid.price_components:
                continue
            components = []
            for component in cid.price_components:
                components.append(reverse_monetary_component(component))
            cid.price_components = components
            bulk_update_list.append(cid)
        ChargeItemDefinition.objects.bulk_update(bulk_update_list, ["price_components"])
    print("Done: Reverse ChargeItemDefinition price_components to float")


def update_resource_category_price_components(apps, schema_editor):
    print("Starting: Update ResourceCategory monetary_components to decimal")
    ResourceCategory = apps.get_model("emr", "ResourceCategory")
    paginator = Paginator(
        ResourceCategory.objects.order_by("id").only(
            "id", "calculated_monetary_components", "configured_monetary_components"
        ),
        1000,
    )
    for page_number in paginator.page_range:
        print(f"Processing ResourceCategory page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for rc in paginator.page(page_number).object_list:
            changed = False
            if rc.calculated_monetary_components:
                components = []
                for component in rc.calculated_monetary_components:
                    components.append(forward_monetary_component(component))
                rc.calculated_monetary_components = components
                changed = True
            if rc.configured_monetary_components:
                components = []
                for component in rc.configured_monetary_components:
                    components.append(forward_monetary_component(component))
                rc.configured_monetary_components = components
                changed = True
            if changed:
                bulk_update_list.append(rc)
        ResourceCategory.objects.bulk_update(
            bulk_update_list,
            ["calculated_monetary_components", "configured_monetary_components"],
        )
    print("Done: Update ResourceCategory monetary_components to decimal")


def reverse_update_resource_category_price_components(apps, schema_editor):
    print("Starting: Reverse ResourceCategory monetary_components to float")
    ResourceCategory = apps.get_model("emr", "ResourceCategory")
    paginator = Paginator(
        ResourceCategory.objects.order_by("id").only(
            "id", "calculated_monetary_components", "configured_monetary_components"
        ),
        1000,
    )
    for page_number in paginator.page_range:
        print(f"Processing ResourceCategory page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for rc in paginator.page(page_number).object_list:
            changed = False
            if rc.calculated_monetary_components:
                components = []
                for component in rc.calculated_monetary_components:
                    components.append(reverse_monetary_component(component))
                rc.calculated_monetary_components = components
                changed = True
            if rc.configured_monetary_components:
                components = []
                for component in rc.configured_monetary_components:
                    components.append(reverse_monetary_component(component))
                rc.configured_monetary_components = components
                changed = True
            if changed:
                bulk_update_list.append(rc)
        ResourceCategory.objects.bulk_update(
            bulk_update_list,
            ["calculated_monetary_components", "configured_monetary_components"],
        )
    print("Done: Reverse ResourceCategory monetary_components to float")


def update_facility_discount_monetary_components(apps, schema_editor):
    print("Starting: Update Facility discount_monetary_components to decimal")
    Facility = apps.get_model("facility", "Facility")
    paginator = Paginator(
        Facility.objects.order_by("id").only("id", "discount_monetary_components"), 1000
    )
    for page_number in paginator.page_range:
        print(f"Processing Facility page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for facility in paginator.page(page_number).object_list:
            if not facility.discount_monetary_components:
                continue
            components = []
            for component in facility.discount_monetary_components:
                components.append(forward_monetary_component(component))
            facility.discount_monetary_components = components
            bulk_update_list.append(facility)
        Facility.objects.bulk_update(bulk_update_list, ["discount_monetary_components"])
    print("Done: Update Facility discount_monetary_components to decimal")


def reverse_update_facility_discount_monetary_components(apps, schema_editor):
    print("Starting: Reverse Facility discount_monetary_components to float")
    Facility = apps.get_model("facility", "Facility")
    paginator = Paginator(
        Facility.objects.order_by("id").only("id", "discount_monetary_components"), 1000
    )
    for page_number in paginator.page_range:
        print(f"Processing Facility page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for facility in paginator.page(page_number).object_list:
            if not facility.discount_monetary_components:
                continue
            components = []
            for component in facility.discount_monetary_components:
                components.append(reverse_monetary_component(component))
            facility.discount_monetary_components = components
            bulk_update_list.append(facility)
        Facility.objects.bulk_update(bulk_update_list, ["discount_monetary_components"])
    print("Done: Reverse Facility discount_monetary_components to float")


def update_charge_item_price_components(apps, schema_editor):
    print("Starting: Update ChargeItem unit_price_components to decimal")
    ChargeItem = apps.get_model("emr", "ChargeItem")
    paginator = Paginator(
        ChargeItem.objects.order_by("id"), 1000
    )
    for page_number in paginator.page_range:
        print(f"Processing ChargeItem page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for ci in paginator.page(page_number).object_list:
            if not ci.unit_price_components:
                continue
            components = []
            for component in ci.unit_price_components:
                components.append(forward_monetary_component(component))
            ci.unit_price_components = components
            sync_charge_item_costs(ci)
            bulk_update_list.append(ci)
        ChargeItem.objects.bulk_update(bulk_update_list, ["unit_price_components"])
    print("Done: Update ChargeItem unit_price_components to decimal")


def reverse_update_charge_item_price_components(apps, schema_editor):
    print("Starting: Reverse ChargeItem unit_price_components to float")
    ChargeItem = apps.get_model("emr", "ChargeItem")
    paginator = Paginator(
        ChargeItem.objects.order_by("id"), 1000
    )
    for page_number in paginator.page_range:
        print(f"Processing ChargeItem page {page_number}/{paginator.num_pages}")
        bulk_update_list = []
        for ci in paginator.page(page_number).object_list:
            if not ci.unit_price_components:
                continue
            components = []
            for component in ci.unit_price_components:
                components.append(reverse_monetary_component(component))
            ci.unit_price_components = components
            sync_charge_item_costs(ci)
            bulk_update_list.append(ci)
        ChargeItem.objects.bulk_update(bulk_update_list, ["unit_price_components"])
    print("Done: Reverse ChargeItem unit_price_components to float")

class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0055_resourcecategory_calculated_monetary_components_and_more"),
        ("facility", "0478_facility_discount_codes_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_charge_item_definition_price_components,
            reverse_update_charge_item_definition_price_components,
        ),
        migrations.RunPython(
            update_resource_category_price_components,
            reverse_update_resource_category_price_components,
        ),
        migrations.RunPython(
            update_facility_discount_monetary_components,
            reverse_update_facility_discount_monetary_components,
        ),
        migrations.RunPython(
            update_charge_item_price_components,
            reverse_update_charge_item_price_components,
        ),
    ]
