# Generated by Django 6.0 on 2026-01-16 15:54

from django.db import migrations, models


def mark_active_locations(apps, schema_editor):
    FacilityLocation = apps.get_model('emr', 'FacilityLocation')
    FacilityLocation.objects.filter(current_encounter__isnull=False).update(availability_status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0056_monetary_components_float_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylocation',
            name='availability_status',
            field=models.CharField(default='available', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(mark_active_locations, reverse_code=migrations.RunPython.noop),
    ]
