# Generated by Django 6.0 on 2026-01-21 01:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0056_monetary_components_float_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
