# Generated by Django 5.1.4 on 2026-01-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0056_monetary_components_float_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='separately_billable',
            field=models.BooleanField(default=True),
        ),
    ]
