# Generated by Django 5.1.4 on 2025-04-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0056_rename_retruned_amount_paymentreconciliation_returned_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeitem',
            old_name='total_price_component',
            new_name='total_price_components',
        ),
        migrations.RenameField(
            model_name='chargeitem',
            old_name='unit_price_component',
            new_name='unit_price_components',
        ),
    ]
