# Generated by Django 5.1.4 on 2025-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0057_rename_total_price_component_chargeitem_total_price_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charge_items_copy',
            field=models.JSONField(default=list),
        ),
    ]
