# Generated by Django 6.0 on 2026-01-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0058_invoice_is_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='extensions',
            field=models.JSONField(default=dict),
        ),
    ]
