# Generated by Django 6.0 on 2026-01-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0057_chargeitemdefinition_tags'),
        ('emr', '0058_invoice_is_refund'),
    ]

    operations = [
    ]
