# Generated by Django 5.1.4 on 2025-05-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0059_rename_total_price_component_invoice_total_price_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitem',
            name='paid_invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.invoice'),
        ),
    ]
