# Generated by Django 5.1.4 on 2026-01-21 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0059_questionnaireresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='extensions',
            field=models.JSONField(default=dict),
        ),
    ]
