# Generated by Django 6.0 on 2026-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0060_chargeitemdefinition_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='separately_billable',
            field=models.BooleanField(default=True),
        ),
    ]
