# Generated by Django 5.1.4 on 2026-01-23 05:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0061_questionnaireresponsetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponsetemplate',
            name='available_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
