# Generated by Django 5.1.4 on 2026-01-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0062_questionnaireresponsetemplate_available_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponsetemplate',
            name='questionnaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.questionnaire'),
        ),
    ]
