# Generated by Django 5.1.4 on 2025-05-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0063_alter_productknowledge_slug_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequest',
            name='requested_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.productknowledge'),
        ),
    ]
