# Generated by Django 5.1.4 on 2026-01-25 17:01

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0063_alter_questionnaireresponsetemplate_questionnaire'),
    ]

    operations = [
        TrigramExtension()
    ]
