# Generated by Django 5.1.4 on 2026-01-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0064_auto_20260125_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='primary_encounter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.encounter'),
        ),
    ]
