# Generated by Django 5.1.4 on 2025-05-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0065_rename_defenitional_productknowledge_definitional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeitemdefinition',
            old_name='price_component',
            new_name='price_components',
        ),
    ]
