# Generated by Django 5.1.4 on 2026-01-27 16:56

import json

from django.core.paginator import Paginator
from django.db import migrations, models


def copy_interpretation_to_interpretation_new(apps, schema_editor):
    Observation = apps.get_model('emr', 'Observation')
    batch_size = 10000
    queryset = Observation.objects.filter(interpretation__isnull=False).exclude(interpretation__exact='').only('id', 'interpretation').order_by('id')
    paginator = Paginator(queryset, batch_size)

    for page_num in paginator.page_range:
        page = paginator.page(page_num)
        observations = list(page.object_list)
        for observation in observations:
            interpretation = observation.interpretation.replace("\'", "\"")
            try:
                observation.interpretation_new = json.loads(interpretation)
            except (json.JSONDecodeError, TypeError):
                observation.interpretation_new = {}
        Observation.objects.bulk_update(observations, ['interpretation_new'], batch_size=batch_size)
        print(f"Page {page_num}/{paginator.num_pages} updated ({len(observations)} records)")

class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0065_account_primary_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='interpretation_new',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(copy_interpretation_to_interpretation_new , reverse_code=migrations.RunPython.noop),
        migrations.RenameField(
            model_name='observation',
            old_name='interpretation',
            new_name='interpretation_old',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='interpretation_new',
            new_name='interpretation',
        ),
        migrations.AlterField(
            model_name='observation',
            name='interpretation_old',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
