# Generated by Django 5.1.4 on 2026-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0065_account_primary_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='separately_billable',
            field=models.BooleanField(default=True),
        ),
    ]
