# Generated by Django 5.1.4 on 2026-01-27 17:48

from django.db import migrations, models


def mark_active_locations(apps, schema_editor):
    FacilityLocation = apps.get_model('emr', 'FacilityLocation')
    FacilityLocation.objects.filter(current_encounter__isnull=False).update(system_availability_status='available')
    FacilityLocation.objects.filter(current_encounter__isnull=True).update(system_availability_status='reserved')

class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0066_observation_interpretation_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylocation',
            name='system_availability_status',
            field=models.CharField(default='available', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(mark_active_locations , reverse_code=migrations.RunPython.noop),
    ]
