# Generated by Django 5.1.4 on 2025-05-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0066_rename_price_component_chargeitemdefinition_price_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplydelivery',
            name='delivery_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_deliveries', to='emr.facilitylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_deliveries', to='emr.facilitylocation'),
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='status',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='supplied_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emr.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='supplied_item_condition',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='supplied_item_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
