# Generated by Django 6.0 on 2026-02-02 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0067_facilitylocation_system_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='care_team_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
