# Generated by Django 5.1.4 on 2025-05-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0068_supplyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyrequest',
            name='item',
        ),
    ]
