# Generated by Django 6.0 on 2026-02-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0068_encounter_care_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='can_edit_charge_item',
            field=models.BooleanField(default=True),
        ),
    ]
