# Generated by Django 6.0 on 2026-02-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0069_chargeitemdefinition_can_edit_charge_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productknowledge',
            name='names_cache',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
