# Generated by Django 5.1.4 on 2025-05-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0069_remove_supplyrequest_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emr.productknowledge'),
            preserve_default=False,
        ),
    ]
