# Generated by Django 5.1.4 on 2025-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0070_supplyrequest_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareservice',
            name='internal_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
