# Generated by Django 6.0 on 2026-02-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0071_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='supplydelivery',
            name='total_purchase_price',
        ),
    ]
