# Generated by Django 5.1.4 on 2025-05-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0073_medicationdispense'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdispense',
            name='charge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.chargeitem'),
        ),
    ]
