# Generated by Django 6.0 on 2026-03-01 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_facility_monetory_config(apps, schema_editor):
    Facility = apps.get_model('facility', 'Facility')
    FacilityMonetoryConfig = apps.get_model('emr', 'FacilityMonetoryConfig')
    for facility in Facility.objects.all():
        FacilityMonetoryConfig.objects.create(
            facility=facility,
            discount_codes=facility.discount_codes,
            discount_monetary_components=facility.discount_monetary_components,
            invoice_number_expression=facility.invoice_number_expression,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0073_product_purchase_price_and_more'),
        ('facility', '0483_remove_facility_corona_testing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityMonetoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('discount_codes', models.JSONField(default=list)),
                ('discount_monetary_components', models.JSONField(default=list)),
                ('invoice_number_expression', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility', unique=True)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_facility_monetory_config, reverse_code=migrations.RunPython.noop),
    ]
