# Generated by Django 5.1.4 on 2025-05-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0074_medicationdispense_charge_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplydelivery',
            name='supply_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.supplyrequest'),
        ),
    ]
