# Generated by Django 6.0 on 2026-03-01 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0074_facilitymonetoryconfig'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitem',
            name='discount_configuration',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='discount_configuration',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='facilitymonetoryconfig',
            name='discount_configuration',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymonetoryconfig',
            name='facility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
    ]
