# Generated by Django 5.1.4 on 2025-05-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0075_supplydelivery_supply_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplydelivery',
            name='supplied_inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.inventoryitem'),
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.organization'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='supplied_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.product'),
        ),
    ]
