# Generated by Django 6.0 on 2026-03-18 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0075_chargeitem_discount_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='managing_organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
