# Generated by Django 6.0 on 2026-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0076_organization_managing_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconfig',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
