# Generated by Django 5.1.4 on 2025-05-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0076_supplydelivery_supplied_inventory_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationdispense',
            name='product',
        ),
        migrations.AddField(
            model_name='medicationdispense',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emr.inventoryitem'),
            preserve_default=False,
        ),
    ]
