# Generated by Django 5.1.4 on 2025-05-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0077_remove_medicationdispense_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdispense',
            name='days_supply',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
