# Generated by Django 5.1.4 on 2025-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0078_alter_medicationdispense_days_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequest',
            name='dispense_status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
