# Generated by Django 6.0 on 2026-07-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0079_resourcerequest_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='productknowledge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.resourcecategory'),
        ),
    ]
