# Generated by Django 5.1.4 on 2025-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0079_medicationrequest_dispense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productknowledge',
            name='base_unit',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
