# Generated by Django 6.0 on 2026-08-12 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylocation',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
