# Generated by Django 6.0 on 2026-08-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='encounter_class_history',
        ),
    ]
