# Generated by Django 5.1.4 on 2025-05-21 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0080_productknowledge_base_unit')
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationdefinition',
            name='category',
        )
    ]
