# Generated by Django 6.0 on 2026-08-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0081_facilitylocation_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='encounter_class_history',
        ),
    ]
