# Generated by Django 5.1.4 on 2025-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0081_remove_observationdefinition_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdefinition',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
