# Generated by Django 6.0 on 2026-07-15 13:52

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0081_questionnaire_auth_context_questionnaire_facility_and_more'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacilityValueSetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValueSetFacilityOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='valueset',
            name='auth_context',
            field=models.CharField(default='instance', max_length=255),
        ),
        migrations.AddField(
            model_name='valueset',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
        migrations.AddField(
            model_name='valueset',
            name='facility_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.facilityorganization'),
        ),
        migrations.AddField(
            model_name='valueset',
            name='inherited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valueset',
            name='internal_organization_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
        migrations.AddField(
            model_name='valueset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.valueset'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'instance'), ('deleted', False), ('latest_revision__isnull', True)), fields=('slug',), name='unique_questionnaire_slug_instance'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'user'), ('deleted', False), ('latest_revision__isnull', True)), fields=('slug',), name='unique_questionnaire_slug_user'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'facility'), ('deleted', False), ('latest_revision__isnull', True)), fields=('slug', 'facility'), name='unique_questionnaire_slug_facility'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'facility_organization'), ('deleted', False), ('latest_revision__isnull', True)), fields=('slug', 'facility_organization'), name='unique_questionnaire_slug_facility_organization'),
        ),
        migrations.AddConstraint(
            model_name='valueset',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'instance'), ('deleted', False)), fields=('slug',), name='unique_valueset_slug_instance'),
        ),
        migrations.AddConstraint(
            model_name='valueset',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'user'), ('deleted', False)), fields=('slug',), name='unique_valueset_slug_user'),
        ),
        migrations.AddConstraint(
            model_name='valueset',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'facility'), ('deleted', False)), fields=('slug', 'facility'), name='unique_valueset_slug_facility'),
        ),
        migrations.AddConstraint(
            model_name='valueset',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'facility_organization'), ('deleted', False)), fields=('slug', 'facility_organization'), name='unique_valueset_slug_facility_organization'),
        ),
        migrations.AddField(
            model_name='userfacilityvaluesetpreference',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfacilityvaluesetpreference',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
        migrations.AddField(
            model_name='userfacilityvaluesetpreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfacilityvaluesetpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfacilityvaluesetpreference',
            name='valueset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.valueset'),
        ),
        migrations.AddField(
            model_name='valuesetfacilityorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valuesetfacilityorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.facilityorganization'),
        ),
        migrations.AddField(
            model_name='valuesetfacilityorganization',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valuesetfacilityorganization',
            name='valueset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.valueset'),
        ),
        migrations.AddConstraint(
            model_name='userfacilityvaluesetpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('slug', 'facility', 'user'), name='unique_user_facility_valueset_preference'),
        ),
    ]
