# Generated by Django 6.0 on 2026-07-15 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0082_userfacilityvaluesetpreference_and_more'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionnaire',
            name='unique_questionnaire_slug_user',
        ),
        migrations.RemoveConstraint(
            model_name='valueset',
            name='unique_valueset_slug_user',
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'user'), ('deleted', False), ('latest_revision__isnull', True)), fields=('slug', 'facility', 'created_by'), name='unique_questionnaire_slug_user'),
        ),
        migrations.AddConstraint(
            model_name='valueset',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_context', 'user'), ('deleted', False)), fields=('slug', 'facility', 'created_by'), name='unique_valueset_slug_user'),
        ),
    ]
