# Generated by Django 5.1.4 on 2025-05-21 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0082_observationdefinition_category')
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdispense',
            name='dosage_instruction',
            field=models.JSONField(blank=True, default=list, null=True),
        )
    ]
