# Generated by Django 6.0 on 2026-07-29 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0083_remove_questionnaire_unique_questionnaire_slug_user_and_more'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityResourceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=255)),
                ('is_group', models.BooleanField(default=False)),
                ('category', models.JSONField(default=dict)),
                ('main_code', models.JSONField(default=dict)),
                ('alternate_coding', models.JSONField(default=list)),
                ('subject_type', models.CharField(max_length=255)),
                ('subject_id', models.UUIDField()),
                ('effective_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('performer', models.JSONField(default=dict)),
                ('value_type', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('note', models.TextField()),
                ('method', models.JSONField(default=dict)),
                ('reference_range', models.JSONField(default=list)),
                ('interpretation', models.JSONField(default=dict)),
                ('parent', models.UUIDField(null=True)),
                ('component', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('data_entered_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_observations_entered', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('observation_definition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.observationdefinition')),
                ('questionnaire_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.questionnaireresponse')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityResourceQuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('revision', models.IntegerField(default=1)),
                ('subject_type', models.CharField(max_length=255)),
                ('subject_id', models.UUIDField()),
                ('responses', models.JSONField(default=list)),
                ('cleaned_response', models.JSONField(default=dict)),
                ('structured_responses', models.JSONField(default=dict)),
                ('structured_response_type', models.CharField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='completed', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.questionnaire')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
