# Generated by Django 6.0 on 2026-07-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0084_facilityresourceobservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityresourceobservation',
            name='questionnaire_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.facilityresourcequestionnaireresponse'),
        ),
    ]
