# Generated by Django 5.1.4 on 2025-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0085_patientidentifierconfig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='facility_identifiers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='instance_identifiers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
