# Generated by Django 5.1.4 on 2025-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0086_patient_facility_identifiers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
