# Generated by Django 6.0 on 2026-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0086_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='actions',
            field=models.JSONField(default=list),
        ),
    ]
