# Generated by Django 5.1.4 on 2025-05-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0087_invoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.productknowledge'),
        ),
    ]
