# Generated by Django 6.0 on 2026-08-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0081_facilitylocation_tags'),
        ('emr', '0087_questionnaire_actions'),
    ]

    operations = [
    ]
