# Generated by Django 6.0 on 2026-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0088_merge_20260820_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueset',
            name='disable_composition',
            field=models.BooleanField(default=False),
        ),
    ]
