# Generated by Django 6.0 on 2026-09-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0082_remove_encounter_encounter_class_history'),
        ('emr', '0089_valueset_disable_composition'),
    ]

    operations = [
    ]
