# Generated by Django 5.1.4 on 2025-06-07 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0092_activitydefinition_tags_chargeitem_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='facility_tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='instance_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
