# Generated by Django 6.0 on 2026-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0093_workspace_organization_cache_workspaceorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
    ]
