# Generated by Django 5.1.4 on 2025-06-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0093_patient_facility_tags_patient_instance_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyrequest",
            name="suppliers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_requests",
                to="emr.organization",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="facility_identifiers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
