# Generated by Django 5.1.4 on 2025-07-08 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0096_alter_activitydefinition_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbooking',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
