# Generated by Django 5.1.4 on 2025-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0100_alter_account_total_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productknowledge',
            name='alternate_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
